- lib/util/cmd.helper.js
At the moment, the program does not recognise `::1` as a localhost address, this PR addresses this
> Make package IPv6 ready

- README.md
- dockerfile
update docker image. 
using now default alpine 3.7 image (comes with nodejs 8.9.1). It's 15 MB smaller now.
> update docker image

- lib/xsql.js
When using _p ang _size query params in URL, the first row is skipped.
Example:
_p = 1 & _size = 20
reqParams._index will be = (1 - 1) * 20 + 1 = 1; 
Generated SQL will be SELECT * FROM ? LIMIT 1,20. This SQL skips first element in the table
Correct SQL that should be generated is SELECT * FROM ? LIMIT 0,20
> Fixing pagination issue when using _p & _size

- index.js
- lib/util/cmd.helper.js
- lib/xapi.js
- package-lock.json
- package.json
- tests/tests.js
The current implementation is broken - the `_version` endpoint returns the version of the package `pkginfo` (0.4.1) instead of that of this package (0.4.9).
(Calling `const pkginfo = require('pkginfo')(module);` exposes the info on `module.exports`, not on the variable `pkginfo`.)
> Fixed version bug

- lib/xsql.js
The current implementation of the pagination starts at _p=1 (_p=0 yields the same result). This is counter-intuitive. Pagination should start at _p=0.
This PR fixes that.
> Made pagination start at p=0 instead of p=1

- lib/util/cmd.helper.js
Some environments (like google cloud) require connection to be established via unix sockets.
This PR adds support for mysql's unix socket connection.
Example:
```
xmysql -u $DB_USER -d $DB_NAME -p $DB_PASSWORD -S $DB_SOCKET_PATH 
```
> Adds support for unix socketPath

- packages/nocodb/package-lock.json
- packages/nocodb/package.json
Refer to #222 - Running ``npm run watch:build`` under packages/nocodb causes ``'nodemon' is not recognized as an internal or external command, operable program or batch file.``
> fix: add missing nodemon to devDependencies

- .github/workflows/docker.yml
- packages/nocodb/Dockerfile
Resolves #183, resolves #249
This PR introduces a github action workflow to automate building nocodb into 3 architectures, namely:
-  `linux/amd64`
-  `linux/arm64`
- `linux/arm/v7`
The trigger for the github action is manual (on  workflow_dispatch) as per discussion as of now, where the maintainers can enter the tag/version variable (`Docker image tag`) as seen in the screenshot below:
Clicking **Run workflow** will result in the workflow pushing 2 tags to the nocodb dockerhub repo, namely (refer line 68-69 in `.github/workflows/docker.yml`):
- `nocodb:<version>`
- `nocodb:latest`
The Dockerfile is also modified to use multi-stage builds (so the builder can compile **sqlite3** properly for `arm64` and `arm/v7`) while keeping the final image small. Comments are added to further describe …
> Docker multiarch workflow

- README.md
This PR adds a `Deploy on Railway` button which allows users to deploy NocoDB to Railway in just one click.
> Add deploy on Railway button

- README.md
- packages/nocodb/src/lib/utils/NcConfigFactory.ts
docker compose ECS integration only passes secrets via runtime available files. This allows for nocodb to be provided with a database configuration via a secret without too much hassle
> NC_DATABASE_URL_FILE patch

- packages/nc-gui/components/project/spreadsheet/components/expandedForm.vue
There is text overflow issue that when text length is large then causes bug that button moves up and it doesn't looks good overall. So put a text limit using css.
Signed-off-by: Ayush Sahu <aztrexdx@gmail.com>
> Expanded form fix for text overflow

- docker-compose/nginx-proxy-manager/docker-compose.yml
Here my example for using nginx-proxy-manager for exposing nocodb to the outside. 
It creates 2 networks:
One for the nocodedb app container and mysql database. Thus mysql is not exposed beyond this network as it is with the traefik example. And one for nginx-proxy-manager and the nocodb app container.
> Example docker-compose.yml for use with nginx-proxy-manager and 2 seperate networks

- packages/noco-docs/content/en/getting-started/installation.md
Heroku Deployment video at https://docs.nocodb.com/getting-started/installation#heroku-deployment is pointing to another video. This change fixes it.
> Docs: update heroku's deployment youtube video id

- packages/noco-docs/content/en/setup-and-usages/user-management.md
Hello! I'm new to this, so forgive me if this is the incorrect way to contribute.
I wanted to add a page that explained the user permissions because I couldn't find this info anywhere. The tables were largely inspired from this page: https://support.airtable.com/hc/en-us/articles/202887099-Permissions-overview.
Please complete the table with check-marks and x's to indicate what the various roles can or can't do.
> Add page to explain role permissions, user mgmt

- packages/nocodb/src/lib/noco/common/BaseApiBuilder.ts
- packages/nocodb/src/lib/noco/gql/GqlApiBuilder.ts
- packages/nocodb/src/lib/noco/rest/RestApiBuilder.ts
It's fixing the issue of relationships getting removed whenever table metadata is recreated from Meta management. 
The same is also mentioned in the comment of https://github.com/nocodb/nocodb/issues/712. 
It's changing how `nc_relations` entries are made when table metadata is recreated. 
> fix: removal of physical relationships on metadata recreate

- packages/nocodb/src/lib/sqlMgr/code/models/xc/BaseModelXcMeta.ts
Signed-off-by: vijayrathore8492 <professional.vijay8492@gmail.com>
Fix typo in `BaseModelXcMeta.ts` to preserve column types
> fix typo to preserve column types

- packages/noco-docs/content/en/setup-and-usages/formulas.md
Fixed a typo in the following section. "Division of numeric values" operator should be "/" but is "-". Production URL  [Provide summary of changes.](https://docs.nocodb.com/setup-and-usages/formulas#numeric-operators)
> Typo fixed

- packages/nc-gui/components/project/appStore/FormInput.vue
- packages/nc-gui/components/project/appStore/inputs/checkboxField.vue
- packages/nocodb/src/plugins/mino/Minio.ts
Currently in "Configure Minio", the field "Use SSL" is using text field which is not a good idea as users don't know whether they should input. This PR includes the changes to cater this case.
Before: 
After:
> enhancement(ui): add checkbox field to app store input 

- packages/nc-gui/components/project/appStore.vue
Plugin search is broken after typing a letter. It throws ``Cannot read properties of undefined (reading 'toLowerCase') ``.
Use ``title`` instead of ``name``.
> fix: Cannot read properties of undefined (reading 'toLowerCase') in App Store

- packages/nc-gui/components/project/spreadsheet/rowsXcDataTable.vue
Ref: #828 
If there are multiple NN cells, once we input something, it will trigger ``save()``. In this function, it may return early if some conditions are not met, such as not all NN cells have values. Due to this early exit, the ``saving`` is still set as ``true`` which blocking the current row operation.
No matter there is an early return or not, we have to mark it ``false`` anyway at the end. Hence, putting the reset statement to finally block.
Edit the first row. Two cells with red outliner are NN cells without values.
Input ``A`` to ``title1``. The red outliner for ``title1`` is gone as there is a value. No loading spinner is here as we are not saving.
Input ``A`` to ``title3``. As all required fields are not null, it will trigger the save function. 
Reload the view. The data …
> fix: reset saving flag anyway

- packages/nocodb/src/lib/noco/NcProjectBuilder.ts
Ref: #1034 
Currently the hooks can still be found in ``this.builder.hooks`` after deleting them. This PR is to add one more case ``tableXcHooksDelete`` in NcProjectBuilder listener to trigger ``onHooksUpdate()`` to load the latest hook from ``nc_hooks``.
> fix: update hook list after deleting webhook

- packages/nc-gui/components/project/spreadsheet/components/editableCell.vue
- packages/nc-gui/components/project/spreadsheet/mixins/cell.js
Ref: #1042 
Currency field is saved immediately which triggers validation if there is no further input (~1000ms) after the first change.
> fix: disable syncDataDebounce for currency field

- packages/nc-gui/store/tabs.js
Ref: #1126 
Previously treeview contains View section. However, now it has been merged under Tables. Therefore, the parent node should be ``tableDir`` instead of ``viewDir``.
SQL Views can be rendered after hard refresh.
> fix: wrong parent node for SQL Views

- packages/nocodb/src/lib/noco/common/BaseApiBuilder.ts
- packages/nocodb/src/lib/noco/gql/GqlApiBuilder.ts
- packages/nocodb/src/lib/noco/rest/RestApiBuilder.ts
New MultiSelect / SingleSelect columns are not working properly in the latest version. The root cause was overwritting `dtxp` property on the table create/update.
New Single/Multi-select column creation working with `text` type in MySQL.
re #1132
> fix: keep dtxp property on table create/update

- packages/nc-gui/components/project/spreadsheet/components/importExport/columnMappingModal.vue
- packages/nc-gui/components/project/spreadsheet/components/moreActions.vue
Ref: #880 
Currently boolean values like True, Yes, No are not accepted as the DB type is like tinyint(1). The changes in this PR are to validate if incoming values are boolean type as well as converting to either 0 or 1 before inserting.
Some test data
```
Id,Bool,Num
1,'Yes',1
2,"Y",1
3,'NO',1
4,"0",1
5,1,1
6,0,1
7,true,1
8,false,1
9,1,1
```
```
10,bad,1
```
> fix: allow different boolean values for checkbox type

- packages/nc-gui/components/project/spreadsheet/mixins/spreadsheet.js
- packages/nc-gui/helpers/sqlUi/MssqlUi.js
- packages/nc-gui/helpers/sqlUi/MysqlUi.js
- packages/nc-gui/helpers/sqlUi/SqliteUi.js
- packages/nocodb/src/lib/dataMapper/lib/sql/CustomKnex.ts
- packages/nocodb/src/lib/sqlUi/MssqlUi.ts
- packages/nocodb/src/lib/sqlUi/MysqlUi.ts
- packages/nocodb/src/lib/sqlUi/SqliteUi.ts
Ref: #589 & #996 
Some types like ``bigint`` or ``uuid`` need to be casted when comparing the target value. Currently there is no such handlng. This PR is to cast it as TEXT and compare with the target value (p.s. also string type).
Before specifying search value
Searching ``bigint`` column 
Searching ``uuid`` column
Searching normal column
> fix: cast search column in custom knex for uuid & fix search issue for bigint

- packages/nc-gui/components/project/spreadsheet/components/expandedForm.vue
- packages/nc-gui/components/project/spreadsheet/views/xcGridView.vue
Ref: #1151 
- show ``Add new row`` option even if there is no PK
- fix ``undefined updated successfully`` message after adding a new row in ``ExpandedForm``.
> fix: missing add row option

- packages/nc-gui/components/project/spreadsheet/components/virtualCell/components/listItems.vue
Ref: #781 
If we add a new row and link record before saving, the option list is empty. If you click reload button, it will throw an error as well. This is because the list is retrieved by calling ``paginatedM2mNotChildrenList`` where one of the parameters is ``pid``, i.e. the row id. It is used in ``whereNotIn`` in ``m2mNotChildren``. If we haven't saved the record, ``pid`` would be ``undefined``, which results in this issue. 
The change in this PR is to assign a default value to ``pid`` if it is not defined. If we add a new record, then the list should include all options as there is no selected one. The default value should be a non-existing row id to avoid collision. Hence, ``-1`` is chosen.
> fix: undefined parent id when calling paginatedM2mNotChildrenList

- packages/nc-gui/components/auth/userManagement.vue
- packages/nocodb/src/lib/noco/meta/NcMetaIO.ts
- packages/nocodb/src/lib/noco/meta/NcMetaIOImpl.ts
- packages/nocodb/src/lib/noco/rest/RestAuthCtrl.ts
Ref: #214 
Currently you can only delete users in project level. If you accidentally invite someone with a wrong email address, there is no way to delete it in UI level. This PR is to cater this case. 
Create a new user
Remove this user from the current project
Remove this user from NocoDB
> fix: add missing delete user logic

- packages/nocodb/src/__tests__/rest.test.ts
- packages/nocodb/src/lib/noco/rest/RestAuthCtrl.ts
This PR uniforms the format of some 400 responses of `/auth/signin`.
Issue: #1266 
Throwing exception directly has been replaced with returning a msg interface.
And a unit test case for no credentials has been added.
"Missing credentials" now responses a json with both `msg` and `message` properties. This is because some people may rely on the property `message`.
> Uniform 400 response format of REST /auth/signin

- packages/nocodb/src/lib/noco/rest/RestAuthCtrl.ts
I have made a mistake in PR #1274 and it responses incorrect message when wrong credentials was provided when signing in.
It has been fixed. Sorry for making mistakes.
And I have added the type annotation in the comment. However I think it's better to make sure that the TypeScript is working for lib "passport". Now it's AnyScript and quite misleading.
Update /auth/signin handler to make sure it returns the correct json.
> Fix incorrect response while wrong credentials was provided

- packages/nc-gui/components/project/spreadsheet/components/virtualCell/formulaCell.vue
- packages/nc-gui/helpers/formulaList.js
- packages/nocodb/src/lib/dataMapper/lib/sql/formulaQueryBuilderFromString.ts
Added a new formula called URL() which is compatible with other formulas.
Example usage: URL("https://google.com")
ref: closes #1028 
Uses URI::(url) syntax for handling URLs.
> feat: add URL formula

- packages/nocodb/src/lib/dataMapper/lib/sql/formulaQueryBuilderFromString.ts
Uppercase formula column names wasn't working because if you select as without quotes on pg it pretends case-insensitive. Added quotes around column name selector to get around this.
Ref: fixes #1332 
Same result with or without uppercase letters on formula columns:
This commit effect queries:
SELECT 1 as Formula, 1 as formula FROM table; -> SELECT 1 as "Formula", 1 as "formula" FROM table;
> fix: uppercase formula column names on postgresql

- packages/nocodb/src/lib/sqlMgr/code/models/xc/BaseModelXcMeta.ts
Options added for Single Select and Multi select columns are getting lost after metadata refresh. This PR fixes a simple error in checking column types to preserve options.
> correct uidt check to preserve select column options after metadata sync

- packages/nc-gui/components/project/spreadsheet/components/editableCell/dateTimePickerCell.vue
- packages/nc-gui/helpers/formulaList.js
- packages/nocodb/src/lib/dataMapper/lib/sql/formulaQueryBuilderFromString.ts
- packages/nocodb/src/lib/dataMapper/lib/sql/functionMappings/mssql.ts
- packages/nocodb/src/lib/dataMapper/lib/sql/functionMappings/mysql.ts
- packages/nocodb/src/lib/dataMapper/lib/sql/functionMappings/pg.ts
- packages/nocodb/src/lib/dataMapper/lib/sql/functionMappings/sqlite.ts
Added a new formula called DATEADD which supports date arithmetics.
It takes 3 arguments DATEADD(date, number, 'interval')
- Date can be date or datetime, result changes according to given type
- Interval values depends on database but common ones work for each (day, month etc.)
- Number can be negative for subtraction.
Ref: closes #1389 
daytodate: DATEADD(date, 1, 'day')
monthtodatetime: DATEADD(datetime, 2, 'month')
isDateAfter: IF(NOW() < date, "true", "false")
isDatePlus10After: IF(NOW() < DATEADD(date,10,'day'), "true", "false")
(Date of execution: 2022-03-07)
DateTime Picker was giving an error on MySQL (timezone part) so I implemented a work around for it. Although I tried this with different versions, this error needs confirming it might be caused by my setup.
MSSQL date picker …
> feat: DATEADD formula for date arithmetics 

- packages/noco-docs/content/en/setup-and-usages/rollup.md
Fixes a typing error on the Rollup documentation page.
"Distrinct" was misspelled and has been replaced with "Distinct"
N/A
> docs: Fix typo in rollup.md

- packages/nc-gui/components/project/spreadsheet/components/editColumn.vue
`@input` event does not work for checkboxes.Checkboxes in advance options while edit column are not working because of it.
This PR fixes it and uses `@change` event.
> use correct event on checkbox

- packages/noco-docs/content/en/developer-resources/rest-apis.md
The example for the `Exists` REST API endpoint uses `DELETE` instead of `GET`.
N/A
> Fix incorrect HTTP method in REST API docs

- packages/nc-gui/components/project/spreadsheet/components/editColumn/customSelectOptions.vue
Handle the commas correctly when adding new options in multi select options. Fixes ref: #1282 
Before, the comma was handled weirdly resulting in such views: 
Now, when you try to add a comma, it adds a new field automatically and auto focuses that field so user can type the next option.
> handle commas correctly in multi select options

- packages/nc-gui/components/project/spreadsheet/components/importExport/columnMappingModal.vue
- packages/nc-gui/components/project/spreadsheet/components/moreActions.vue
Ref: #1537 
- handle null number fields for non-nn columns
- add missing validation for checking nn columns
> fix: csv import logic

- packages/nc-gui/components/project/spreadsheet/components/editColumn.vue
- packages/nc-gui/components/project/spreadsheet/components/editColumn/customSelectOptions.vue
An error was given when you delete default value from single select column, fixed it via making it null if default input is empty.
> fix: select field default value removal

- packages/nocodb/Dockerfile
Add [dumb-init](https://github.com/Yelp/dumb-init#why-you-need-an-init-system)
Fixes https://github.com/nocodb/nocodb/issues/1661
- [*] fix: (bug fix for the user, not a fix to a build script)
```
~/dev/js/nocodb/packages/nocodb robinfrcd/catch-sigint
❯ docker run nocodb/nocodb:latest
select * from `nc_api_tokens`
App started successfully.
Visit -> http://localhost:8080/dashboard
^C
~/dev/js/nocodb/packages/nocodb robinfrcd/catch-sigint
❯ 
```
> Add dumb-init: catch signals

- packages/nc-gui/components/createOrEditProject.vue
- packages/nc-gui/pages/project/xcdb.vue
- packages/nocodb/src/lib/noco-models/Project.ts
- ext db: project created with same name, toast persisted
- xcdb: project created with same name - error message corrected
- cache issue: insert record was failing for following scenario [was working with cache disabled]
- create project, delete project, create another project with same name
- insert record using bulk create api (failing while trying to retrieve project id using project title) 
> fix: toast error corrections & cache flush on delete

- packages/nc-gui/components/releaseInfo.vue
- packages/nc-gui/plugins/projectLoader.js
- packages/nc-gui/store/app.js
- packages/nocodb-sdk/src/lib/Api.ts
- packages/nocodb/src/lib/noco/meta/api/utilApis.ts
- scripts/sdk/swagger.json
- Disables old xcRelease call which is from old API.
- Add new endpoint '/api/v1/db/meta/nocodb/version' to API which fetches latest release version of repo
- Refactor releaseInfo component to act on latest release fetched
> refactor: renew old fetchReleaseInfo

- packages/nocodb/src/lib/noco/meta/api/dataApis/dataAliasApis.ts
There was a duplicate endpoint for dataUpdate which I think supposed to be delete endpoint.
> fix: remove duplicate and add missing delete api

- packages/nc-gui/components/project/appStore/inputs/checkboxField.vue
ref: #1743 
Currently checkbox value will always be false even it is set to true
> fix: checkbox always false issue

- packages/nocodb/src/lib/dataMapper/lib/sql/BaseModelSqlv2.ts
- packages/nocodb/src/lib/dataMapper/lib/sql/conditionV2.ts
> Fix - LTAR based filter

- .github/CONTRIBUTING.md
The old link (https://docs.nocodb.com/#nocodb-repository-structure) was just redirecting to the welcome page of the docs. I think this is because the link is invalid. The correct link to the repository structure should be https://docs.nocodb.com/engineering/repository-structure.
Only docs changes.
> docs: fix link to repository structure in `CONTRIBUTING.md`

- packages/nc-gui/components/project/spreadsheet/mixins/spreadsheet.js
ref: #1784
`_cn` was the previous implementation. Use `alias` now.
> fix: use alias instead of _cn

- packages/nc-gui/components/monaco/MonacoJsonObjectEditor.js
- packages/nc-gui/components/project/spreadsheet/components/editableCell/jsonEditableCell.vue
#1814 might be caused by invalid input (users should not be allowed to save invalid json)
- Disable saving for invalid input
- Show errors to user
> feat: improve json editor

- packages/nc-gui/components/project/spreadsheet/components/moreActions.vue
- packages/nc-gui/helpers/rolePermissionsEE.js
- scripts/cypress/integration/spec/roleValidation.spec.js
Ref: #1683 
- Allow Editors to import CSV
- Revise incorrect _isUIAllowed input
> fix: editor ACL

- packages/nc-gui/components/project/spreadsheet/rowsXcDataTable.vue
- packages/nc-gui/components/project/spreadsheet/views/xcGridView.vue
Ref #1813
- Binded onCellValueChange with save event of editable-cell (to cover firefox's enter save)
- Added saving check for cell editing (prevents multiple saving for chrome)
> fix: cell saving

- packages/nc-gui/components/project/spreadsheet/components/virtualCell.vue
- packages/nc-gui/components/project/spreadsheet/components/virtualCell/formulaCell.vue
- packages/noco-docs/content/en/setup-and-usages/formulas.md
- packages/nocodb/src/lib/dataMapper/lib/sql/formulav2/formulaQueryBuilderv2.ts
- packages/nocodb/src/lib/dataMapper/lib/sql/functionMappings/mssql.ts
- packages/nocodb/src/lib/dataMapper/lib/sql/functionMappings/mysql.ts
- packages/nocodb/src/lib/dataMapper/lib/sql/functionMappings/pg.ts
- packages/nocodb/src/lib/dataMapper/lib/sql/functionMappings/sqlite.ts
Re #1638
- Changed negative interval handling of DATEADD (added 'UnaryExpression' handler to FormulaQueryBuilderv2)
- Merged date operations under DATEADD for all database types
- Removed post-formatting for PostgreSQL as it breaks conditional usage of returned value
- Need a solution to keep date formatting convention on DATEADD for PostgreSQL
> fix: DATEADD negative intervals

- packages/nocodb/src/lib/noco/meta/api/columnApis.ts
- packages/nocodb/src/lib/noco/meta/api/tableApis.ts
Extract column metadata using `sqlClient` instead of relying on the request payload to avoid column metadata mismatch.
re #1753 #1754
> fix: Postgres meta out of sync

- packages/nocodb/src/lib/dataMapper/lib/sql/functionMappings/pg.ts
- packages/nocodb/src/lib/dataMapper/lib/sql/functionMappings/sqlite.ts
Re https://github.com/nocodb/nocodb/issues/1865
Allow using functions (max, min etc.) for DATEADD interval argument which wasn't working for postgreSQL and SQLite.
Dropped case part for pg as it is not used anymore.
> fix: using functions for DATEADD interval

- packages/nc-gui/components/project/spreadsheet/components/editColumn/lookupOptions.vue
- packages/nc-gui/components/project/spreadsheet/components/editColumn/rollupOptions.vue
Show LTAR column name instead of the table name in Lookup/Rollup column creation options.
re #1811 #1768
> refactor: show LTAR column name instead of table name in Lookup/Rollup

- packages/nc-gui/components/project/spreadsheet/components/virtualHeaderCell.vue
> fix: use titles instead of table/column names on tooltips

- packages/nocodb/src/lib/noco/meta/api/swagger/helpers/getSwaggerColumnMetas.ts
- packages/nocodb/src/lib/noco/meta/api/swagger/swaggerApis.ts
Get models from current projects to populate swagger json which contains models and views from the current project.
re #1899
> fix: pass correct project id to get model list

- packages/nc-gui/components/project/spreadsheet/mixins/cell.js
- packages/nc-gui/components/project/spreadsheet/views/xcGridView.vue
Re #1932
Disables on outside click listener for monaco editor.
This way:
- the dialog doesn't close when you click inside
- keeps data when you minimize the dialog
- also makes it harder to accidentally close monaco editor while minimized (closed with proper buttons or selecting another cell)
> fix: monaco editor dialog closes on click

- packages/nocodb-sdk/src/lib/sqlUi/MssqlUi.ts
Allow to set the length of nvarchar. (I tested with 'MAX' it works too). It allows to change the type from SingleLineText to MultiLineText in the UI for the mssql databases.
closes #1930
> fix: allow to edit the length of a nvarchar (mssql). #1930

- packages/nocodb/src/lib/dataMapper/lib/sql/BaseModelSqlv2.ts
- packages/nocodb/src/lib/noco-models/Model.ts
Extract the model by `id` instead of `table_name` to avoid extracting the wrong model from the meta table.
re #1946
Verified by creating nested lookup `a => b => a`
> fix: Nested lookup

- packages/nocodb/src/lib/noco/meta/api/columnApis.ts
- packages/nocodb/src/lib/noco/meta/api/tableApis.ts
ref: #1945 
- add missing logic to delete the orphans columns and m2m table.
- m2m to self table
- m2m to other table
> fix: m2m delete logic

- packages/nocodb/src/lib/noco/meta/api/columnApis.ts
Re #1955 
As options are handled from meta for databases beside MySQL the options should be appended to created column meta.
> fix: single/multi select options at creation

- packages/nc-gui/components/project/spreadsheet/components/moreActions.vue
- packages/nocodb/src/lib/dataMapper/lib/sql/BaseModelSqlv2.ts
- pass the correct `data` to `after.delete` webhook. ref: #2024 
- show the webhook listing page instead of empty detail page after reopening webhook from MoreAction
> fix: webhook-related issues

- packages/nocodb/src/lib/dataMapper/lib/sql/conditionV2.ts
- packages/nocodb/src/lib/noco-models/Filter.ts
The comparison operators `btw` and `nbtw` were not working in List API anymore. This PR is to fix it.
> fix: add btw and nbtw filters

- packages/nc-gui/components/project/spreadsheet/components/editColumn/FormulaOptions.vue
- packages/nocodb-sdk/src/lib/formulaHelpers.ts
- packages/nocodb/src/lib/dataMapper/lib/sql/formulav2/formulaQueryBuilderv2.ts
- fix incorrect data type - e.g. `ADD({numberic_formula}, 10)`.
- remove unexpected $pt.name$ - create a formula and edit it. `{$column_name$}` is shown rather than `{column_name}`.
- add ( ) to formula for precedence. ref to #2128 
- formula1 = 1 + 1
- formula2 = {formula1} * 5 = 1 + 1 * 5 (current behaviour) but expected to be (1 + 1) * 5
> fix: issues related to formula

- packages/noco-docs/content/en/getting-started/installation.md
- packages/nocodb/src/lib/noco/meta/api/sync/importApis.ts
In the existing release it Airtable import will fail in docker if mapped to a port other than `8080`.
re #2127
> fix: Support Airtable import even mapped to a different port

- packages/nc-gui/components/project/spreadsheet/components/editColumn/FormulaOptions.vue
- packages/nc-gui/components/project/spreadsheet/helpers/uiTypes.js
- packages/nocodb/src/lib/dataMapper/lib/sql/formulav2/formulaQueryBuilderv2.ts
- packages/nocodb/src/lib/noco-models/Column.ts
- packages/nocodb/src/lib/noco/meta/api/columnApis.ts
Previously any NULL value in formula with CONCAT would make the entire result empty. Now it's considered as an empty string instead. 
Example: F: `CONCAT({Title}, {Title1}, {Title2}, "B")`
|---|---|
- Show column options in suggestion list when users enter `{` as what's following must be a column.
- Fix the incorrect insertAtCursor position when calling appendText. Previously selecting `column1` after `{` would become `{{column1}` while `{column1}` is expected.
- Fix incorrect ID passing to `FormulaColumn.update`. Previously deleting a column that is referenced by a formula would throw an error and all data will be not shown when calling dataList as something wrong with the cache part as attribute `error` is not updated due to the wrong ID.
> enhancement: formula

- packages/nocodb/src/lib/noco/common/XcMigrationSourcev2.ts
- packages/nocodb/src/lib/noco/migrationsv2/nc_016_alter_hooklog_payload_types.ts
nc_hook_logs_v2.payload type is boolean. but in webHookHelpers.ts ,payload type it should be text. will be can't save hook log.
https://github.com/nocodb/nocodb/blob/4d423a383077d2c25fd9903856ba857abcd50800/packages/nocodb/src/lib/noco/meta/helpers/webhookHelpers.ts#L250
https://github.com/nocodb/nocodb/blob/4d423a383077d2c25fd9903856ba857abcd50800/packages/nocodb/src/lib/noco/meta/helpers/webhookHelpers.ts#L277
> fix: alter_hooklog_payload_types

- packages/nc-gui/components/project/spreadsheet/components/MoreActions.vue
when upload csv has SingleSelect or MultiSelect type，and value is empty，will be failed
> fix: when_select_empty_importData_failed

- packages/nocodb/src/lib/dataMapper/lib/sql/conditionV2.ts
- Fix some logics when filtering a formula column with ops `isEmpty`, `isNotEmpty`, `isLike` & `isNotLike`. 
(ref - #2177)
F: `{Title}`
> fix: formula filter

- packages/nocodb/src/lib/dataMapper/lib/sql/helpers/getAst.ts
Passing nested query to nested getAst calls was wrong if `fields=*`
Before this fix the multi-nested query was not working correctly. If you wanted to pass something to a double nested record it was not working if you specified `?fields=*` because it would pass along `query.nested` instead of `query.nested.NestedRecord`
f.e.: `?fields=*&nested[NestedRecord][fields]=*&nested[NestedRecord][nested][DoubleNestedRecord][fields]=*` was not working correctly
It was passed correctly here already:
https://github.com/nocodb/nocodb/blob/c06f43c1cda71a140c83bc7473035746ec6bc154/packages/nocodb/src/lib/dataMapper/lib/sql/helpers/getAst.ts#L60
but not in the else block:
> fix passing nested query in nested getAst calls

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/formulav2/formulaQueryBuilderv2.ts
knex would replace `?` to `25` in `knex.raw`. This PR is to escape the question marks before executing.
ref: #2294 
formula: `CONCAT("?", "A")`
formula2: `CONCAT("??", "A")`
> fix: question mark in CONCAT

- packages/nocodb/src/lib/meta/api/projectUserApis.ts
Invite and Edit user under User Management would trigger the same function `saveUser`. For the latter one, it would trigger `projectUserUpdate` while the other one would triggers `projectUserAdd`, which later calls `userInvite`. However, Add User To Project would also trigger the same as Invite. In current `userInvite` function, if the user exists, it would be updated and the cache will be changed also. And this logic should be only for the existing users who are not in the project.
Check if the target user is in the current project or not. If so, throw an error.
ref: #2301 
User Exists + Already in the project
User Exists + Not in the project
User Not Exists
> fix: missing logic in userInvite

- packages/nc-gui/components/project/spreadsheet/components/cell/CurrencyCell.vue
- packages/nc-gui/components/project/spreadsheet/components/editColumn/CurrencyOptions.vue
Disabled currency options for columns using 'money' db type on PostgreSQL (it has own currency code/locale implementation but their community also suggest not using it https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_money)
Re https://github.com/nocodb/nocodb/issues/2255
> fix: pg database type money

- packages/nc-gui/components/project/spreadsheet/components/EditableCell.vue
- packages/nc-gui/components/project/spreadsheet/components/editableCell/EnumListEditableCell.vue
- packages/nc-gui/components/project/spreadsheet/components/editableCell/SetListEditableCell.vue
SingleSelect record change fires without `ignoreWebhook` query.
Extended fix for MultiSelect
Re #2277
> fix: SingeSelect/MultiSelect webhook trigger

- packages/nc-gui/components/project/spreadsheet/components/editableCell/RatingCell.vue
Make rating read-only if referred in a lookup cell.
ref: #2045
> fix: Make rating readonly in lookup column

- packages/nc-gui/components/project/spreadsheet/components/VirtualHeaderCell.vue
Reload metadata of related metadata on LinkToAnotherRecord column delete.
https://user-images.githubusercontent.com/61551451/173379978-91c40975-eafc-4aaf-85e8-f4ea0c50f0be.mov
> Fix: Reload related table metadata after relation column delete

- packages/nc-gui/components/project/spreadsheet/RowsXcDataTable.vue
- packages/nc-gui/components/project/spreadsheet/components/ExpandedForm.vue
- packages/nc-gui/components/project/spreadsheet/helpers/getPlainText.js
- packages/nc-gui/nuxt.config.js
- packages/nc-gui/package-lock.json
- packages/nc-gui/package.json
- packages/nc-gui/plugins/domPurify.js
- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
- packages/nocodb/src/lib/meta/api/auditApis.ts
- Sanitise comment data to avoid XSS attack.
- Encode any HTML content in the string to render as text in the comment even if HTML content present in value'
ref: #2262
> Fix: Sanitise comment data 

- packages/nc-gui/components/project/spreadsheet/components/editableCell/DateTimePickerCell.vue
Save/Update datetime picker value even if user clicked outside.
re #2354
> Fix: Save datetime on  'click:outside' event

- packages/nocodb/src/lib/meta/api/sync/importApis.ts
- packages/nocodb/src/lib/meta/api/userApi/helpers.ts
- packages/nocodb/src/lib/meta/api/userApi/userApis.ts
- Include `token_version` value in jwt payload
- Use a generic function to populate jwt token to avoid repetition
re #2361
> Fix: Include `token_version` value in jwt payload

- packages/nocodb/src/lib/meta/api/sync/helpers/job.ts
ID*, id? on remote was causing `Duplicate column name 'ID_'`
Added check for column name.
> fix: sync duplicate column_name after sanitize

- packages/nocodb/src/lib/meta/api/sync/helpers/job.ts
Treat decimal values as double in MySQL during import. this allows bigger decimal values to be seamlessly imported
Line number: 486 ~ 490
Verified locally for MySQL/ SQLite. Fails for PG (WIP)
> fix: treat decimal as double in mysql

- packages/nc-gui/components/import/templateParsers/ExcelTemplateAdapter.js
date1904 fix was done previously for fixing precision bug & timezone offset issues introduced by xlsx, while CSV shouldn't be applicable.
ref: #2334 
Using reporter's CSV
> fix: exclude date1904 fix from csv quick import

- packages/nocodb/src/lib/models/Project.ts
disable shared base -> leftover cache makes the old link still accessible.
ref: #2358
> fix: delete project:<uuid> in cache for disable shared base

- packages/nocodb/src/lib/Noco.ts
- packages/nocodb/src/lib/meta/api/userApi/initStrategies.ts
- Use JwtStrategy to check `expiresIn` (ref: #2422)
Setting `NC_JWT_EXPIRES_IN=60000` for testing, i.e 60 seconds. (By default, it's `10h`.)
1. Frontend - no action for 60 seconds - then refresh the page
2. API - run curl command retrieved from Get API Snippet -  no action for 60 seconds - run it again
> fix: expired jwt token still usable

- packages/nocodb/tests/export-import/ReadMe.md
- packages/nocodb/tests/export-import/config.json
- packages/nocodb/tests/export-import/exportSchema.js
- packages/nocodb/tests/export-import/importSchema.js
- external module built using SDK to export/import schema
- can be used to duplicate project (data imported as well if source project is accessible)
- TBD: nested lookup/rollup/formula
Locally verified. Not integrated with mainline. Resides in `packages/nocodb/tests/export-import`folder
> feat: export-import using SDK (WIP)

- packages/nocodb/src/lib/meta/api/dataApis/dataAliasExportApis.ts
- packages/nocodb/src/lib/models/View.ts
- No view will be given for existing export csv api. This PR is to feed the default view for export. ?
(ref: #2395)
> fix: use default view if no view is specified

- packages/noco-docs/content/en/developer-resources/rest-apis.md
- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/conditionV2.ts
- packages/nocodb/src/lib/models/Filter.ts
In version 0.90.0 and after `not` was removed from the filters, however, it was still there in the docs. This PR fixes the docs as well as adds support for `not`.
> add support to not in filters

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/helpers/getAst.ts
In the data list API Field projection is not working for nested columns if the 'fields' query parameter set
In the list API, if you provide `fields` and `nested[relatedTable][fields]` both, nested projection does not get applied.
> fix nested field projection

- packages/nc-gui/components/import/ImportFromAirtable.vue
- UI option to enable / disable all views import (grid / gallery / form)
- enable / disable option verified
Only primary grid view will be imported if option is disabled. Else, all grid / gallery / form views will be imported.
> feat: support secondary view import

- packages/nocodb/src/lib/meta/api/userApi/initAdminFromEnv.ts
- packages/nocodb/src/lib/meta/api/userApi/initStrategies.ts
- packages/nocodb/src/lib/meta/api/userApi/userApis.ts
- packages/nocodb/src/lib/models/User.ts
On admin environment variables update ( `NC_ADMIN_EMAIL` and `NC_ADMIN_PASSWORD` )
- Invalidate old token if admin email changed in env
- Invalidate token if password updated in env
- Avoid unnecessary updates if both email and passwords are the same
| Project type | Test environment | Expected behavior | Status |
|------|-----|-----|---|
| Existing | Updated `NC_ADMIN_EMAIL` with a non-existing users email | Old super admin tokens should be invalid | __Verified__ (@mertmit) |
| Existing | Updated `NC_ADMIN_EMAIL` with an existing users email | Old tokens of both super and another user(deleted) should be invalid | __Not tested__ |
| Existing | Updated `NC_ADMIN_PASSWORD` | Old super admin tokens should be invalid  | __Verified__ (@mertmit) |
| Existing | Updated `NC_ADMIN_PASSWORD` and …
> Fix: invalidate token if admin email or password changed

- packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts
- packages/nocodb/src/lib/db/sql-mgr/code/models/xc/ModelXcMetaPg.ts
When using postgresql as source, json/jsonb types are inferred as LongText in nocodb schema. Meanwhile, json type in nocodb cannot be saved as jsonb type in postgresql.
This PR fixes the inference of json type and add jsonb as one of db types for json.
Creation of jsonb columns and the inference of JSON types are verified.
creation:
inference:
Note: I'm not sure if there are any compatibility consideration to infer json as LongText, but we cannot edit LongText json in ui as they are displayed as "[object]" in the editor.
> feat: json inference and jsonb saving for postgresql

- .github/workflows/ci-cd.yml
- package.json
- packages/nocodb/package.json
- packages/nocodb/src/run/dockerRunPG_CyQuick.ts
- scripts/cypress/integration/common/9a_QuickTest.js
CI-CD quick tests were disabled during recent commits overlap. Re-enabling.
CI/CD
> fix: cypress quick test enable in CICD

- packages/nocodb/src/lib/migrations/v2/nc_013_sync_source.ts
- packages/nocodb/src/lib/migrations/v2/nc_016_alter_hooklog_payload_types.ts
Foreign key length correction in migration file.
re #2201
> fix(migration): foreign key length correction

- packages/nocodb/src/lib/meta/api/tableApis.ts
when call  api/v1/db/meta/projects/{projectId}/tables to create table.
hava 3 columns.  id,title1,title2.  title2.pv is true.
result: title1.pv true , title2.pv true.
```json
{
"title": "123",
"table_name": "nc_1h1n__123",
"columns": [
{
"title": "id",
"column_name": "id",
"uidt": "Number",
"dt": "int",
"np": "10",
"ns": "0",
"clen": null,
"cop": "1",
"pk": 1,
"pv": false,
"rqd": 1,
"un": 1,
"ct": "int unsigned",
"ai": 1,
"unique": 0,
"cdf": null,
"cc": "",
"csn": null,
"dtx": "specificType",
"dtxp": "",
"dtxs": "0",
"au": 0,
"deleted": null,
"system": 0,
"order": null,
"meta": null
},
{
"title": "title1",
"column_name": "title1",
"uidt": "Date",
"dt": "varchar",
"np": null,
"ns": null,
"clen": "255",
"cop": "14",
"pk": 0,
"pv": false,
"rqd": 0,
"un": 0,
"ct": "varchar(255)",
"ai": 0, …
```
> fix: duplicate pv

- packages/nc-gui/components/project/spreadsheet/components/SortListMenu.vue
- packages/nc-gui/components/project/spreadsheet/components/editColumn/LookupOptions.vue
- packages/nc-gui/components/project/spreadsheet/components/virtualCell/LookupCell.vue
- Fixed empty pills from appearing in lookup column when the lookup column has multiple null items.
- Unwanted tables appearing in lookup dropdown i.e tables not shown in Table List in the Project tree view of dashboard like junction table.
- Fixed an UI issue where sort button indicates it has a sort even tho it has no sort(except for the default empty sort when we click the `Add sort option`
Ref: #2610 
Fixed empty pills from appearing in lookup column:
Unwanted tables appearing in lookup dropdown:(used to show store table)
UI issue fix of sort button
> fix/Fixed empty pills from appearing in lookup column, unwanted tables appearing in lookup dropdown and UI issue of sort

- packages/nc-gui/components/project/spreadsheet/RowsXcDataTable.vue
- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
- packages/nocodb/src/lib/meta/api/dataApis/dataAliasApis.ts
ref: #2557 
- In SQLite, we're using virtual key - so whether there is m2m / hm deletion - the deletion is considered valid. However, others would throw `Cannot delete or update a parent row: a foreign key constraint fails`
- This PR is to change the to-be-deleted row contains any m2m / hm data. If so, toast a message to indicate users to remove the data first just like table deletion logic.
Base Table
Delete Row with ID = 2 
Delete Row with ID = 3 
Delete Row with ID = 4
Add one more record and select all to delete
Only row with ID = 4 is deleted
> fix: delete rows containing m2m / hm data

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
- packages/nocodb/src/lib/meta/helpers/PagedResponse.ts
Re #2635
- ExcludedList
- list -> sort, where
- findOne -> sort, where
- groupBy -> sort, where
- hmList -> limit, offset
- mmList -> limit, offset
- PagedResponseImpl -> hande aliases
| Endpoints | where(w)           | sort(s)            | limit(l)           | offset(o)          |
|-----------|--------------------|--------------------|--------------------|--------------------|
| list      | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| findOne   | :heavy_check_mark: | :heavy_check_mark: | not_needed         | not_needed         |
| groupBy   | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| hmList    | not_impl           | not_impl           | :heavy_check_mark: | :heavy_check_mark: |
| mmList    | not_impl …
> fix: query param aliases for various API endpoints

- packages/nc-gui/components/utils/DlgTableCreate.vue
- packages/nocodb/src/lib/meta/api/tableApis.ts
- limit the table length in frontend and backend
- mysql: 64
- pg: 63
- mssql: 128
- sqlite: 255
Payload: https://drive.google.com/file/d/13IK67Sx93nvnb_3gLUBDLgoEC7XTQiso/view?usp=sharing
> fix: large characters in table create

- packages/nc-gui/components/project/spreadsheet/components/ColumnFilter.vue
- packages/nocodb/src/lib/meta/api/filterApis.ts
- packages/nocodb/src/lib/models/Filter.ts
- Enabled support for grouped filter
- CSS corrections 
Equivalent to => `where FirstName like '%race%' OR (FirstName like '%vi%' and like '%k%')`
> feat: enable grouped filter and some css corrections

- packages/nc-gui/components/import/templateParsers/ExcelTemplateAdapter.js
- fix the regex for `tn` & `cn` when importing csv or excel - ref: #2677 
CSV:
Excel:
> fix: import cn & tn replace regex

- packages/nc-gui/assets/style/style.css
- packages/nc-gui/components/project/spreadsheet/components/ColumnFilter.vue
- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/conditionV2.ts
- packages/nocodb/src/lib/models/Filter.ts
- Apply grouped filter only under the nested group ( re #2679 )
- Remove scrollbar from nested group
- Remove unnecessary `%` from like query ( re #2681 )
`%%%val%%%` => `%val%`
> Fix - Grouped filter unexpected behaviour

- packages/nocodb/docker/index.js
- packages/nocodb/src/__tests__/graphql.test.ts
- packages/nocodb/src/__tests__/rest.test.ts
- packages/nocodb/src/__tests__/restv2.test.ts
- packages/nocodb/src/lib/v1-legacy/nc.try.ts
- packages/nocodb/src/run/docker.ts
- packages/nocodb/src/run/dockerRunMysql.ts
- packages/nocodb/src/run/dockerRunPG.ts
- packages/nocodb/src/run/dockerRunPG_CyQuick.ts
- packages/nocodb/src/run/try.ts
#2711
Unable to get the correct request, after using nginx forwarding agent。
After the test, code snippet and swagger API doc are found, and the URL is determined by req Ncsiteurl control. After nginx proxy forwarding, req Protocol can only get http.
`packages\nocodb\src\lib\Noco.ts`
```
/******************* Middlewares : start *******************/
this.router.use((req: any, _res, next) => {
req.nc = this.requestContext;
req.ncSiteUrl =
this.config?.envs?.[this.env]?.publicUrl ||
this.config?.publicUrl ||
req.protocol + '://' + req.get('host');
req.ncFullUrl = req.protocol + '://' + req.get('host') + req.originalUrl;
next();
});
```
```
const server = express();
server.enable('trust proxy');
```
>  feat: server.enable('trust proxy');

- packages/nc-gui-v2/composables/useProject.ts
- packages/nc-gui-v2/composables/useUIPermission/index.ts
- packages/nc-gui-v2/lib/constants.ts
Load project specific user roles and use it with UI permission composable.
Usage
```js
const { isUIAllowed } = useUIPermission()
if(isUIAllowed('permissionName')){
// logic here
}
```
> feat(gui-v2): get project roles

- packages/nc-gui-v2/components/template/Editor.vue
- packages/nc-gui-v2/components/template/utils.ts
* fix types
* change arrow fns to regular functions to avoid ordering issues
* move templateColumns to utils file
* 
> refactor(gui-v2): cleanup template editor component

- packages/nc-gui-v2/components/cell/DatePicker.vue
- packages/nc-gui-v2/components/cell/DateTimePicker.vue
- packages/nc-gui-v2/components/cell/YearPicker.vue
Ref: [comment](https://github.com/nocodb/nocodb/pull/2899#issuecomment-1200174342)
Removed `calendar` icon from `DatePicker`, `DateTimePicker` and `YearPicker`
UI:
> Removed `calendar` icon from `DatePicker`, `DateTimePicker` and `YearPicker`

- packages/nc-gui-v2/composables/useApi/index.ts
- packages/nc-gui-v2/plugins/state.ts
* fix useApi not returning axios errors to the calling `catch` block
> fix(gui-v2): use promise reject when returning api error

- packages/nc-gui-v2/components/smartsheet-toolbar/ToggleDrawer.vue
- packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
- packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
- packages/nc-gui-v2/components/tabs/Smartsheet.vue
- packages/nc-gui-v2/context/index.ts
* add RightSidebarInj injection key
* change right sidebar toggle icons
* limit views menu height to max 200px
> refactor(gui-v2): change right sidebar toggle icons

- packages/nc-gui-v2/components/cell/Email.vue
- packages/nc-gui-v2/components/cell/Url.vue
- packages/nc-gui-v2/components/virtual-cell/Formula.vue
ref: #2927
common - font size are not uniform
- Will revise in spreadsheet PR
display text was highlighted in blue in v1 for currency cell. is it by design to mark everything uniform in v2?
- Checked with Mert a month ago. It's not expected to show in Blue. In v2, they will display normally.
URL  - validation failure case, no pop-up error displayed
- in v1, i don't see a pop-up error
Email - validation failure case, no pop-up error displayed
- in v1, I don't see pop-up error. Current logic s that if it s not a valid email, it renders as a text instead of link with mailto
On editing a cell part of the formula, the cell value in the formula column didn't update. ignore if this will be picked up during spreadsheet activity
- I don't see there is an option to change the formula now. Will come …
> fix(gui-v2): cell follow ups

- packages/nc-gui-v2/composables/index.ts
- packages/nc-gui-v2/composables/useInjectionState/index.ts
* extends on VueUses' `createInjectionState`
* immediately returns injection state on provide
> feat(gui-v2): add `useInjectionState` composable

- packages/nc-gui-v2/composables/useUIPermission/index.ts
- packages/nc-gui-v2/composables/useUIPermission/rolePermissions.ts
* rename `RolePermissions` to `Permission`
* allow wildcard permission for creator and owner roles
> fix(gui-v2): permission type not allowing wildcard

- packages/nc-gui-v2/components/cell/Percent.vue
- packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
- packages/nc-gui-v2/components/smartsheet/Cell.vue
- packages/nc-gui-v2/composables/useColumn.ts
- packages/nc-gui-v2/utils/percentUtils.ts
ref: #2895
- add percent utils
- add `isPercent` in `useCloumn` composable
- add `<CellPercent/>` in Cell
- add icon for percent cells
- add percent rendering based on column meta, getting, setting logic
> feat(gui-v2): percent cell

- packages/nc-gui-v2/components/webhook/Editor.vue
- packages/nc-gui-v2/components/webhook/Test.vue
- Sending `user` context is not supported. Remove associated information from the webhook panel
locally verified
> refactor: remove user context information from webhook panel

- packages/nc-gui-v2/pages/project/index/create-external.vue
- packages/nc-gui-v2/utils/projectCreateUtils.ts
External PostgreSQL & MsSQL connection on v2 always results with 'public' schema as we normally store searchPath in dataSource object rather than dataSource.connection
Fixed property path for both clients.
> fix(gui-v2): fix project schema for pg and mssql

- packages/nc-gui-v2/components/smartsheet-column/CurrencyOptions.vue
- packages/nc-gui-v2/components/smartsheet-column/DurationOptions.vue
- packages/nc-gui-v2/components/smartsheet-column/RatingOptions.vue
- packages/nc-gui-v2/composables/useColumnCreateStore.ts
- set meta as `{}` rather than `null`
- set default values for each column options
> fix(gui-v2): fix empty meta & feed default values

- packages/nc-gui-v2/components/smartsheet-column/CheckboxOptions.vue
- packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
ref: #2985 
- add checkbox options
- add @ckpack/vue-color as color picker as antdv doesn't provide such component
TODO: antdv doesn't support object as value. need a workaround for it.
> feat(gui-v2): checkbox options

- packages/nc-gui-v2/components/tabs/auth/user-management/UsersModal.vue
Use of invite-more button shows the default error; null check added
https://user-images.githubusercontent.com/86527202/182288159-9a1411c7-efd2-49a3-b7a8-a2c756bc6c64.png
> fix: info message error when using invite more option

- packages/nc-gui-v2/components/smartsheet-column/CheckboxOptions.vue
- packages/nc-gui-v2/components/smartsheet-column/RatingOptions.vue
ref: #2962
- Rating Select: antdv doesn't support object as value.
- Checkbox Select: antdv doesn't support object as value.
> fix(gui-v2): select object value issue

- packages/nc-gui-v2/app.vue
- packages/nc-gui-v2/components.d.ts
- packages/nc-gui-v2/nuxt.config.ts
* enables auto-imports of icons
* does not work for dynamic icons ⚠️ 
> feat(gui-v2): add icons resolver to component auto-loader

- packages/nc-gui-v2/components/general/Language.vue
- packages/nc-gui-v2/nuxt.config.ts
> refactor(gui-v2): remove vuetify from language switcher

- packages/nc-gui-v2/components/smartsheet-header/Cell.vue
- packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
- packages/nc-gui-v2/components/smartsheet/sidebar/RenameableMenuItem.vue
* abort renaming view on failed validation
> fix(gui-v2): abort renaming view on failed validation

- packages/nc-gui-v2/pages/index/user/index/index.vue
> fix(gui-v2): sign out after reset pwd like v1

- packages/nc-gui-v2/layouts/base.vue
- packages/nc-gui-v2/pages/project/index/create-external.vue
- packages/nc-gui-v2/pages/project/index/create.vue
- add missing logos in project creation pages - ref: #3100
> fix(gui-v2): add missing logos

- packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
- packages/nc-gui-v2/components/smartsheet-column/FormulaOptions.vue
ref: #3146
- `formulaSuggestionDrawer` has been removed in previous PR. This PR is to remove those leftover code.
> fix(gui-v2): remove formulaSuggestionDrawer

- packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
Fix extension for https://github.com/nocodb/nocodb/commit/5ec7971c145a0a310e0ed3e8fc588d55c07096b2
`Webhook` & `API Snippet` multiple click was opening easter egg menu
> fix(gui-v2): easter icons appear when toggling toolbar icons twice

- packages/nc-gui-v2/pages/signup/[[token]].vue
Ref: #3220
- Added more reactive password hint.
- Email validation doesn't show email is required and invalid in the case of empty email field.
UI:
> Improved email and password validation of signup page

- packages/nc-gui-v2/components/smartsheet/Grid.vue
- packages/nc-gui-v2/components/smartsheet/expanded-form/index.vue
- packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/AddRow.vue
- packages/nc-gui-v2/components/tabs/Smartsheet.vue
- packages/nc-gui-v2/composables/useViewData.ts
- packages/nc-gui-v2/context/index.ts
ref: #3119
- Clicking on `Add new row` button creates an empty row and opens the modal.
- If `cancel` button is clicked in `expanded form` then the created row will be deleted (this is not in v1).
> Made `Add new row` button functional

- packages/nc-gui-v2/components/smartsheet/sidebar/RenameableMenuItem.vue
* renamable item not triggering dblclick
> fix(gui-v2): dblclick not triggered on renmable menu item

- scripts/sdk/swagger.json
https://all-apis.nocodb.com/#tag/DB-table/operation/db-table-create
The API docs are saying that the field `columns` is not required. However, from understanding #2809 a table needs minimum 1 column. There is the `columns` field required. Technically, the `columns` shouldn't be an empty but I don't know to add a note for this.
> docs: make field `columns` required for creating a table via the REST API

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
ref: #3226
The issue was that in the case of checking for total linkable parents for a record(`bt`) ,if it has no parent already linked, this resulted in a sql query where it was bugging out due to a subquery in the lines of `where 'id' not in (null)` erroring out.
> fix/Fixed pagination info of nestedChildrenExcludedList api where `totalRows` was set wrong due to a bugged sql query

- packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
- ref: #3161 
>  After submit form, click on form view name in right nav bar should re-open view 
> fix(gui-v2): reload the page if the same form view is clicked

- packages/nc-gui-v2/components/shared-view/Grid.vue
- packages/nc-gui-v2/components/smartsheet-toolbar/Export.vue
- packages/nc-gui-v2/components/smartsheet-toolbar/ExportSubActions.vue
- packages/nc-gui-v2/components/smartsheet-toolbar/ViewActions.vue
- packages/nc-gui-v2/components/smartsheet-toolbar/ViewInfo.vue
- packages/nc-gui-v2/components/smartsheet/Grid.vue
- packages/nc-gui-v2/components/smartsheet/Toolbar.vue
- packages/nc-gui-v2/composables/useUIPermission/rolePermissions.ts
- packages/nc-gui-v2/composables/useViewColumns.ts
- packages/nc-gui-v2/layouts/shared-view.vue
- packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index/index.vue
Ref: #3279 
https://github.com/nocodb/nocodb/issues/3282
For `Viewer/commenter` users:
- Added view title and removed the view edit option.
- Added a download button in toolbar
- Fixed welcome page for viewer.
- Fixed `show all` `hide all` in fields menu.
- `Add new row` button hidden
For shared view:
- Added view title and removed the view edit option.
- Removed bottom padding and unnecassry ui elements in shared view
UI:
Viewer view:
Shared View:
> vue3: Fixed UI issues for Viewer and Shared view

- packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
Ref: https://github.com/nocodb/nocodb/issues/3274
- Fixed stale fields badge issue
- Aligned `show system fields` check box
> vue3: Fixed stale fields badge issue and improved ui for fields menu

- packages/nc-gui-v2/components/cell/attachment/index.vue
- packages/nc-gui-v2/components/smartsheet/Cell.vue
- packages/nc-gui-v2/components/smartsheet/Gallery.vue
- packages/nc-gui-v2/composables/useViewColumns.ts
Re #2631
- Double click card for expanded form view
- Reload hook
- Cards are read-only (implemented a new cell prop overwriting readOnly value only if provided)
- Fixed hidden field indicator
> fix(gui-v2): gallery view

- packages/nc-gui-v2/components/template/Editor.vue
- ref: #3316 
Using [simple.xlsx](https://github.com/nocodb/nocodb/files/9414143/simple.xlsx)
> fix(gui-v2): incorrect sheet names in excel import

- packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
Kludge: trigger route update twice. But avoids a complete reload of page from the beginning.
verified locally
> fix: avoid complete page reload on clicking view name in right navbar

- packages/nc-gui-v2/components/smartsheet/Grid.vue
- packages/nc-gui-v2/components/tabs/Smartsheet.vue
- packages/nc-gui-v2/composables/useViewData.ts
- packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index.vue
- packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index/[type]/[title]/[[viewTitle]].vue
Ref: https://github.com/nocodb/nocodb/issues/3089 
re #3340
Known issue:
- On tab change api is called twice and state related to tab is changed multiple times.
Here we are logging on changes on activeTab state in page(`index.vue`) and changes on the `tabs.value?.[activeTabIndex.value]` (activeTab is just a computed of this) (`useTabs.ts`)
> vue3: Forced meta loading when tab changes

- packages/nc-gui-v2/components/template/Editor.vue
- ref: #3392 
Sheet name can be different than `tableName`. As we only allow one file to be imported, we choose the first key. 
> fix(gui-v2): use import data with the first key

- .github/workflows/release-executables.yml
- .github/workflows/release-pr-v2.yml
- .github/workflows/release-pr.yml
- README.md
- packages/noco-docs/content/en/getting-started/installation.md
ref: #3378 
- add missing extension for windows executables
- use `iwr` (Invoke-WebRequest) instead of `iwp`
> fix: windows executables

- packages/nc-gui-v2/components/template/Editor.vue
ref: #3427
Currently the key names in `importData` won't be updated when `editableTn` got updated. This PR is to handle this case. Also it checks if the current import include duplicate table names.
> fix(gui-v2): missing data in quick import after renaming

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/pg.ts
> fix: operator does not exist: double precision % integer

- packages/nc-gui-v2/composables/useProject.ts
- packages/nc-gui-v2/composables/useUIPermission/index.ts
- packages/nc-gui-v2/composables/useUIPermission/rolePermissions.ts
> fix(gui-v2): handle opening shared view/base opening in same window

- packages/nc-gui-v2/components/smartsheet/Toolbar.vue
ref: #3454 
add missing `allowCSVDownload` condition
Share View without allowing download
Base case - viewer / commenter
Base case - editor
> fix(gui-v2): add missing allowCSVDownload condition

- packages/nc-gui-v2/plugins/a.i18n.ts
Allow using `i18n` outside setup, like within a composable which invoke from a plugin.
Sample usage:
```typescript
import { getI18n } from '~/plugins/a.i18n'
export function useSample(){
const { t } = getI18n().global
console.log(t('general.home'))
}
```
> fix(gui-v2): make i18n globally available outside setup

- packages/nc-gui-v2/components/general/ChromeWrapper.vue
- packages/nc-gui-v2/components/general/ColorPicker.vue
- packages/nc-gui-v2/composables/useProject.ts
- packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
- packages/nc-gui-v2/pages/index/index/index.vue
Re #3459
- Wrapper component for Chrome (ChromeWrapper)
- This emits input on color change and usable without v-model (broken for vue-color library we use)
- Allows returning of any color mode vue-color supports (hex, hex8, hsl, hsv, rgba) instead of full object
- Handle theme colors using events emitted and functions instead of watchers
- Change ColorPicker to use ChromeWrapper (returns hex8 easier to handle / cleaner code)
- SaveTheme allows either only primaryColor or accentColor and uses theme color for missing prop
> fix: theme palette

- packages/nc-gui/components/cell/attachment/utils.ts
Use local storage option for attachment only in a shared public form.
re #3541 
> fix: show attachment cell data in shared grid view

- packages/nc-gui/plugins/initializeFeedbackForm.ts
- packages/nocodb/src/lib/meta/api/utilApis.ts
> fix: drop await / errors from feed-back form handler

- packages/nc-gui/components/smartsheet/Gallery.vue
Re #3599 
Use object-cover for gallery card cover image
As we use object-cover some parts of the image might be missed, an alternative approach would have been using object-contain but it results with extra space for most aspect ratios.
Example:
Open for any suggestion / alternative
> fix: gallery card cover image distortion

- packages/nc-gui/components/smartsheet-toolbar/ShareView.vue
- packages/nc-gui/package.json
- packages/nc-gui/web-types.json
* web-types stops Webstorm from complaining that `v-e` is an unrecognized directive
> feat(nc-gui): add web types for directives

- packages/nc-gui/components/cell/Checkbox.vue
* changed checkbox cell prop type to allow string
* if previous value was a string val, the initial val is also a string, which causes warnings - might be a TODO to fix this properly
* changed vModel to support this behavior 
> fix(nc-gui): checkbox cell unselectable 

- packages/nc-gui/composables/useProject.ts
- packages/nc-gui/composables/useViewData.ts
- packages/nc-gui/lib/types.ts
- packages/nc-gui/nuxt-shim.d.ts
- packages/nc-gui/pages/[projectType]/[projectId]/index.vue
- packages/nc-gui/pages/[projectType]/[projectId]/index/index.vue
- packages/nc-gui/pages/[projectType]/[projectId]/index/index/[type]/[title]/[[viewTitle]].vue
- packages/nc-gui/pages/index/index/index.vue
* fixes #3635 
* only load project if no request is running already
* move fetching project to parent page to prevent multiple loads
* defer subpages until project is loaded
* show spinner when loading
* reset state when page is unmounted
> fix(nc-gui): project state not properly reset 

- scripts/cypress/integration/common/00_pre_configurations.js
- scripts/cypress/integration/common/1a_table_operations.js
- scripts/cypress/integration/common/1b_table_column_operations.js
- scripts/cypress/integration/common/1c_sql_view.js
- scripts/cypress/integration/common/1e_meta_sync.js
- scripts/cypress/integration/common/2a_table_with_belongs_to_colulmn.js
- scripts/cypress/integration/common/2b_table_with_m2m_column.js
- scripts/cypress/integration/common/3a_filter_sort_fields_operations.js
- scripts/cypress/integration/common/3b_formula_column.js
- scripts/cypress/integration/common/3c_lookup_column.js
- scripts/cypress/integration/common/3d_rollup_column.js
- scripts/cypress/integration/common/3f_link_to_another_record.js
- scripts/cypress/integration/common/4a_table_view_grid_gallery_form.js
- scripts/cypress/integration/common/4b_table_view_share.js
- scripts/cypress/integration/common/4c_form_view_detailed.js
- scripts/cypress/integration/common/4d_table_view_grid_locked.js
- scripts/cypress/integration/common/4e_form_view_share.js
- scripts/cypress/integration/common/4f_grid_view_share.js
- scripts/cypress/integration/common/5a_user_role.js
- scripts/cypress/integration/common/6b_downloadCsv.js
- scripts/cypress/integration/common/6d_language_validation.js
- scripts/cypress/integration/common/6e_project_operations.js
- scripts/cypress/integration/common/6f_attachments.js
- scripts/cypress/integration/common/6g_base_share.js
- scripts/cypress/integration/common/7a_create_project_from_excel.js
- scripts/cypress/integration/common/7b_import_from_airtable.js
- scripts/cypress/integration/common/8a_webhook.js
- scripts/cypress/integration/common/9a_QuickTest.js
- scripts/cypress/integration/spec/roleValidation.spec.js
- scripts/cypress/support/commands.js
- Local storage handling fixed
- save local storage after each test case
- restore before each test case
- after hook operations, if required: restore local storage before execution & save after
- before hook operations, if required: restore local storage before execution & save after
- Tab assumed always available on opening table; not toggling anywhere currently
- TBD: add test to toggle right nav bar & ensure its hidden    
- verified in CI-CD
- at times, screen goes blank; tests failures related to this need fix; wip
> test: cy views suite local storage & tab handling corrections

- packages/nc-gui/components/smartsheet-toolbar/ColumnFilter.vue
- packages/nc-gui/components/smartsheet/Grid.vue
- packages/nc-gui/components/webhook/Drawer.vue
- packages/nc-gui/components/webhook/Editor.vue
- packages/nc-gui/composables/useViewFilters.ts
- packages/nc-gui/context/index.ts
* when adding filters in webhook drawer, hide loading spinner on smartsheet
* are reloads after each filter necessary or can it instead be done at a later point? Like closing the drawer/edit tab of the webhook?
* Fixes #3633  
> refactor(nc-gui): hide loading spinner when reloading from webhook filters 

- packages/nc-gui/components/smartsheet-column/AdvancedOptions.vue
- packages/nocodb/src/lib/meta/api/columnApis.ts
From Discord (thanks for reporting Shard#3121)
This issue seems reproducible only for PG
- Hide dtxp from select columns' advanced options as it might conflict users
- Handle PG default response, handle properly on front-end
- Show correct sample values for select columns
- Allow escaped quotes ('') for default options
> fix(pg): select column default value

- packages/nocodb/src/lib/meta/api/sync/helpers/job.ts
Airtable provides an option for the `Number` field to be displayed as either integer or decimal. Internally stores numbers as decimals. Mapping backend type as `integer` leads to an error when we attempt to store decimal values. Hence mapping all `Number` fields as `decimal` in the backend.
> fix: Import Airtable to SQL Databases - fix number as a decimal

- packages/nc-gui/components/general/FullScreen.vue
- packages/nc-gui/components/smartsheet-toolbar/ColumnFilter.vue
- packages/nc-gui/pages/[projectType]/[projectId]/index/index.vue
- Avoid showing scrollbars on hovering fullscreen button
- Show fullscreen button always
> Fix: Fullscreen button bugs

- package.json
- packages/nc-gui/nuxt.config.ts
- packages/nc-gui/plugins/ant.ts
Toast duration is made configurable.
Would help in reducing CY test execution time.
> chore(nc-gui): env var for info-msg duration

- packages/nc-gui/components/api-client/Headers.vue
webhook header dropdown made searchable
locally verified
> fix(nc-gui): search option for webhook-header dropdown

- packages/nc-gui/components/smartsheet-toolbar/SharedViewList.vue
Adding max-width-[250px] to wrap the password and generating `"` based on the length of the password.
None
> fix(nc-gui): adding max-width-250px to sharedViewList password

- packages/nc-gui/components/smartsheet/expanded-form/Header.vue
Added `min-w-4` so that icons in gallery view don't get squished.
Issue - https://github.com/nocodb/nocodb/issues/3647
None
> fix(nc-gui): adding min-w-4 to icons in gallery view drawer

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
- packages/nocodb/src/lib/meta/api/columnApis.ts
- packages/nocodb/src/lib/meta/api/projectUserApis.ts
- packages/nocodb/src/lib/meta/api/tableApis.ts
- packages/nocodb/src/lib/meta/api/userApi/userApis.ts
- packages/nocodb/src/lib/models/Audit.ts
- packages/nocodb/tests/unit/index.test.ts
Behavior:
- All `await Audit.insert` will be blocking/awaiting in test environment.
- All `await Audit.insert` will be non blocking in non test environment.
Rational being in test environment, data reset is being done using Audit table. Thus we need to await there but for other environments, this awaiting will slow things down.
> Fix(nocodb): Audit insert will always await in test env while in normal environments will by default not await

- packages/nc-gui/layouts/shared-view.vue
Hopefully this is an easy change to review and accept: when a shared view is loaded into an iframe, this allows the parent page to respond to navigating away from the shared view page.
I am planning to use this in my NocoDB plugin for Outline. Right now if I click a url inside of my NocoDB table in a shared view, it loads the page in the iframe, and I want the parent page to navigate to the URL instead. Detecting navigation events from the parent directly, without using postmessage API, is not possible with the strict cross-origin policy in modern browsers.
> feat(nc-gui): shared-view postmessage on locationchange

- .github/workflows/ci-cd.yml
- scripts/cypress/integration/common/00_pre_configurations.js
Often it's required to trigger CICD even when PR is in a draft state (specifically when making changes to CY). Marking it as `ready for review` would also start the `release PR` action. Hence introducing conditional triggering of CI even if PR is in draft state if it includes label `trigger-CI`
- Verified triggering of CI when label `trigger-CI` is included
- Verified skipping of CI when label is excluded (status quo)
> chore(CICD): conditionally trigger CICD for draft PR

- packages/nc-gui/components/smartsheet/column/SelectOptions.vue
- packages/nocodb/src/lib/meta/api/columnApis.ts
Re #3896
- Change default value on corresponding option title change
- Handle escaping single quotes for default option values on backend (keep front-end consistent)
> fix: select options default value

- packages/nc-gui/pages/[projectType]/form/[viewId]/index/survey.vue
- scripts/cypress/integration/common/4i_survey_form.js
- scripts/cypress/integration/test/pg-restViews.js
- scripts/cypress/integration/test/restViews.js
- scripts/cypress/integration/test/xcdb-restViews.js
- scripts/cypress/support/commands.js
- scripts/cypress/support/page_objects/mainPage.js
- Create a form view
- `Country` table
- modify `title`
- modify `form-description`
- configure success message
- enable `show submit another form` option
- enable `show another form after 5 secs` option 
- Share form, enable `survey mode`
- Visit the shared form link
- Verification (for each page)
- header, description
- footer index
- expected field label
- expected button (OK/Submit)
- Post submit
- success message
- `submit another form` button 
- Clean up
- delete form
- remove submitted entry from table
Locally verified for MySQL
> test: survey form

- packages/nc-gui/components/general/Overlay.vue
ref: #4004
- change z-index of overlay from 100 to 2000. (since default z-index for drawer mask is 1000, so we need to set to a value which is greater than 1000)
> fix(nc-gui): overlay z-index

- packages/nc-gui/components/cell/attachment/index.vue
- packages/nc-gui/components/smartsheet/Gallery.vue
- packages/nc-gui/components/smartsheet/Kanban.vue
- packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
- packages/nocodb-sdk/src/lib/Api.ts
- packages/nocodb/src/lib/migrations/XcMigrationSourcev2.ts
- packages/nocodb/src/lib/migrations/v2/nc_022_add_kanban_fk_cover_image_col_id.ts
- packages/nocodb/src/lib/models/KanbanView.ts
- packages/nocodb/src/lib/models/View.ts
- scripts/sdk/swagger.json
- add cover image to kanban view
- introduce no image option in cover image fields menu
No Cover Image (no attachment column) / No Image is selected.
With Cover Image
With Cover Image but no value
> feat: kanban cover image

- packages/nc-gui/components/smartsheet/Cell.vue
- packages/nc-gui/components/smartsheet/Grid.vue
Re #4018
- Automatically create a new row on navigating next within last row
- Save new created row if pressed enter even if content is empty (smart spreadsheet behavior)
> feat: automatically create a new row on navigating next within last row

- packages/nc-gui/components/cell/MultiSelect.vue
- packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
- packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
- packages/nc-gui/components/tabs/Smartsheet.vue
- packages/nc-gui/composables/useTabs.ts
- packages/nc-gui/composables/useViewFilters.ts
- packages/nc-gui/composables/useViewSorts.ts
- packages/nc-gui/lib/types.ts
Keep tab level state for views(for `viewer` and `commenter` role) in open tabs and on revisit restore the state.
re #3261 
> fix: tab level state

- packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
Find unique neighbours on formula paths, therefore avoiding "circular
reference" incorrect error validation while editing formula columns.
Use `new Set` to create a array of graph dependencies without dupications.
https://user-images.githubusercontent.com/3846247/195473594-0dbc4807-1c05-40d0-8e93-fb2b6fbc7191.mov
https://user-images.githubusercontent.com/3846247/195473738-810be0db-0183-4c00-bed8-acea09daf498.mov
(IMO, I think this part of the code could use some unit testing - adding the duplicated graph depedencies scenario would be straightforward and it would be easier to "see" the coverage of use cases)
ref: #4024
> fix(ng-gui): find unique neighbours

- packages/nc-gui/components/smartsheet/Grid.vue
* Fixes issue where navigating between views causes warnings about injections only being usable in setup()
> fix(nc-gui): remove `useMetas` from watch cb

- packages/nc-gui/components/cell/Decimal.vue
- packages/nc-gui/components/cell/Float.vue
- packages/nc-gui/components/cell/Integer.vue
- packages/nc-gui/components/cell/MultiSelect.vue
- packages/nc-gui/components/cell/Percent.vue
- packages/nc-gui/components/cell/TextArea.vue
- packages/nc-gui/components/general/ShareBaseButton.vue
- packages/nc-gui/components/shared-view/Grid.vue
- packages/nc-gui/components/smartsheet/sidebar/toolbar/DebugMeta.vue
- packages/nc-gui/components/smartsheet/sidebar/toolbar/DeleteTable.vue
- packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
- packages/nc-gui/lib/types.ts
- packages/nc-gui/utils/viewUtils.ts
* type fixes
* resolves warning mentioned in #4021 
> chore(nc-gui): fix types and cleanup unused vars

- packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts
Re #3955
- Interpret `bigint` and `bigserial` as number on UI level
> fix: interpret `bigint` and `bigserial` as number on UI level

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
- packages/nocodb/src/lib/meta/api/dataApis/dataAliasApis.ts
- packages/nocodb/tests/unit/rest/tests/tableRow.test.ts
- packages/nocodb/tests/unit/rest/tests/viewRow.test.ts
Add nested filter/sort support for nested list data(LTAR).
```
{
method: 'GET',
url: 'http://localhost:8080/api/v1/db/data/noco/p_1k2arq41xw5qsg/Country/views/Country',
params: {fields: 'City List'},
headers: {
'xc-auth': '....'
}
}
```json
[{
"City List": [
{
"CityId": 2,
"City": "Abha"
},
{
"CityId": 6,
"City": "Addis Abeba"
},
{
"CityId": 251,
"City": "Kabul"
}
]
}
]
```
----
```
{
method: 'GET',
url: 'http://localhost:8080/api/v1/db/data/noco/p_1k2arq41xw5qsg/Country/views/Country',
params: {fields: 'City List', 'nested[City List][where]': '(City,like,ad)'},
headers: {
'xc-auth': '....'
}
}
```json
[{
"City List": [
{
"CityId": 6,
"City": "Addis Abeba"
}
]
}]
```
> fix: add filter and sort support on nested list data

- packages/nc-gui/package-lock.json
- packages/nocodb-sdk/package-lock.json
- packages/nocodb-sdk/package.json
- packages/nocodb/package-lock.json
```
npm ERR! npm ERR! Could not resolve dependency:
npm ERR! npm ERR! dev typedoc@"^0.22.17" from the root project
npm ERR! npm ERR! 
npm ERR! npm ERR! Conflicting peer dependency: typescript@4.7.4
npm ERR! npm ERR! node_modules/typescript
npm ERR! npm ERR!   peer typescript@"4.0.x || 4.1.x || 4.2.x || 4.3.x || 4.4.x || 4.5.x || 4.6.x || 4.7.x" from typedoc@0.22.18
npm ERR! npm ERR!   node_modules/typedoc
npm ERR! npm ERR!     dev typedoc@"^0.22.17" from the root project
```
bump typedoc version.
> fix: npm release github action issue

- packages/nc-gui/components/cell/Checkbox.vue
- Allow number for checkbox modelValue as sqlite3 returns 1/0 for boolean causing following warning
> fix(nc-gui): add number type to checkbox modelValue

- packages/nc-gui/assets/style.scss
- packages/nc-gui/components/erd/Flow.vue
- packages/nc-gui/components/erd/RelationEdge.vue
- packages/nc-gui/components/erd/TableNode.vue
- packages/nc-gui/components/erd/View.vue
- packages/nc-gui/components/erd/utils.ts
- packages/nc-gui/components/smartsheet/toolbar/Erd.vue
- packages/nc-gui/package-lock.json
- packages/nc-gui/package.json
- when zooming out in ERD, show a more basic version of the flow (skeleton mode)
https://user-images.githubusercontent.com/78412429/195872423-8e41af7b-0cf2-4eeb-a38a-0422b3f99d2a.mov
https://user-images.githubusercontent.com/78412429/195872645-fd62232c-f8a7-48f6-bca3-fafa0a6757f6.mov
https://user-images.githubusercontent.com/78412429/195872525-123a2949-13d1-4dd4-89a9-7db2a307b034.mov
https://user-images.githubusercontent.com/78412429/195872573-2b4ce52e-ca85-49c2-a143-e66f644a3d56.mov
> feat(nc-gui): toggle skeleton mode in erd when zooming out too far 

- packages/nc-gui/components/dashboard/TreeView.vue
- packages/nc-gui/components/general/Tooltip.vue
- toggle tooltip when key is pressed and mouse leaves/reenters element
- toggle tooltip on modifier key change
- use isHovering to detect element hover
> refactor(nc-gui): extend tooltip toggle conditions

- packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
- packages/nocodb/src/lib/meta/api/columnApis.ts
- packages/nocodb/src/lib/meta/api/sync/helpers/job.ts
MySQL: we use enum for single select and set for multi select but [set only allow 64 distinct members](https://dev.mysql.com/doc/refman/8.0/en/set.html). So we will fallback using text for multi-select when importing a multi-select column with options more than 64.
- MySQL use find_in_set only if dt is set (this logic was missing from column apis)
- AT import:
- match select options case-insensitive (as this leads duplicate entries on db level)
- use text as dt if 64 or more options provided for multiselect on MySQL
- use text as dt if 64 or more options provided for multiselect on MySQL (Extended this fix to column api level)
> fix: at import failing if more than 64 select options provided

- packages/nc-gui/components/smartsheet/Gallery.vue
ref: #3599
No test changes
This PR changes the styling of cover images from `object-cover`, which scales down the image to the smallest size so it fills the entire container, to `object-contain` which scales the image so it fits entirely within the container. 
**Old:** `object-cover` looks better in terms of design, since each card is uniformly filled with the image. However, information is lost in this case.
**New:** `object-contain` displays the full image, albeit much smaller in the case of wider or longer images. 
Since the cards are responsive and their width varies, it's unadvisable to fix their size to the size of the image.
Ideally, the user would be able to choose how the image is displayed, similar to this UI from …
> fix(nc-gui): gallery cover image is clipped

- packages/nc-gui/components/smartsheet/Grid.vue
- packages/nc-gui/components/smartsheet/Row.vue
- packages/nc-gui/components/smartsheet/TableDataCell.vue
- packages/nc-gui/composables/useSmartsheetStore.ts
- fixes cellRefs not resetting on table change, i.e. it only added more and more refs to the array instead of replacing them
> fix(nc-gui): use `TableDataCell` component to set cell refs

- packages/nc-gui/components/smartsheet/toolbar/ShareView.vue
- packages/nc-gui/composables/useMultiSelect/index.ts
- packages/nc-gui/composables/useViewData.ts
- packages/nc-gui/pages/[projectType]/form/[viewId]/index.vue
- packages/nc-gui/pages/[projectType]/form/[viewId]/index/survey.vue
> fix(nc-gui): dark mode styles for longtext field in form view

- .github/workflows/release-docker.yml
- .github/workflows/release-draft.yml
- .github/workflows/release-executables.yml
- .github/workflows/release-nightly-dev.yml
- .github/workflows/release-nocodb.yml
- .github/workflows/release-pr.yml
As titled, GitHub Actions is deprecating save-state and set-output commands. This PR is to remove all `set-ouput` commands and replaced by Github ENV.
ref: #4171
> refactor(workflows): replace set-output with github env

- packages/nc-gui/components.d.ts
- packages/nc-gui/components/api-client/Headers.vue
ref: #4159 
- change webhook header to autocomplete to allow users to input custom value
> feat(nc-gui): allow webhook header accept custom input

- packages/nc-gui/package-lock.json
- packages/nocodb-sdk/package-lock.json
- packages/nocodb-sdk/package.json
- packages/nocodb/package-lock.json
As `swagger-typescript-api` team has officially released the [bug fix release](https://github.com/acacode/swagger-typescript-api/releases/tag/10.0.2) to address typescript version issue, this PR is to revert the workaround changes done in https://github.com/nocodb/nocodb/pull/3384.
**P.S clean ~/.npm/_npx and remove node_modules first.**
> chore: remove typescript resolutions workaround

- packages/nocodb/src/lib/meta/api/sync/helpers/EntityMap.ts
- packages/nocodb/src/lib/meta/api/sync/helpers/job.ts
- packages/nocodb/src/lib/meta/api/sync/helpers/readAndProcessData.ts
Re #4023 #4176
- Dynamic EntityMap (uses SQLite)
- Keep memory foot-print limited for import (only limited number of records loaded into memory, others are kept in temporary SQLite db)
> feat: at import memory

- packages/nocodb/src/lib/plugins/backblaze/Backblaze.ts
- packages/nocodb/src/lib/plugins/backblaze/index.ts
ref: #4188
- fix region format (previously it requires `s3.` at the beginning while backblaze states region is the 2nd part of url.
- revise placeholders to give more hints
> fix: backblaze region format

- packages/nocodb-sdk/package.json
Some breaking changes on [swagger-typescript-api](https://github.com/acacode/swagger-typescript-api/releases)
Also it is better to use specific version and handle upgrades manually to avoid those situations.
> chore: downgrade and fix swagger-typescript-api version

- packages/nc-gui/components/smartsheet/Gallery.vue
- packages/nc-gui/composables/useViewData.ts
Avoid overwriting LTAR and Lookup cell on cell update since it's not part of the update API response.
re #4220 
> Fix: Grid cell - avoid overwriting LTAR and Lookup cell on cell update

- packages/nocodb/src/lib/meta/api/userApi/initAdminFromEnv.ts
#2759
First check if any user with role 'user,super' exists if not
- If provided an existing mail change user role to super user
- If provided a new mail create an super user account with given credentials
> fix: allow env variables to recover missing super user

- packages/nc-gui/components/smartsheet/Gallery.vue
Do not display the fields with empty values in the gallery view.
ref: https://github.com/nocodb/nocodb/issues/4204
Before:
After:
> feat(gallery): skip empty value to be displayed in the gallery view

- packages/nocodb/src/lib/plugins/backblaze/Backblaze.ts
- packages/nocodb/src/lib/plugins/gcs/Gcs.ts
- packages/nocodb/src/lib/plugins/linode/LinodeObjectStorage.ts
- packages/nocodb/src/lib/plugins/mino/Minio.ts
- packages/nocodb/src/lib/plugins/ovhCloud/OvhCloud.ts
- packages/nocodb/src/lib/plugins/s3/S3.ts
- packages/nocodb/src/lib/plugins/scaleway/ScalewayObjectStorage.ts
- packages/nocodb/src/lib/plugins/spaces/Spaces.ts
- packages/nocodb/src/lib/plugins/upcloud/UpoCloud.ts
- packages/nocodb/src/lib/plugins/vultr/Vultr.ts
- packages/nocodb/src/lib/utils/pluginUtils.ts
ref: #4213
Error `no such file or directory` shows sometimes when testing the plugin. The reason is the file `temp.txt` isn't ready when we need it. We should have waited for the stream emitting `finish` before the futher process.
> fix: app store plugin test

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/pg.ts
cast numeric in the first parameter in round function (PG only).
ref: #4232
with precision `3`.
without precision.
> fix(nocodb): handle type in round function in postgres

- packages/nc-gui/components/erd/Flow.vue
- packages/nc-gui/components/erd/RelationEdge.vue
- packages/nc-gui/package-lock.json
- packages/nc-gui/package.json
- scripts/playwright/pages/Dashboard/commonBase/Erd.ts
- use `EdgeLabelRenderer` to prevent edge labels from overlapping with edges (in stacking order)
> fix(nc-gui): overlapping edge labels

- packages/nocodb/src/lib/meta/helpers/extractProjectIdAndAuthenticate.ts
If user try to update child filters, it's getting error as user not allowed. This PR fixes this issue.
The error is happening when filterParentId is sent in request parameter. In backend projectId is not searched with filter parent and noco backend consider all these requests as unauthorized as authorization is project based.
> add project Id with filterparent requests

- .github/workflows/playwright-test-workflow.yml
- packages/nc-gui/tests/playwright/.gitignore
- packages/nc-gui/tests/playwright/README.md
- packages/nocodb/package.json
-  Made maximum timeout to 30 minutes for a CI instance
- Quick test's backend is now waited on till its ready
- Handling playwright report of quick test as a different report. Quick tests playwright reports were overwriting the actual tests report.
- Added backend log of quick test server as GH artifact
> fix(test): Maximum timeout for each instance is 30 minutes and improved quick test CI configuration

- packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts
ref: #4397
when use postgres. db field type is 'jsonb'.  cell can't show CellJson.
https://github.com/nocodb/nocodb/blob/d550ca461d67a7699d730455ddf548863b243639/packages/nc-gui/composables/useColumn.ts#L22
> fix: pg_jsonb_type_mistake

- packages/nc-gui/components/smartsheet/ApiSnippet.vue
The API snippet template string were wrong for the nocodb-sdk tab. This PR fixes them. 
* Create a test Project and Table
* Go to "Get API Snippet" 
* Go to Tabl `nocodb-sdk`
* Try out the snippets in a simple Node project
> fix: correct api sample template strings

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
ref: #4480
currently attachment data is stored in TEXT and parse to object in UI level. This PR is to convert it to array of objects so that users don't need to convert themselves while using our APIs.
webhook response
```json
[
{
"Id": 10,
"Title": "a2",
"CreatedAt": "2022-11-25 12:30:23",
"UpdatedAt": "2022-11-25 12:31:56",
"title72": null,
"nc_deak__Sheet-2_id": null,
"title7": null,
"title6": null,
"title8": [
{
"url": "http://localhost:8080/download/noco/xcdb/Sheet-1/title8/iDii5f.jpeg",
"title": "haha.jpeg",
"mimetype": "image/jpeg",
"size": 6494
}
]
}
]
```
list response
```
{
...
"title8": [
{
"url": "http://localhost:8080/download/noco/xcdb/Sheet-1/title8/44Z_bA.jpeg",
"title": "haha.jpeg",
"mimetype": "image/jpeg",
"size": 6494
}
]
}
```
Anything for maintainers to be made aware …
> fix(nocodb): convert attachment type in api response

- packages/nc-gui/windi.config.ts
Ref: #4501 
The windy css class names were getting removed, so added them to `safeList`
> fix(nc-gui): Fixed column icon for LTAR, rollup

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/formulaQueryBuilderFromString.ts
- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/formulav2/formulaQueryBuilderv2.ts
- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/mysql.ts
ref: #4527 
- mark CallExpression on pt.right for division
- cast char first before casting as double for FLOAT
For select option, the data type would be `enum` . The existing SQL would produce the wrong result.
```sql
-- existing
(CAST(`t1` as DOUBLE)) / `t2`
-- PR
CAST(CAST(`t1` as CHAR) AS DOUBLE) / CAST(CAST(`t2` as CHAR) AS DOUBLE)
```
> fix: formula division for mysql

- packages/nc-gui/layouts/default.vue
Re #4529
- Refresh sidebar only if next view doesn't have sidebar
> fix: improved refresh sidebar logic

- packages/nc-gui/assets/style.scss
Remove the outline of the search input element which is shown when the element is focused.
> Remove outline of search input in single select

- .github/uffizzi/docker-compose.uffizzi.yml
- .github/workflows/release-pr.yml
- .github/workflows/uffizzi-preview.yml
ref: #3990
This PR adds github workflows to take the docker image built from the "PR Release" workflow to create a preview deployment using Uffizzi. A comment will be posted to every PR with a link to the preview environment from where you can debug nocodb. 
I have tested this on my personal fork [here](https://github.com/waveywaves/nocodb/pull/2#issuecomment-1318681417). Considering the complexity of workflow, it's better if the preview environments are merged and then tested on the repo itself as suggested by @o1lab.
> chore: previews for every PR release using Uffizzi

- packages/nocodb/src/lib/db/sql-client/lib/sqlite/SqliteClient.ts
- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/CustomKnex.ts
- packages/nocodb/src/lib/meta/MetaAPILogger.ts
- packages/nocodb/src/lib/meta/NcMetaIOImpl.ts
- packages/nocodb/src/lib/meta/api/projectApis.ts
- packages/nocodb/src/lib/utils/NcConfigFactory.ts
- sqlite3 requires us to pass useNullAsDefault in order to surpass warning, we were passing that in various places, implemented that to root so we don't need to add it everywhere
- removed no more required flag from various places
> fix: add useNullAsDefault flag for sqlite on root level

- .github/uffizzi/docker-compose.uffizzi.yml
Revert MSSQL and MySQL changes in the uffizzi docker-compose as the preview doesn't seem to be working.
After increasing the memory on the container for both the dbs, the DBs came up but nocodb wasn't responding correctly. We will have to pursue another solution where the preview could be chosen from github action comments.
> revert mssql and mysql in uffizzi previews

- packages/nocodb/README.md
I just fixed some trivial typos and grammar in a README file.
> fix trivial typos in a README

- README.md
- markdown/readme/languages/chinese.md
- markdown/readme/languages/dutch.md
- markdown/readme/languages/french.md
- markdown/readme/languages/german.md
- markdown/readme/languages/indonesian.md
- markdown/readme/languages/italian.md
- markdown/readme/languages/japanese.md
- markdown/readme/languages/korean.md
- markdown/readme/languages/portuguese.md
- markdown/readme/languages/russian.md
- markdown/readme/languages/spanish.md
- packages/noco-docs/content/en/getting-started/installation.md
- packages/noco-docs/content/en/getting-started/upgrading.md
> docs: remove heroku info

- .github/workflows/uffizzi-preview.yml
The preview workflow doesn't run on success but on completion of the workflow before it. This change ensures that the workflow won't run on a failure or partial success of the PR Release workflow.
> Add condition to uffizzi preview to run only on success of previous workflow

- packages/nc-gui/components/smartsheet/toolbar/SearchData.vue
- packages/nc-gui/composables/useFieldQuery.ts
- packages/nc-gui/composables/useSmartsheetStore.ts
- tests/playwright/pages/Dashboard/common/Toolbar/SearchData.ts
- tests/playwright/pages/Dashboard/common/Toolbar/index.ts
- tests/playwright/tests/views.spec.ts
https://user-images.githubusercontent.com/31967149/207461451-4b32a9dd-3760-42db-96cc-6257a1544ac6.mov
Search queries are mixed between views and tables in unpredictable way.
That happens because of accidentally mutating copied objects.
> fix save search query

- packages/nc-gui/components/smartsheet/Cell.vue
- packages/nc-gui/components/smartsheet/Grid.vue
- packages/nc-gui/composables/useMultiSelect/cellRange.ts
- packages/nc-gui/composables/useMultiSelect/index.ts
- packages/nc-gui/lib/types.ts
- tests/playwright/pages/Dashboard/Grid/index.ts
- tests/playwright/pages/Dashboard/common/Cell/index.ts
- tests/playwright/tests/cellSelection.spec.ts
Locked cells break multiselect behavior since they stop click event.
https://user-images.githubusercontent.com/31967149/207723328-24e05599-5f03-4774-8396-f79c4cf9b2e0.mov
"By sense" it would be much better, if activeCell was computed upon selectedRange, but since selectedRange should be updated straightaway, and cell should become active only after child clicks are handled (to maintain old behavior, e.g. to edit date field, two clicks had to be done -- one to select cell, and another one to open date dropdown). The same could be achieved with async computed, but I didn't want to install additional library.
A little more "oddness" adds the fact, that
a) we want cell become active BEFORE dblclick handler
b) for MultiSelect data cell mouseDown event is prevented …
> fix multiselect

- packages/nc-gui/pages/index/index/index.vue
- tests/playwright/pages/ProjectsPage/index.ts
- tests/playwright/tests/projectOperations.spec.ts
- Connect to external DB option removed from project list page
- External datasource can be added after creating a default root DB project
> refactor(gui): remove dropdown for create project from project list page

- packages/nc-gui/components/virtual-cell/barcode/Barcode.vue
The BarcodeWrapper component's template has a fragment as root element (so no single parent HTML element). 
It was called though with a class property (which was actually dead code - not used anywhere) assigned to it which results in the Vue warning (see attached screenshot). 
When adding barcodes to a table/grid view, the Vue warning shown in the attached screenshot should not appear anymore on this branch.
> Fix vue warning (remove unused class of Barcode Wrapper)

- .github/workflows/release-nightly-dev.yml
- .github/workflows/release-pr.yml
Currently we retrieve the version tag in https://github.com/nocodb/nocodb/releases/latest but this page doesn't show the pre-release version causing the incorrect tag name during the build if the latest is a pre-release.
> fix(workflows): handle pre release tag case

- packages/nocodb/src/lib/models/Base.ts
- packages/nocodb/src/lib/models/Model.ts
Re #4759
- Remove leftover relations in col_relations on model delete
> fix: remove datasource

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/pg.ts
Formula like `MOD(10 / 2, 5)` would fail because fn(10 / 2) would return double precision.
ref: #4768
> fix(nocodb): MOD for postgres

- packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
- packages/nocodb/src/lib/Noco.ts
- packages/nocodb/src/lib/meta/helpers/extractProjectIdAndAuthenticate.ts
- packages/nocodb/src/lib/models/Filter.ts
- packages/nocodb/src/lib/version-upgrader/NcUpgrader.ts
- packages/nocodb/src/lib/version-upgrader/ncFilterUpgrader.ts
ref: #4793 
`project_id` in `nc_filter_exp_v2` is incorrect if users input the filter value first (since `fk_column_id` is missing which causes picking the first project id). This PR does the following changes
- upgrader to correct the `project_id` based on either `fk_view_id`, `fk_hook_id` or `fk_column_id` so that users can update / delete the problematic filters.
- disable filter value input if filter field is not chosen (in frontend)
- if `fk_column_id` is not provided, `project_id` should be retrieved from either `fk_view_id` or `fk_hook_id` (in backend).
the first 3 filters can be updated / deleted successfully
> fix: filters logic

- packages/nc-gui/components/smartsheet/column/LookupOptions.vue
- packages/nc-gui/components/smartsheet/column/RollupOptions.vue
- packages/nc-gui/lang/en.json
Use "Link to another record" instead of "Child table"
> refactor: 'Link To Another Record' instead of 'Child Table'

- charts/nocodb/.gitignore
- charts/nocodb/.helmignore
- charts/nocodb/Chart.yaml
- charts/nocodb/templates/NOTES.txt
- charts/nocodb/templates/_helpers.tpl
- charts/nocodb/templates/configmap.yaml
- charts/nocodb/templates/deployment.yaml
- charts/nocodb/templates/hpa.yaml
- charts/nocodb/templates/ingress.yaml
- charts/nocodb/templates/pvc.yaml
- charts/nocodb/templates/secret.yaml
- charts/nocodb/templates/service.yaml
- charts/nocodb/templates/serviceaccount.yaml
- charts/nocodb/templates/tests/test-connection.yaml
- charts/nocodb/values.yaml
Initial work was done by https://github.com/one-acre-fund/oaf-public-charts/tree/main/charts/nocodb
The changes include mostly fixes and the addition of missing features.
It currently requires a ReadWriteMany volume to support multiple replicas, as uploaded files are stored there.
I don't have much experience with NocoDB itself. Additional information are very welcome.
Implements #1544
- [x ] feat: (new feature for the user, not a new feature for build script)
> feat: Adds helm chart

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/pg.ts
- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/sqlite.ts
- tests/playwright/tests/columnFormula.spec.ts
ref: #4816 
- revise DATETIME_DIFF sql for sqlite & pg
- add DATETIME_DIFF playwright tests
```
DATETIME_DIFF("2023-01-12", "2021-08-29", "years")
```
> fix: sqlite datetime diff

- packages/nc-gui/components.d.ts
- packages/nc-gui/components/smartsheet/column/SelectOptions.vue
- tests/playwright/pages/Dashboard/Grid/Column/SelectOptionColumn.ts
- tests/playwright/tests/columnSingleSelect.spec.ts
Since option removal is a destructive operation in can be a good idea to warn a user beforehead
> Undo select option removal

- packages/nc-gui/composables/useTable.ts
Re #4662
- Hide auto-created mm system column from warning
> fix: hide system relation column from LTAR popup

- packages/nc-gui/components/shared-view/Grid.vue
- packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
There was some warnings caused by injections
- Added default value for ReloadViewMetaHookInj
- Provided IsLockedInj from shared grid
> fix: injection warnings on shared view

- packages/nc-gui/utils/filterUtils.ts
- tests/playwright/tests/columnSingleSelect.spec.ts
Re #4462
- Exclude incompatible options for select columns
- Add any of and not any of filtering for single select
> fix: filtering options for select columns

- packages/nocodb/src/lib/models/Base.ts
Re #4871
The issue was reproducible when there is a lookup / roll up on one of the sheet after link column
( Sheet-1 has a belongs to column, Sheet-2 has a has many + lookup/roll up in that case base delete was failing because it was trying to remove belongs to before removing depending lookup / roll up columns)
- While removing a base, delete relational columns in order (Lookup -> Roll up -> FK -> LTAR)
> fix: remove relations in a logical order from meta on base delete

- packages/nc-gui/utils/filterUtils.ts
- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/conditionV2.ts
Include `null` values in not like filter result
> Fix: Filter - include null values in not like filter result

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/pg.ts
ref: #4920
- f0:  `AND(true, AND(true, false))`
- f1: `AND(true, OR(true, false))`
- f2: `OR(true, AND(true, false))`
- f3: `OR(true, OR(true, false))`
- f4: `OR(OR(true, OR(true, false)), OR(true, false))`
> fix(nocodb): argument of OR/AND must be type boolean, not type integer

- .github/uffizzi/docker-compose.uffizzi.yml
- docker-compose/mysql/docker-compose.yml
- docker-compose/nginx-proxy-manager/docker-compose.yml
- packages/nocodb/docker-compose.yml
- GA on 2015
- end of life on Oct this year
- we're using at least 8.0 to develop / test (playwright)
- some of existing sql may not work in 5.x  (#4929)
> chore: bumb mysql container image version to 8.0.32

- packages/nc-gui/composables/useKanbanViewStore.ts
- packages/nc-gui/composables/useSmartsheetStore.ts
- packages/nc-gui/composables/useViewData.ts
- packages/nocodb/src/lib/meta/api/attachmentApis.ts
ref: #4958
- gallery view doesn't use attachment cells. hence, patch `url` after getting the data.
> fix(nc-gui): cater new attachments in gallery view

- packages/nc-gui/assets/style.scss
- packages/nc-gui/components/smartsheet/sidebar/RenameableMenuItem.vue
- icons should be inline (fixes: #4974)
> fix(nc-gui): nc-icon positions

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/CustomKnex.ts
- in postgres, bigint is not supported in STRING_AGG because it only works for string value. Hence, this PR is to cast the data type of the input.
> fix(nocodb): fix invalid formula caused by STRING_AGG in postgres

- packages/nc-gui/components/smartsheet/Cell.vue
- packages/nc-gui/components/smartsheet/Grid.vue
Re #4952
- Change the way fixed row height css handled so it is compatible with other browsers (tested with Chrome, Firefox, Safari)
> fix: css for fixed row height

- packages/nc-gui/components/smartsheet/Cell.vue
- packages/nc-gui/components/smartsheet/Grid.vue
- packages/nocodb/src/lib/Noco.ts
- packages/nocodb/src/lib/models/Model.ts
- packages/nocodb/src/lib/version-upgrader/NcUpgrader.ts
- packages/nocodb/src/lib/version-upgrader/ncAttachmentUpgrader.ts
- packages/nocodb/src/lib/version-upgrader/ncAttachmentUpgrader_0104002.ts
Steps to reproduce the issue: 
- Create a single select column & an attachment column and input some data
- Create a new grid view
- update single select cell
- switch to another view
- hard refresh -> grid is broken due to broken attachment
Reason: 
- since `url` will be enriched the attachment cell, and `saveOrUpdateRecords` in Grid.vue will be triggered when switching views. In this way, the attachment value will be corrupted like
```
{"{\"path\":\"download/noco/xcdb2/attachment2/a/JRubxMQgPlcumdm3jL.jpeg\",\"title\":\"haha.jpeg\",\"mimetype\":\"image/jpeg\",\"size\":6494,\"url\":\"http://localhost:8080/download/noco/xcdb2/attachment2/a/JRubxMQgPlcumdm3jL.jpeg\"}"}
```
while the expected one is
```
[{"path":"download/noco/xcdb2/attachment2/a/JRubxMQgPlcumdm3jL.jpeg","title":"haha.jpeg", …
```
> fix: broken attachments

- packages/nc-gui/components/cell/Url.vue
- packages/nc-gui/components/dlg/TableRename.vue
- packages/nc-gui/components/smartsheet/Cell.vue
- packages/nc-gui/components/smartsheet/Grid.vue
- packages/nc-gui/components/smartsheet/VirtualCell.vue
- packages/nc-gui/components/smartsheet/column/AdvancedOptions.vue
- packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
- packages/nc-gui/components/smartsheet/column/SelectOptions.vue
- packages/nc-gui/components/tabs/auth/user-management/UsersModal.vue
- packages/nc-gui/composables/useMultiSelect/index.ts
- packages/nc-gui/composables/useProject.ts
- packages/nc-gui/composables/useSelectedCellKeyupListener/index.ts
- packages/nc-gui/pages/index/index.vue
- packages/nc-gui/pages/index/index/create.vue
- packages/nc-gui/utils/columnUtils.ts
- packages/nocodb/src/lib/models/View.ts
re https://github.com/nocodb/nocodb/issues/4573
> Miscellaneous bug fixes and improvements

- packages/nocodb/tests/unit/factory/row.ts
- packages/nocodb/tests/unit/rest/index.test.ts
- packages/nocodb/tests/unit/rest/tests/filter.test.ts
- Xcdb project: hence even data is generated locally for required datatypes, instead of using sakila
- Covered so far
- Text based : single line, long text, phone number, email, url
- Numerical : number, decimal, percent, currency, rating, duration
- Select based : single & multi select
> test: UT for filter APIs

- packages/nc-gui/components/template/Editor.vue
- packages/nc-gui/composables/useTable.ts
- for import on the landing page, `baseId` is not provided which causes the issue. This PR is to add the default base id if it is not provided.
Use the csv provided by user in the issue.
> fix(nc-gui): use the default base id if baseId is not provided

- packages/nocodb/src/lib/meta/api/userApi/initStrategies.ts
- packages/nocodb/src/lib/v1-legacy/gql/GqlAuthResolver.ts
- packages/nocodb/src/lib/v1-legacy/rest/RestAuthCtrl.ts
- If A invites B, and B sign in without setting the password (using invite token), then it would show the reported error due to null salt. 
- This PR is to check if `user.salt` is null and remind them to sign up with the invite token to set the password first.
> fix(nocodb): prevent from hashing a null salt

- packages/nc-gui/components/cell/attachment/Modal.vue
- packages/nc-gui/components/template/Editor.vue
- packages/nc-gui/components/virtual-cell/Lookup.vue
- Render attachment cell properly in the lookup
- Render lookup cells in read-only mode
- Hide attachment edit(rename) option in read-only mode
re #5052 
> fix: Attachment lookup column bug

- packages/nocodb/src/lib/meta/api/attachmentApis.ts
Allows uploads for public base url users with editors. This was not working anymore in the latest versions (and I am not sure it was ever implemented correctly).
This fix is probably not 100% correct, but I need a working docker image for my quickfix, but don't I am not able to create the image manully successfully, so I created this PR.
* Share a project via the public base url with editor role.
* Try to upload a file on an attachment field when using the base url.
> Allow uploads for public base url users with editor role

- packages/nc-gui/components/dashboard/TreeView.vue
- packages/nc-gui/composables/useApi/interceptors.ts
- packages/nc-gui/composables/useCellUrlConfig.ts
- packages/nc-gui/composables/useDashboard.ts
- packages/nc-gui/composables/useLTARStore.ts
- packages/nc-gui/composables/useProject.ts
- packages/nc-gui/composables/useTabs.ts
- packages/nc-gui/composables/useViewData.ts
- packages/nc-gui/plugins/tele.ts
- Changed useProject and useTabs to shared composable from injection state
- Change useRoute logic on composables and plugins
- Reset project state when out of {projectType} path
Composable useRoute from nuxt3 depends on <NuxtPage>, if we use it within composables (especially interlinked composables for example: Within component we use composable A and from composable A we call composable B which use useRoute composable) it is inconsistent. (it is either undefined or static)
To avoid this behavior in composables we are now relying on useRouter (which doesn't have any stability issue) and get currentRoute as a ref from it.
So
```
const route = useRoute()
```
becomes
```
const router = useRouter()
const route = $(router.currentRoute)
```
We used to use injection state for project and tabs, …
> feat: use shared composable for project and tabs

- packages/nc-gui/assets/style.scss
- packages/nocodb/src/lib/db/sql-client/lib/KnexClient.ts
- packages/nocodb/src/lib/meta/api/columnApis.ts
- packages/nocodb/src/lib/meta/api/helpers/index.ts
- packages/nocodb/src/lib/meta/api/helpers/populateMeta.ts
- packages/nocodb/src/lib/meta/api/metaDiffApis.ts
- packages/nocodb/src/lib/models/GridViewColumn.ts
- packages/nocodb/src/lib/models/Model.ts
- packages/nocodb/src/lib/models/View.ts
- packages/nocodb/src/lib/version-upgrader/ncStickyColumnUpgrader.ts
Populate a unique foreign key constraint name rather than relying on knex generated name.
re #4615
> fix: Populate unique fk constraint name 

- packages/nocodb/src/lib/Noco.ts
- packages/nocodb/src/lib/meta/api/helpers/populateMeta.ts
- packages/nocodb/src/lib/meta/helpers/mapDefaultDisplayValue.ts
- packages/nocodb/src/lib/models/Model.ts
- packages/nocodb/src/lib/version-upgrader/NcUpgrader.ts
- packages/nocodb/src/lib/version-upgrader/ncStickyColumnUpgrader.ts
Re #5122 
- assign first column as display value if no pk
- assign pk as display value if no other columns
- handle missing display value in ncStickyUpgrader
- drop possible duplicated display values when display value updated
> fix: missing display value

- packages/nc-gui/composables/useProject.ts
- packages/nc-gui/pages/[projectType]/[projectId]/index/index/index.vue
PR for:
- closes https://github.com/nocodb/nocodb/issues/5103
- [ x ] fix: (bug fix for the user, not a fix to a build script)
1. The useProject.ts file in the nc-gui package:
A filter has been added to the bases computed property to only include those that have the enabled property set to true.
2. The index.vue file in the nc-gui package:
The baseId property has been added to the openQuickImportDialog function, and it is set to the id of the first base in the bases array that has the enabled property set to true.
In summary, these changes filter out disabled bases in the bases computed property, and pass the id of the first enabled base to the openQuickImportDialog function as the baseId property.
You can test it like in the issue description
> fix: wrong baseid in QuickImport

- packages/nc-gui/components/account/ResetPassword.vue
- packages/nc-gui/components/general/MiniSidebar.vue
- packages/nc-gui/components/smartsheet/header/Cell.vue
- packages/nc-gui/composables/useApi/interceptors.ts
- packages/nc-gui/composables/useGlobal/actions.ts
- packages/nc-gui/layouts/base.vue
- packages/nc-gui/pages/[projectType]/[projectId]/index.vue
- packages/nc-gui/pages/index/index/user.vue
- packages/nocodb-sdk/src/lib/Api.ts
- packages/nocodb/src/lib/meta/api/userApi/userApis.ts
- packages/nocodb/src/schema/swagger.json
- Hide the column edit option from the shared form
- Add logout API for clearing refresh token from cookie and database to avoid automatic token generation in GUI
closes #5205 
closes #5197
> fix: Remove double click column edit option from shared form

- charts/nocodb/templates/pvc.yaml
This feature of allowing custom PVC access modes in the NocoDB Helm chart can be very useful for several reasons. One of the main reasons is that it provides greater flexibility and control over the storage of the application's data.
In a Kubernetes cluster, different workloads may have different storage requirements. For example, some applications may require shared read-write access to a common set of data, while others may require only read-only or write-only access. By allowing the customization of PVC access modes, the NocoDB Helm chart can better support a wider range of storage requirements and provide more fine-grained control over the access mode of the PVC.
In addition, some managed Kubernetes providers, such as certain cloud providers, do not have a standard way to create …
> add feature to set custom pvc access mode, e.g. read-write-many

- packages/nc-gui/components/cell/Checkbox.vue
- packages/nc-gui/components/cell/ClampedText.vue
- packages/nc-gui/components/cell/Currency.vue
- packages/nc-gui/components/cell/Text.vue
- packages/nc-gui/components/cell/TextArea.vue
- packages/nc-gui/components/smartsheet/Cell.vue
- packages/nc-gui/components/smartsheet/expanded-form/Header.vue
- packages/nc-gui/components/smartsheet/expanded-form/index.vue
- packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
- packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue
- packages/nc-gui/components/webhook/Editor.vue
- packages/nc-gui/composables/useExpandedFormStore.ts
- tests/playwright/pages/Dashboard/ExpandedForm/index.ts
- tests/playwright/pages/Dashboard/Grid/index.ts
- tests/playwright/pages/Dashboard/common/Cell/index.ts
> UI enhancement and fixes

- packages/nc-gui/components/webhook/Editor.vue
with `NC_CLOUD=true`, eventOperation will be blocked since the logic is inside loadPluginList. Since eventOperation and onNotTypeChange logic doesn't relate to loadPluginList, this PR is simply to move them out.
> fix(nc-gui): move eventOperation and onNotTypeChange logic out of loadPluginList

- packages/nocodb-sdk/src/lib/formulaHelpers.ts
- handle `\` in formula. Use `\\`. closes #5315
- handle `'` in formula. Use `\'`.
```
CONCAT("\\", "A")
```
```
CONCAT("\'", "A")
```
> fix(sdk): escapeLiteral

- packages/nc-gui/components/dashboard/TreeView.vue
- packages/nc-gui/layouts/shared-view.vue
- packages/nc-gui/nuxt.config.ts
- Set meta title to `<project_title>: <table_title> | NocoDB` if applicable
- Set meta title to `<table_title> | NocoDB` for shared view (project title will not be disclosed)
> feat: title tag

- packages/nc-gui/components/smartsheet/sidebar/RenameableMenuItem.vue
From DF - Tried to rename form: thought that clicking outside of name edit text field means 'saving'
> refactor(nc-gui): use VNodeRef for focusInput & blur to call onRename

- packages/nc-gui/components/account/UsersModal.vue
- packages/nc-gui/components/cell/Email.vue
- packages/nc-gui/components/cell/Url.vue
- packages/nc-gui/components/smartsheet/Cell.vue
- packages/nc-gui/components/smartsheet/Form.vue
- packages/nc-gui/components/tabs/auth/user-management/UsersModal.vue
- packages/nc-gui/context/index.ts
- packages/nc-gui/lang/en.json
- packages/nc-gui/pages/[projectType]/form/[viewId]/index/index.vue
- packages/nc-gui/pages/[projectType]/form/[viewId]/index/survey.vue
- packages/nc-gui/utils/validation.ts
- tests/playwright/pages/Dashboard/Form/index.ts
- tests/playwright/pages/Dashboard/SurveyForm/index.ts
- Email Validation in Form View (invalid value won't be saved - error message will be shown once blurred)
- URL Validation in Form View (invalid value won't be saved - error message will be shown once blurred)
- avoid setting invalid email value in Grid View (similar to URL)
- fix incorrect required toggle logic in Form View (Playwright)
> enhancement: validations

- packages/nc-gui/components/smartsheet/Cell.vue
> Editing in Grid view would send update request twice
`emit('save')` will be triggered in `vModel.set`. Hence, we don't need to trigger again in `syncAndNavigate`. Since there is no sync in `syncAndNavigate`, `syncAndNavigate` will be renamed to `navigate`.
> fix(nc-gui): extra patch request

- tests/playwright/pages/ProjectsPage/index.ts
- tests/playwright/tests/projectOperations.spec.ts
Project operations test suite was flaky. Could be
- because of flicker in project rename modal
- project being created already existed (due to retry may be)
Proposed remedy
- ensure project is removed always before test (using API)
- add a second delay to ensure rename modal flicker is sorted out
> test: fix project operations flaky test

- packages/nocodb/src/lib/db/sql-client/lib/pg/PgClient.ts
This change adds a schemaExists check. The check doesn't need `CREATE ON DATABASE` permissions. Whereas the `CREATE SCHEMA IF NOT EXISTS ??  AUTHORIZATION ?? ` does.
So it avoids throwing an error in case where both: 
- The schema already exists
- The user doesn't have  `CREATE ON DATABASE` permission
Fixes issue: https://github.com/nocodb/nocodb/issues/5398
Running loaclly. Awaiting workflow
> fix(nocodb): Add postgres data source w/o `CREATE ON DATABASE` permission

- packages/nc-gui/components/dashboard/settings/AuditTab.vue
- packages/nc-gui/components/smartsheet/Pagination.vue
- packages/nc-gui/components/tabs/auth/UserManagement.vue
- packages/nc-gui/components/webhook/CallLog.vue
- add missing `v-model` to `page-size` according to the doc. Otherwise, page size indicator won't be changed. See the one in Audit.
> fix(nc-gui): page-size in pagination

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
closes: #5456
- previously we only handle `(x,y,z)` but not `(x,y)`
> fix(nocodb): add missing parsing logic

- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/pg.ts
- fix incorrect search formula in pg (closes: #5460)
```
IF((SEARCH({Title}, "Beides") != 0), "2.0","WRONG")
```
> fix(nocodb): search formula in pg.ts

- packages/nc-gui/components/cell/attachment/Image.vue
- packages/nc-gui/components/smartsheet/Cell.vue
- packages/nc-gui/composables/useAttachment.ts
- packages/nocodb-sdk/src/lib/Api.ts
- packages/nocodb/src/lib/controllers/publicControllers/publicData.ctl.ts
- packages/nocodb/src/lib/services/attachment.svc.ts
- packages/nocodb/src/lib/services/public/publicData.svc.ts
- packages/nocodb/src/schema/swagger.json
- fix request body content type - use `multipart/form-data` so that `multer` would work
- closes: #5434
> fix(nc-gui): form attachments

- packages/noco-docs/content/en/developer-resources/rest-apis.md
- packages/noco-docs/content/en/developer-resources/sdk.md
- packages/noco-docs/content/en/getting-started/upgrading.md
- packages/noco-docs/content/en/index.md
- packages/noco-docs/content/en/setup-and-usages/meta-management.md
- packages/noco-docs/content/en/setup-and-usages/table-operations.md
Currently if you directly access a page then click a link, the target link will not be correct. This PR is to change `<a href="...">...</a>` to `<NuxtLink/>` with full path for all internal routes. External routes will remain unchanged. 
- closes: #5468
> docs: adopt NuxtLink for internal routes

- packages/nc-gui/components/smartsheet/toolbar/FilterInput.vue
- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/conditionV2.ts
- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/helpers/formulaFnHelper.ts
- for `eq` in datetime filter, it will check the date only. (following AT pattern)
- closes: #5483
> fix(nc-gui): datetime filters

- packages/nc-gui/components/smartsheet/expanded-form/Comments.vue
- packages/nocodb-nest/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
- currently comments would show `The following comment has been created: <comment>` which is from audit description. In comment component, we just need to show the comment part.
- fix missing audit edit details
- if details are not found, use description instead.
before
after
> fix(nc-gui): retrieve the comment part from the audit description

- packages/nocodb-nest/src/services/public-datas.service.ts
- previously you can see the error in network tab if a shared kanban contains hm / mm
> fix(nocodb): allow kanban for calling publicHmList and publicMmList

- charts/nocodb/Chart.yaml
- charts/nocodb/values.yaml
This diff adds support for MySQL to the Helm chart used to deploy NocoDB on Kubernetes. Specifically, it makes the following changes:
In Chart.yaml, it adds a new dependency on the MySQL chart from the Bitnami repository, and sets a condition for enabling it (mysql.enabled).
In values.yaml, it adds a new environment variable (NC_DB) that specifies the connection string for the MySQL database. It also adds a new section for configuring the MySQL chart, including authentication credentials and persistence settings. The enabled flag for MySQL is set to false by default.
Overall, this change allows users to deploy NocoDB using MySQL as the underlying database instead of Postgres, providing more options for managing the application's data.
- [ x ] feat: (new feature for the user, not a new …
> add mysql to helm chart

- packages/nc-gui/components/cell/Currency.vue
- change the input type to `number`
- show currency code for `0`
- closes: #5607
> fix(nc-gui): currency field

- packages/nc-gui/components/smartsheet/header/Menu.vue
- packages/nocodb/src/services/columns.service.ts
We were only removing it from meta (as we only call Model.delete over it) which causing unnecessary mm tables to exist in database.
> fix: drop mm table on column delete

- packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
- packages/nc-gui/components/webhook/Editor.vue
- packages/nc-gui/composables/useViewFilters.ts
- packages/nocodb/src/Noco.ts
- packages/nocodb/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/db/sql-client/lib/sqlite/SqliteClient.ts
- packages/nocodb/src/models/Model.ts
- packages/nocodb/src/modules/event-emitter/fallback-event-emitter.ts
- packages/nocodb/src/modules/event-emitter/nestjs-event-emitter.ts
- packages/nocodb/src/modules/metas/metas.module.ts
- packages/nocodb/src/services/hook-handler.service.spec.ts
- packages/nocodb/src/services/hook-handler.service.ts
- tests/playwright/pages/Dashboard/Grid/index.ts
- tests/playwright/pages/Dashboard/WebhookForm/index.ts
- tests/playwright/pages/Dashboard/common/Cell/index.ts
- tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts
- tests/playwright/tests/db/filters.spec.ts
- tests/playwright/tests/db/undo-redo.spec.ts
- We generate data using local machine timezone, so use local timezone on tests as well.
- wait for response on child expand and row unlink
- we rely on viewId from BaseModelSqlv2 but we don't enforce it on creation, so I map default view for model if no viewId provided
> test: time filter timezone fix

- packages/nocodb/src/controllers/filters.controller.ts
- packages/nocodb/src/services/filters.service.ts
- closes: #5639
- previously `filterParentId` is always undefined since we haven't added `@Param()` decorator for `filterParentId`.
> fix(nc-gui): filter nested group

- packages/nocodb/src/middlewares/public/public.middleware.ts
- in docker, `process.cwd()` is `/usr/src/app` while the public directory is `/usr/src/app/docker/public`
- closes: #5125
> fix(nocodb): incorrect public path for docker

- packages/nc-gui/composables/useSharedFormViewStore.ts
- tests/playwright/pages/SharedForm/index.ts
- tests/playwright/tests/db/viewForm.spec.ts
- currently the column takes from form columns which is not expected. revised the logic in `useSharedFormViewStore.ts`
- closes: #5694
> fix(nc-gui): incorrect shared form logic

- build-local-docker-image.sh
- packages/nocodb/Dockerfile.local
- packages/nocodb/webpack.local.config.js
1. modularised shell script "build-local-docker-image.sh". Breaking down into smaller functions. 
2. stdout all the messages to a dedicated file so future debugging becomes easier
3. npm uninstall nocodb-sdk is removed from here and its now happening in DockerFile. This will help avoiding an updated to package.json and package-lock.json in local git repo. 
4. fix module.exports.node from packages/nocodb/webpack.local.config.js. This was failing under certain versions of node
- [x ] refactor: (refactoring production code, eg. renaming a variable)
- [ x] chore: (updating grunt tasks etc; no production code change)
> chore: clean up image build script and bug fix with packaging

- packages/nocodb/package-lock.json
- packages/nocodb/package.json
- packages/nocodb/src/controllers/projects.controller.ts
- packages/nocodb/src/middlewares/public/public.middleware.ts
- In non-docker container runtime, we are still seeing the issue where the swagger API views are not properly loaded after #5693 . Using https://github.com/sindresorhus/is-inside-container instead of `is-docker` to account for both docker and non-docker container runtimes.
> fix(nocodb):use is-inside-container to account ffor non-docker container runtime

- packages/nocodb/src/models/Model.ts
Previously we only allowed one base so `base_id` wasn't included in the cache key. Since currently multiple bases are possible, hence this PR is to include it.
- closes: #5701
- closes: #5568
> fix(nocodb): model list cache

- packages/nocodb/src/models/Base.ts
- packages/nocodb/src/services/app-init.service.ts
- packages/nocodb/src/version-upgrader/NcUpgrader.ts
- packages/nocodb/src/version-upgrader/ncProjectConfigUpgrader.ts
This pull request addresses an encryption issue introduced in version 0.107.0. In that version, a temporary fallback secret key was used for JWT token encryption and project base config encryption, causing projects created in 0.107.0 to be unable to decrypt their project base config.
To resolve this issue, this PR updates(using an upgrader) the project base config encryption by using the correct secret key. By updating the encryption, we ensure that all projects created from version 0.107.0 onwards can successfully decrypt their project base config.
- Create a project using 0.107.0
- Add an external datasource
- Now connect the same source to our latest version and it may fail to extract config
- test on this branch or PR build with the same `NC_DB`
Anything for maintainers to be made …
> fix: Update project base config encryption with proper secret key

- packages/nocodb-sdk/src/lib/Api.ts
- packages/nocodb/src/schema/swagger.json
Column dtxp property will be options for select columns which can be longer than 255 (StringOrNull type has 255 maxLength). We have no limit on option count, so it can exceed that limit which results with ajv schema error (TableReqType > NormalColumnRequestType > dtxp).
Note: it is already like this in ColumnType
> fix: drop dtxp max length from column request schema

- packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
See Issue #5648 for context. The changes I made should fix that and remove the dropdown from appearing on the first issue, thereby reducing confusion on why there's a boolean operator selector at the front of the filtering UI.
When adding a filter group, this is what it looks like:
Let's say I added a filter at the bottom of the filter group (or filter) and then deleted the top filter. The "Where" word will automatically update.
Before deleting top filter group:
After deleting top filter group:
This applies to the nested ones as well.
> fix(nocodb): Fixed filtering boolean visual bug

- package.json
- scripts/installLocalSdk.js
- one command to install and build sdk, and install local sdk for frontend and backend.
```
npm run install:local-sdk
```
- used after release / include in github action in the future.
> feat: add install:local-sdk

- packages/nc-gui/components/cell/ClampedText.vue
- packages/nc-gui/components/cell/MultiSelect.vue
- packages/nc-gui/components/cell/SingleSelect.vue
- packages/nc-gui/components/cell/Text.vue
- packages/nc-gui/components/cell/TextArea.vue
- packages/nc-gui/components/smartsheet/Grid.vue
- packages/nc-gui/components/virtual-cell/QrCode.vue
- packages/nc-gui/components/virtual-cell/barcode/Barcode.vue
- packages/nc-gui/context/index.ts
- tests/playwright/tests/db/toolbarOperations.spec.ts
- tests/playwright/tests/db/undo-redo.spec.ts
Re #5077
- Tiny css change for rendering new lines
- Wrap MultiSelect tags based on row height
Before
After
MultiSelect example
> feat: render new lines for LongText

- packages/nc-gui/components/cell/MultiSelect.vue
- packages/nc-gui/components/cell/SingleSelect.vue
- packages/nc-gui/components/smartsheet/Grid.vue
- packages/nc-gui/composables/useMultiSelect/index.ts
- MultiSelect order when cell is active
- Improve hiding context menu (avoid showing changed menu before closing)
- Revised mouse event handling
- moved click part to mousedown/up (to avoid handling same part twice)
- scroll to cell on mouseover while selecting
- disable edit mode on changing active cell
- avoid setting `isMouseDown` flag if edit enabled (some cells shrink after edit mode)
> fix: various fixes for UI

- packages/nocodb/package-lock.json
- packages/nocodb/package.json
- packages/nocodb/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/modules/jobs/jobs/at-import/helpers/readAndProcessData.ts
- packages/nocodb/src/services/bulk-data-alias.service.ts
This should fix heap out of memory issues on import
> fix: dynamic batch based on byte size

- tests/playwright/tests/db/features/timezone.spec.ts
Root DB support for MySQL & PG was added recently for CI. Enabling Timezone XCDB tests hence.
> test: enable timezone spec for mysql & pg

- packages/nocodb/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/db/conditionV2.ts
Added a check on the WherePK constructor to check if the data type on the db is binary(16) and if the pk is a valid uuid.
If it's a uuid then returns it as a Binary.
> Fixed bug when trying to open a row with a binary encoded uuid as PK

- packages/nocodb/src/db/sql-mgr/code/models/xc/ModelXcMetaMssql.ts
- packages/nocodb/src/db/sql-mgr/code/models/xc/ModelXcMetaMysql.ts
- packages/nocodb/src/db/sql-mgr/code/models/xc/ModelXcMetaOracle.ts
I found bug for Sync existing Data Sources specifically for Mysql Database.
If type of field in existing Database is JSON, we can't edit the json because invalid render. see the image below
it because wrong mapping UI Data Type in process Sync Meta Data Source.
this PR just change mapping UI Data type from this:
```
case 'json':
return 'LongText';
```
to this
```
case 'json':
return 'JSON';
```
Result of this changes look like this.
> fix: wrong mysql meta sync UI Data Type

- packages/nc-gui/components/smartsheet/Form.vue
- packages/nc-gui/pages/[projectType]/form/[viewId]/index.vue
- packages/nc-gui/pages/[projectType]/form/[viewId]/index/index.vue
> fix: text input overflow on focus

- packages/nc-gui/components/general/HelpAndSupport.vue
- packages/nc-gui/pages/[projectType]/[projectId]/index.vue
- packages/nc-gui/plugins/jobs.ts
- packages/nc-gui/plugins/tele.ts
- packages/nocodb/src/gateways/socket.gateway.ts
- packages/nocodb/src/modules/jobs/jobs.gateway.ts
- Fixed a socket error that occurred when using a reverse proxy.
- Change socket request address to `appInfo.ncSiteUrl` base.
- Change the socket namespace correctly.
- Request swagger url based on to `NC_PUBLIC_URL` environment variable.
This fix was implemented in response to the reported issue with the number #6147.
1. set nginx.conf and run nginx
```
location /nocodb/dashboard {
proxy_pass http://localhost:8080/nocodb/dashboard;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
location /nocodb/ {
proxy_pass http://localhost:8080/;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme; …
```
> Fixed: Reverse proxy by nocodb

- packages/nc-gui/lib/enums.ts
The word `한국인` means the Korean people, so in this case, '한국어' is correct, which means the language of Korea.
https://en.wikipedia.org/wiki/Korean_language
> fix: language name correction for ko

- packages/noco-docs/content/en/setup-and-usages/languages.md
Small typo at https://docs.nocodb.com/setup-and-usages/languages/
lanuages => languages
> typo (lanuages => languages)

- packages/noco-docs/content/en/setup-and-usages/formulas.md
Doc. on formulas.
incorrect use of $ instead of {}
Typos
> formulas doc: typos. inccorect $ sign.

- docker-compose/traefik/docker-compose.yml
The traefik `docker-compose.yml` references an env variable `CLOUDFLARE_TOKEN` that does not exist in the corresponding env file:
https://github.com/nocodb/nocodb/blob/develop/docker-compose/traefik/docker-compose.yml#L65
https://github.com/nocodb/nocodb/blob/develop/docker-compose/traefik/.env#L3
This PR replaces it with the correct env. I chose to update the compose file instead of the env file because the `CF_DNS_API_TOKEN` name is easier to google in order to figure out permissions needed for the token.
`docker compose up` should result in traefik being able to acquire an SSL cert.
-
> fix:  replace reference to missing env in docker-compose/traefik

- packages/nc-gui/layouts/shared-view.vue
> fix: i18n translation button

- packages/nc-gui/components/cell/TextArea.vue
- packages/nc-gui/components/cell/attachment/index.vue
* Expand icon is made visible only on click in case of Long Text and Attachment
* Also made the same changes to drop-files icon in Attachment
* Expand icon in Long Text is replaced with the one used in Attachment
Old
New
> fix(nc-gui): expand icon made visible on click

- packages/nocodb/src/services/api-docs/swagger/templates/params.ts
> fix: Missing Links column in swagger child api path param list

- packages/nocodb/src/models/ProjectUser.ts
Add `${MetaTable.PROJECT_USERS}.created_at as created_at`  to getUsersList function.
Before fix:
After fix:
> fix: project collaborators "Date Joined" is always "a few seconds ago"

- packages/nc-gui/components/cell/TextArea.vue
- packages/nc-gui/components/smartsheet/Cell.vue
Long text expand button enabled in shared view.
> fix(nc-gui): long text expand in shared view

- packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
- Adjusted bottom border radius when one single field
Closes #6523
> fix: fix bottom radius when one field

- packages/nc-gui/components/cell/attachment/utils.ts
- packages/nc-gui/composables/useAttachment.ts
- packages/noco-docs/versioned_docs/version-0.109.7/020.getting-started/020.environment-variables.md
- packages/nocodb/package.json
- packages/nocodb/src/cache/CacheMgr.ts
- packages/nocodb/src/cache/NocoCache.ts
- packages/nocodb/src/cache/RedisCacheMgr.ts
- packages/nocodb/src/cache/RedisMockCacheMgr.ts
- packages/nocodb/src/controllers/attachments-secure.controller.ts
- packages/nocodb/src/controllers/attachments.controller.ts
- packages/nocodb/src/controllers/public-datas-export.controller.ts
- packages/nocodb/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/models/PresignedUrl.ts
- packages/nocodb/src/models/TemporaryUrl.ts
- packages/nocodb/src/models/index.ts
- packages/nocodb/src/modules/datas/helpers.ts
- packages/nocodb/src/modules/metas/metas.module.ts
- packages/nocodb/src/plugins/s3/S3.ts
- packages/nocodb/src/plugins/storage/Local.ts
- packages/nocodb/src/services/attachments.service.ts
- packages/nocodb/src/utils/globals.ts
- pnpm-lock.yaml
- tests/playwright/tests/db/columns/columnAttachments.spec.ts
Adds signed/temporary attachment support for both local and S3.
So we will return signedPath/signedUrl with api response which will be available only set period of time (Defaults to 2 hours can be changed via NC_ATTACHMENT_EXPIRE_SECONDS).
(Note: expiration time is rounded to next xy:z0 so within period of 10 mins we return same link)
This change is backwards compatible (supports old links) unless user specifies NC_SECURE_ATTACHMENTS=true in his environment.
> feat: signed attachments

- packages/nocodb/src/db/BaseModelSqlv2.ts
* fixed Row ID not showing on DELETE
> fix(nocodb): rowId issue after in audit log

- charts/nocodb/templates/deployment.yaml
- charts/nocodb/templates/pvc.yaml
- charts/nocodb/values.yaml
Make the Kubernetes volume optional, enabled by default
> make volume optional

- packages/nocodb/src/services/columns.service.ts
There was a problem restricting us to add columns with special characters
> fix: allow special characters in column aliases

- packages/nc-gui/components/smartsheet/grid/GroupBy.vue
- avoid expanding to fill page if table is small
> fix: group by for small tables

- packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
- tests/playwright/pages/Dashboard/TreeView.ts
- tests/playwright/tests/db/features/baseShare.spec.ts
hide context menu for shared base
> fix: hide context menu for shared base

- packages/nc-gui/components/template/Editor.vue
- packages/nc-gui/composables/useColumnCreateStore.ts
- packages/nc-gui/utils/validation.ts
- packages/nocodb/src/helpers/columnHelpers.ts
- packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
- packages/nocodb/src/services/columns.service.ts
- packages/nocodb/src/services/tables.service.ts
- Allow column title up to 255 for all database types, and truncate column_name on backend if required
> feat: limit column title to 255 for all db types

- scripts/upgradeNocodbSdk.js
- Exclude pw from script as it should always target local sdk
> chore: exclude pw package.json

- packages/nc-gui/utils/workerUtils.ts
- closes: #6720 
Previously, we were using `new Worker` for worker url. However, if we deploy to cloud, it would cause `XXX cannot be accessed from origin YYY`, since `app.nocodb.com` couldn't access `cdn.nocodb.com` due to CORS. In #6708, `crossoriginworker` was introduced which solves the above issue but it breaks the local case - `Cannot use import statement outside a module`.
This PR is simply to 
- cover both cloud & local cases
- and remove `getWorkerURL` since it is not in use.
Try the CDN url & local worker url for testing locally.
> fix(nc-gui): initWorker logic and remove unused code

- packages/nc-gui/components/cell/Json.vue
> fix: JSON cell height based on user selected row height

- packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
During import, date/dateTime type filters were ignored as they were not supported earlier. @wingkwong had fixed date related filters, but it wasn't applied to airtable import earlier. 
> feat: import date/datetime filters from airtable

- packages/nocodb/src/helpers/getAst.ts
- Avoid getting unnecessary system column(HM relation to junction table) if getHiddenColumn is defined
> fix: Avoid getting unnecessary system column if getHiddenColumn is defined

- packages/nc-gui/components/erd/View.vue
- packages/nc-gui/composables/useTableNew.ts
- Error toast message when switching to another table from ERD view
- `"TypeError: Cannot read properties of undefined (reading 'columns')"` - Error when opening ERD view directly using url
> fix: Bugs related to ERD

- packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
My pull request resolves fields dropdown UI closes: #6781
Handle longer text by adding text ellipsis using TailwindCSS and showing full name on hover using NcTooltip.
Before
After
Hover
> fix(nc-gui): add ellipsis and show full name on hover

- packages/nocodb/src/services/columns.service.ts
> fix: include schema name in multiselect option update query

- packages/nocodb/src/db/BaseModelSqlv2.ts
- input `2023-11-01 12:00` and refresh. It should keep the same value.
> fix(nocodb): pg datetime issue

- packages/nc-gui/components/cell/DateTimePicker.vue
closes: https://github.com/nocodb/nocodb/issues/5988
Monday as first day of week in calendar popup
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
> feat: Monday as first day of week in calendar popup

- packages/nc-gui/components/account/License.vue
- packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
- packages/nc-gui/components/dashboard/TreeView/TableList.vue
- packages/nc-gui/components/dashboard/TreeView/TableNode.vue
- packages/nc-gui/components/dashboard/TreeView/index.vue
- packages/nc-gui/components/dlg/QuickImport.vue
- packages/nc-gui/components/workspace/ProjectList.vue
- packages/nc-gui/composables/useGlobal/actions.ts
- packages/nc-gui/composables/useGlobal/index.ts
- packages/nc-gui/helpers/parsers/JSONUrlTemplateAdapter.ts
- packages/nc-gui/package.json
- packages/nc-gui/plugins/state.ts
- pnpm-lock.yaml
This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.
> fix: import nuxt composables from #imports

- packages/nocodb/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/db/conditionV2.ts
- Support blank operation in filter with different format
- Negated filter operation missing null values when filtering using LTAR(Belongs To)
> fix: Issues related to filter

- packages/nc-gui/middleware/auth.global.ts
> fix:  Google OAuth based token generation logic correction

- packages/nocodb/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/models/Model.ts
- packages/nocodb/src/services/datas.service.ts
- packages/nocodb/tests/unit/rest/tests/groupby.test.ts
> fix: Avoid applying default view filter and sort if viewId is not passed

- packages/nocodb/src/services/columns.service.ts
Knex trims leading and trailing spaces by default which ends up breaking our behavior (alias and title is different).
We will trim them on our side as well to match that behavior.
> fix: trim leading and trailing spaces from column titles

- packages/nc-gui/components/dlg/ColumnDuplicate.vue
- packages/nc-gui/components/smartsheet/header/Menu.vue
- packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.processor.ts
- packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
Re #6874
Formula column still keeps old titles inside **formula_raw** after column title change. This was causing duplicate to break. I replaced logic to derive formula_raw from formula (which uses column ids, we use this while rendering as well so it is not breaking after title change)
> fix: duplicate formula column after alias change

- renovate.json
- `onlyNpm` has been merged to default preset. We don't need to extend anymore.
- closes: #6993 
> fix(renovate): remove onlyNpm & enable it again

- packages/noco-docs/docs/150.engineering/070.translation.md
Fix GitHub casing in Translation page
> Fix GitHub casing in Translation page

- packages/nocodb/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/db/conditionV2.ts
- packages/nocodb/src/db/generateLookupSelectQuery.ts
- packages/nocodb/src/db/sortV2.ts
- packages/nocodb/src/helpers/catchError.ts
- packages/nocodb/src/helpers/getAst.ts
> refactor: Uniform error message

- .github/workflows/release-docker.yml
- .github/workflows/release-npm.yml
- scripts/upgradeNocodbSdk.js
- Depending on `workspace: ^` we need to manually push that change to master after release, we can instead use package name to replace the version
(see rn after the release master have versions instead of workspace: ^)
- Add --ignore-workspace for pnpm install of nocodb-sdk as we need to publish before bumping other packages
> chore: logic for replacing version

- packages/nocodb-sdk/src/lib/formulaHelpers.ts
- packages/nocodb/src/db/BaseModelSqlv2.ts
- Knex have limitations with special characters (especially dot)
- PG doesn't support >65 length aliases and automatically trims them
To avoid those issues and further issues from raising, we can replace all aliases (column.title) with ids, so they are fixed length and never contains special characters. After running the query we will remap them with the titles.
Disadvantage is we end up with an extra post-processing (substituteColumnIdsWithColumnTitles)
It is pretty much straight forward process but for BelongsTo type we need to do extra fetching.
Further optimizing: We have post-processing for date/attachment and now aliases, so we end up iterating data multiple times, I think we can wrap all together to shrink iterations.
> feat: id instead title in queries

- markdown/readme/languages/spanish.md
- At the end of "Por qué estamos construyendo esto?" and  "Nuestra misión" extra quotation marks, removed.
- There is a miss-translation between spanish billions and english billions, in spanish "billions" refers to: 1,000,000,000,000, while in english billions is 1,000,000,000, if we want to refer to the english quantity the correct term is "miles de millones" (thousands of millions).
> Subtle update to spanish.md

- packages/nocodb/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/services/columns.service.ts
- packages/nocodb/tests/unit/factory/column.ts
- packages/nocodb/tests/unit/rest/tests/filter.test.ts
> fix: Validate select options before insert

- packages/nocodb/src/strategies/authtoken.strategy/authtoken.strategy.ts
Closes #7084
- use getWithRoles for auth token
> fix: use getWithRoles for auth token strategy

- packages/nc-gui/components.d.ts
- packages/nc-gui/components/cell/Percent.vue
- packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
- packages/nc-gui/components/smartsheet/column/PercentOptions.vue
- packages/nc-gui/components/smartsheet/column/PercentOptionsLegacy.vue
> feat: display as progress

- packages/nocodb/src/helpers/apiHelpers.ts
Use getSchema to avoid compiling validator multiple times.
> fix: use getSchema instead of validate for ajv

- packages/nc-gui/composables/useViewColumns.ts
**Error Occurred In** : 
when changing the name from column headers the column names was not updated in **fieldsMenu**
Fixed column syncing in  **useViewColumnOrThrow** Hook
> fix : fixed column syncing in useViewColumnsOrThrow hook

- packages/nc-gui/components/smartsheet/column/DefaultValue.vue
- packages/nocodb/src/services/columns.service.ts
> fix: Escape single quote properly and when updating single select default value

- packages/nocodb/src/controllers/tables.controller.ts
- packages/nocodb/src/filters/global-exception/global-exception.filter.ts
- packages/nocodb/src/interface/config.ts
- packages/nocodb/src/middlewares/extract-ids/extract-ids.middleware.ts
- packages/nocodb/src/strategies/authtoken.strategy/authtoken.strategy.ts
- packages/nocodb/src/strategies/base-view.strategy/base-view.strategy.ts
- packages/nocodb/src/strategies/google.strategy/google.strategy.ts
- packages/nocodb/src/strategies/jwt.strategy.ts
- packages/nocodb/src/types/express.d.ts
Closes #7084
we are referring ncProjectId as ncBaseId which is expected after rename, so I renamed all occurences of ncProjectId with ncBaseId
> fix: rename ncProjectId to ncBaseId

- packages/nocodb/src/schema/swagger.json
closes #6078 
Refresh Token API docs become more descriptive and easy to understand
fix: (insufficient and incorrect documentation for /auth/token/refresh)
> fix : insufficient and incorrect documentation for /auth/token/refresh endpoint

- packages/nocodb/src/cache/RedisCacheMgr.ts
- packages/nocodb/src/cache/RedisMockCacheMgr.ts
Avoid appending if list is not present in cache.
> fix: append before getList

- packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
- packages/nc-gui/components/webhook/Editor.vue
- packages/nocodb/src/helpers/webhookHelpers.ts
> Nc feat/webhook conditions

- packages/nc-gui/components/cell/RichText.vue
- packages/nc-gui/composables/useMultiSelect/index.ts
> fix: rich text first char issue

- packages/nocodb/src/db/BaseModelSqlv2.ts
> fix: Has-many unlink api - accept array of object with primary key

- tests/playwright/pages/Base.ts
- tests/playwright/pages/Dashboard/Grid/Column/index.ts
- tests/playwright/tests/db/columns/columnFormula.spec.ts
formula tests to run based on supported db type
pw formula tests for mysql regex
remove sqlite exclusion for LOG test
> pw formula tests, check formula not supported error

- packages/nc-gui/components/cell/Checkbox.vue
- packages/nc-gui/components/cell/Currency.vue
- packages/nc-gui/components/cell/DatePicker.vue
- packages/nc-gui/components/cell/DateTimePicker.vue
- packages/nc-gui/components/cell/MultiSelect.vue
- packages/nc-gui/components/cell/Percent.vue
- packages/nc-gui/components/cell/Rating.vue
- packages/nc-gui/components/cell/SingleSelect.vue
- packages/nc-gui/components/cell/YearPicker.vue
- packages/nc-gui/components/cell/attachment/index.vue
- packages/nc-gui/components/nc/Button.vue
- packages/nc-gui/components/smartsheet/Cell.vue
- packages/nc-gui/components/smartsheet/DivDataCell.vue
- packages/nc-gui/components/smartsheet/expanded-form/index.vue
- packages/nc-gui/components/virtual-cell/BelongsTo.vue
- packages/nc-gui/components/virtual-cell/Links.vue
- packages/nc-gui/components/virtual-cell/Lookup.vue
- packages/nc-gui/components/virtual-cell/QrCode.vue
- packages/nc-gui/components/virtual-cell/barcode/Barcode.vue
- packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/index.vue
- packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/survey.vue
- tests/playwright/pages/Dashboard/common/Cell/SelectOptionCell.ts
- tests/playwright/pages/Dashboard/common/Topbar/Share.ts
- tests/playwright/tests/db/columns/columnSingleSelect.spec.ts
- tests/playwright/tests/db/views/viewForm.spec.ts
> Nc fix/tab focus

- packages/nocodb/src/middlewares/extract-ids/extract-ids.middleware.ts
> fix(nocodb): 403 forbidden message

- packages/nc-gui/components/dlg/share-and-collaborate/Collaborate.vue
- packages/nc-gui/components/project/AccessSettings.vue
- packages/nc-gui/components/workspace/CollaboratorsList.vue
- packages/nc-gui/pages/forgot-password.vue
- packages/nc-gui/pages/signin.vue
- packages/nc-gui/pages/signup/[[token]].vue
- packages/nocodb-sdk/src/lib/dateTimeHelper.ts
- tests/playwright/pages/Dashboard/common/Cell/SelectOptionCell.ts
- tests/playwright/pages/Dashboard/common/Cell/UserOptionCell.ts
> Nc fix/UI ux fixes

- packages/nc-gui/components/cell/DatePicker.vue
- packages/nc-gui/components/cell/DateTimePicker.vue
- packages/nc-gui/components/cell/Decimal.vue
- packages/nc-gui/components/cell/Duration.vue
- packages/nc-gui/components/cell/MultiSelect.vue
- packages/nc-gui/components/cell/Percent.vue
- packages/nc-gui/components/cell/SingleSelect.vue
- packages/nc-gui/components/cell/TimePicker.vue
- packages/nc-gui/components/cell/Url.vue
- packages/nc-gui/components/cell/User.vue
- packages/nc-gui/components/cell/YearPicker.vue
- tests/playwright/pages/Dashboard/Grid/Column/UserOptionColumn.ts
- tests/playwright/pages/Dashboard/Grid/Group.ts
- tests/playwright/pages/Dashboard/Grid/index.ts
- tests/playwright/pages/Dashboard/common/Cell/SelectOptionCell.ts
- tests/playwright/pages/Dashboard/common/Cell/UserOptionCell.ts
- tests/playwright/tests/db/views/viewForm.spec.ts
- Fixed select field remove btn and expand (arrow down) btn overlap issue
- Fixed NULL display in cell isn't uniform
> Fix expand button overlap issue on Select-Type related fields & NULL display in cell uniform issue

- packages/nocodb/src/cache/RedisCacheMgr.ts
> fix: avoid flushing redis when cloud init

- packages/nc-gui/package.json
- pnpm-lock.yaml
- ref: #7390
- The current package version of `v3-infinite-loading` is `@1.2.2` which is not firing `infinite` event.
```vue
<InfiniteLoading v-bind="$attrs" @infinite="loadListData">
<template #spinner>
<div class="flex flex-row w-full justify-center mt-2">
<GeneralLoader />
</div>
</template>
<template #complete>
<span></span>
</template>
</InfiniteLoading>
```
- Due to this only predefined list data is rendering in page (e.g. count=20) not all list data
- So to fix this we have to update this package version from `@1.2.2` to latest version`@1.3.1`
> fix(deps): update v3-infinite-loading to 1.3.1 to fix infinite loading issue

- packages/nocodb/src/db/sql-client/lib/pg/PgClient.ts
- packages/nocodb/src/services/columns.service.ts
- packages/nocodb/src/services/tables.service.ts
- PgClient isunique and primarykey detection on indexlist query
- index.key_name instead of index.index_name (all of our clients provide key_name)
- avoid skipping deleting hm columns from mm tables
- forceDeleteSystem flag for column delete
- Delete link column even if it is missing the mm table (allows recovering broken tables)
> fix: mm table deletion

- packages/nc-gui/components/smartsheet/details/Fields.vue
- packages/nc-gui/composables/useApi/index.ts
- packages/nc-gui/composables/useApi/interceptors.ts
- packages/nc-gui/composables/useGlobal/actions.ts
- packages/nc-gui/composables/useGlobal/types.ts
- packages/nocodb/src/helpers/PagedResponse.ts
- packages/nocodb/src/middlewares/extract-ids/extract-ids.middleware.ts
- packages/nocodb/src/strategies/jwt.strategy.ts
- Instead of 403 return 401 when token invalid
- Avoid overriding existing additional roles props when loading user info using refresh token
> Nc fix: Refresh token related issues

- packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation.md
This commit updates the installation documentation for Windows users, **adding the missing -OutFile flag** to the PowerShell commands. This ensures the executable files for NocoDB are **correctly downloaded and saved** in the user's working directory, enhancing the installation experience and preventing potential confusion or errors during setup.
- [- ] ~~feat: (new feature for the user, not a new feature for build script)~~
- [- ] ~~fix: (bug fix for the user, not a fix to a build script)~~
- [ -] ~~style: (formatting, missing semi colons, etc; no production code change)~~
- [ -] ~~refactor: (refactoring production code, eg. renaming a variable)~~
- [- ] ~~test: (adding missing tests, refactoring tests; no production code change)~~
- [- ] ~~chore: (updating grunt tasks etc; no production …
> Add -OutFile flag to Windows download commands in 010.installation.md

- packages/nocodb/src/cache/CacheMgr.ts
- packages/nocodb/src/cache/NocoCache.ts
- packages/nocodb/src/cache/RedisCacheMgr.ts
- packages/nocodb/src/cache/RedisMockCacheMgr.ts
- packages/nocodb/src/models/ApiToken.ts
- packages/nocodb/src/models/Base.ts
- packages/nocodb/src/models/Column.ts
- packages/nocodb/src/models/Filter.ts
- packages/nocodb/src/models/FormViewColumn.ts
- packages/nocodb/src/models/GalleryViewColumn.ts
- packages/nocodb/src/models/GridViewColumn.ts
- packages/nocodb/src/models/Hook.ts
- packages/nocodb/src/models/HookFilter.ts
- packages/nocodb/src/models/KanbanViewColumn.ts
- packages/nocodb/src/models/LookupColumn.ts
- packages/nocodb/src/models/MapViewColumn.ts
- packages/nocodb/src/models/Model.ts
- packages/nocodb/src/models/ModelRoleVisibility.ts
- packages/nocodb/src/models/RollupColumn.ts
- packages/nocodb/src/models/SelectOption.ts
- packages/nocodb/src/models/Sort.ts
- packages/nocodb/src/models/Source.ts
- packages/nocodb/src/models/User.ts
- packages/nocodb/src/models/View.ts
- packages/nocodb/src/utils/globals.ts
- deprecate getAll and delAll (they were using `KEYS pattern` which we would like to avoid)
- add bulk del support (less number of calls to Redis)
- set before all appendToList calls (we make use of existing child key so this is a must now)
- keep list of parents on child object
- extra operations for functions
- set: get existing __nc_list__ if any and keep it for new value 
- appendToList: get existing __nc_list__ if any & append list being appended and set child
- setList: get existing __nc_list__ if any & append list being set and set child
- use list of parents to delete CHILD_TO_PARENT
- use mget for getList (less number of calls to Redis)
> feat: revise cache

- packages/nocodb/src/modules/jobs/jobs/at-import/helpers/readAndProcessData.ts
- Fixes payload too large issue when single record have huge amount of links
> fix: avoid pushing all links of record at once

- packages/nocodb/src/db/sql-mgr/code/models/xc/BaseModelXcMeta.ts
- packages/nocodb/src/db/sql-mgr/code/models/xc/ModelXcMetaMssql.ts
- packages/nocodb/src/db/sql-mgr/code/models/xc/ModelXcMetaMysql.ts
- packages/nocodb/src/db/sql-mgr/code/models/xc/ModelXcMetaOracle.ts
- packages/nocodb/src/db/sql-mgr/code/models/xc/ModelXcMetaPg.ts
- packages/nocodb/src/db/sql-mgr/code/models/xc/ModelXcMetaSnowflake.ts
- packages/nocodb/src/db/sql-mgr/code/models/xc/ModelXcMetaSqlite.ts
- packages/nocodb/src/version-upgrader/v1-legacy/BaseApiBuilder.ts
This PR removes duplicated code in the database models. Method `renderXcColumns` was duplicated in all database models, so the easiest way to fix duplication move it to the parent class.
> refactor: Remove duplicated code in models

- README.md
The current link to app store in the README points to an outdated page. Update it to the latest doc.
Changed the link to App store in main README.
> Update app store link to latest doc

- packages/nocodb/src/utils/acl.ts
This change will enable VIEWER to receive emails, whenever new entry added via FORM
fixes #7535
I created two users: SUPER ADMIN and VIEWER:
- SUPER ADMIN created base, table and the form; also configured SMTP
- VIEWER opened FORM and enabled "E-mail me at ..." switch
- confirmed, that now there is no error and the switch state saved (if fails in `master`)
- confirmed, that email is actually sent
> ACL: move isPluginActive from CREATOR to VIEWER; fixes #7535

- packages/nc-gui/components/cell/RichText.vue
- packages/nc-gui/components/cell/TextArea.vue
- packages/nc-gui/components/cell/Url.vue
- packages/nc-gui/composables/useMultiSelect/index.ts
> Nc fix: URL and LongText cell double click edit enable issue

- packages/nocodb/src/services/columns.service.ts
> Nc fix: column delete issue due to incorrect switch break statement in column delete service

- packages/nc-gui/components/nc/DateWeekSelector.vue
- packages/nc-gui/components/smartsheet/calendar/Cell.vue
- packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue
- packages/nc-gui/components/smartsheet/calendar/MonthView.vue
- packages/nc-gui/components/smartsheet/calendar/RecordCard.vue
- packages/nc-gui/components/smartsheet/calendar/VRecordCard.vue
- packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue
- packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
- packages/nc-gui/components/smartsheet/calendar/index.vue
- packages/nc-gui/composables/useViewColumns.ts
- packages/nc-gui/utils/iconUtils.ts
> feat(nc-gui): calendar drag-drop granularity

- packages/nocodb/src/models/Model.ts
> fix: Multi-source table list cache issue

- packages/nocodb/src/helpers/formulaHelpers.ts
- packages/nocodb/src/models/CalendarViewColumn.ts
- packages/nocodb/src/models/Column.ts
- packages/nocodb/src/models/Filter.ts
- packages/nocodb/src/models/GalleryViewColumn.ts
- packages/nocodb/src/models/GridViewColumn.ts
- packages/nocodb/src/models/Model.ts
- packages/nocodb/src/models/Sort.ts
- packages/nocodb/src/models/View.ts
- Closes #7770
- Pass ncMeta reference to use same transaction for all sql operation
> ix: SQLite - upgrader timeout bug

- packages/nc-gui/components/smartsheet/calendar/index.vue
- packages/nc-gui/composables/useCalendarViewStore.ts
- packages/nc-gui/composables/useExpandedFormStore.ts
- packages/nc-gui/composables/useSharedView.ts
- packages/nocodb/src/controllers/calendars-datas.controller.ts
- packages/nocodb/src/controllers/data-alias.controller.ts
- packages/nocodb/src/controllers/data-table.controller.ts
- packages/nocodb/src/controllers/public-datas.controller.ts
- packages/nocodb/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/modules/datas/datas.module.ts
- packages/nocodb/src/schema/swagger-v2.json
- packages/nocodb/src/schema/swagger.json
- packages/nocodb/src/services/calendar-datas.service.ts
- packages/nocodb/src/services/datas.service.ts
- packages/nocodb/src/services/public-datas.service.ts
- packages/nocodb/tests/unit/rest/tests/viewRow.test.ts
> feat(nocodb): calendar data apis

- packages/nc-gui/app.vue
- packages/nc-gui/components/general/FormBanner.vue
- packages/nc-gui/components/nc/ErrorBoundary.vue
- packages/nc-gui/components/smartsheet/Form.vue
- packages/nc-gui/composables/useViewGroupBy.ts
- Add missing try catch in group by load methods
- Extended version of NuxtErrorBoundary component to show modal
> fix: Handle group by load method exceptions

- packages/noco-docs/docs/060.table-operations/020.field-operations.md
- packages/noco-docs/docs/060.table-operations/030.filter.md
- packages/noco-docs/docs/060.table-operations/040.sort.md
- packages/noco-docs/docs/060.table-operations/050.group-by.md
- packages/noco-docs/docs/060.table-operations/060.row-height.md
- packages/noco-docs/docs/060.table-operations/070.search.md
- packages/noco-docs/docs/060.table-operations/080.download.md
- if there is a slash at the end, the current links would redirect to the wrong path.
- For example,
- Go to `https://docs.nocodb.com/table-operations/field-operations/#change-cover-field-gallerykanban-view`
- Click any link in related topics
> fix(docs): related topics links in table operations

- packages/nocodb/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/helpers/PagedResponse.ts
- packages/nocodb/src/helpers/extractLimitAndOffset.ts
- packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
- packages/nocodb/src/services/calendar-datas.service.ts
- packages/nocodb/src/services/datas.service.ts
- use parseMetaProp on export service
- rename calendarLimitOverride to limitOverride and reuse for export service
- add missing catch block for async call
> fix: duplicate base/model

- packages/noco-docs/docs/070.fields/040.field-types/060.formula/030.string-functions.md
- packages/nocodb-sdk/src/lib/formulaHelpers.ts
- packages/nocodb/src/db/functionMappings/commonFns.ts
- tests/playwright/tests/db/columns/columnFormula.spec.ts
This adds `URLENCODE` that percent-encodes special characters, so that column value can be safely substituted into URLs.
Tested on PostgreSQL. But it should work fine on other backends, too.
> Add support for `URLENCODE` function

- packages/nc-gui/components/dashboard/settings/data-sources/EditBase.vue
> fix: Sync both filename and connection.filename when updating SQLite datasource

- pnpm-lock.yaml
We are building nocodb using [pnpm2nix-nzbr][1], and that library requires all dependencies to have integrities.
And it's also more secure, since if someone hijacks that website and replaces that tarball with something malicious, pnpm will refuse to use that.
[1]: https://github.com/nzbr/pnpm2nix-nzbr
I have verified that `pnpm install` works. Also, `pnpm update` preserves the hash.
@vijayrathore8492 Please review.
> chore(deps): Add integrity for the xlsx tarball

- packages/nc-gui/components/dlg/share-and-collaborate/ShareBase.vue
- packages/nc-gui/components/dlg/share-and-collaborate/SharePage.vue
- packages/nc-gui/components/dlg/share-and-collaborate/View.vue
- packages/nc-gui/components/general/CopyUrl.vue
- packages/nc-gui/components/general/ShareProject.vue
- packages/nc-gui/components/nc/Modal.vue
- packages/nc-gui/components/nc/Switch.vue
- packages/nc-gui/components/nc/Tabs.vue
- packages/nc-gui/components/project/ShareBaseDlg.vue
- packages/nc-gui/components/roles/Badge.vue
- packages/nc-gui/components/workspace/InviteSection.vue
- packages/nc-gui/lang/en.json
- tests/playwright/pages/Dashboard/common/Topbar/Share.ts
- tests/playwright/pages/Dashboard/common/Topbar/index.ts
- tests/playwright/tests/db/features/baseShare.spec.ts
> feat(nc-gui): new share ui

- packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
- packages/nc-gui/components/smartsheet/Kanban.vue
- packages/nc-gui/lib/acl.ts
- Hide Add record button when user doesn't have dataInsert permission. 
Button "Add record" opens form with disabled fields and you can't submit this form.
- Remove tableRename, tableDelete from org level role permissions for hiding Rename and Delete buttons in table context menu.
Hide buttons which perform actions that are not allowed by backend. 
Remove tableRename, tableDelete from org level because these permissions are not related to org level actions.
I tested all the changes.
Added screenshot for first problem
> fix(nc-gui): Hide Rename, Delete, Add record buttons when user doesn't have necessary permissions

- packages/nocodb/src/models/BaseUser.ts
- packages/nocodb/src/models/User.ts
> fix: Always store full version data of base-users in cache

- packages/nocodb-sdk/src/lib/globals.ts
- packages/nocodb/src/filters/global-exception/global-exception.filter.ts
- packages/nocodb/src/helpers/catchError.ts
Catch body-parser error and return as NcBaseErrorv2 with proper response and avoid logging to console.
> fix: handle body parser error and avoid logging

- packages/nc-gui/components/erd/RelationEdge.vue
- packages/nc-gui/components/erd/utils.ts
- packages/nc-gui/composables/useViewFilters.ts
> fix: add one to one relation in ERD diagram

- .github/workflows/release-executables.yml
- scripts/downgradeSqlite.js
> Downgrade sqlite version while building executables

- packages/nc-gui/components/cell/RichText.vue
> fix: avoid focus to rich text unless it is expanded

- packages/nc-gui/components/workspace/CollaboratorsList.vue
> fix: load ws role 

- packages/nocodb/src/services/base-users/base-users.service.ts
- packages/nocodb/src/utils/emailUtils.ts
- packages/nocodb/src/utils/index.ts
> fix: sanitise workspace/base name in invite email

- packages/nc-gui/components/nc/DateWeekSelector.vue
- packages/nc-gui/components/nc/MonthYearSelector.vue
- packages/nc-gui/components/smartsheet/Toolbar.vue
- packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue
- packages/nc-gui/components/smartsheet/calendar/MonthView.vue
- packages/nc-gui/components/smartsheet/calendar/SideMenu.vue
- packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue
- packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
- packages/nc-gui/components/smartsheet/calendar/YearView/Month.vue
- packages/nc-gui/components/smartsheet/calendar/YearView/index.vue
- packages/nc-gui/components/smartsheet/calendar/index.vue
- packages/nc-gui/components/smartsheet/toolbar/Calendar/Mode.vue
- packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue
- packages/nc-gui/composables/useCalendarViewStore.ts
- tests/playwright/pages/Dashboard/Calendar/CalendarWeekDateTime.ts
> fix(nc-gui): update calendar

- packages/nocodb/src/utils/emailUtils.ts
- scripts/upgradeNcGui.js
- Closes https://github.com/nocodb/nocodb/issues/8493
> fix: Email invitation bug

- packages/nc-gui/components/nc/Select.vue
- packages/nc-gui/components/smartsheet/toolbar/Calendar/Mode.vue
> fix: additional padding in select cell

- packages/nc-gui/composables/useCommandPalette/index.ts
- packages/nocodb/src/services/command-palette.service.ts
- packages/nocodb/src/services/org-users.service.ts
- packages/nocodb/src/utils/acl.ts
> fix: Cmd K not working for viewer roles

- packages/nc-gui/components/cell/DatePicker.vue
- packages/nc-gui/components/cell/DateTimePicker.vue
- packages/nc-gui/components/cell/TimePicker.vue
- packages/nc-gui/components/cell/YearPicker.vue
- packages/nc-gui/composables/useUndoRedo.ts
- packages/nc-gui/utils/browserUtils.ts
> Nc fix: disable undo redo if expanded form is open 

- packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
- packages/nc-gui/lang/en.json
- packages/nocodb-sdk/src/lib/formulaHelpers.ts
> refactor: show unsupported formula functions as disabled

- packages/nocodb/src/controllers/auth/ui/emailTemplates/invite.ts
- packages/nocodb/src/controllers/auth/ui/emailTemplates/verify.ts
- packages/nocodb/src/services/base-users/ui/emailTemplates/invite.ts
- packages/nocodb/src/services/base-users/ui/emailTemplates/verify.ts
Just some small rewordings / corrections of the invitation and e-mail verification templates.
Untested.
Note that the `<%- baseName %>` placeholder doesn't work, i.e. results in an empty string in the sent e-mail. Unfortuantely, I dunno how to fix this.
> fix: tweak invite and verify e-mail templates

- packages/nc-gui/components/shared-view/Calendar.vue
- packages/nc-gui/components/shared-view/Gallery.vue
- packages/nc-gui/components/shared-view/Grid.vue
- packages/nc-gui/components/shared-view/Kanban.vue
- packages/nc-gui/components/shared-view/Map.vue
- packages/nc-gui/components/smartsheet/grid/Table.vue
- packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
- packages/nc-gui/components/tabs/Smartsheet.vue
- packages/nc-gui/composables/useViewColumns.ts
- We don't render fields menu for xs mobile views
> fix: load fields from composable instead of fields menu

- packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
- packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
- packages/nc-gui/components/smartsheet/toolbar/FieldListAutoCompleteDropdown.vue
- packages/nc-gui/composables/useViewFilters.ts
- tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts
> Nc feat/filter UI

- packages/nocodb/src/app.module.ts
- packages/nocodb/src/interface/Jobs.ts
- packages/nocodb/src/modules/global/global.module.ts
- packages/nocodb/src/modules/jobs/fallback/fallback-queue.service.ts
- packages/nocodb/src/modules/jobs/jobs-service.interface.ts
- packages/nocodb/src/modules/jobs/jobs.controller.ts
- packages/nocodb/src/modules/jobs/jobs.module.ts
- packages/nocodb/src/modules/jobs/jobs/at-import/at-import.controller.ts
- packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.controller.ts
- packages/nocodb/src/modules/jobs/jobs/health-check.processor.ts
- packages/nocodb/src/modules/jobs/jobs/meta-sync/meta-sync.controller.ts
- packages/nocodb/src/modules/jobs/jobs/source-create/source-create.controller.ts
- packages/nocodb/src/modules/jobs/jobs/source-delete/source-delete.controller.ts
- packages/nocodb/src/modules/jobs/jobs/webhook-handler/webhook-handler.processor.ts
- packages/nocodb/src/services/hook-handler.service.ts
- move webhook handler to worker
> feat: move webhook handler to worker

- .github/workflows/release-nocodb.yml
- This step have to run after npm release as it also commits into master
> chore: move sync action after npm release as it pushes some commits

- packages/nocodb/src/services/public-datas.service.ts
The field names in file attachments were being decoded incorrectly. Added proper `UTF-8` decoding to ensure non-english field names are handled properly.
[recording-29_05_2024.webm](https://github.com/nocodb/nocodb/assets/45072928/d38b2cb6-e951-4095-add6-a0d47cce16b1)
> Decode field name as utf-8

- packages/nocodb/src/services/users/users.service.ts
The correct API endpoint is [`POST /api/v1/auth/email/validate/{token}`](https://data-apis-v1.nocodb.com/#tag/Auth/operation/auth-email-validate).
fixes #7241
fixes #7473
Untested.
> fix: e-mail verification endpoint path

- packages/nc-gui/composables/useViewFilters.ts
> fix: Wait until any previous filter is saving

- packages/nc-gui/store/notification.ts
Closes https://github.com/nocodb/nocodb/issues/8760
Previously we were awaiting the pollNotifications recursively causing pending promises growing in the stack causing high cpu usage.
When setTimeout is used, the pollNotifications is placed in the event queue and executed after current execution context.
> fix: break synchronous execution of recursive function

- packages/nocodb/src/controllers/notifications.controller.ts
- packages/nocodb/src/modules/jobs/jobs.controller.ts
- packages/nocodb/src/modules/jobs/redis/jobs-redis.ts
- packages/nocodb/src/redis/pubsub-redis.ts
- packages/nocodb/src/services/notifications/notifications.service.ts
- Instead of keeping a global unsubscribe callback return it when subscribing
> fix: return unsubscribe callback on subscribing

- packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
- packages/nc-gui/composables/useViewFilters.ts
- packages/nocodb/src/db/conditionV2.ts
- packages/nocodb/src/helpers/columnHelpers.ts
> Nc fix/shared view filter

- packages/nocodb/src/models/Column.ts
- packages/nocodb/src/models/LinkToAnotherRecordColumn.ts
- packages/nocodb/src/services/columns.service.ts
- Add virtual as expected & avoid overriding with default
> fix: add virtual as expected & avoid overriding with default

- packages/nc-gui/components/smartsheet/Form.vue
- packages/nc-gui/components/smartsheet/column/DefaultValue.vue
- packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
- packages/nc-gui/composables/useData.ts
- packages/nc-gui/composables/useSharedFormViewStore.ts
- packages/nc-gui/utils/columnUtils.ts
- packages/nc-gui/utils/dataUtils.ts
> fix(nc-gui): default value update issue if value is 0

- packages/nc-gui/components/dlg/ViewCreate.vue
- packages/nc-gui/components/smartsheet/Gallery.vue
- packages/nc-gui/components/smartsheet/Kanban.vue
- packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
- packages/nc-gui/components/virtual-cell/Lookup.vue
> feat: Use lookup over attachment field as cover image in gallery & kanban view

- packages/nocodb/src/services/app-hooks/app-hooks.service.ts
- packages/nocodb/src/services/notifications/notifications.service.ts
Only listen specific events to avoid extra overhead
> fix: avoid listening all events

- packages/nocodb/src/db/BaseModelSqlv2.ts
Fixes #8667
- Send all columns on delete & update webhook
> fix: webhook delete & update payload

- packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
- packages/nocodb/src/meta/migrations/v2/nc_050_tenant_isolation.ts
- packages/nocodb/src/meta/migrations/v2/nc_054_id_length.ts
Fixes #8773
In older versions there was a bug that causes our users to use custom ids while creating base, if they ended up creating bases with id longer than 20 characters it breaks tenant isolation migration
- Replace long base ids with new ones before migration
- Make base_id columns 20 in every table
> fix: long base_id issue

- tests/playwright/pages/Dashboard/Settings/Acl.ts
- tests/playwright/pages/Dashboard/Settings/DataSources.ts
- tests/playwright/tests/db/usersAccounts/accountTokenManagement.spec.ts
- tests/playwright/tests/db/usersAccounts/rolesPreview.spec.ts
> test: UI ACL

- packages/nc-gui/components/dashboard/View.vue
- packages/nc-gui/composables/useGlobal/actions.ts
- packages/nc-gui/composables/useGlobal/state.ts
- packages/nc-gui/composables/useGlobal/types.ts
- packages/nc-gui/lib/constants.ts
- packages/nc-gui/nuxt.config.ts
- packages/nc-gui/store/sidebar.ts
- tests/playwright/pages/Dashboard/Grid/Column/index.ts
- tests/playwright/quickTests/commonTest.ts
> Fix: Persist the left sidebar width and use pixels instead of percentage to configure the sidebar width

- packages/nocodb/src/models/Model.ts
-  avoid checking names cross-source (missing source_id)
> fix: avoid checking names cross-source

- packages/nc-gui/pages/signin.vue
- packages/nc-gui/pages/signup/[[token]].vue
Fixes trim issues in signin and signup pages.
fix: Bug: SignIn/SignUp -- trim extra spaces if any #8910 
Now, there is no such trim error in signin/signup pages.
> fix: #8910 trim extra space during sign in & sign up

- packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
- packages/nocodb/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/helpers/NcPluginMgrv2.ts
- packages/nocodb/src/models/FormView.ts
- packages/nocodb/src/models/PresignedUrl.ts
- packages/nocodb/src/modules/jobs/jobs/data-export/data-export.processor.ts
- packages/nocodb/src/plugins/s3/S3.ts
- packages/nocodb/src/plugins/s3/index.ts
- packages/nocodb/src/services/attachments.service.ts
This change adds a **S3 endpoint** input value and environment variable for the S3 plugin.
Why? Endpoint can be set on the Minio plugin already, however that one does not support environment variables. Since the S3 protocol is supported by many providers, many of them not using Minio, it makes sense to have this option on the S3 plugin as well.
This change is backwards-compatible, the default endpoint is AWS.
Tested and working with Scaleway object storage
Relevant issues: #4993, #7903
> feat: add S3 endpoint input

- packages/nc-gui/components/cell/attachment/Carousel.vue
- packages/nc-gui/components/cell/attachment/Modal.vue
- packages/nc-gui/components/cell/attachment/index.vue
- packages/nc-gui/components/cell/attachment/utils.ts
- packages/nc-gui/composables/useAttachment.ts
- packages/nc-gui/composables/useSharedView.ts
- packages/nocodb/src/controllers/attachments-secure.controller.ts
- packages/nocodb/src/controllers/attachments.controller.ts
- packages/nocodb/src/controllers/public-datas.controller.ts
- packages/nocodb/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/helpers/attachmentHelpers.ts
- packages/nocodb/src/models/PresignedUrl.ts
- packages/nocodb/src/modules/jobs/jobs/data-export/data-export.processor.ts
- packages/nocodb/src/plugins/s3/S3.ts
- packages/nocodb/src/schema/swagger.json
- packages/nocodb/src/services/attachments.service.ts
- packages/nocodb/src/services/public-datas.service.ts
- Allow preview for types ['image', 'pdf', 'video', 'audio']
- Redirect to download using an internal endpoint
> feat: allow preview for media types

- packages/nc-gui/components/dashboard/TreeView/ViewsList.vue
Added a check for the 'isSharedBase' to determine whether the 'Create Views' button would appear when sharing user's Base. The button will now only appear if the ifSharedBase value is false meaning that it will not appear in the Base share version.
Untested.
> fix: 'Create View' button appearing through sharing link of Base #9055

- packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts
- packages/nocodb/src/plugins/s3/S3.ts
- packages/nocodb/src/services/attachments.service.ts
- call generate thumbnail job only for image attachments (instead of filtering inside the job, this way we will get better statistics & less number of jobs)
- thumbnail errors & path
- temporarily use arraybuffer for S3 as well to calculate image dimensions
> fix: thumbnail errors & path

- packages/nocodb/src/helpers/dataHelpers.ts
Lookup for mm or hm will be an array but we wrap bt with array as well to unify.
Issue here is we store attachment as json array as well and we are using `Array.isArray(value) ? value : [value]` which skips wrapping as it is already an array and send nested value as an object instead of array of objects.
> fix: properly export looked up attachments

- packages/nc-gui/components/smartsheet/column/AdvancedOptions.vue
Add `title` attribute to `AdvancedOptions.vue` to display the full name of the helper columns on mouse hover.
> 🖱 Add `title` attribute to `AdvancedOptions.vue` on mouse hover

- packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
move `NC_ATTACHMENT_EXPIRE_SECONDS` to storage block and clarify that it only takes effect if `NC_SECURE_ATTACHMENTS` is enabled.
> docs: move `NC_ATTACHMENT_EXPIRE_SECONDS` to storage block

- packages/nocodb-sdk/src/lib/Api.ts
- packages/nocodb/tests/unit/rest/tests/newDataApis.test.ts
- tests/playwright/tests/db/features/verticalFillHandle.spec.ts
https://github.com/nocodb/nocodb/pull/9283 introduced new default for minimum limit caused tests to break
> test: update according to minimum limit

- packages/nc-gui/composables/useViewData.ts
- packages/nc-gui/store/tables.ts
- packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
- packages/nocodb/src/helpers/catchError.ts
> fix: load table even if formula error is present

- packages/nc-gui/components/account/ResetPassword.vue
- packages/nc-gui/components/account/Setup.vue
- packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
- packages/nc-gui/components/general/MiniSidebar.vue
- packages/nc-gui/composables/useApi/interceptors.ts
- packages/nc-gui/composables/useGlobal/actions.ts
- packages/nc-gui/composables/useGlobal/types.ts
- packages/nc-gui/layouts/base.vue
- packages/nc-gui/layouts/new.vue
- packages/nc-gui/middleware/02.auth.global.ts
- packages/nc-gui/pages/account/index.vue
- On signout clear store values only after redirecting to signin page, otherwise it will try to load project and throw 401 error.
- Re https://github.com/nocodb/nocodb/issues/8922#issuecomment-2322819659
> fix: Clear store values only after redirecting to SignIn page

- packages/nc-gui/components/dlg/TableDescriptionUpdate.vue
- packages/nc-gui/composables/useApi/interceptors.ts
- packages/nc-gui/composables/useGlobal/actions.ts
- packages/nc-gui/composables/useGlobal/index.ts
- packages/nc-gui/composables/useGlobal/types.ts
- packages/nc-gui/store/notification.ts
- packages/nc-gui/utils/ncUtils.ts
- Remove 5-mins early token generation code since it's leading to duplicate refresh token request and leadings to logout
- Avoid calling logout api when it's triggered programatically in UI(for example when failed token generation)
- Keep refresh token generation progress state in LocalStorage to sync across multiple tabs and avoid duplicate request
- Re #9311
> fix: Refresh-token based token generation issues

- packages/nc-gui/components/smartsheet/column/ButtonOptions.vue
- packages/nocodb/src/models/Column.ts
- Refactor required message
- Return default col options if missing (AT Import includes those without colOptions instead of having a migration lets support this, moving forward we can consider if we want to avoid creating them altogether)
> fix: handle missing col options for button

- packages/nocodb/src/helpers/populateMeta.ts
- packages/nocodb/src/utils/NcHelp.ts
- Restrict concurrent operations to 5 by default (we allow 10 meta connections so lets avoid occupying all of them)
> feat: restrict concurrent operations

- packages/nc-gui/app.vue
- packages/nc-gui/components/cmd-k/index.vue
- packages/nc-gui/components/general/Loader.vue
- packages/nc-gui/composables/useCommandPalette/index.ts
- packages/nocodb/src/helpers/commandPaletteHelpers.ts
- packages/nocodb/src/models/Base.ts
- packages/nocodb/src/models/BaseUser.ts
- packages/nocodb/src/models/Model.ts
- packages/nocodb/src/models/View.ts
- packages/nocodb/src/services/command-palette.service.ts
- packages/nocodb/src/utils/globals.ts
- Get all required information for command palette in single query
- Cache single query response separately (per user / ws)
> feat: single query command palette & dedicated cache

- packages/nocodb/src/db/conditionV2.ts
- Skip trimming options while applying filter
- If MySQL and datatype is Enum/Set then trim trailing whitespace
> fix: skip trimming options while applying filter

- docker-compose/1_Auto_Upstall/noco.sh
- closes #9533 
${parameter:+word} always expands word when parameter is set
validated with docker bin
docker compose config > /dev/null; echo $?
> 0
> fix: compose configuration generation

- docker-compose/1_Auto_Upstall/noco.sh
> feat: add sqlite support in the upstall script

- packages/nc-gui/components/cmd-k/index.vue
- packages/nc-gui/composables/useCommandPalette/index.ts
- packages/nc-gui/utils/filterUtils.ts
- packages/nocodb-sdk/src/lib/Api.ts
- packages/nocodb/src/helpers/commandPaletteHelpers.ts
- packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
- packages/nocodb/src/services/api-docs/swaggerV2/swagger-base.json
- packages/nocodb/src/services/command-palette.service.ts
- tests/playwright/pages/Dashboard/Command/CmdKPage.ts
> fix: cmdk improvements

- packages/nc-gui/components/feed/Social.vue
- packages/nc-gui/components/feed/View.vue
> Nc fix: add tab key to query params

- packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
- packages/nc-gui/lib/enums.ts
patch #9574 ColumnFilter ToolBar Correctly Show I18n string 
LanguageAlias for zh_Hans
this is a minor patch, tested on windows, ColumnFilter  Correctly Show I18n "and"/"or"   string.
> ColumnFilter ToolBar Correctly Show I18n string and LanguageAlias for zh_Hans

- packages/nc-gui/composables/useSharedFormViewStore.ts
> Nc fix(nc-gui): form redirect url issue

- packages/nc-gui/composables/useData.ts
Refs: #9615
Encoded id using the encodeURIComponent function call.
> fix: encode primary key before sending PATCH request

- packages/nc-gui/composables/useSharedExecutionFn.ts
- packages/nc-gui/store/notification.ts
- useSharedExecutionFn uses mutex lock mechanism over local storage to execute only once (returns same result as well)
- apply this logic to notifications polling to reduce redundant calls
> feat: poll notifications from single tab

- .github/workflows/release-docker.yml
The currently published NocoDB image is incompatible with [Kamal](https://kamal-deploy.org/) out of the box. This is due to Kamal requiring a service label to be attached to the image.
```
ERROR (SSHKit::Command::Failed): Exception while executing on host 5.78.123.98: docker exit status: 1
docker stdout: Image nocodb/nocodb:0.257.0 is missing the 'service' label
docker stderr: Nothing written
```
This PR adds a `service=nocodb` label to future image builds. This is a harmless addition that ensures NocoDB can be deployed using Kamal without needing to rebuild the image and host it independently. It also simplifies future upgrades, as users will no longer have to manually pull the latest image, label it, and push it to their own repositories.
Anything for …
> Add service Label to NocoDB image for compatibility with Kamal

- packages/nc-gui/components/dlg/QuickImport.vue
This PR increases the file size limit for uploads from 5MB to 25MB in QuickImport.vue.
1. Manually tested the file upload functionality by attempting to upload files larger than 5MB but less than 25MB.
2. Verified that files larger than 25MB are rejected with an appropriate error message.
N/A
> enhancement: increase file size limit to 25MB in QuickImport.vue (ref: #5858)

- packages/noco-docs/docs/100.data-sources/050.updating-secret.md
- packages/nocodb/src/version-upgrader/upgraders/0225002_ncDatasourceDecrypt.ts
- Re #9653
- If decryption failed with environment variable then fallbacks to store table value if available
- If meta db source on failure fallback the config value to null since the value of config is encrypted json string `null`
> Add fallback mechanism in decrypt upgrader

- packages/nc-gui/composables/useViewGroupBy.ts
- packages/nc-gui/utils/aliasUtils.ts
Simplify alias logic in useViewGroupby
> fix: simplify alias generation for groupby

- packages/nocodb/Dockerfile
- packages/nocodb/Dockerfile.local
- packages/nocodb/Dockerfile.timely
[`node:18.20.4-alpine`](https://hub.docker.com/_/node) is currently the latest tag of the v18 major release line. To lower update maintenance burden and automatically pick up the latest minor release, just use the `node:18-alpine` tag.
None.
> chore: update Node.js builder image

- packages/nc-gui/components/dlg/QuickImport.vue
- packages/nc-gui/utils/errorUtils.ts
Show meaningful error if import url is not accessible (usually because of CORS).
- in `extractSdkResponseErrorMsg` function, when there is no response, check deeper inside the error to determine the reason.
> fix(nc-gui): show meaningful error to user if import url is not accessible

- packages/nocodb/src/db/conditionV2.ts
- HM part of One-to-one self link blank filter not working as expected 
> fix: use alias when constructing hm filter query to avoid self-reference issue

- packages/nocodb/Dockerfile
- packages/nocodb/Dockerfile.local
- packages/nocodb/Dockerfile.timely
Update Alpine Linux runner image to v3.20. It ships the same version (v20.15.1) of Node.js than v3.19.
None.
> chore: update runner image

- packages/nc-gui/components/dlg/ViewCreate.vue
- packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue
Disable end Date support for createdAt, updatedAt, Formula
> fix: disable endDate for created-at, updated-at, formula

- packages/nc-gui/components/dashboard/settings/base/index.vue
- packages/nc-gui/composables/useBetaFeatureToggle.ts
> fix: enable snapshots

- docker-compose/1_Auto_Upstall/noco.sh
- docker-compose/2_pg/docker-compose.yml
pin postgresql to 16.6, currently it pulls latest and this can cause headaches for users when the latest tag bumps major version as the they will have to do manual migraton
> chore(docker): pin postgresql to 16.6

- tests/playwright/tests/db/features/keyboardShortcuts.spec.ts
- tests/playwright/tests/db/views/viewForm.spec.ts
> Nc test/keyboard shortcuts

- packages/nc-gui/components/nc/DatePicker.vue
Resolves #9633. Updates `DatePicker` to make Monday first day of the week.
**Previous Behavior**
**Current Behavior**
> feat(nc-gui): allow Monday to be the first column in date picker

- packages/nc-gui/components/ai/Settings.vue
- packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue
- packages/nc-gui/components/smartsheet/column/AiButtonOptions.vue
- packages/nc-gui/components/smartsheet/column/ButtonOptions.vue
- packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
- packages/nc-gui/components/smartsheet/column/LongTextOptions.vue
- packages/nc-gui/components/smartsheet/column/UITypesOptionsWithSearch.vue
- packages/nc-gui/components/smartsheet/details/Fields.vue
- packages/nc-gui/components/smartsheet/topbar/ViewListDropdown.vue
> Nc fix/prompt existing issues

- build-local-docker-image.sh
This PR fixes an issue in `build-local-docker-image.sh` at line 48, where the script attempted to execute a directory instead of a file.  
The incorrect command was:  
```sh
EE=true ${SCRIPT_DIR}/node_modules/@rspack/cli/bin
```
This caused the following error during the build process:  
```
./build-local-docker-image.sh: line 48: ./node_modules/@rspack/cli/bin: Is a directory
```
The error was also reflected in `build-local-docker-image.log` as:  
```
Info: Build nocodb, package nocodb-sdk and nc-gui
ERROR: package_nocodb failed
```
The corrected command now explicitly points to the executable file within the directory. This change ensures successful execution of the build script.  
---
---
Added the correct script path:  
```sh
${SCRIPT_DIR}/node_modules/@rspack/cli/bin/rspack.js
``` …
> Fix incorrect script path in build-local-docker-image.sh  

- .github/workflows/release-pr.yml
- .github/workflows/uffizzi-preview.yml
v3 of `actions/upload-artifact` and `actions/download-artifact` will be fully deprecated by **30 January 2025**. Jobs that are scheduled to run during the brownout periods will also fail. See:
1. https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
2. https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/
3. https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#artifacts-v3-brownouts
> chore(release-pr): update `upload-artifact` action to v4

- .github/workflows/uffizzi-preview.yml
The "Deploy Uffizzi Preview" job has been failing (https://github.com/nocodb/nocodb/actions/runs/12237653725/job/34133889626) since PR #9859 was merged. I forgot to specify the `run-id` in PR #9859, which caused the `cache-compose-file` job to attempt downloading artifacts from the current workflow, resulting in no matches. Instead, it should download artifacts uploaded by the workflow that triggered the run.
Fixes: 2684cedddf ("chore(release-pr): update `upload-artifact` action to v4 (#9859)")
/cc @dstala and @mertmit for review again :pray:
> ci(uffizzi-preview): use id of the workflow that triggered the workflow run

- .github/workflows/uffizzi-preview.yml
The "Deploy Uffizzi Preview" is still failing, https://github.com/nocodb/nocodb/actions/runs/12238779097.
Turns out GitHub token is required to download artifacts from another workflow run, see https://github.com/actions/download-artifact/issues/320.
Fixes: 62e1485143 ("ci(uffizzi-preview): use id of the workflow that triggered the workflow run (#10003)")
Fixes: 2684cedddf ("chore(release-pr): update `upload-artifact` action to v4 (#9859)")
/cc @mertmit :pray: Sorry for the multiple PRs, this time it should really work
> ci(uffizzi-preview): provide GitHub token to download artifacts

- packages/nocodb/src/db/sql-client/lib/pg/typeCast.ts
Negatives are preserved. If statement starts with '-', number will be negated.
Resolves https://github.com/nocodb/nocodb/issues/9417?notification_referrer_id=NT_kwDOAlwHQLQxMjIyMzcxMDY2MjozOTU4NTYwMA#event-15614497636
fix: (bug fix for the user, not a fix to a build script)
> fix(nocodb): sql: preserve negative symbols

- packages/nc-gui/composables/useKanbanViewStore.ts
- packages/nocodb/src/db/BaseModelSqlv2.ts
https://github.com/nocodb/nocodb/issues/10057
> fix: group empty string as null 

- packages/nc-gui/components/n/README.md
- packages/nc-gui/components/n/Select/Table.vue
- packages/nc-gui/components/n/Select/View.vue
- packages/nc-gui/components/n/Select/index.vue
- packages/nc-gui/components/n/Select/types.d.ts
- packages/nc-gui/store/views.ts
- packages/nc-gui/utils/iconUtils.ts
> feat: N Components

- packages/nc-gui/components/smartsheet/header/Menu.vue
- packages/nocodb-sdk/src/lib/UITypes.ts
- packages/nocodb-sdk/src/lib/index.ts
- packages/nocodb/src/db/sql-client/lib/pg/PgClient.ts
- packages/nocodb/src/services/columns.service.ts
fix: cannot delete id column in True Data Reflection is enabled
> fix: cannot delete id column

- packages/nc-gui/components/dashboard/Sidebar.vue
- packages/nc-gui/components/dashboard/Sidebar/BeforeUserInfo.vue
- packages/nc-gui/components/dashboard/Sidebar/Feed.vue
- packages/nc-gui/components/dashboard/Sidebar/TopSection.vue
- packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
- packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
- packages/nc-gui/components/dashboard/TreeView/TableNode.vue
- packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue
- packages/nc-gui/components/dashboard/TreeView/index.vue
- packages/nc-gui/components/general/Gift.vue
- packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
- Update sidebar items font weight from `450 -> 550` default and on active `600`
> Nc fix/update sidebar item font weight

- packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
- packages/nc-gui/lang/en.json
> Nc fix/delay formula type reset till saving

- packages/nc-gui/assets/style.scss
- packages/nc-gui/components/nc/Dropdown.vue
- packages/nc-gui/components/nc/Switch.vue
- packages/nc-gui/components/smartsheet/column/DecimalOptions.vue
- packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
- packages/nc-gui/components/smartsheet/column/RollupOptions.vue
- packages/nc-gui/components/smartsheet/column/UITypesOptionsWithSearch.vue
- packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
- packages/nc-gui/components/smartsheet/grid/Table.vue
- packages/nc-gui/components/smartsheet/toolbar/AddLookupsDropdown.vue
- packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
- packages/nc-gui/components/virtual-cell/Rollup.vue
- tests/playwright/pages/Dashboard/common/Toolbar/Fields.ts
- tests/playwright/tests/db/columns/columnLtarDragdrop.spec.ts
Improves the fields menu
- Cleaner UI
- Quick new field creation shortcut
- Quick lookup creation shortcut
- Better scroll handling
> Fix: Fields menu improvement

- packages/nc-gui/composables/useInfiniteData.ts
Created At and CreatedBy info getting lost in grid when the record is updated while getting saved
Closes https://github.com/nocodb/nocodb/issues/9490
> Fix: update data overwrites the insert data in grid

- packages/nocodb-sdk/src/lib/Api.ts
- packages/nocodb/src/models/Column.ts
We are listing from MetaTable.COL_RELATIONS which is colOptions itself so we should directly access the required prop.
Issue pointed & fix provided by https://github.com/gaurav-peswani-truva
Ref: https://github.com/nocodb/nocodb/issues/9728#issuecomment-2565820589
> fix: use proper reference for related model id

- packages/nc-gui/components/smartsheet/grid/GroupByTable.vue
- packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
- packages/nc-gui/components/smartsheet/grid/Table.vue
- packages/nc-gui/components/smartsheet/grid/index.vue
- packages/nc-gui/nuxt.config.ts
> fix(nc-gui): grid row visibility issue in mobile view

- packages/nc-gui/components/cell/Json.vue
- packages/nc-gui/components/monaco/Editor.vue
- packages/nc-gui/components/smartsheet/Form.vue
- packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index.vue
Make the JSON always editable in the modal. No inline editing of JSON.
1. In Grid View, you can trigger the modal by
a. Typing on it.
b. Pressing Enter
c. Double clicking the cell.
d. Pressing the expand button.
2. In other views
a. Pressing the expand button
b. Single click on the field.
The UI buttons (Cancel and Save and the expand/contract) buttons are unified like the rest of the app so they don't look out of place.
The JSON editor modal is resizable horizontally.
There was also a bug fix where the json editor wasn't focused upon expansion.
> feat: better json editing ux 

- nix/module.nix
now nixos users just have to `services.nocodb.enable = true`
tested on nixos
> chore(nix/module): zeroconf

- packages/nocodb/src/db/BaseModelSqlv2.ts
mm link is not deleted when a record is deleted. Closes: https://github.com/nocodb/nocodb/issues/8366
> fix (nocodb): mm link not deleted when row deleted

- .github/workflows/nix-bumper.yml
- flake.nix
- nix/bumper/bumper.sh
- nix/bumper/default.nix
avoid nix hash missmatch issues when pnpm-lock is updated
this pr allows us to confidently run `nix run github:nocodb/nocodb/<branch-name>`
to locally test any pr/branch at any time with a single command 
tested with nix run
> chore(github/workflow/bumper): init 

- .github/workflows/nix-bumper.yml
> chore(github/workflow/bumper): fixes

- packages/nc-gui/components/workspace/integrations/forms/EditOrAdd/Database/index.vue
- packages/nocodb/src/controllers/integrations.controller.ts
- packages/nocodb/src/controllers/sources.controller.ts
- packages/nocodb/src/helpers/responseHelpers.ts
> fix: mask creds on get

- packages/nocodb-sdk/src/lib/index.ts
- packages/nocodb-sdk/src/lib/regex/index.ts
- packages/nocodb-sdk/src/lib/regex/token.spec.ts
- packages/nocodb-sdk/src/lib/regex/token.ts
- packages/nocodb/src/helpers/columnHelpers.ts
- tests/playwright/tests/db/features/undo-redo.spec.ts
Do not replace chinese, japanese and cryillic letters for column name. Closes: https://github.com/nocodb/nocodb/issues/8606
> fix: support japanese, chinese and cryillic letters

- packages/nocodb/src/db/genRollupSelectv2.ts
When a rollup refer to formula column, send table alias which previously not. Closes: https://github.com/nocodb/nocodb/issues/10429
> fix: send table alias for rollup when column is formula

- packages/nc-gui/components/cell/Checkbox/index.vue
false readonly checkbox still show empty square. Closes https://github.com/nocodb/nocodb/issues/9815
> fix (nc-gui): false readonly checkbox still show empty square

- packages/nocodb/src/db/BaseModelSqlv2.ts
Don't filter for the assumed view used for sorting linked records.
> fix: don't apply filtering for the assumed default view

- packages/nc-gui/components/cell/Integer/Editor.vue
- packages/nc-gui/composables/useMultiSelect/convertCellData.ts
- packages/nc-gui/utils/dataUtils.ts
- packages/nocodb/src/helpers/catchError.ts
In PG, long numbers cause number overflow issues.
In Javascript, numbers after `Number.MAX_SAFE_VALUE` and before `Number.MIN_SAFE_VALUE` lose their precision so there is data loss. We fix the issue of number overflow by limiting the numeric values between the safe range.
Also the BE errors was throwing 'unknown' column error. Now it should correctly specify which column is causing the issue.
> fix: limit the number to safe integers

- packages/nc-gui/components/smartsheet/grid/canvas/index.vue
Double click on col resize should not open the column edit modal.
> fix: double click on col resize shouldn't open column edit modal

- packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
Resolves #9876
The following changes are in `formulaQueryBuilderv2.ts`:
- SUM works by recursively calling an evaluation function over the relevant columns to accumulate a final result
- In the case where there is more than one argument left, the argument in question (left) is defaulted to 0 using`COALESCE`
- In the base case (there is exactly one argument left), the argument is defaulted to 0 using `COALESCE`
Manual UI testing of the SUM forumla
I have attached screenshots of testing on the UI
> fix: Prevent sum from failing if field is blank

- packages/nc-gui/components/smartsheet/column/RollupOptions.vue
- packages/nc-gui/components/smartsheet/grid/canvas/cells/Rollup.ts
- packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts
- packages/nc-gui/components/smartsheet/grid/canvas/index.vue
- packages/nc-gui/components/smartsheet/grid/canvas/loaders/ImageLoader.ts
- packages/nc-gui/utils/columnUtils.ts
fix: Canvas throwing error in console
fix: Rollup not inheriting formula formatting options
Closes https://github.com/nocodb/nocohub/issues/4730
Closes https://github.com/nocodb/nocodb/issues/10712
> Nc canvas related issues

- packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
- Closes https://github.com/nocodb/nocodb/issues/10708
- Sanitise string literals in formula to escape `?` since it have special meaning in knex and treated as dynamic param.
> fix: Sanitise string literals in formula

- packages/nocodb/src/db/BaseModelSqlv2.ts
- Closes https://github.com/nocodb/nocodb/issues/10700
> fix: Handle row ID of audit record for tables with composite primary keys

- packages/nocodb/src/models/Source.ts
- packages/nocodb/src/utils/dataUtils.ts
Re - https://discord.com/channels/661905455894888490/1346768933562224661
> fix: Handle missing searchPath value while merging config

- packages/nc-gui/components/smartsheet/column/LookupOptions.vue
- packages/nc-gui/components/smartsheet/column/RollupOptions.vue
- packages/nc-gui/components/smartsheet/expanded-form/index.vue
- packages/nocodb-sdk/src/lib/UITypes.ts
- packages/nocodb-sdk/src/lib/index.ts
- packages/nocodb/src/models/Model.ts
> Nc fix: Miscellaneous bug fixes

- packages/nc-gui/components/dlg/View/Create.vue
The **Add Description** button previously appeared even when no applicable column types were present, which was redundant. This update hides the button when it's not needed.
> Fix: hide description field if no applicabale columns present

- packages/nc-gui/components/cmd-k/index.vue
- packages/nc-gui/components/cmd-l/index.vue
Fixes issue where the Cmd+K command modal doesn't appear on top when another modal is open (Attached current behaviour). Ensures Cmd+K modal is prioritized in z-index stacking.
https://github.com/user-attachments/assets/387beb94-c9c0-4e82-a9e1-9496594b1890
> Fix: Cmd+K visibility

- packages/nocodb-sdk/src/lib/columnHelper/utils/cell.ts
fix (nocodb-sdk): isFloat on cell.ts previously compare abstract type with UITypes, and not uidt with UITypes.
> fix (nocodb-sdk): isFloat on cell.ts

- packages/nc-gui/store/views.ts
- Go to All Tables Page
- Expand a Table in List
- Now open a view in the table. Now you will end up with loading indicator in toolbar and topbar
> fix: view loading indicator does not stops

- packages/nocodb/src/services/columns.service.ts
fix (nocodb): handle null-ish filter value for single select. Closes https://github.com/nocodb/nocodb/issues/11112
> fix (nocodb): handle null-ish filter value for single select

- packages/nocodb-sdk/src/lib/Api.ts
- packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.processor.ts
- packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
Fixes #11241
- Avoid skipping empty values
- Restore rqd on column duplicate instead of applying right away
> fix: duplicate with rqd

- packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
Added [default value](https://github.com/nocodb/nocodb/blob/4c54106fea66ecba719f07d19105a7e262c9ecf3/packages/nocodb/src/helpers/initBaseBehaviour.ts#L77-L78) and fixed instructions to disable it.
> docs: fix `NC_DISABLE_PG_DATA_REFLECTION` description

- packages/nocodb/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/utils/dataUtils.ts
- Use when case to batch update multiple records with a single query which is a lot more sufficient
Simple Benchmark to compare using local PG show it is ~20x faster (Both used transaction, case when approach used batches of 1000 records per query)
```
Benchmark Results:
Batched CASE WHEN (tx):    94 ms — updated rows: 10000
Multiple UPDATEs (tx):     2046 ms — updated rows: 10000
```
> fix: improve bulk update

- packages/nocodb/src/plugins/smtp/index.ts
The help texts of `from` and `rejectUnauthorized` were outright wrong.
Note that the meaning of `rejectUnauthorized` is outlined [here](https://nodemailer.com/smtp#3-allow-selfsigned-certificates) in the Nodemailer upstream project.
None.
> refactor: improve SMTPPlugin `help_text`s

- packages/nc-gui/components/dashboard/settings/data-sources/SupportedDocs.vue
- packages/nc-gui/components/workspace/integrations/SupportedDocs.vue
Changed the `<div>` title in the UI for relevant documentation from *Supported Docs* to ***Relevant documentation***, which better conveys the meaning.
None.
These strings are hardcoded, i.e. not yet translatable (which would be preferable).
> refactor: improve UI div title

- packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
fix (nc-gui): check for dynamic if filter column changed
> fix (nc-gui): check for dynamic if filter column changed

- packages/nocodb/src/models/Column.ts
Throwing here leads to row being created but not added to meta
Also in document we show uidt as non-mandatory
> fix: avoid throwing if uidt is missing

- packages/nc-gui/components/smartsheet/column/SelectOptions.vue
fix (nc-gui): index prop lost after vmodel changed. Closes https://github.com/nocodb/nocodb/issues/11545
> fix (nc-gui): index prop lost after vmodel changed

- packages/nocodb/src/db/BaseModelSqlv2.ts
- packages/nocodb/src/helpers/dbHelpers.ts
fix: empty lookup when tranforming object. Closes https://github.com/nocodb/nocodb/issues/11696#issuecomment-2982867469
> fix: empty lookup when tranforming object

- packages/nc-gui/components/smartsheet/grid/canvas/index.vue
- Grid with Group By – The context menu for the display value field does not open when clicking on the chevron.
- Grid without Group By – The field context menu only opens when clicking precisely on the dropdown chevron. Clicking on the surrounding area, even though the cursor changes to a pointer, has no effect.
> fix: minor ui correction #6013

- packages/nocodb/src/models/View.ts
- packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
fix: when duplicate table, include row coloring info when view is default
> fix: when duplicate table, include row coloring info when view is default

- packages/nc-gui/store/sidebar.ts
- ref: Failed to execute 'exitFullscreen' on 'Document': Document not active
- ref: document.documentElement.requestFullscreen is not a function. (In 'document.documentElement.requestFullscreen()', 'document.documentElement.requestFullscreen' is undefined)
> Nc fix/sentry errors 4 sep

- packages/nocodb/src/services/api-docs/swaggerV2/templates/paths.ts
Correct casing of an example JSON key in the Swagger V2 documentation. 
The previous key casing was incorrect, which could confuse users when following the example.
Verified that the corrected JSON key matches the actual API response and the example now works as expected.
> docs(swaggerV2): fix typo in example JSON key casing

- .github/CONTRIBUTING.md
The Issue :
The link to the COMMIT_CONVENTION.md file was broken when viewing the CONTRIBUTING.md file from the repository's main "Contributing" tab (displayed in the 
header of the repository page). The relative link was being resolved from the repository root instead of from within the .github directory, which resulted in a 
"404 Not Found" error for users trying to access the commit convention guidelines.
The Fix
This PR replaces the broken relative link with the full, absolute URL pointing to the COMMIT_CONVENTION.md file on the develop branch. Using an absolute URL is 
the most robust solution, ensuring the link works correctly for all users across all of GitHub's different file-viewing contexts (the special "Contributing" 
tab, the direct file browser, etc.).
To verify the fix:
1. …
> fix: update link to Commit Message Convention in CONTRIBUTING.md

- packages/nc-gui/components/smartsheet/Cell.vue
- packages/nc-gui/components/virtual-cell/BelongsTo.vue
- packages/nc-gui/components/virtual-cell/HasMany.vue
- packages/nc-gui/components/virtual-cell/Links.vue
- packages/nc-gui/components/virtual-cell/ManyToMany.vue
- packages/nc-gui/components/virtual-cell/OneToOne.vue
- packages/nc-gui/components/virtual-cell/components/ItemChip.vue
- packages/nc-gui/components/virtual-cell/components/ListItem.vue
- tests/playwright/pages/Dashboard/Grid/Column/index.ts
- tests/playwright/pages/Dashboard/TreeView.ts
- tests/playwright/pages/Dashboard/common/Cell/index.ts
- tests/playwright/pages/Dashboard/common/Topbar/index.ts
- tests/playwright/tests/db/columns/columnFormula.spec.ts
- ref: #12467 
- Fixed: In shared view bt, link to another record cell value not visible in expanded form
- Just visibility issue, it was hidden under lock cell overlay which has to be present only at rool level of cell not nested level 
> Fix: Lock pre-filled as readonly is not working for virtual links/ltar fields
