packages/nocodb/src/services/api-docs/swagger/getSwaggerColumnMetas.ts, packages/nocodb/src/services/api-docs/swagger/templates/paths.ts
=> fix: Add missing endpoints in swagger json

packages/nocodb/src/version-upgrader/NcUpgrader.ts
=> fix: Exclude any unnecessary props from app version JSON store value

packages/nc-gui/components/project/InviteProjectCollabSection.vue
=> fix: Project invite logic correction

packages/nocodb/src/services/project-users/project-users.service.ts
=> fix: validate invite role

packages/nocodb/src/run/testDocker.ts, tests/playwright/pages/Account/Users.ts, tests/playwright/tests/db/usersAccounts/accountUserManagement.spec.ts, tests/playwright/tests/db/usersAccounts/rolesCreate.spec.ts
=> test: enable org role test

packages/nc-gui/components/dashboard/settings/data-sources/CreateBase.vue, packages/nc-gui/components/dashboard/settings/data-sources/EditBase.vue
=> fix: sync edit  base design with  create base design

packages/nc-gui/components/cell/attachment/index.vue
=> feat: resize attachment image

packages/nc-gui/components/smartsheet/Gallery.vue
Implemented search for gallery view
=> fix(nc-gui): gallery search

packages/nc-gui/components/dashboard/TreeView/BaseOptions.vue, tests/playwright/pages/Dashboard/TreeView.ts
=> fix: i18n label

packages/nocodb/src/utils/roleHelper.ts
Value can be null so we need to handle that case
=> fix: null check for role power function

packages/nc-gui/components/dashboard/Sidebar/TopSection.vue
add translate to `title.teamAndSettings` on TopSection.vue
Run local successful with stub on .json
=> feat(nc-gui): add translate to title.teamAndSettings

packages/nc-gui/layouts/shared-view.vue, packages/nc-gui/pages/index.vue, packages/nc-gui/pages/index/[typeOrId].vue, packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index.vue, packages/noco-docs/docusaurus.config.js, packages/noco-docs/package-lock.json, packages/noco-docs/package.json, packages/noco-docs/src/modules/tele.js
- Missing scrollbar in shared view ( closes #6276)
- Docs analytics
=> Miscellaneous UI fixes

packages/nc-gui/components/dashboard/TreeView/BaseOptions.vue, tests/playwright/pages/Dashboard/TreeView.ts
=> test: context menu import fix

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/dashboard/settings/DataSources.vue, packages/nc-gui/components/erd/Flow.vue, packages/nc-gui/components/erd/TableNode.vue, packages/nc-gui/components/general/Modal.vue, packages/nc-gui/components/smartsheet/toolbar/Reload.vue, packages/nc-gui/components/smartsheet/toolbar/ViewInfo.vue
* Relations opened from project is made a modal
* Zoom in modal adjusted
=> feat(nc-gui): relations made modal

packages/nc-gui/components/account/AppStore.vue, packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue, packages/nc-gui/components/general/JoinCloud.vue, packages/nc-gui/components/workspace/Menu.vue
* Join cloud is made a button.
* Alignment fixed for cloud button
* Padding fixed for App Store
* Menu Logo changed
=> feat(nc-gui): cloud button ui update

packages/nc-gui/components.d.ts, packages/nc-gui/components/cell/Checkbox.vue, packages/nc-gui/components/cell/attachment/index.vue, packages/nc-gui/components/smartsheet/Gallery.vue, packages/nc-gui/components/virtual-cell/Formula.vue, packages/nc-gui/components/virtual-cell/Links.vue, packages/nc-gui/components/virtual-cell/QrCode.vue, packages/nc-gui/components/virtual-cell/barcode/JsBarcodeWrapper.vue, packages/nocodb/src/helpers/getAst.ts, tests/playwright/pages/Dashboard/ViewSidebar/index.ts
With Image
Without Image
Cards If no Image
=> feat: gallery ui revamp

packages/nc-gui/components/dlg/share-and-collaborate/ManageUsers.vue, packages/nc-gui/components/dlg/share-and-collaborate/View.vue, packages/nc-gui/components/nc/Badge.vue, packages/nc-gui/components/nc/Select.vue, packages/nc-gui/components/project/AccessSettings.vue, packages/nc-gui/components/project/InviteProjectCollabSection.vue, packages/nc-gui/components/project/View.vue, packages/nc-gui/components/roles/Badge.vue, packages/nc-gui/components/roles/Selector.vue, packages/nc-gui/components/workspace/CollaboratorsList.vue, packages/nc-gui/components/workspace/InviteSection.vue, packages/nc-gui/components/workspace/View.vue, packages/nc-gui/utils/iconUtils.ts, tests/playwright/pages/Dashboard/BulkUpdate/index.ts, tests/playwright/pages/WorkspacePage/CollaborationPage.ts, tests/playwright/pages/WorkspacePage/ContainerPage.ts
=> feat: email badging on bulk email send

packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue, packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/dashboard/TreeView/ViewsList.vue, packages/nc-gui/components/dlg/ViewCreate.vue, packages/nc-gui/components/smartsheet/Gallery.vue, packages/nc-gui/components/smartsheet/expanded-form/Header.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue, packages/nc-gui/components/tabs/Smartsheet.vue, packages/nc-gui/composables/useExpandedFormStore.ts, packages/nocodb/src/services/public-datas.service.ts
=> Fix: shared view gallery 

packages/nc-gui/components/smartsheet/Gallery.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, tests/playwright/pages/Dashboard/Grid/index.ts, tests/playwright/tests/db/general/tableColumnOperation.spec.ts
=> fix: disable insert row option from cell context menu

packages/nc-gui/components/smartsheet/toolbar/SearchData.vue, packages/nc-gui/store/views.ts, packages/nocodb/src/modules/datas/helpers.ts
=> fix: Sidebar navigation issues

packages/nc-gui/assets/nc-icons/cpu.svg, packages/nc-gui/assets/nc-icons/database1.svg, packages/nc-gui/assets/nc-icons/server.svg, packages/nc-gui/components/general/ApiTiming.vue, packages/nc-gui/components/smartsheet/Gallery.vue, packages/nc-gui/components/smartsheet/Pagination.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nocodb/src/controllers/data-alias.controller.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/helpers/getAst.ts, packages/nocodb/src/models/Base.ts, packages/nocodb/src/modules/datas/helpers.ts, packages/nocodb/src/services/datas.service.ts, tests/playwright/tests/db/features/filters.spec.ts, tests/playwright/tests/utils/general.ts
- Avoid fetching entire parent table data while fetching the parents.
- Support binary key as belongs to parent key
=> fix: Belongs to performance issue

packages/nc-gui/components/account/Token.vue, tests/playwright/pages/Account/Token.ts, tests/playwright/tests/db/usersAccounts/accountTokenManagement.spec.ts
=> feat: new token table design

packages/nc-gui/assets/style.scss, packages/nc-gui/components.d.ts, packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue, packages/nc-gui/components/nc/MenuItem.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/header/Menu.vue, packages/nc-gui/components/smartsheet/sidebar/RenameableMenuItem.vue, packages/nc-gui/windi.config.ts, packages/nocodb-sdk/src/lib/Api.ts, tests/playwright/pages/Dashboard/Grid/Group.ts, tests/playwright/pages/Dashboard/Grid/index.ts, tests/playwright/tests/db/columns/columnAttachments.spec.ts
=> fix: missing ui features in context menu

.github/workflows/publish-docs-index-typesense.yml, packages/noco-docs/typesense-scrape-config.json
- [ x] chore: (updating grunt tasks etc; no production code change)
=> typesense-scraper workflow job

.github/workflows/publish-docs-index-typesense.yml
=> fix users and work-dir for gh workflow

packages/noco-docs/docusaurus.config.js, packages/noco-docs/package-lock.json, packages/noco-docs/package.json, packages/noco-docs/src/css/custom.scss
=> add default typesense search bar to docs site

.github/workflows/playwright-test-workflow.yml
=> fix gh_runner_artf_url

packages/nc-gui/components/general/ColorPicker.vue, packages/nc-gui/components/smartsheet/column/SelectOptions.vue
- closes #6483
https://github.com/nocodb/nocodb/assets/66205494/c93a3d10-5952-4d3e-8f6e-364a4c2b2ae2
=> fix: color picker realtime update

packages/nc-gui/components/cell/Checkbox.vue, packages/nc-gui/components/smartsheet/column/DefaultValue.vue
* Default value input padding fixed
=> Nc fix/checkbox

packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue, packages/nc-gui/composables/useViewFilters.ts, packages/nocodb/src/db/conditionV2.ts
- Show filter options based on Lookup column type
- MySQL date comparison query correction
=> Show filter options based on lookup column type

.github/workflows/playwright-test-workflow.yml, .github/workflows/pre-build-for-playwright.yml, scripts/self-hosted-gh-runner/node-pnpm-check.sh, tests/playwright/scripts/self-hosted-gh-runner/node-pnpm-check.sh
=> install pnpm only first time or on version mismatch

packages/nc-gui/components/dlg/share-and-collaborate/SharePage.vue
=> fix: remove rtl orientation for ee

packages/nc-gui/components/smartsheet/grid/Table.vue
=> feat: disabled cell ui

packages/nc-gui/components/webhook/Editor.vue
=> fix: disable webhook body configuration in EE

packages/nc-gui/components/tabs/auth/user-management/ShareBase.vue
Leftover from project -> base change
=> fix: duplicated variable name

packages/nc-gui/components/smartsheet/header/Cell.vue, packages/nc-gui/components/smartsheet/header/VirtualCell.vue, tests/playwright/pages/Dashboard/Grid/index.ts
=> fix: drop overlapping tooltip

packages/nc-gui/components/smartsheet/grid/Table.vue
- drop unnecessary refs
- change pagination value after loading data (drop await on change page which is blocking)
=> fix: frontend performance

packages/nc-gui/assets/nc-icons/bt-solid.svg, packages/nc-gui/assets/nc-icons/hm-solid.svg, packages/nc-gui/assets/nc-icons/mm-solid.svg, packages/nc-gui/components/smartsheet/header/VirtualCellIcon.ts, packages/nc-gui/components/virtual-cell/components/Header.vue, packages/nc-gui/utils/iconUtils.ts
=> feat: update Links icons

packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/services/data-table.service.ts
- Support both title and column_name for PK
- throwExceptionIfNotExist logic
- move check before update
- add check to delete
=> fix: new data apis

packages/nc-gui/components/smartsheet/Gallery.vue, packages/nc-gui/components/smartsheet/Map.vue, packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/grid/index.vue, packages/nc-gui/components/smartsheet/header/Cell.vue, packages/nc-gui/components/smartsheet/header/VirtualCell.vue, packages/nc-gui/components/tabs/Smartsheet.vue, packages/nc-gui/composables/useExpandedFormStore.ts, packages/nc-gui/utils/dataUtils.ts, packages/nocodb/src/controllers/audits.controller.ts, packages/nocodb/src/services/audits.service.ts
Fixed Flicker when changing records from expanded view
=> Fix: Expanded Records

packages/nc-gui/components/general/ShareProject.vue, packages/nc-gui/composables/useApi/interceptors.ts, packages/nc-gui/middleware/auth.global.ts, packages/nc-gui/pages/forgot-password.vue, packages/nc-gui/pages/signin.vue, packages/nc-gui/pages/signup/[[token]].vue, packages/nocodb/src/modules/jobs/jobs.module.ts, packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.controller.ts
=> feat: continue after signin

packages/nocodb/src/modules/jobs/jobs/at-import/helpers/fetchAT.ts
- at import is broken due to some response change, fixed regex to fit new pattern
=> fix: fetch at parsing

packages/nc-gui/components/project/View.vue
=> fix: members to settings route

packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/composables/useExpandedFormStore.ts
- Fixed issue with comment not loading and syncing with the grid comment count
- Fixed grid jumping when comments are there
=> Expanded form bug fix

packages/nc-gui/assets/nc-icons/lookup.svg, packages/nc-gui/components/cell/attachment/Image.vue, packages/nc-gui/components/cell/attachment/Modal.vue, packages/nc-gui/components/cell/attachment/index.vue, packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/utils/iconUtils.ts
Added Copy Record URL
Updated Delete Modal Text to be Row Display name
=> Fix: expanded Record

packages/nc-gui/components/nc/Pagination.vue, packages/nc-gui/components/smartsheet/Pagination.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/virtual-cell/BelongsTo.vue, packages/nc-gui/components/virtual-cell/HasMany.vue, packages/nc-gui/components/virtual-cell/Links.vue, packages/nc-gui/components/virtual-cell/ManyToMany.vue, packages/nc-gui/components/virtual-cell/components/ListItems.vue, packages/nc-gui/composables/useViewData.ts, tests/playwright/pages/Dashboard/Grid/index.ts
- Reuse grid cells
- Skeleton loader keep table headers on page change
- Only load link modals on demand
=> feat: grid optimizations

packages/nocodb/src/services/datas.service.ts
=> refactor: Replace console.log with Nestjs Logger

packages/nc-gui/components/dashboard/TreeView/AddNewTableNode.vue, packages/nc-gui/components/dashboard/TreeView/BaseOptions.vue, packages/nc-gui/components/dlg/AirtableImport.vue, packages/nc-gui/components/project/ImportModal.vue
=> fix: pass base id to at import modal

packages/nc-gui/components/project/AccessSettings.vue
closes #6434
Show a super badge for super user in project list, allow him to update users other than owner.
=> fix: handle super user on project collaborator list

packages/nc-gui/components/cell/MultiSelect.vue, packages/nc-gui/components/cell/SingleSelect.vue, packages/nc-gui/components/smartsheet/Cell.vue, packages/nc-gui/components/smartsheet/column/DefaultValue.vue, packages/nc-gui/components/smartsheet/column/SelectOptions.vue, packages/nocodb/src/db/sql-client/lib/sqlite/SqliteClient.ts, packages/nocodb/src/services/columns.service.ts
- allow quoted default values
- fix duplicate if default value present
=> fix: default value for select options

packages/nc-gui/composables/useMultiSelect/convertCellData.ts, packages/nc-gui/composables/useMultiSelect/index.ts
Small fix until we find a better way to handle.
=> fix: long text to single text paste

packages/nc-gui/components/cell/MultiSelect.vue, packages/nc-gui/components/cell/SingleSelect.vue, packages/nocodb/src/services/columns.service.ts
- handle trailing spaces
- supported types
=> fix: text to select conversion

packages/nc-gui/components/virtual-cell/Links.vue, packages/nc-gui/components/virtual-cell/components/ListChildItems.vue
=> fix: skelton missing in link modal

packages/nc-gui/package.json, pnpm-lock.yaml
<details><summary>Details</summary>
<p>
HTTP snippet was not working on  new codebase but reducing the version is working fine
</p>
</details>  
=> fix: downgraded http snippet

packages/nc-gui/components/dashboard/TreeView/ViewsList.vue, packages/nc-gui/components/dashboard/settings/DataSources.vue, packages/nc-gui/components/dashboard/settings/data-sources/CreateBase.vue, packages/nc-gui/components/dashboard/settings/data-sources/EditBase.vue, packages/nc-gui/components/dlg/ProjectDuplicate.vue, packages/nc-gui/components/dlg/TableCreate.vue, packages/nc-gui/components/dlg/TableDuplicate.vue, packages/nc-gui/components/dlg/TableRename.vue, packages/nc-gui/components/dlg/ViewCreate.vue, packages/nc-gui/components/dlg/ViewDelete.vue, packages/nc-gui/components/dlg/WorkspaceDelete.vue, packages/nc-gui/store/views.ts, tests/playwright/pages/Dashboard/Command/CmdKPage.ts
=> fix: Use table name for recent Views in default view

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/smartsheet/toolbar/GroupByMenu.vue
=> fix: removed reload menu:

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/dashboard/settings/DataSources.vue, packages/nc-gui/components/general/BaseLogo.vue, packages/nc-gui/components/nc/Tooltip.vue, packages/nc-gui/components/project/AllTables.vue, packages/nc-gui/components/project/View.vue, tests/playwright/pages/Dashboard/ProjectView/DataSourcePage.ts
Data sources table now makes button icon only on small screen and fixed issue with base logo
Added workspace user count to project view
Improved Base count in project view
Fixed base deletion issue by creator
Added tooltip for Data sources table buttons only on small screen
=> Misc issues

packages/nc-gui/store/views.ts
=> refactor: unify view store

packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/composables/useGridViewColumn.ts, packages/nc-gui/plugins/resizeDirective.ts
=> fix: column resize

packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/virtual-cell/components/ListChildItems.vue, packages/nc-gui/components/virtual-cell/components/ListItems.vue
=> Nc fix/grid loader

packages/nc-gui/components/cell/attachment/index.vue, packages/nc-gui/components/smartsheet/Kanban.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/toolbar/ViewInfo.vue, packages/nc-gui/composables/useExpandedFormStore.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/helpers/getAst.ts
=> feat(nc-gui): update kanban card design

packages/nc-gui/components/smartsheet/column/SelectOptions.vue
=> Single select list perf followup

packages/nocodb/src/filters/global-exception/global-exception.filter.ts
=> refactor: Avoid unnecessary error logging

packages/nc-gui/components/cell/attachment/index.vue
=> fix(nc-gui): Fixed issue with image opening in kanban view

packages/nc-gui/components/dashboard/settings/DataSources.vue, packages/nc-gui/components/dashboard/settings/data-sources/CreateBase.vue, packages/nc-gui/components/general/Modal.vue, packages/nc-gui/components/project/AllTables.vue, packages/nc-gui/components/workspace/View.vue
=> fix: disable closing create source modal while creating

packages/nc-gui/components/cell/Checkbox.vue, packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
=> Nc fix/misc

packages/nc-gui/components/template/Editor.vue, packages/nc-gui/helpers/parsers/CSVTemplateAdapter.ts, packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
=> fix: import various

packages/nc-gui/components/dlg/SharedBaseDuplicate.vue, packages/nc-gui/pages/index.vue
Stay in modal until it gets completed
=> fix: better ux for duplicate shared base

packages/nc-gui/components/dashboard/TreeView/index.vue, packages/nc-gui/components/dlg/ProjectDuplicate.vue, packages/nc-gui/components/dlg/SharedBaseDuplicate.vue, packages/nc-gui/components/dlg/TableDuplicate.vue
Moved poller to modal, so keep modal open while job is running
=> fix: better ux for duplicate modals

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/dlg/ProjectDuplicate.vue, packages/nc-gui/components/dlg/SharedBaseDuplicate.vue, packages/nc-gui/components/dlg/TableDuplicate.vue, packages/nc-gui/components/nc/Pagination.vue, packages/nc-gui/components/workspace/ProjectList.vue, packages/nc-gui/store/config.ts
- remove leftover code
- use storeToRefs before watch
=> fix: remove leftover code

.github/workflows/release-npm.yml
This reverts commit 5f1e8aec18baede1bf923e81a1a34ead54cc3802.
=> Revert "chore: hardcode package name"

packages/nocodb/src/schema/swagger-v2.json
=> Swagger json v2 path correction

packages/nc-gui/helpers/parsers/parserHelpers.ts
=> fix: convert cell value before calling isURL method to avoid unexpected error

packages/nocodb/src/db/conditionV2.ts
=> fix: Convert condition value type to string before applying any string method

packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts, packages/nocodb/src/plugins/backblaze/Backblaze.ts, packages/nocodb/src/plugins/gcs/Gcs.ts, packages/nocodb/src/plugins/linode/LinodeObjectStorage.ts, packages/nocodb/src/plugins/mino/Minio.ts, packages/nocodb/src/plugins/ovhCloud/OvhCloud.ts, packages/nocodb/src/plugins/s3/S3.ts, packages/nocodb/src/plugins/scaleway/ScalewayObjectStorage.ts, packages/nocodb/src/plugins/spaces/Spaces.ts, packages/nocodb/src/plugins/upcloud/UpoCloud.ts, packages/nocodb/src/plugins/vultr/Vultr.ts, packages/nocodb/src/services/attachments.service.ts
- Add responseType to axios request of upload by url
=> fix: upload via url to buckets

packages/nc-gui/components/dlg/QuickImport.vue, packages/nc-gui/package.json, packages/nc-gui/utils/workerUtils.ts, pnpm-lock.yaml
=> fix: Import worker issue

packages/noco-docs/docusaurus.config.js, packages/noco-docs/src/css/header.scss
- Add join cloud button to docs
Desktop:
Mobile:
=> docs: join cloud button

packages/nc-gui/helpers/parsers/CSVTemplateAdapter.ts, packages/nc-gui/helpers/parsers/ExcelTemplateAdapter.ts, packages/nc-gui/helpers/parsers/parserHelpers.ts
- revise isCheckboxType logic
- use isCheckboxType for init detect
=> fix(nc-gui): single select in quick import

packages/nc-gui/components/cell/MultiSelect.vue, packages/nc-gui/components/cell/SingleSelect.vue, packages/nc-gui/components/cell/attachment/Carousel.vue, packages/nc-gui/components/cell/attachment/index.vue, packages/nc-gui/components/dashboard/Sidebar.vue, packages/nc-gui/components/dashboard/TreeView/TableNode.vue, packages/nc-gui/components/nc/Select.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue
Fixed styling of non view table nodes in mobile view
SingleSelect and MutliSelect improved for mobile view
Improved attachment cell for mobile
=> Mobile followup

packages/nc-gui/helpers/parsers/CSVTemplateAdapter.ts, packages/nc-gui/helpers/parsers/ExcelTemplateAdapter.ts
=> fix(nc-gui): import type mismatch

packages/nocodb/src/db/BaseModelSqlv2.ts
- Handle signing for mm lookups over attachments
=> fix: handle attachment lookups

packages/nocodb/src/helpers/columnHelpers.ts, packages/nocodb/src/services/columns.service.ts
=> fix: avoid duplicate column_name error by adding suffix

packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
=> feat: groupby airtable import

packages/nc-gui/components/nc/Button.vue, packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/composables/useExpandedFormStore.ts
=> Nc fix/comment save delay removed

packages/nc-gui/components/dlg/AirtableImport.vue
- Show logs to front-end even if job fails too fast
=> fix: better error handling for at import

packages/nocodb/package.json, packages/nocodb/src/Noco.ts, packages/nocodb/src/app.module.ts, packages/nocodb/src/db/conditionV2.ts, packages/nocodb/src/filters/global-exception/global-exception.filter.ts, pnpm-lock.yaml
=> fix: Sentry integration correction

packages/nc-gui/components/smartsheet/expanded-form/index.vue
- Added responsive for mobile in expanded form hidden fields
=> Mobile expanded form

packages/nocodb/src/controllers/utils.controller.ts, packages/nocodb/src/db/sql-mgr/v2/SqlMgrv2.ts
- Hardcode pool for test connection
- Drop connection after testing connection
=> fix: better connection handling for test connection

packages/nocodb/src/schema/swagger-v2.json
Swagger v2 data API description
=> docs: swagger description update for v2

packages/nc-gui/assets/style/fonts.css, packages/nc-gui/windi.config.ts
Increased font weight for each weight class
The issue with this way is we do not allow any font weight below 450
=> Changed font weights

packages/nc-gui/components/cell/Checkbox.vue, packages/nc-gui/components/nc/Button.vue, packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/header/CellIcon.ts, packages/nc-gui/components/smartsheet/toolbar/SearchData.vue
Ref https://github.com/nocodb/nocodb/issues/6505
Fixed generic button on focus style coming when focused if we hide/unhide the browser window
Fixed option alignment for expanded form
Improved UI for expanded form
Improved search button style
Fixed add new record button hiding when scrolling to right
=> Misc UI fix

packages/nc-gui/plugins/state.ts
Fixes: #https://github.com/nocodb/nocodb/issues/6700
=> Fixed i18n fallback locale not loading issue

packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
=> fix: enable autosave by default, since we don't have save button anymore

packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue, packages/nc-gui/lang/en.json
=> Add forum link in sidebar bottom menu

packages/nocodb/src/services/meta-diffs.service.ts
=> fix: exclude Qrcode and Barcode while checking removed column

packages/nocodb/src/controllers/utils.controller.ts, packages/nocodb/src/filters/global-exception/global-exception.filter.ts
=> Refactor: remove rate-limiter for health api

packages/nc-gui/components/dashboard/settings/DataSources.vue, packages/nc-gui/components/dashboard/settings/Erd.vue, packages/nc-gui/components/dlg/ProjectErd.vue, packages/nc-gui/components/smartsheet/details/Erd.vue, tests/playwright/tests/db/features/erd.spec.ts
Fixes #https://github.com/nocodb/nocodb/issues/6458
=> Hide col for project erd

packages/nocodb/src/services/api-docs/swagger/getSwaggerColumnMetas.ts, packages/nocodb/src/services/api-docs/swagger/templates/params.ts
- Closes #6477 
- Closes #6783 
=> fix: Swagger schema corrections

packages/nc-gui/components/shared-view/Gallery.vue, packages/nc-gui/components/shared-view/Grid.vue, packages/nc-gui/components/shared-view/Kanban.vue, packages/nc-gui/components/shared-view/Map.vue, packages/nc-gui/composables/useViewSorts.ts, tests/playwright/tests/db/views/viewGridShare.spec.ts
=> refactor: Avoid loading default sort in shared view

packages/nc-gui/components/account/UserList.vue, packages/nc-gui/lib/acl.ts, packages/nocodb/src/utils/acl.ts
Fixes: #https://github.com/nocodb/nocodb/issues/6784
=> Added user management to org creator and user cannot delete them selves

packages/nocodb/src/models/Column.ts
=> fix: Column meta update is not persisting the change in meta db

packages/nocodb/src/db/BaseModelSql.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/helpers/extractLimitAndOffset.ts, packages/nocodb/src/services/utils.service.ts
- closes: #6790 
`DB_QUERY_LIMIT_DEFAULT=345`
=> fix(nocodb): config limit

packages/nocodb/src/db/sql-client/lib/sqlite/SqliteClient.ts
=> fix: Avoid treating default value `CURRENT_TIMESTAMP`as string

packages/noco-docs/docusaurus.config.js
=> fix(docs): Site url correction

packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue, packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/column/SelectOptions.vue, packages/nc-gui/components/smartsheet/details/Fields.vue, packages/nc-gui/composables/useTableNew.ts, tests/playwright/tests/db/general/multiFieldEditor.spec.ts
=> Nc feat/fields follow

packages/nocodb/src/helpers/stringHelpers.ts, packages/nocodb/src/services/attachments.service.ts, packages/nocodb/src/services/public-datas.service.ts
=> fix(nocodb): attachment original name

packages/nc-gui/assets/style.scss, packages/nc-gui/components/dashboard/Sidebar/TopSection.vue, packages/nc-gui/components/project/View.vue, packages/nc-gui/components/smartsheet/toolbar/ViewInfo.vue, packages/nc-gui/lang/en.json, packages/nc-gui/store/tables.ts
=> Nc fix/breadcrumb linked

packages/nc-gui/composables/useMultiSelect/index.ts
=> fix: Backspace to delete selected cell

packages/nc-gui/components/cell/Currency.vue, packages/nc-gui/components/cell/Decimal.vue, packages/nc-gui/components/cell/Duration.vue, packages/nc-gui/components/cell/Email.vue, packages/nc-gui/components/cell/Float.vue, packages/nc-gui/components/cell/Percent.vue, packages/nc-gui/components/cell/PhoneNumber.vue, packages/nc-gui/components/cell/Text.vue, packages/nc-gui/components/cell/TextArea.vue, packages/nc-gui/components/cell/Url.vue, packages/nc-gui/composables/useUndoRedo.ts
=> fix: stop undo actions on event for inputs

packages/nocodb/src/services/columns.service.ts
- Avoid throwing if no options provided
=> fix: null check for select options

packages/nc-gui/components/account/Profile.vue, packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue, packages/nc-gui/components/general/UserIcon.vue, packages/nc-gui/components/project/AccessSettings.vue, packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/composables/useRoles/index.ts
=> Fixed user display name

packages/nc-gui/components/dlg/ViewCreate.vue, packages/nc-gui/components/workspace/CreateProjectDlg.vue, packages/nc-gui/composables/useTableNew.ts, tests/playwright/tests/db/views/viewKanban.spec.ts
=> Nc fix/remove untitled default name

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/dashboard/TreeView/TableNode.vue, packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue
=> Nc fix/remove capitalization

packages/nc-gui/assets/nc-icons/file-image.svg, packages/nc-gui/components/virtual-cell/components/ListItem.vue, packages/nc-gui/utils/iconUtils.ts
=> Nc fix/links modal UI fix

packages/nc-gui/pages/index.vue
=> fix: Cleanup redirection url from localstorage

packages/nc-gui/components/smartsheet/column/DefaultValue.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue
=> Nc fix/expanded form readonly field

packages/nc-gui/components/nc/Pagination.vue
=> fix: Pagination virtual scroll bug

packages/nc-gui/components/dlg/KeyboardShortcuts.vue, packages/nc-gui/components/nc/Pagination.vue, packages/nc-gui/components/smartsheet/Pagination.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/grid/usePaginationShortcuts.ts, packages/noco-docs/docs/020.getting-started/040.keyboard-shortcuts.md
=> Nc fix/keyboard shortcut for changing page

packages/nc-gui/components/virtual-cell/components/ListChildItems.vue
closes: https://github.com/nocodb/nocodb/issues/6844
Linked records modal from form view is stuck with skeleton loader
https://www.loom.com/share/f745d0ae3d8a4a87bcaf53d7c5528e6b
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
=> fix: Linked records modal from form view is stuck with skeleton loader

packages/nc-gui/components/smartsheet/details/Fields.vue
=> fix(nc-gui): column hash not updated on meta change

packages/nocodb/src/db/sql-client/lib/sqlite/SqliteClient.ts
=> Nc fix/geo default value fix

packages/nc-gui/components/virtual-cell/Lookup.vue
=> Nc fix/lookup overflow fix

packages/nocodb/src/helpers/webhookHelpers.ts
=> Exclude unnecessary contents from webhook error log

packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts, packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
=> fix: this record exist issue for pg duplicate

packages/nocodb/src/controllers/attachments-secure.controller.ts, packages/nocodb/src/controllers/attachments.controller.ts, packages/nocodb/src/services/attachments.service.ts
=> fix: use sendFile for old apis

packages/nocodb/src/Noco.ts, packages/nocodb/src/filters/global-exception/global-exception.filter.ts
=> refactor: Error logging

packages/nc-gui/components/cell/DatePicker.vue, packages/nc-gui/components/cell/DateTimePicker.vue, packages/nc-gui/plugins/a.dayjs.ts
=> refactor: Move dayjs global changes to plugin to avoid unnecessary code repetition

packages/nocodb-sdk/src/lib/Api.ts, packages/nocodb/src/schema/swagger.json
=> fix: Add max length password validation

packages/nc-gui/components/dashboard/View.vue
=> fix: Added min and max width for sidebar size for desktop

packages/nc-gui/components/dashboard/settings/data-sources/CreateBase.vue, packages/nc-gui/components/dashboard/settings/data-sources/EditBase.vue, packages/nc-gui/composables/useTableNew.ts
=> Nc fix/ignore column camelization when inflection set none

packages/nc-gui/composables/useGlobal/state.ts, packages/nc-gui/composables/useGlobal/types.ts
=> Nc fix/open last opened workspace id if none given on first load

packages/nc-gui/components/nc/Dropdown.vue, packages/nc-gui/components/smartsheet/details/Fields.vue, packages/nc-gui/lang/en.json
=> Nc fix/added column id field explorer

packages/nc-gui/components/smartsheet/grid/Table.vue
=> fix: group by header

packages/nocodb/src/interface/Jobs.ts, packages/nocodb/src/modules/jobs/fallback/fallback-queue.service.ts, packages/nocodb/src/modules/jobs/jobs/source-create/source-create.controller.ts, packages/nocodb/src/modules/jobs/jobs/source-create/source-create.processor.ts, packages/nocodb/src/modules/jobs/jobs/source-delete/source-delete.controller.ts, packages/nocodb/src/modules/jobs/jobs/source-delete/source-delete.processor.ts
=> refactor: job name

packages/nc-gui/components/dashboard/settings/DataSources.vue, packages/nc-gui/components/dashboard/settings/UIAcl.vue, packages/nc-gui/components/general/CopyUrl.vue, packages/nc-gui/components/general/DeleteModal.vue, packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/toolbar/ViewInfo.vue, packages/nc-gui/lang/en.json, packages/nc-gui/store/config.ts
=> Nc fix/misc UI fix 2

packages/nc-gui/components/virtual-cell/QrCode.vue, packages/nc-gui/components/virtual-cell/barcode/Barcode.vue, packages/nc-gui/components/virtual-cell/barcode/JsBarcodeWrapper.vue, packages/nc-gui/lang/en.json, packages/nc-gui/utils/svgToPng.ts
=> Nc feat/add barcode image

packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/db/CustomKnex.ts, packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts, packages/nocodb/src/db/sql-client/lib/KnexClient.ts, packages/nocodb/src/db/sql-client/lib/mysql/MysqlClient.ts, packages/nocodb/src/db/sql-client/lib/pg/PgClient.ts, packages/nocodb/src/models/Source.ts, packages/nocodb/src/services/columns.service.ts, packages/nocodb/src/services/tables.service.ts, tests/playwright/pages/Dashboard/ProjectView/Metadata.ts, tests/playwright/tests/db/features/metaSync.spec.ts
use single exec for all queries
=> fix: use exec

packages/nocodb/src/filters/global-exception/global-exception.filter.ts, packages/nocodb/src/helpers/webhookHelpers.ts, packages/nocodb/src/services/datas.service.ts
=> refactor: use error method for logging error

packages/nc-gui/components/cell/Email.vue, packages/nc-gui/components/cell/GeoData.vue, packages/nc-gui/components/cell/PhoneNumber.vue, packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue, packages/nc-gui/components/dashboard/TreeView/AddNewTableNode.vue, packages/nc-gui/components/dlg/AirtableImport.vue, packages/nc-gui/components/general/CopyUrl.vue, packages/nc-gui/components/general/JoinCloud.vue, packages/nc-gui/components/general/Share.vue, packages/nc-gui/components/general/ShareProject.vue, packages/nc-gui/components/general/Social.vue, packages/nc-gui/components/general/language/Menu.vue, packages/nc-gui/components/smartsheet/ApiSnippet.vue, packages/nc-gui/components/smartsheet/column/FormulaOptions.vue, packages/nc-gui/components/smartsheet/toolbar/ShareView.vue, packages/nc-gui/components/webhook/CallLog.vue, packages/nc-gui/components/webhook/Drawer.vue, packages/nc-gui/components/webhook/Editor.vue, packages/nc-gui/components/workspace/Menu.vue, packages/nc-gui/pages/profile/[[username]].vue, packages/nc-gui/pages/signup/[[token]].vue, packages/nc-gui/utils/svgToPng.ts, packages/nc-gui/utils/urlUtils.ts
=> refactor: Add rel attribute if links are using _blank

packages/nc-gui/components/cell/TextArea.vue, packages/nocodb/src/models/Model.ts
=> Copy base bug fix

packages/nocodb/src/services/app-hooks-listener.service.ts
Drop duplicate handlers(events already triggered from ui)
=> fix: cleanup app-hook handlers

packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts, packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
Re #6874
- Fix issue with sanitize column as virtual columns doesn't have column_name
- Add support for qr/barcode column duplicate
=> fix: duplicate qr and barcode columns

packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
=> fix: null check for serialized column names

packages/nc-gui/components/cell/MultiSelect.vue, packages/nc-gui/components/cell/SingleSelect.vue, packages/nocodb/src/services/columns.service.ts
closes #6960
- Handle trailing space handling for select options while rendering
=> fix: trailing space handling for select options

packages/nocodb/src/db/sql-client/lib/pg/PgClient.ts, packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
=> fix: regex to get default value

packages/nc-gui/store/sidebar.ts
=> Added ws role icon in ws menu

packages/nc-gui/components/smartsheet/details/Fields.vue
=> fix: Fixed virtual column icon fields editor fix

packages/nc-gui/components/cell/Json.vue
=> fix: Invalid json genration

packages/nocodb/src/db/conditionV2.ts, packages/nocodb/src/helpers/getAst.ts, packages/nocodb/src/services/datas.service.ts
=> fix: Apply filter validation on v1 list api

packages/nc-gui/components/dlg/QuickImport.vue, packages/nc-gui/components/template/Editor.vue, packages/nc-gui/composables/useColumnCreateStore.ts, packages/nc-gui/utils/validation.ts, packages/nocodb/src/services/tables.service.ts, tests/playwright/pages/Dashboard/Import/ImportTemplate.ts
=> Nc fix/csv import bug fix

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nocodb/src/controllers/api-docs/api-docs.controller.ts, packages/nocodb/src/services/api-docs/api-docs.service.ts, packages/nocodb/src/services/api-docs/swagger/templates/paths.ts, packages/nocodb/src/services/api-docs/swaggerV2/getPaths.ts, packages/nocodb/src/services/api-docs/swaggerV2/getSchemas.ts, packages/nocodb/src/services/api-docs/swaggerV2/getSwaggerColumnMetas.ts, packages/nocodb/src/services/api-docs/swaggerV2/getSwaggerJSONV2.ts, packages/nocodb/src/services/api-docs/swaggerV2/swagger-base.json, packages/nocodb/src/services/api-docs/swaggerV2/templates/headers.ts, packages/nocodb/src/services/api-docs/swaggerV2/templates/params.ts, packages/nocodb/src/services/api-docs/swaggerV2/templates/paths.ts, packages/nocodb/src/services/api-docs/swaggerV2/templates/schemas.ts
=> Show v2 apis in swagger

packages/nc-gui/components/dlg/AirtableImport.vue, packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
- Delete partially created tables on error
- Loading state for Import button
- Reload tables if import fails
=> fix: at import UX

packages/nc-gui/components/smartsheet/column/SelectOptions.vue
=> fix: use options instead of rendered options

packages/nc-gui/components/smartsheet/column/SelectOptions.vue
=> fix: select options delete and reorder

packages/nc-gui/lib/enums.ts
Correctly modified the translation of "enum Language { ko" in the "enum.ts" file.
- [■] style: (formatting, missing semi colons, etc; no production code change)
=> Korean enum Language correction

packages/nocodb/src/db/BaseModelSqlv2.ts
=> fix: New data api(v2) insert method bug

packages/nocodb/package.json, packages/nocodb/src/plugins/backblaze/Backblaze.ts, packages/nocodb/src/plugins/gcs/Gcs.ts, packages/nocodb/src/plugins/linode/LinodeObjectStorage.ts, packages/nocodb/src/plugins/mino/Minio.ts, packages/nocodb/src/plugins/ovhCloud/OvhCloud.ts, packages/nocodb/src/plugins/s3/S3.ts, packages/nocodb/src/plugins/scaleway/ScalewayObjectStorage.ts, packages/nocodb/src/plugins/spaces/Spaces.ts, packages/nocodb/src/plugins/upcloud/UpoCloud.ts, packages/nocodb/src/plugins/vultr/Vultr.ts, pnpm-lock.yaml
- Avoid loading all file to memory
=> fix(s3): use stream to upload via url

packages/noco-docs/docs/150.engineering/060.builds-and-releases.md
Fix GitHub Casing issue in  060.builds-and-releases.md
=> Fix GitHub Casing issue in  060.builds-and-releases.md

packages/nc-gui/composables/useTableNew.ts, packages/nc-gui/store/views.ts
=> fix: on clicking table node navigate to default view

packages/nocodb/src/db/BaseModelSqlv2.ts
=> fix: Avoid treating value as column_name in sql join 

packages/nocodb/src/db/BaseModelSqlv2.ts
- closes #7020 
- Ignore duplicate item in id list using Set
=> fix: ignore duplicate item in  LTAR

packages/nc-gui/components/smartsheet/details/Fields.vue
=> fix: delete for formula in fields menu

packages/nocodb-sdk/package.json, packages/nocodb-sdk/src/lib/Api.ts, packages/nocodb/package.json, pnpm-lock.yaml, scripts/sdk/templates/http-clients/axios-http-client.eta, tests/playwright/package.json
=> chore: bump axios version

packages/nc-gui/components/dashboard/TreeView/TableNode.vue, packages/nc-gui/components/smartsheet/Pagination.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/tabs/Smartsheet.vue, packages/nc-gui/composables/useTableNew.ts, packages/nc-gui/composables/useViewData.ts, packages/nc-gui/lib/types.ts, packages/nc-gui/store/tables.ts, packages/nc-gui/store/views.ts
=> Nc fix/skelton fix

packages/nc-gui/assets/nc-icons/credit-card.svg, packages/nc-gui/assets/nc-icons/layers.svg, packages/nc-gui/components/cell/DatePicker.vue, packages/nc-gui/components/cell/DateTimePicker.vue, packages/nc-gui/components/cell/MultiSelect.vue, packages/nc-gui/components/cell/SingleSelect.vue, packages/nc-gui/components/cell/attachment/Modal.vue, packages/nc-gui/components/cell/attachment/index.vue, packages/nc-gui/components/dlg/share-and-collaborate/SharePage.vue, packages/nc-gui/components/smartsheet/Cell.vue, packages/nc-gui/components/smartsheet/Form.vue, packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/details/Fields.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/header/Cell.vue, packages/nc-gui/components/smartsheet/header/VirtualCell.vue, packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue, packages/nc-gui/components/virtual-cell/BelongsTo.vue, packages/nc-gui/components/virtual-cell/HasMany.vue, packages/nc-gui/components/virtual-cell/Links.vue, packages/nc-gui/components/virtual-cell/ManyToMany.vue, packages/nc-gui/components/virtual-cell/components/ItemChip.vue, packages/nc-gui/lang/en.json, packages/nc-gui/store/views.ts, tests/playwright/pages/Dashboard/Grid/index.ts, tests/playwright/pages/Dashboard/common/Footbar/index.ts, tests/playwright/pages/Dashboard/common/Toolbar/ViewMenu.ts, tests/playwright/tests/db/general/viewMenu.spec.ts
Fixes: https://github.com/nocodb/nocodb/issues/6934
=> Locked mode 

packages/nc-gui/lib/acl.ts
Enable Excel import for creators & editors, not just super-admin
Manually tested locally
=> fix: Update acl.ts to allow editor to import excel files

packages/nc-gui/components/cell/MultiSelect.vue, packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/column/SelectOptions.vue, packages/nc-gui/components/virtual-cell/Lookup.vue, packages/nc-gui/components/virtual-cell/QrCode.vue, packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/db/generateLookupSelectQuery.ts, packages/nocodb/src/db/sortV2.ts
=> Miscellaneous bug fixes/enhancements

packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts, packages/nocodb/src/modules/jobs/jobs/at-import/helpers/readAndProcessData.ts
- properly handle nested lookups
- improved duplicate name generation
- truncate select options that are longer than 255 chars
=> fix: various at-import issues

packages/nc-gui/components/smartsheet/Toolbar.vue, packages/nc-gui/components/smartsheet/VirtualCell.vue, packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue, packages/nc-gui/components/virtual-cell/Links.vue, packages/nc-gui/components/virtual-cell/components/ListChildItems.vue, packages/nc-gui/components/virtual-cell/components/ListItem.vue
Closes [Bug: Additional download menu displayed in toolbar for viewer & commenter role](https://github.com/nocodb/nocodb/issues/7065)
Closes https://github.com/nocodb/nocodb/issues/7066
Closes https://github.com/nocodb/nocohub/issues/1908
=> Nc fix/misc 3

packages/nc-gui/composables/useGlobal/state.ts, packages/nc-gui/composables/useGlobal/types.ts, packages/nc-gui/pages/signin.vue, packages/nocodb/src/models/Store.ts, packages/nocodb/src/services/utils.service.ts, packages/nocodb/src/utils/globals.ts
- re https://github.com/nocodb/nocodb/issues/4330#issuecomment-1819891775
=> Remove signup link from signup page if invite only signup enabled

packages/nocodb-sdk/src/lib/formulaHelpers.ts
- use title instead of id while substituting
=> fix: use title instead of id while substituting

packages/nc-gui/components/nc/Switch.vue
=> fix: Render label span only if default  slot is defined

packages/nocodb/src/helpers/getAst.ts
=> fix: Fields query param - virtual column

packages/nocodb/src/controllers/data-table.controller.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/services/data-table.service.ts
=> fix: Extract row id value using title

packages/nocodb/src/controllers/attachments-secure.controller.ts, packages/nocodb/src/controllers/attachments.controller.ts, packages/nocodb/src/services/attachments.service.ts
Only preview image, pdf and plain text attachments.
=> fix: filter mimetypes to preview in browser

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/dashboard/TreeView/TableNode.vue, packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue, packages/nc-gui/components/dashboard/settings/UIAcl.vue, packages/nc-gui/components/nc/Tooltip.vue, packages/nc-gui/components/project/View.vue, packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue, packages/nc-gui/components/smartsheet/details/Fields.vue, packages/nc-gui/components/smartsheet/header/Cell.vue, packages/nc-gui/components/smartsheet/header/VirtualCell.vue, packages/nc-gui/components/smartsheet/toolbar/CreateSort.vue, packages/nc-gui/components/smartsheet/toolbar/FieldListAutoCompleteDropdown.vue, packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue, packages/nc-gui/components/smartsheet/toolbar/OpenedViewAction.vue, packages/nc-gui/components/smartsheet/toolbar/SearchData.vue, tests/playwright/pages/Dashboard/Grid/index.ts
added **showOnTruncateOnly** prop in **NcTooltip** component to show tooltip when the element is truncated
=> fix : added showOnTruncateOnly prop in tooltip component

packages/nocodb/src/db/conditionV2.ts
=> fix: exact date filter not working on datetime

packages/nc-gui/components/project/View.vue
- Re https://github.com/nocodb/nocodb/pull/7179#pullrequestreview-1770549502
=> fix: Load userList only if allowed

packages/nocodb/src/version-upgrader/ncXcdbLTARIndexUpgrader.ts
=> fix: Ignore throwing error in upgrader if error is index already exist

packages/nc-gui/components/smartsheet/details/Fields.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/tabs/Smartsheet.vue, packages/nc-gui/composables/usePaste.ts, packages/nc-gui/lang/en.json, packages/nc-gui/utils/iconUtils.ts, tests/playwright/pages/Dashboard/Grid/index.ts, tests/playwright/tests/db/general/cellSelection.spec.ts
=> feat: paste option in cell right click context menu

packages/nc-gui/components/smartsheet/expanded-form/index.vue
=> fix(nc-gui): add missing kanban clbk in expanded form

packages/nc-gui/components/smartsheet/grid/GroupBy.vue, packages/nc-gui/components/smartsheet/grid/GroupByTable.vue
=> fix: Avoid setting default value(LTAR/Links) when adding new row in grouped by table

packages/nc-gui/components/template/Editor.vue
=> fix : fixed table cell overflow in uploadExcel Model

packages/nocodb/src/utils/common/NcConnectionMgrv2.ts
=> fix: Mysql - If buffer type convert to hex value and convert to int only if type is bit

packages/nocodb/src/db/sql-client/lib/KnexClient.ts
=> fix: support function calls for default timestamp

packages/nc-gui/components/smartsheet/grid/Table.vue
Fill handle bugs on closing expanded form
=> fix: clear fill handle properly on expanded form close

.github/workflows/uffizzi-preview.yml
This change sanitizes user input from contributor fork workflows. This mitigates a security vulnerability identified by the `backstage` project.
=> Updates to Uffizzi Deployment Workflow.

packages/nocodb-sdk/src/lib/formulaHelpers.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
=> fix: Formula followup bugs

packages/nc-gui/components/smartsheet/column/DecimalOptions.vue
=> fix: Update dtxs when decimal precision is changing

packages/nocodb-sdk/src/lib/formulaHelpers.ts, packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
=> Nc fix/formula fixes

packages/nocodb/src/db/BaseModelSqlv2.ts
=> fix: Handle scenarios where no select options are there

packages/nc-gui/components/smartsheet/Toolbar.vue, packages/nc-gui/composables/useViewData.ts
closes #7265
search added in public shared view
=> feature / search added in shared view

packages/nc-gui/components/virtual-cell/Formula.vue, packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts, packages/nocodb/src/db/functionMappings/commonFns.ts, packages/nocodb/src/helpers/formulaHelpers.ts, packages/nocodb/src/models/Column.ts, packages/nocodb/src/models/FormulaColumn.ts
=> Nc fix/formula bugs

tests/playwright/pages/Base.ts, tests/playwright/pages/Dashboard/Grid/Column/index.ts, tests/playwright/tests/db/columns/columnFormula.spec.ts
=> update tests for invalid function error

packages/noco-docs/docs/130.automation/020.webhook/020.create-webhook.md
=> docs: webhook updates

packages/nocodb/src/db/functionMappings/sqlite.ts
=> fix: SQLIte Formula - include time value in NOW function

.github/workflows/release-executables.yml
https://github.com/actions/upload-artifact?tab=readme-ov-file#not-uploading-to-the-same-artifact
=> Use different name for upload artifact to avoid conflict

packages/nc-gui/components/smartsheet/header/CellIcon.ts, packages/nc-gui/composables/useSharedFormViewStore.ts
- fix: listing users for shared form user field
- fix: null check on cellIcon
=> fix: shared form user field

packages/nc-gui/components/cell/RichText.vue
=> fix: strike and underline for rich text

tests/playwright/pages/Dashboard/Grid/Column/UserOptionColumn.ts
- Fixed playwright test case fail issue while selecting default user for `single select user field`
=> fix: select default user playwright test fail issue

packages/nocodb-sdk/src/lib/formulaHelpers.ts
- Closes #7324 
- SUBSTR
- MID
- RIGHT
- LEFT
=> fix: Formula validation correction

packages/nc-gui/components/general/NocoIcon.vue
=> fix: Broken logo in Signin/Signup page

packages/nocodb/src/cache/RedisCacheMgr.ts, packages/nocodb/src/cache/RedisMockCacheMgr.ts
- Use type from ioredis for client
=> fix: use type from ioredis for clients

packages/nocodb/src/db/BaseModelSqlv2.ts
- returning id for mysql single insertion
=> fix: mysql single insert

packages/nc-gui/composables/useData.ts
=> fix: Reload data after bulk update

packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/composables/useExpandedFormStore.ts
=> fix: Avoid resetting input field when using Links in expanded form 

packages/nocodb/src/db/BaseModelSqlv2.ts
=> refactor: variable name

packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/column/SelectOptions.vue
- 🔦 Feature: Expand viewable SingleSelect area #7236
=> feat: expand select option area in details fields tab (Sync EE to OSS )

packages/nocodb/src/utils/nc-config/NcConfig.ts
=> refactor: Better error message when meta db connection missing database name

packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/models/Column.ts, packages/nocodb/src/utils/RequestQueue.ts, packages/nocodb/src/version-upgrader/ncXcdbCreatedAndUpdatedTimeUpgrader.ts
=> fix: Upgrader issue - CreatedTime and LastModifiedTime upgrader

packages/nc-gui/components/smartsheet/VirtualCell.vue, packages/nc-gui/components/smartsheet/details/Fields.vue, packages/nc-gui/components/smartsheet/grid/GroupByLabel.vue, packages/nc-gui/components/tabs/Smartsheet.vue, packages/nc-gui/components/virtual-cell/components/ListChildItems.vue, packages/nc-gui/components/virtual-cell/components/ListItems.vue, packages/nc-gui/composables/useLTARStore.ts, packages/nocodb/src/services/columns.service.ts
=> Multifield editor bug fixes ( Sync EE to OSS )

packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue, packages/nc-gui/composables/useViewFilters.ts
=> fix: avoid loading view filters to webhook condition

packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts, packages/nocodb/src/modules/jobs/jobs/at-import/helpers/fetchAT.ts, packages/nocodb/src/services/tables.service.ts
=> fix: various at import issues

packages/nc-gui/components/smartsheet/toolbar/FilterInput.vue, tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts
=> Nc fix/filter bugs

packages/nc-gui/components/cell/User.vue, packages/nocodb/src/services/public-metas.service.ts
=> Nc fix/sharedbase user

packages/nocodb/src/helpers/PagedResponse.ts, packages/nocodb/src/schema/swagger.json
=> Nc fix/pagination bugs

packages/nc-gui/components/smartsheet/column/LookupOptions.vue, packages/nc-gui/components/smartsheet/column/RollupOptions.vue, packages/nc-gui/composables/useApi/interceptors.ts, packages/nc-gui/composables/useGlobal/index.ts, packages/nc-gui/composables/useSmartsheetStore.ts, packages/nc-gui/composables/useViewData.ts, packages/nc-gui/utils/columnUtils.ts, packages/nocodb/src/cache/RedisCacheMgr.ts, packages/nocodb/src/db/BaseModelSqlv2.ts
=> Nc fix/sentry error

packages/nc-gui/components/smartsheet/details/Fields.vue, packages/nc-gui/lang/en.json, tests/playwright/pages/Dashboard/Details/FieldsPage.ts, tests/playwright/pages/Dashboard/Details/index.ts, tests/playwright/tests/db/features/multiFieldEditor.spec.ts
=> Nc test/multi field editor

packages/nocodb/src/db/BaseModelSqlv2.ts
- Handle the case if input provided for user field is array of non-object types
=> fix: handle invalid user object input

packages/nocodb/src/db/conditionV2.ts, packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts, packages/nocodb/src/db/genRollupSelectv2.ts, packages/nocodb/src/db/generateLookupSelectQuery.ts
Turkish letter İ was causing links to break, fixed that and other possible places
=> fix: use knex raw to avoid special character issue

packages/nocodb-sdk/src/lib/formulaHelpers.ts, packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts, packages/nocodb/src/db/functionMappings/commonFns.ts, packages/nocodb/src/db/functionMappings/pg.ts, packages/nocodb/src/models/FormulaColumn.ts
=> fix: formula improvements

packages/nocodb/src/helpers/webhookHelpers.ts
=> Nc fix/webhook filters

packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
- convert cdf to string before processing
=> fix: serialize default value

packages/nocodb-sdk/src/lib/formulaHelpers.ts, packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts, packages/nocodb/src/db/functionMappings/pg.ts
=> Formula - accept all types when when expected type is string

packages/nc-gui/components/dashboard/settings/UIAcl.vue, packages/nc-gui/components/general/TableIcon.vue, packages/nc-gui/components/project/AllTables.vue, packages/nc-gui/components/smartsheet/details/Fields.vue, packages/nc-gui/components/smartsheet/expanded-form/Comments.vue
=> Nc: Misc UI fixes

packages/nc-gui/components/cell/ReadOnlyDateTimePicker.vue, packages/nc-gui/components/cell/ReadOnlyUser.vue, packages/nc-gui/components/cell/RichText.vue, packages/nc-gui/components/cell/User.vue, packages/nc-gui/components/general/UserIcon.vue, packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, tests/playwright/pages/Dashboard/Grid/Column/UserOptionColumn.ts, tests/playwright/pages/Dashboard/common/Cell/UserOptionCell.ts
=> Nc: User based fields ui updates

packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/models/Column.ts, packages/nocodb/tests/unit/model/tests/baseModelSql.test.ts, packages/nocodb/tests/unit/rest/tests/columnTypeSpecific.test.ts, packages/nocodb/tests/unit/rest/tests/newDataApis.test.ts
Fixes: stability issue with unit tests
=> fix: add order to column if missing

packages/nc-gui/components/shared-view/Gallery.vue, packages/nc-gui/components/smartsheet/Kanban.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/composables/useExpandedFormStore.ts, tests/playwright/pages/SharedForm/index.ts
=> Nc: fixed shared gallery & kanban view expanded form issue

packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/grid/useColumnDrag.ts
=> Nc: fixed column drag & drop issue on safari browser

packages/nc-gui/components/dashboard/TreeView/ViewsList.vue, packages/nc-gui/components/smartsheet/Kanban.vue, packages/nc-gui/components/smartsheet/column/SelectOptions.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/grid/useColumnDrag.ts, packages/nc-gui/components/smartsheet/header/CellIcon.ts, packages/nc-gui/components/virtual-cell/HasMany.vue, packages/nc-gui/components/virtual-cell/ManyToMany.vue, packages/nc-gui/composables/useViewGroupBy.ts, packages/nc-gui/lang/en.json, packages/nocodb-sdk/src/lib/formulaHelpers.ts
=> Nc fix/sentry errors 2

packages/nocodb/src/models/Column.ts, packages/nocodb/src/models/Filter.ts, packages/nocodb/src/models/GalleryViewColumn.ts, packages/nocodb/src/models/GridViewColumn.ts, packages/nocodb/src/models/Model.ts, packages/nocodb/src/models/Sort.ts, packages/nocodb/src/models/View.ts
=> Nc fix/delete table view col performance

packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts, packages/nocodb/src/modules/jobs/jobs/at-import/helpers/readAndProcessData.ts
- Log and skip data import errors
- Handle longText
=> fix: at import data

packages/nocodb/src/services/columns.service.ts, packages/nocodb/src/services/tables.service.ts
=> Nc fix: Skip getting column list from database on table/column create

tests/playwright/pages/Account/Users.ts, tests/playwright/tests/db/usersAccounts/accountUserManagement.spec.ts
=> test: remove user before retry

packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts, packages/nocodb/src/modules/jobs/jobs/at-import/helpers/fetchAT.ts, packages/nocodb/src/modules/jobs/jobs/at-import/helpers/readAndProcessData.ts, packages/nocodb/src/plugins/s3/S3.ts, packages/nocodb/src/services/attachments.service.ts
- Reduce memory footprint
- Better concurrency control
=> feat: at import improved

packages/nocodb/src/helpers/getColumnPropsFromUIDT.ts
=> Nc fix: select field issue with trailing spaces when creating using API

packages/nc-gui/components/smartsheet/grid/GroupBy.vue, packages/nocodb/src/db/conditionV2.ts
=> Nc fix: Groupby doesn't work if formula field dataType is numeric

packages/nocodb/src/cache/RedisCacheMgr.ts, packages/nocodb/src/cache/RedisMockCacheMgr.ts
- Fallback to clearing list if a key gone missing
=> fix: fallback for missing list key

packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
=> fix: avoid unnecessary concurrency

packages/nocodb/src/models/Column.ts, packages/nocodb/src/models/Model.ts
=> fix: cache fix for rename operation

packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/grid/GroupByLabel.vue, packages/nc-gui/components/virtual-cell/BelongsTo.vue, packages/nocodb-sdk/src/lib/helperFunctions.ts, packages/nocodb/src/models/Column.ts, packages/nocodb/src/models/View.ts, tests/playwright/pages/Dashboard/Grid/Column/index.ts, tests/playwright/pages/Dashboard/common/Toolbar/Fields.ts, tests/playwright/tests/db/columns/columnLinkToAnotherRecord.spec.ts, tests/playwright/tests/db/columns/columnMenuOperations.spec.ts, tests/playwright/tests/db/columns/columnRelationalExtendedTests.spec.ts, tests/playwright/tests/db/features/metaLTAR.spec.ts, tests/playwright/tests/db/views/viewGridShare.spec.ts
=> Nc fix/UI bug fixes

packages/nocodb/src/db/BaseModelSqlv2.ts
=> Nc fix/nested lookup

markdown/readme/languages/ukrainian.md
This PR adjusts Ukrainian translation.
=> docs(Readme): Adjust Ukrainian translation

packages/nc-gui/components/smartsheet/column/FormulaOptions.vue, packages/nc-gui/components/smartsheet/toolbar/CreateGroupBy.vue, packages/nc-gui/components/smartsheet/toolbar/CreateSort.vue, packages/nc-gui/components/smartsheet/toolbar/FieldListAutoCompleteDropdown.vue, packages/nc-gui/composables/useViewColumns.ts, packages/nocodb-sdk/src/lib/UITypes.ts, packages/nocodb-sdk/src/lib/globals.ts, packages/nocodb-sdk/src/lib/index.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/db/genRollupSelectv2.ts, packages/nocodb/src/services/tables.service.ts
=> Nc fix/m2m table

packages/nc-gui/components/account/UserList.vue, packages/nc-gui/components/roles/Badge.vue, packages/nc-gui/components/roles/Selector.vue, packages/nc-gui/components/workspace/InviteSection.vue
=> Nc fix: org level creator own role update issue

packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/composables/useData.ts, tests/playwright/tests/db/features/webhook.spec.ts
=> Nc fix: bulk delete webhook trigger issue on deleting single selected row 

packages/nocodb/src/db/BaseModelSqlv2.ts
=> fix: Use correct datetime format based on current source(datasource)

packages/nc-gui/components/smartsheet/Form.vue, packages/nc-gui/components/smartsheet/Gallery.vue, packages/nc-gui/components/smartsheet/Map.vue, packages/nc-gui/components/smartsheet/Row.vue, packages/nc-gui/components/smartsheet/SharedMapMarkerPopup.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/grid/GroupBy.vue, packages/nc-gui/components/smartsheet/grid/GroupByTable.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue, packages/nc-gui/components/smartsheet/toolbar/SearchData.vue, packages/nc-gui/components/tabs/Smartsheet.vue, packages/nc-gui/composables/useLTARStore.ts, packages/nc-gui/composables/useViewGroupBy.ts, packages/nc-gui/context/index.ts, packages/nc-gui/utils/colorsUtils.ts
=> Nc fix: offset issue while searching table field value

packages/nc-gui/components/dashboard/TreeView/TableList.vue, packages/nc-gui/components/dashboard/TreeView/ViewsList.vue, packages/nc-gui/components/dashboard/TreeView/index.vue, packages/nc-gui/lib/acl.ts, packages/nc-gui/store/bases.ts, packages/nocodb/src/models/Base.ts, packages/nocodb/src/models/BaseUser.ts, packages/nocodb/src/schema/swagger-v2.json, packages/nocodb/src/schema/swagger.json, packages/nocodb/src/services/bases.service.ts
=> Nc feat: base reorder and fixed views reorder issue

packages/nc-gui/nuxt.config.ts
=> Nc fix: docsearch is not defined

packages/nc-gui/components/nc/Select.vue, packages/nc-gui/composables/useApi/interceptors.ts, packages/nc-gui/composables/useGlobal/state.ts, packages/nc-gui/composables/useGlobal/types.ts, packages/nc-gui/lang/en.json, packages/nc-gui/middleware/auth.global.ts, packages/nc-gui/utils/urlUtils.ts, packages/nc-gui/utils/validation.ts, packages/nocodb/src/controllers/auth/auth.controller.ts, packages/nocodb/src/db/util/DebugMgr.ts, packages/nocodb/src/helpers/apiHelpers.ts, packages/nocodb/src/middlewares/global/global.middleware.ts, packages/nocodb/src/services/users/users.service.ts, packages/nocodb/src/services/utils.service.ts, packages/nocodb/src/strategies/jwt.strategy.ts, packages/nocodb/src/types/express.d.ts, packages/nocodb/src/utils/globals.ts, packages/nocodb/tests/unit/init/cleanupMeta.ts, packages/nocodb/tests/unit/init/index.ts, packages/nocodb/tests/unit/rest/index.test.ts, tests/playwright/pages/Account/Authentication.ts, tests/playwright/pages/Account/index.ts, tests/playwright/pages/SsoIdpPage/OpenIDLoginPage.ts, tests/playwright/pages/SsoIdpPage/SAMLLoginPage.ts, tests/playwright/setup/index.ts
=> Nc - SSO tests

packages/nocodb/src/controllers/auth/auth.controller.ts
=> Nc fix: e.isAuthenticated is not a function

packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue, packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue, packages/nc-gui/components/virtual-cell/Formula.vue, packages/nc-gui/composables/useViewFilters.ts, packages/nc-gui/utils/filterUtils.ts, packages/nocodb-sdk/src/lib/UITypes.ts, packages/nocodb-sdk/src/lib/index.ts, packages/nocodb-sdk/src/lib/sqlUi/SqliteUi.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/db/conditionV2.ts, packages/nocodb/src/db/sortV2.ts
=> Nc feat/formula imp

packages/nc-gui/components/cell/Currency.vue
=> fix(nc-gui): fail to trigger submitCurrency in firefox

packages/nc-gui/composables/useMultiSelect/convertCellData.ts
=> fix(nc-gui): validate date with date format from column meta

packages/nc-gui/components/dashboard/TreeView/index.vue
=> fic(nc-gui): disable base reorder in mobile view nocodb/nocodb#7582

packages/noco-docs/docs/070.fields/020.primary-key.md
=> docs: updates to created-at, updated-at behaviour

packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue, packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue, packages/nc-gui/components/smartsheet/toolbar/ViewInfo.vue, packages/nc-gui/store/tables.ts
=> Nc - fix: shared base breadcrumb links and view options access issue

packages/noco-docs/docs/140.account-settings/030.authentication/010.overview.md, packages/noco-docs/docs/140.account-settings/030.authentication/030.SAML-SSO/010.okta.md, packages/noco-docs/docs/140.account-settings/030.authentication/030.SAML-SSO/020.auth0.md, packages/noco-docs/docs/140.account-settings/030.authentication/030.SAML-SSO/030.ping-identity.md, packages/noco-docs/docs/140.account-settings/030.authentication/030.SAML-SSO/040.azure-ad.md, packages/noco-docs/docs/140.account-settings/030.authentication/030.SAML-SSO/050.keycloak.md, packages/noco-docs/docs/140.account-settings/030.authentication/040.OIDC-SSO/010.okta.md, packages/noco-docs/docs/140.account-settings/030.authentication/040.OIDC-SSO/020.auth0.md, packages/noco-docs/docs/140.account-settings/030.authentication/040.OIDC-SSO/030.ping-identity.md, packages/noco-docs/docs/140.account-settings/030.authentication/040.OIDC-SSO/040.azure-ad.md
=> docs : SSO docs update

packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
=> fix: move filter logic inside condition

packages/nc-gui/components/cell/Currency.vue
- closes: #7415
- closes: #6255
=> fix(nc-gui): save currency issue in safari

packages/nc-gui/components/smartsheet/Cell.vue
=> fix(nc-gui): incorrect condition blocking expand button in text area in share view

docker-compose/setup-script/noco.sh
=> NocoDB docker-compose init script

packages/nocodb/src/modules/jobs/jobs/at-import/helpers/readAndProcessData.ts
closes https://github.com/nocodb/nocohub/issues/2300
=> fix: airtable ltar error

docker-compose/setup-script/noco.sh
=> chore: Remove the SMTP config prompt(setup script)

docker-compose/setup-script/noco.sh
=> NocoDB setup script -  fallback to localhost if public ip not found

packages/nocodb/src/cache/RedisCacheMgr.ts
=> chore: NC_FLUSH_CACHE env variable

packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/grid/usePaginationShortcuts.ts, tests/playwright/tests/db/features/keyboardShortcuts.spec.ts
=> Nc feat(nc-gui): Keyboard interactions on tables: new rows, page navigation

packages/nc-gui/nuxt.config.ts, packages/nocodb/src/cache/CacheMgr.ts
=> Nc fix: sort from field context menu

packages/nc-gui/components/smartsheet/toolbar/RowHeight.vue
=> Nc fix(nc-gui): row height access for viewer role

packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue
=> Nc fix: responsive design UI fixes

docker-compose/setup-script/noco.sh
=> chore: Add Redis and define network explicitly in docker-compose

tests/playwright/constants/index.ts
=> test: fix atbl import

packages/nocodb/src/db/conditionV2.ts, packages/nocodb/src/db/sortV2.ts
=> Nc fix: search with lookup on numbers does not work

packages/nc-gui/components/virtual-cell/components/ListChildItems.vue, packages/nc-gui/components/virtual-cell/components/ListItems.vue
=> Nc fix(nc-gui): auto focus the search field in the 'Add New Link' form

packages/nc-gui/components/smartsheet/Form.vue, packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts, packages/nocodb/src/meta/migrations/v2/nc_039_form_view_filds.ts, packages/nocodb/src/meta/migrations/v2/nc_039_sqlite_alter_column_types.ts, packages/nocodb/src/meta/migrations/v2/nc_040_form_view_alter_column_types.ts, packages/nocodb/src/schema/swagger-v2.json, packages/nocodb/src/schema/swagger.json
=> Nc fix/form view field limit

packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue, packages/nc-gui/components/general/JoinCloud.vue, packages/nc-gui/components/general/ReleaseInfo.vue, packages/nc-gui/components/general/SocialCard.vue
- added rel for twitter link
- replaced no-rel with noopener only for nocodb links
=> fix: rel for links

docker-compose/setup-script/noco.sh
=> chore: Docker-compose volume name correction

packages/nc-gui/components/smartsheet/Row.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/composables/useData.ts, packages/nc-gui/composables/useLTARStore.ts, packages/nc-gui/composables/useMultiSelect/convertCellData.ts, packages/nc-gui/composables/useMultiSelect/index.ts, packages/nc-gui/composables/useSmartsheetRowStore.ts, packages/nc-gui/composables/useViewSorts.ts, packages/nc-gui/lang/en.json, packages/nc-gui/utils/dataUtils.ts, packages/nocodb/src/controllers/data-table.controller.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/schema/swagger.json, packages/nocodb/src/services/data-table.service.ts, packages/nocodb/src/utils/acl.ts
- ref: #3878
- ref: #7552
- ref: #7557
=> Nc copy and and paste a linked record and date/dateTime field value from one cell to another

packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/models/Model.ts
Fixes https://github.com/nocodb/nocodb/issues/7626
=> fix: Support composite key in insert and update APIs

packages/nc-gui/layouts/general.vue, packages/nc-gui/pages/account/index.vue, packages/nc-gui/pages/forgot-password.vue, packages/nc-gui/pages/index/[typeOrId]/form/[viewId].vue, packages/nc-gui/pages/profile/[[username]].vue, packages/nc-gui/pages/projects/index.vue, packages/nc-gui/pages/reset/[id].vue, packages/nc-gui/pages/signin.vue, packages/nc-gui/pages/signup/[[token]].vue, tests/playwright/pages/Account/Authentication.ts, tests/playwright/pages/SsoIdpPage/GoogleLoginPage.ts
=> Nc feat/sso google

packages/nc-gui/components/cell/attachment/utils.ts, packages/nc-gui/composables/useMultiSelect/convertCellData.ts, packages/nc-gui/composables/useMultiSelect/index.ts, packages/nc-gui/lang/en.json, packages/nc-gui/utils/fileUtils.ts, packages/nocodb/src/services/public-datas.service.ts
=> Nc feat: drag and drop image from webpage and fix: allow duplicate file upload

packages/noco-docs/docs/140.account-settings/030.authentication/010.overview.md, packages/noco-docs/docs/140.account-settings/030.authentication/030.SAML-SSO/010.okta.md, packages/noco-docs/docs/140.account-settings/030.authentication/030.SAML-SSO/020.auth0.md, packages/noco-docs/docs/140.account-settings/030.authentication/030.SAML-SSO/030.ping-identity.md, packages/noco-docs/docs/140.account-settings/030.authentication/030.SAML-SSO/040.azure-ad.md, packages/noco-docs/docs/140.account-settings/030.authentication/030.SAML-SSO/050.keycloak.md, packages/noco-docs/docs/140.account-settings/030.authentication/040.OIDC-SSO/010.okta.md, packages/noco-docs/docs/140.account-settings/030.authentication/040.OIDC-SSO/020.auth0.md, packages/noco-docs/docs/140.account-settings/030.authentication/040.OIDC-SSO/030.ping-identity.md, packages/noco-docs/docs/140.account-settings/030.authentication/040.OIDC-SSO/040.azure-ad.md
=> docs : update docs related to SSO

packages/nc-gui/lang/en.json
=> Nc fix: PW test fail issue - Kanban View

packages/nc-gui/.eslintrc.js, packages/nc-gui/components/cmd-j/index.vue, packages/nc-gui/components/general/NocoIcon.vue, packages/nc-gui/layouts/shared-view.vue, packages/nc-gui/utils/iconUtils.ts, pnpm-lock.yaml
- will leave  lint issues related to calendar to Anbarasu.
=> fix: lint issues

packages/noco-docs/docs/140.account-settings/020.api-tokens.md
=> docs: update usage of api token

packages/nc-gui/components/cell/attachment/utils.ts, packages/nc-gui/composables/useMultiSelect/convertCellData.ts, packages/nc-gui/composables/useMultiSelect/index.ts, packages/nc-gui/utils/fileUtils.ts, packages/nocodb-sdk/src/lib/helperFunctions.ts, packages/nocodb/src/services/public-datas.service.ts
=> Nc fix: handle duplicate filename suffix properly

packages/nc-gui/components/smartsheet/details/Fields.vue, packages/nocodb/src/models/View.ts
=> Nc fix: show newly added column in same view & hide from all other views

packages/nc-gui/components/smartsheet/calendar/index.vue, packages/nc-gui/composables/useCalendarViewStore.ts, packages/nc-gui/lang/en.json, packages/nocodb/src/services/datas.service.ts, packages/nocodb/src/services/public-datas.service.ts
=> fix(nc-gui): error handling

packages/nc-gui/components/smartsheet/sidebar/toolbar/ExportCache.vue, packages/nc-gui/components/smartsheet/toolbar/ExportSubActions.vue, packages/nc-gui/components/smartsheet/toolbar/MoreActions.vue
=> fix(nc-gui): export issue

packages/nc-gui/components/cell/attachment/utils.ts
=> fix(nc-gui): file-saver import issue

packages/noco-docs/package-lock.json
=> chore(deps): update package-lock.json in noco-docs

packages/nocodb/src/controllers/base-users.controller.spec.ts, packages/nocodb/src/controllers/grid-columns.controller.ts, packages/nocodb/src/controllers/grids.controller.ts, packages/nocodb/src/controllers/model-visibilities.controller.ts, packages/nocodb/src/controllers/plugins.controller.ts, packages/nocodb/src/controllers/sorts.controller.ts, packages/nocodb/src/controllers/sources.controller.spec.ts, packages/nocodb/src/controllers/sync.controller.ts, packages/nocodb/src/controllers/view-columns.controller.ts, packages/nocodb/src/filters/global-exception/global-exception.filter.spec.ts, packages/nocodb/src/guards/global/global.guard.spec.ts, packages/nocodb/src/interceptors/is-upload-allowed/is-upload-allowed.interceptor.spec.ts, packages/nocodb/src/interface/config.ts, packages/nocodb/src/main.ts, packages/nocodb/src/middlewares/global/global.middleware.spec.ts, packages/nocodb/src/middlewares/gui/gui.middleware.spec.ts, packages/nocodb/src/modules/auth/auth.module.ts, packages/nocodb/src/modules/jobs/fallback/fallback-queue.service.ts, packages/nocodb/src/modules/jobs/jobs.module.ts, packages/nocodb/src/modules/metas/metas.module.ts, packages/nocodb/src/modules/users/users.module.ts, packages/nocodb/src/services/app-hooks/interfaces.ts, packages/nocodb/src/services/base-users/base-users.service.spec.ts, packages/nocodb/src/services/bases.service.spec.ts, packages/nocodb/src/services/org-tokens-ee.service.spec.ts, packages/nocodb/src/strategies/authtoken.strategy/authtoken.strategy.spec.ts, packages/nocodb/src/strategies/google.strategy/google.strategy.ts, packages/nocodb/tsconfig.json
- Get rid of global module reimports
- Rename spec classes
- tsconfig include & exclude
=> fix: nestjs issues

packages/nocodb/src/models/CalendarView.ts
=> fix: wrong usage of deepDel

packages/nc-gui/app.vue, packages/nocodb-sdk/src/lib/formulaHelpers.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts, packages/nocodb/src/services/data-table.service.ts, packages/nocodb/src/services/datas.service.ts
=> fix: various small issues

tests/playwright/tests/db/features/filters.spec.ts
=> Nc test/filter leap year fix

packages/nc-gui/components/virtual-cell/components/ListChildItems.vue, packages/nc-gui/components/virtual-cell/components/ListItems.vue
=> fix(nc-gui): unable to add new record to linked table by `add new link`

packages/nc-gui/components/dlg/ViewCreate.vue
=> fix(nc-gui): invalid docs link

packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue, packages/nc-gui/composables/useMultiSelect/convertCellData.ts, packages/nc-gui/utils/iconUtils.ts, packages/nocodb-sdk/src/lib/dateTimeHelper.ts
=> Nc fix: add support to copy paste date and dateTime with unknown format 

README.md, markdown/readme/languages/chinese.md, markdown/readme/languages/dutch.md, markdown/readme/languages/french.md, markdown/readme/languages/german.md, markdown/readme/languages/indonesian.md, markdown/readme/languages/italian.md, markdown/readme/languages/japanese.md, markdown/readme/languages/korean.md, markdown/readme/languages/portuguese.md, markdown/readme/languages/russian.md, markdown/readme/languages/spanish.md, markdown/readme/languages/ukrainian.md, packages/nocodb/README.md
- currently some links are pointing to pages in old ui, this PR is to update them so that new users don't need to switch to the new one and search in docs. 
=> docs: update documentation links

packages/nocodb/src/models/BaseUser.ts
Closes https://github.com/nocodb/nocodb/issues/7775
- clear list on user delete to refresh inheritance
=> fix: clear list on user delete to refresh inheritance

packages/nc-gui/components/nc/DateWeekSelector.vue, packages/nc-gui/components/nc/MonthYearSelector.vue, packages/nc-gui/components/smartsheet/calendar/SideMenu.vue, packages/nc-gui/components/smartsheet/calendar/SideRecordCard.vue, packages/nc-gui/components/smartsheet/calendar/YearView.vue, packages/nc-gui/components/smartsheet/calendar/index.vue, packages/nc-gui/composables/useCalendarViewStore.ts, packages/nc-gui/utils/browserUtils.ts
=> feat(nc-gui): Calendar Year View Updates

packages/nocodb/src/models/FormView.ts
=> refactor: move query param check to a common function

packages/nocodb/src/schema/swagger-v2.json
=> fix: Remove invalid comma in swagger json

.github/workflows/ci-cd.yml
- Remove invalid character from swagger JSON
- Add action to validate swagger JSON - check for parsing errors 
=> fix: Remove invalid character from swagger json

packages/nc-gui/components/nc/ErrorBoundary.vue
=> fix: handle if error is undefined/null in ErrorBoundary component 

packages/nc-gui/components/webhook/Editor.vue, packages/nocodb/src/helpers/webhookHelpers.ts
=> refactor: show body tab for customization

packages/nc-gui/assets/style.scss, packages/nc-gui/components/dlg/ViewCreate.vue, packages/nc-gui/components/nc/DateWeekSelector.vue, packages/nc-gui/components/nc/ErrorBoundary.vue, packages/nc-gui/components/nc/MonthYearSelector.vue, packages/nc-gui/components/smartsheet/calendar/Cell.vue, packages/nc-gui/components/smartsheet/calendar/DayView/DateField.vue, packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue, packages/nc-gui/components/smartsheet/calendar/MonthView.vue, packages/nc-gui/components/smartsheet/calendar/RecordCard.vue, packages/nc-gui/components/smartsheet/calendar/SideMenu.vue, packages/nc-gui/components/smartsheet/calendar/SideRecordCard.vue, packages/nc-gui/components/smartsheet/calendar/VRecordCard.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue, packages/nc-gui/components/smartsheet/calendar/index.vue, packages/nc-gui/components/smartsheet/toolbar/CalendarRange.vue, packages/nc-gui/composables/useCalendarViewStore.ts, packages/nc-gui/lib/types.ts, packages/nocodb/src/db/conditionV2.ts, packages/nocodb/src/services/calendar-datas.service.ts
=> feat(nc-gui): refined ranges support & end Date for Date Field

packages/noco-docs/docusaurus.config.js
=> Nc fix(docs): Update broken edit this page link

packages/nc-gui/components/cell/Json.vue, packages/nc-gui/components/cell/MultiSelect.vue, packages/nc-gui/components/cell/SingleSelect.vue, packages/nc-gui/components/cell/User.vue, packages/nc-gui/components/dlg/share-and-collaborate/SharePage.vue, packages/nc-gui/components/general/ColorPicker.vue, packages/nc-gui/components/monaco/Editor.vue, packages/nc-gui/components/smartsheet/Cell.vue, packages/nc-gui/components/smartsheet/Form.vue, packages/nc-gui/composables/useSharedFormViewStore.ts, packages/nc-gui/composables/useViewData.ts, packages/nc-gui/lang/en.json, packages/nc-gui/lib/enums.ts, packages/nc-gui/lib/types.ts, packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index.vue, packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/index.vue, packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/survey.vue, packages/nc-gui/store/views.ts, packages/nc-gui/utils/cell.ts, packages/nc-gui/utils/dataUtils.ts, tests/playwright/pages/Dashboard/Form/index.ts
Covered: Pre-fill form fields except `Links field`
- ref: #2862
- ref: #3027
- ref: #7800
Old PR ref:
- nocodb/nocodb/pull/5330
=> Nc feat: Prefill shared form by query params

packages/nc-gui/composables/useTableNew.ts
=> Nc fix(nc-gui): Incorrect route when navigating to view after visiting base members page 

packages/nc-gui/components/dashboard/TreeView/TableNode.vue
=> Nc fix/auto collapse sidebar base table

packages/nocodb/src/helpers/webhookHelpers.ts
- add timeout to webhook calls
=> fix: add timeout to webhook calls

packages/nc-gui/components/smartsheet/calendar/DayView/DateField.vue, packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue, packages/nc-gui/components/smartsheet/calendar/MonthView.vue, packages/nc-gui/components/smartsheet/calendar/SideMenu.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
=> fix(nc-gui): lint

packages/nc-gui/components/smartsheet/toolbar/RowHeight.vue
=> Nc fix(nc-gui): row height menu dropdown ui changes

packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue, packages/nc-gui/components/smartsheet/calendar/MonthView.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
Adds calendar optimization which was not synced earlier. 
=> fix: missing calendar optmzin on oss

packages/nc-gui/middleware/01.security.global.ts, packages/nc-gui/pages/index/[typeOrId]/form/[viewId].vue
=> fix: allow shared form in iframe

packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue, packages/nocodb/src/controllers/view-columns.controller.ts
=> Nc fix/7808 column reorder

packages/nc-gui/components/nc/Modal.vue, packages/nc-gui/components/project/AccessSettings.vue, packages/nc-gui/components/project/ShareBaseDlg.vue, packages/nc-gui/components/project/View.vue, packages/nc-gui/components/roles/Selector.vue, packages/nc-gui/components/workspace/InviteSection.vue, packages/nc-gui/composables/useRoles/index.ts, packages/nc-gui/lang/en.json, packages/nc-gui/lib/acl.ts, packages/nocodb-sdk/src/lib/enums.ts, packages/nocodb/src/middlewares/extract-ids/extract-ids.middleware.ts, packages/nocodb/src/models/BaseUser.ts, packages/nocodb/src/schema/swagger.json
=> feat: base level share

packages/nc-gui/components/virtual-cell/BelongsTo.vue, packages/nc-gui/components/virtual-cell/HasMany.vue, packages/nc-gui/components/virtual-cell/Links.vue, packages/nc-gui/components/virtual-cell/ManyToMany.vue, packages/nc-gui/components/virtual-cell/components/LinkedItems.vue, packages/nc-gui/components/virtual-cell/components/ListItem.vue, packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue, packages/nc-gui/composables/useLTARStore.ts, tests/playwright/pages/Dashboard/ExpandedForm/index.ts, tests/playwright/tests/db/columns/columnLinkToAnotherRecord.spec.ts
Closes https://github.com/nocodb/nocodb/issues/7655
=> fix(nc-gui): Update offset of LinkedRecords in accordance with links and unlinks

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
=> fix: disable default source menu/action options if it's disabled

packages/nocodb/src/services/api-docs/swaggerV2/swagger-base.json
Change "BadReqeust" to "BadRequest"
closes #7848
=> docs: Correct typo in swagger response definition

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/dashboard/settings/data-sources/EditBase.vue, packages/nc-gui/components/monaco/Editor.vue, packages/nc-gui/components/smartsheet/calendar/DayView/DateField.vue, packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue, packages/nc-gui/components/smartsheet/calendar/MonthView.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
=> fix(nc-gui): lint errors

scripts/pkg-executable/package.json
=> chore: downgrade sqlite version for executable

packages/nc-gui/components/smartsheet/grid/usePaginationShortcuts.ts
=> Nc feat: Swap keyboard shortcut for going to first and last pages

packages/nocodb/src/middlewares/extract-ids/extract-ids.middleware.ts, packages/nocodb/src/utils/acl.ts
Closes https://github.com/nocodb/nocodb/issues/7870
=> fix(nocodb): comment update not working for roles other than superAdmin

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/smartsheet/column/SelectOptions.vue
=> Nc fix(nc-gui): select type fields default value update issue

packages/nc-gui/components/smartsheet/details/Api.vue
=> fix: api-snippet-v2

packages/nc-gui/assets/style.scss, packages/nc-gui/components/account/AppStore.vue, packages/nc-gui/components/account/License.vue, packages/nc-gui/components/nc/Select.vue, packages/nc-gui/components/project/ShareBaseDlg.vue, packages/nc-gui/pages/account/index/users/[[nestedPage]].vue
=> Nc fix/scroll behavior

packages/nc-gui/components/cell/attachment/utils.ts, packages/nc-gui/components/smartsheet/column/AttachmentOptions.vue, packages/nc-gui/composables/useMultiSelect/convertCellData.ts
=> fix(nc-gui): incorrect maxAttachmentSize

scripts/upgradeNocodbSdk.js
- Update upgradeNocodbSdk script in master
- Added revertSDK env variable support which will be used for targeting local nocodb-sdk
=> chore: update upgradeNocodbSdk script

packages/nc-gui/components/cell/SingleSelect.vue, packages/nc-gui/composables/useMultiSelect/index.ts, tests/playwright/pages/Dashboard/Grid/index.ts, tests/playwright/pages/Dashboard/WebhookForm/index.ts, tests/playwright/tests/db/features/undo-redo.spec.ts, tests/playwright/tests/db/features/webhook.spec.ts
=> Nc fix(nc-gui): Use of escape any number of times should not make selected cell go away

packages/nc-gui/composables/useSharedFormViewStore.ts
=> Nc fix(nc-gui): prefill form issue on clicking submit another form btn & show blank form after 5 sec

tests/playwright/pages/Dashboard/Calendar/CalendarDayDateTime.ts, tests/playwright/tests/db/views/viewCalendar.spec.ts
=> fix: failing calendar tests

packages/nc-gui/store/views.ts
=> fix(nc-gui): view reorder lost if we minimise table

packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue
=> fix: calendar datetime overlap fix

packages/nc-gui/components/smartsheet/PlainCell.vue, packages/nc-gui/components/smartsheet/calendar/DayView/DateField.vue, packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue, packages/nc-gui/components/smartsheet/calendar/MonthView.vue, packages/nc-gui/components/smartsheet/calendar/SideMenu.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/composables/useSharedFormViewStore.ts
Closes https://github.com/nocodb/nocodb/issues/8249
=> fix: Expanded Record Fields

packages/nc-gui/components/webhook/Editor.vue, packages/noco-docs/docs/130.automation/020.webhook/020.create-webhook.md
=> Nc enable webhook body

packages/nc-gui/components/smartsheet/Cell.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue, packages/nc-gui/composables/useData.ts, packages/nc-gui/composables/useExpandedFormStore.ts, packages/nc-gui/composables/useLTARStore.ts, packages/nc-gui/lib/types.ts, packages/nc-gui/utils/dataUtils.ts, packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/db/sql-mgr/code/models/xc/ModelXcMetaSnowflake.ts, packages/nocodb/src/helpers/getUniqueName.ts, packages/nocodb/src/helpers/populateMeta.ts
- add runOps function
- fix errors that arise while creating nested record on a new record
- link nested record on create (UI)
- fix issue with composite keys on bulkDelete & bulkUpdate
- improve m2m junction table detection (match fks & pks)
=> fix: pre-post insert ops

packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/composables/useViewData.ts, packages/nocodb/package.json, pnpm-lock.yaml
- This prop was not taking effect
=> fix: wire up shouldShowLoading

tests/playwright/pages/Dashboard/BulkUpdate/index.ts, tests/playwright/pages/Dashboard/ExpandedForm/index.ts, tests/playwright/pages/Dashboard/Grid/Column/index.ts, tests/playwright/pages/Dashboard/TreeView.ts, tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts, tests/playwright/setup/index.ts, tests/playwright/tests/db/columns/columnMultiSelect.spec.ts, tests/playwright/tests/db/columns/columnSingleSelect.spec.ts, tests/playwright/tests/db/columns/columnUserSelect.spec.ts
=> tests: PW flaky tests fix

packages/nocodb/src/models/View.ts, tests/playwright/tests/db/columns/columnLinkToAnotherRecord.spec.ts
=> Nc fix/link creation

packages/nc-gui/store/org.ts
=> fix: Add missing org store placeholder

packages/nc-gui/components/cell/Rating.vue, packages/nc-gui/components/dlg/TableDelete.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/composables/useData.ts, packages/nc-gui/composables/useMultiSelect/index.ts
=> Nc fix/UI flaws

pnpm-lock.yaml, tests/playwright/package.json
=> test: PW upgrade

packages/nocodb/src/filters/global-exception/global-exception.filter.ts, packages/nocodb/src/helpers/catchError.ts
=> fix: avoid logging known db errors

packages/nc-gui/composables/useViewGroupBy.ts, packages/nc-gui/lib/types.ts
=> fix: group by belongs to

packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
=> fix: belongs-to relation in shared form

packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue, packages/nc-gui/composables/useViewFilters.ts, packages/nocodb/src/helpers/webhookHelpers.ts, tests/playwright/pages/Dashboard/WebhookForm/index.ts
- Lock logical op in the filter group
- nested filter support in webhook
=> Allow only same logical operation in filter group level

packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue, packages/nc-gui/components/smartsheet/header/VirtualCell.vue, packages/nc-gui/components/virtual-cell/OneToOne.vue, packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue, packages/nc-gui/lang/en.json, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/services/columns.service.ts, tests/playwright/pages/Dashboard/Details/FieldsPage.ts, tests/playwright/pages/Dashboard/Grid/Column/index.ts
=> Nc one to one

packages/noco-docs/docs/070.fields/040.field-types/040.links-based/010.links.md
=> docs: Update link modal  

packages/nc-gui/components/project/AccessSettings.vue
=> fix(nc-gui): Translation issue - Members not found

packages/nc-gui/components/cell/MultiSelect.vue, packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/dashboard/TreeView/TableNode.vue, packages/nc-gui/components/project/View.vue, packages/nc-gui/components/smartsheet/column/RollupOptions.vue, packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue, packages/nc-gui/components/smartsheet/toolbar/OpenedViewAction.vue, packages/nc-gui/components/smartsheet/toolbar/ViewInfo.vue, packages/nc-gui/composables/useViewColumns.ts, packages/nocodb-sdk/src/lib/helperFunctions.ts, tests/playwright/pages/Dashboard/common/Toolbar/Fields.ts
=> Nc fix/UI flaws p2

packages/nc-gui/components/cell/attachment/Image.vue, packages/nc-gui/components/cell/attachment/Modal.vue, packages/nc-gui/components/cell/attachment/index.vue
=> Nc attachment UI

packages/nc-gui/components/cell/attachment/sort.ts
=> fix: Issue with sortable destroy

packages/nc-gui/components/smartsheet/grid/GroupByTable.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/toolbar/GroupByMenu.vue, packages/nc-gui/composables/useViewGroupBy.ts, packages/nc-gui/utils/sortUtils.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/models/Sort.ts, packages/nocodb/src/schema/swagger.json
=> feat: sort groups by records count

packages/nocodb/Dockerfile, packages/nocodb/Dockerfile.local
=> chore: skip build tar & untar step from dockerfile

packages/nc-gui/components/account/UserList.vue
- closes: https://github.com/nocodb/nocodb/issues/8432
=> fix(nc-gui): Translation issue - Search members

packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.processor.ts, packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
=> Nc fix/duplicate link

packages/nc-gui/components/cell/RichText.vue
=> fix(nc-gui): form desciption update issue

packages/nc-gui/components/cmd-k/index.vue, packages/nc-gui/components/dashboard/Sidebar/TopSection.vue, packages/nc-gui/components/dashboard/Sidebar/TopSection/Header.vue, packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/dashboard/TreeView/TableNode.vue, packages/nc-gui/components/dashboard/TreeView/ViewsList.vue, packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/toolbar/SearchData.vue, packages/nc-gui/components/workspace/CollaboratorsList.vue, tests/playwright/pages/Dashboard/common/Toolbar/SearchData.ts
=> Nc fix: Misc Design Fixes II

.github/workflows/sync-to-develop.yml
chore: no-frozen-lockfile for sync to develop (it is running in CI but meant to update lockfile)
=> chore: no-frozen-lockfile for sync to develop

packages/nc-gui/components/workspace/CollaboratorsList.vue, packages/nc-gui/components/workspace/View.vue
=> fix: load roles in parent rather than child

packages/nocodb/src/db/BaseModelSqlv2.ts
=> fix: Extract primary key value properly when table missing auto-incremented/auto-generated primary key

packages/nc-gui/components/dashboard/settings/DataSources.vue, packages/nocodb/src/models/Source.ts, packages/nocodb/src/version-upgrader/ncProjectConfigUpgrader.ts
- Handle null and duplicates on initial load
- Handle order calculation on frontend
- Restrict changing default source on backend
=> fix: source reorder

tests/playwright/tests/db/views/viewCalendar.spec.ts
=> test: calendar flaky test

packages/nc-gui/components/virtual-cell/Lookup.vue
=> fix: Extract relation column from useMetas composable

packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/header/VirtualCell.vue, packages/nc-gui/components/smartsheet/header/VirtualCellIcon.ts, packages/nc-gui/components/smartsheet/toolbar/FieldListAutoCompleteDropdown.vue, packages/nc-gui/windi.config.ts
=> fix: Missing lookup/rollup icon colour

packages/nc-gui/assets/style.scss, packages/nc-gui/components/smartsheet/Form.vue, packages/nc-gui/components/smartsheet/form/field-settings.vue, packages/nc-gui/composables/useFormViewStore.ts, packages/nc-gui/composables/useSharedFormViewStore.ts, packages/nc-gui/lang/en.json, packages/nc-gui/utils/formValidations.ts, packages/nc-gui/windi.config.ts
=> Nc fix/form view bug fixes

tests/playwright/pages/Account/Users.ts, tests/playwright/pages/Base.ts, tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts, tests/playwright/tests/db/usersAccounts/accountUserManagement.spec.ts
=> test: fix user field filter test

packages/nocodb/src/filters/global-exception/global-exception.filter.ts
=> fix: unnecessary error logs

packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.processor.ts, packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
=> fix: self link duplicate issues

packages/nc-gui/components/dashboard/settings/BaseAudit.vue, packages/nc-gui/components/dashboard/settings/DataSources.vue, packages/nc-gui/components/dashboard/settings/Metadata.vue, packages/nc-gui/components/dashboard/settings/UIAcl.vue, packages/nc-gui/components/dlg/ProjectAudit.vue, packages/nc-gui/components/general/Modal.vue, packages/nc-gui/components/smartsheet/expanded-form/Comments.vue
=> Nc fix/audit table

packages/nc-gui/package.json, packages/nc-lib-gui/package.json, packages/nocodb-sdk/package.json, packages/nocodb-sdk/pnpm-lock.yaml, packages/nocodb/package.json, pnpm-lock.yaml
=> Post release master sync - 0.207.2(Last release)

packages/nc-gui/components/cell/DatePicker.vue, packages/nc-gui/components/cell/DateTimePicker.vue, packages/nc-gui/components/cell/TimePicker.vue, packages/nc-gui/components/cell/YearPicker.vue, packages/nc-gui/components/nc/DatePicker.vue, packages/nc-gui/components/nc/DateWeekSelector.vue, packages/nc-gui/components/nc/MonthYearSelector.vue, packages/nc-gui/components/nc/TimeSelector.vue, packages/nc-gui/lang/en.json, packages/nc-gui/utils/formValidations.ts, packages/nocodb-sdk/src/lib/dateTimeHelper.ts, tests/playwright/pages/Dashboard/BulkUpdate/index.ts, tests/playwright/pages/Dashboard/ExpandedForm/index.ts, tests/playwright/pages/Dashboard/SurveyForm/index.ts, tests/playwright/pages/Dashboard/common/Cell/DateTimeCell.ts, tests/playwright/pages/Dashboard/common/Cell/TimeCell.ts, tests/playwright/pages/Dashboard/common/Cell/YearCell.ts, tests/playwright/pages/Dashboard/common/Cell/index.ts, tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts, tests/playwright/tests/db/columns/columnDateTime.spec.ts, tests/playwright/tests/db/features/timezone.spec.ts, tests/playwright/tests/db/views/viewFormShareSurvey.spec.ts
=> Nc feat/new date time cell UI

packages/nocodb/src/helpers/exportImportHelpers.ts, packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
Fixes #8539
- Avoid suffix for unique names
- Exclude column itself from title array
- Rename fk child as well as link column
=> fix: match duplicated field titles

.github/workflows/release-nocodb.yml, .github/workflows/sync-to-develop.yml
- Reset master to origin before creating sync branch
=> chore: sync to develop action

.github/workflows/release-nocodb.yml, .github/workflows/sync-to-develop.yml
- Reset master to origin before creating sync branch
=> chore: sync to develop master (master)

packages/nc-gui/components/webhook/Editor.vue
=> fix: webhook ref link

packages/nc-gui/components/dashboard/View.vue
- closes: [Provide summary of changes with issue number if any.](https://github.com/nocodb/nocodb/issues/8569)
=> fix(nc-gui): sidebar width issue

packages/nc-gui/components/dashboard/settings/data-sources/EditBase.vue
- Closes https://github.com/nocodb/nocohub/pull/2979
=> fix: Handle empty searchPath when editing connection params

packages/nc-gui/components/cell/DatePicker.vue, packages/nc-gui/components/cell/DateTimePicker.vue, packages/nc-gui/components/cell/TimePicker.vue, packages/nc-gui/components/cell/YearPicker.vue, packages/nc-gui/components/smartsheet/Form.vue, packages/nc-gui/components/smartsheet/header/Cell.vue, packages/nc-gui/components/smartsheet/header/VirtualCell.vue, packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue, packages/nc-gui/context/index.ts, tests/playwright/pages/Dashboard/Form/index.ts, tests/playwright/pages/Dashboard/SurveyForm/index.ts, tests/playwright/pages/Dashboard/common/Cell/AttachmentCell.ts, tests/playwright/pages/Dashboard/common/Cell/index.ts, tests/playwright/pages/SharedForm/index.ts, tests/playwright/tests/db/views/viewForm.spec.ts
=> Nc test/form view validations

packages/nc-gui/components/nc/Dropdown.vue
=> fix(nc-gui): dropdown placement issue

packages/nc-gui/components/dashboard/settings/app-store/AppInstall.vue
=> fix: App store image path correction

packages/nocodb/src/db/BaseModelSqlv2.ts
- move sanitize to exec
- avoid sanitizing column id
=> fix: move sanitize logic to exec

packages/nocodb/src/controllers/comments.controller.ts, packages/nocodb/src/meta/migrations/v2/nc_046_comment_mentions.ts, packages/nocodb/src/meta/migrations/v2/nc_047_comment_migration.ts, packages/nocodb/src/schema/swagger-v2.json, packages/nocodb/src/schema/swagger.json, packages/nocodb/src/utils/richTextHelper.ts
=> fix: Comments - add maxLength constraint in json schema

packages/nc-gui/components/cmd-l/index.vue
Closes https://github.com/nocodb/nocodb/issues/8591
=> fix: cmdL icons missing

packages/nc-gui/components/smartsheet/details/Api.vue
=> fix: API Token instead of AUTH Token

packages/nocodb/src/helpers/webhookHelpers.ts, packages/nocodb/src/interface/Jobs.ts, packages/nocodb/src/modules/jobs/fallback/fallback-queue.service.ts, packages/nocodb/src/modules/jobs/jobs.controller.ts, packages/nocodb/src/modules/jobs/jobs/at-import/at-import.controller.ts, packages/nocodb/src/modules/jobs/jobs/webhook-handler/webhook-handler.processor.ts, packages/nocodb/src/modules/jobs/redis/jobs-redis.ts, packages/nocodb/src/modules/jobs/redis/jobs.service.ts, packages/nocodb/src/services/hook-handler.service.ts, packages/nocodb/src/services/hooks.service.ts
- return template itself if parsing failed
- avoid storing record data with job logs
- pause job queue only once per instance if NC_WORKER_CONTAINER=false
- avoid skipping hook on one of them fails (if there are multiple hooks with same op)
=> fix: wh jobs

.github/workflows/release-nocodb.yml
=> chore: move sync action after npm release as it pushes some commits

packages/nc-gui/composables/useSharedView.ts, packages/nocodb/src/services/public-metas.service.ts
=> fix: include the range fields as columns in sharedView Meta

packages/nc-gui/components/smartsheet/Gallery.vue, packages/nc-gui/components/smartsheet/Kanban.vue, packages/nc-gui/components/smartsheet/Map.vue, packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue, packages/nc-gui/components/smartsheet/calendar/MonthView.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue, packages/nc-gui/components/smartsheet/calendar/index.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/grid/index.vue, packages/nc-gui/components/virtual-cell/components/LinkedItems.vue, packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue, packages/nc-gui/composables/useExpandedFormStore.ts, packages/nc-gui/lang/en.json
=> fix: expanded view not working on shared view and shared bases

packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/grid/GroupByTable.vue, packages/nc-gui/composables/useData.ts
Fixed record not found error when deleting using expanded form of Gallery View
=> fix: Gallery View delete using expanded form

packages/nocodb/src/db/CustomKnex.ts
=> fix: throw error if invalid operator used in xcCondition

packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
=> docs: Improve environment documentation

packages/nc-gui/composables/useCalendarViewStore.ts, packages/nocodb/src/controllers/public-datas-export.controller.ts, packages/nocodb/src/services/calendar-datas.service.ts
=> Nc fix/cal shared filters

.github/workflows/publish-docs-index-typesense.yml
Add custom trigger support for Docs indexing action from external service.
=> Add custom trigger support for Docs indexing action

packages/nc-gui/components/general/Loader.vue, packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/header/Menu.vue, packages/nc-gui/composables/useExpandedFormStore.ts
=> Nc chore/design expanded record

packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/column/SelectOptions.vue, packages/nc-gui/components/smartsheet/column/UITypesOptionsWithSearch.vue
=> Nc fix/select type default value update issue if option is new

packages/nocodb-sdk/src/lib/globals.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/helpers/catchError.ts
=> Validate pk value before query execution

packages/nc-gui/components/smartsheet/Gallery.vue, packages/nc-gui/components/smartsheet/Kanban.vue, packages/nc-gui/components/smartsheet/Map.vue, packages/nc-gui/components/smartsheet/calendar/index.vue, packages/nc-gui/components/smartsheet/column/DateTimeOptions.vue, packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue, packages/nc-gui/components/smartsheet/column/TimeOptions.vue, packages/nc-gui/components/smartsheet/column/UITypesOptionsWithSearch.vue, packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/grid/index.vue, packages/nc-gui/components/virtual-cell/components/Header.vue, packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
=> Nc fix: UI/UX minor fixes

packages/nc-gui/components/project/View.vue
=> fix: use basesUser to show number of members

packages/nocodb/src/db/generateLookupSelectQuery.ts
=> fix: Lookup sort related issue

packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/column/SelectOptions.vue, packages/nc-gui/components/smartsheet/column/UITypesOptionsWithSearch.vue
=> Nc fix(nc-gui): restore changes old pr

packages/nc-gui/components/smartsheet/Form.vue, packages/nc-gui/components/smartsheet/column/UITypesOptionsWithSearch.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/composables/useFormViewStore.ts, packages/nc-gui/composables/useSharedFormViewStore.ts, packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/index.vue, packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/survey.vue, packages/nc-gui/utils/formValidations.ts, tests/playwright/pages/Dashboard/Form/index.ts, tests/playwright/tests/db/views/viewForm.spec.ts
=> fix(nc-gui): form field validation issue if column title contains `.`

packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
Add [`NC_DISABLE_EMAIL_AUTH`](https://github.com/search?q=repo%3Anocodb%2Fnocodb+NC_DISABLE_EMAIL_AUTH&type=code) to documentation and move other `NC_DISABLE_*` env vars up in table.
=> docs: describe `NC_DISABLE_EMAIL_AUTH`

packages/nc-gui/components/dashboard/TreeView/TableNode.vue
=> Nc fix/reordering deleting view causes it to stuck in state

packages/nc-gui/components/cell/Checkbox.vue, packages/nc-gui/components/cell/DateTimePicker.vue, packages/nc-gui/components/cell/RichText.vue, packages/nc-gui/components/cell/TextArea.vue, packages/nc-gui/components/cell/attachment/index.vue, packages/nc-gui/components/notification/Item/ProjectInvite.vue, packages/nc-gui/components/smartsheet/Gallery.vue, packages/nc-gui/components/smartsheet/Kanban.vue, packages/nc-gui/components/smartsheet/SharedMapMarkerPopup.vue, packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue, packages/nc-gui/components/virtual-cell/QrCode.vue, packages/nc-gui/components/virtual-cell/barcode/JsBarcodeWrapper.vue, packages/nc-gui/components/virtual-cell/components/ListItem.vue, packages/nc-gui/composables/useViewColumns.ts, packages/nc-gui/lang/en.json, packages/nc-gui/lib/enums.ts, packages/nc-gui/utils/dataUtils.ts, packages/nc-gui/utils/formValidations.ts, packages/nc-gui/windi.config.ts, packages/nocodb/src/models/GalleryView.ts, packages/nocodb/src/models/KanbanView.ts, packages/nocodb/src/models/View.ts, tests/playwright/pages/Dashboard/Gallery/index.ts
=> Nc Refactor: Gallery view

packages/nocodb/src/modules/jobs/redis/jobs-event.service.ts
- remove logs for job started/completed
=> chore: remove logs for job started/completed

packages/nc-gui/components/cell/RichText.vue, packages/nc-gui/components/cell/TextArea.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue
=> fix(nc-gui): allow vertical resize for rich text input in form view

packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
- Move get users list to promise
- Use obj args for _formulaQueryBuilder
=> fix: move get users list to promise

packages/nc-gui/components/cell/attachment/Image.vue, packages/nc-gui/components/dashboard/View.vue, packages/nc-gui/components/nc/DateWeekSelector.vue, packages/nc-gui/components/nc/MonthYearSelector.vue, packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue, packages/nc-gui/components/smartsheet/calendar/MonthView.vue, packages/nc-gui/components/smartsheet/calendar/SideMenu.vue, packages/nc-gui/components/smartsheet/calendar/SideRecordCard.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue, packages/nc-gui/components/smartsheet/calendar/YearView/index.vue, packages/nc-gui/components/smartsheet/toolbar/Calendar/ActiveView.vue, packages/nc-gui/components/smartsheet/toolbar/Calendar/Header.vue, packages/nc-gui/components/smartsheet/toolbar/Calendar/Mode.vue, packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue, packages/nc-gui/components/smartsheet/toolbar/Calendar/Today.vue, packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue, packages/nc-gui/composables/useCalendarViewStore.ts, packages/nc-gui/lang/en.json
- Current time indicator
- Hide Week days
- Update sideMenu design
=> feat: calendar followup

packages/nc-gui/components/smartsheet/Gallery.vue, packages/nc-gui/components/smartsheet/Kanban.vue, packages/nc-gui/components/smartsheet/Map.vue, packages/nc-gui/components/smartsheet/Toolbar.vue, packages/nc-gui/components/smartsheet/calendar/index.vue, packages/nc-gui/components/smartsheet/grid/index.vue, packages/nc-gui/composables/useApi/index.ts, packages/nc-gui/composables/useViewData.ts, packages/nc-gui/lang/en.json
=> Nc staing/issues

packages/nocodb/src/cache/CacheMgr.ts, packages/nocodb/src/models/Base.ts, packages/nocodb/src/models/Source.ts, packages/nocodb/src/models/User.ts, packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.controller.ts, packages/nocodb/src/services/bases.service.ts, packages/nocodb/src/services/utils.service.ts, packages/nocodb/tests/unit/init/cleanupMeta.ts, packages/nocodb/tests/unit/rest/tests/base.test.ts
- Fix source soft delete
- Improve refreshTTL pipeline to cover all parents
=> fix: cache pipeline & source delete

packages/nc-gui/plugins/error-handler.ts
=> fix: add a nuxt plugin to handle chunk error

packages/nocodb/src/models/Comment.ts, packages/nocodb/src/models/FormView.ts, packages/nocodb/src/models/Model.ts, packages/nocodb/src/models/PresignedUrl.ts
- delete comments on model delete
=> fix: delete comments on model delete

tests/playwright/tests/db/views/viewCalendar.spec.ts
=> fix: flaky tests

packages/nc-gui/components/cell/RichText/LinkOptions.vue, packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/components/smartsheet/expanded-form/RichComment.vue, packages/nc-gui/components/smartsheet/expanded-form/RichTextOptions.vue, packages/nc-gui/composables/useExpandedFormStore.ts
=> Nc fix/comments UI

packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/composables/useExpandedFormStore.ts, packages/nc-gui/lib/acl.ts
=> fix: comment delete not working

packages/nocodb/src/db/BaseModelSqlv2.ts
=> fix: missing conditionV2

packages/nocodb/src/models/Model.ts
=> fix: Add source_id filter when getting table list

packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/models/Model.ts
=> fix: Support FK column update(system field) in external dbs

packages/nc-gui/composables/useAttachment.ts
=> fix: avoid extra encode

packages/nc-gui/components/dlg/ViewCreate.vue, packages/nc-gui/components/nc/Checkbox.vue, packages/nc-gui/components/shared-view/AskPassword.vue, packages/nc-gui/components/smartsheet/Form.vue, packages/nc-gui/components/smartsheet/Kanban.vue, packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
=> Nc fix/resolve console warnings

tests/playwright/pages/Dashboard/Details/FieldsPage.ts
=> test: fix mfe toggle (trial)

packages/nocodb/src/meta/meta.service.ts, packages/nocodb/src/models/BaseUser.ts, packages/nocodb/src/models/SyncSource.ts, packages/nocodb/src/services/org-users.service.ts
=> fix: delete org user

packages/nc-gui/composables/useViewFilters.ts
=> Type corrections and avoid duplicate filter delete request

packages/nc-gui/components/smartsheet/grid/useColumnDrag.ts
- closes: https://github.com/nocodb/nocodb/issues/8613
=> fix: field sorting will send two requests in weak network

packages/nc-gui/components/smartsheet/grid/useColumnDrag.ts
Logic typo which restricts drag to grid end
=> fix: allow dragging to grid end

packages/nc-gui/components/erd/View.vue
=> fix: ERD - avoid fetching non-source table metas

packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/helpers/catchError.ts
=> fix: missing pk handling

packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nocodb/src/models/KanbanView.ts, packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts, packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
=> Fix: Misc bug fixes

packages/nc-gui/assets/style.scss, packages/nc-gui/components/cell/RichText.vue, packages/nc-gui/components/cell/attachment/RenameFile.vue, packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue, packages/nc-gui/components/dashboard/TreeView/ViewsList.vue, packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue, packages/nc-gui/components/dlg/ProjectDelete.vue, packages/nc-gui/components/dlg/ProjectDuplicate.vue, packages/nc-gui/components/dlg/TableCreate.vue, packages/nc-gui/components/dlg/TableDelete.vue, packages/nc-gui/components/dlg/TableDuplicate.vue, packages/nc-gui/components/dlg/TableRename.vue, packages/nc-gui/components/dlg/ViewCreate.vue, packages/nc-gui/components/dlg/ViewDelete.vue, packages/nc-gui/components/dlg/WorkspaceDelete.vue, packages/nc-gui/components/general/DeleteModal.vue, packages/nc-gui/components/nc/Select.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue, packages/nc-gui/components/smartsheet/toolbar/StackedBy.vue, packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue, packages/nc-gui/components/workspace/CreateProjectDlg.vue, packages/nc-gui/lang/en.json, packages/nc-gui/windi.config.ts, packages/nocodb/src/models/GalleryView.ts, packages/nocodb/src/models/KanbanView.ts
=> Nc Refactor: dialog modals

packages/nc-gui/composables/useViewFilters.ts, packages/nocodb/src/cache/CacheMgr.ts, packages/nocodb/src/cache/NocoCache.ts, packages/nocodb/src/models/Filter.ts, packages/nocodb/src/models/HookFilter.ts
=> Add option to sort cache list data

packages/nc-gui/components/cell/Currency.vue, packages/nc-gui/components/cell/Json.vue, packages/nc-gui/components/smartsheet/Gallery.vue, packages/nc-gui/components/smartsheet/Kanban.vue, packages/nc-gui/components/virtual-cell/components/ItemChip.vue, packages/nocodb/src/models/View.ts
=> Nc Fix: Minor bug fixes

packages/nc-gui/components/smartsheet/column/SelectOptions.vue
=> Nc fix: Selected color not being saved on Single select and Multi select field creation

packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation.md, packages/noco-docs/versioned_docs/version-0.109.7/020.getting-started/010.installation.md
=> chore : simplify self-hosting - default to postgres/sqlite

packages/noco-docs/docs/160.developer-resources/010.rest-APIs/005.overview.md
Add info which is needed to access the API but not provided int the API docs. I edited this page as I don't know how to edit the API docs themselves, though this probably belongs there.
Also adds a minor formatting fix.
=> Add info for API access

packages/nc-gui/composables/useExpandedFormStore.ts
=> fix: comments of prev row loading in expandedform

packages/nc-gui/components/project/View.vue
=> fix(nc-gui): Filter out deleted user from members count 

README.md, packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation.md, packages/noco-docs/versioned_docs/version-0.109.7/020.getting-started/010.installation.md
=> Update readme 3

packages/nc-gui/components/virtual-cell/QrCode.vue, packages/nc-gui/components/virtual-cell/barcode/Barcode.vue
=> fix(nc-gui): qr & barcode visibility issue if referenced value is 0

packages/nc-gui/components/smartsheet/calendar/SideMenu.vue
=> fix: Calendar view sidebar is broken if sidebar has image field record and field has more than 1 image

packages/nocodb/src/models/View.ts
=> fix: display value in new view is not first column 

packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/column/SelectOptions.vue
=> fix: Single select default value option update issue on adding new option from MFE

packages/nc-gui/lib/enums.ts
Added Hungarian language to enum.ts. Please add the language on Crowdin, thank you.
=> Add Hungarian language to enums.ts

packages/nc-gui/components/smartsheet/header/Cell.vue
=> fix: dblclick column edit - restriction

packages/nc-gui/components/dashboard/TreeView/index.vue
=> fix: Pass base prop

packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/column/FormulaOptions.vue, packages/nc-gui/composables/useColumnCreateStore.ts, packages/nc-gui/lang/en.json
=> Nc fix: Formula modal UI/UX 

packages/nc-gui/components/project/AccessSettings.vue, packages/nc-gui/components/smartsheet/Form.vue, packages/nocodb-sdk/src/lib/UITypes.ts
=> Nc fix/misc bugs

packages/nc-gui/components/cell/attachment/index.vue, packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/smartsheet/Pagination.vue, packages/nc-gui/components/smartsheet/column/RatingOptions.vue, packages/nc-gui/components/smartsheet/grid/GroupBy.vue, packages/nc-gui/components/smartsheet/grid/GroupByTable.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/virtual-cell/BelongsTo.vue, packages/nc-gui/components/virtual-cell/HasMany.vue, packages/nc-gui/components/virtual-cell/Links.vue, packages/nc-gui/components/virtual-cell/Lookup.vue, packages/nc-gui/components/virtual-cell/ManyToMany.vue, packages/nc-gui/components/virtual-cell/OneToOne.vue, packages/nc-gui/components/virtual-cell/components/ItemChip.vue, packages/nocodb/src/models/BaseUser.ts, tests/playwright/pages/Dashboard/Grid/Column/index.ts, tests/playwright/tests/db/features/multiFieldEditor.spec.ts
=> Nc fix: misc UI fixes

packages/nc-gui/components/smartsheet/column/BarcodeOptions.vue, packages/nc-gui/components/smartsheet/column/QrCodeOptions.vue, packages/nc-gui/components/virtual-cell/QrCode.vue, packages/nc-gui/components/virtual-cell/barcode/Barcode.vue, packages/nocodb/src/db/BaseModelSqlv2.ts
- Return 'ERR!' & show error message in frontend for this case
=> fix: missing setup for barcode & qr columns

packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts, packages/nocodb/src/modules/jobs/jobs/at-import/helpers/readAndProcessData.ts, packages/nocodb/src/services/columns.service.ts
=> fix: at import links

packages/nc-gui/composables/useSharedView.ts, packages/nc-gui/composables/useViewData.ts, packages/nocodb/src/services/columns.service.ts, packages/nocodb/src/services/public-datas.service.ts
=> Nc fix/shared view opt query

packages/nc-gui/store/notification.ts
=> fix: Avoid polling if token is not present and initialise polling when token changes

packages/nocodb/src/meta/migrations/v1/nc_012_cloud_cleanup.ts
=> refactor: update table drop migration

packages/nc-gui/components/nc/PaginationV2.vue, packages/nc-gui/components/smartsheet/grid/PaginationV2.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/grid/index.vue, packages/nc-gui/composables/useViewAggregate.ts, packages/nocodb-sdk/src/lib/aggregationHelper.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/db/aggregation.ts, packages/nocodb/src/db/generateLookupSelectQuery.ts, packages/nocodb/src/services/data-table.service.ts, packages/nocodb/src/services/public-datas.service.ts
=> Nc fix/api call

packages/nc-gui/composables/useViewAggregate.ts
=> fix: null check

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nocodb-sdk/src/lib/Api.ts
=> fix: DB icon alignment in treeview

packages/noco-docs/docs/070.fields/055.field-summary-footer.md
=> fix: docs build

packages/nc-gui/components/project/AllTables.vue
=> fix: missing storeToRefs

packages/nc-gui/components/cell/DatePicker.vue, packages/nc-gui/components/cell/DateTimePicker.vue, packages/nc-gui/components/cell/TimePicker.vue, packages/nc-gui/components/cell/YearPicker.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/virtual-cell/QrCode.vue, packages/nc-gui/components/virtual-cell/barcode/Barcode.vue, packages/nc-gui/components/workspace/AuditLogs.vue, packages/nc-gui/composables/useUndoRedo.ts, packages/nc-gui/utils/browserUtils.ts
=> Nc fix: expanded record UI/UX

tests/playwright/tests/db/views/viewGridShare.spec.ts, tests/playwright/tests/db/views/viewKanban.spec.ts
=> test: fix-sort-order

packages/nc-gui/components/virtual-cell/BelongsTo.vue, packages/nocodb/src/db/BaseModelSqlv2.ts
=> Nc fix/lookup array value bug

packages/nc-gui/components/smartsheet/Details.vue, packages/nc-gui/components/smartsheet/Form.vue, packages/nc-gui/components/smartsheet/column/BarcodeOptions.vue, packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/column/QrCodeOptions.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/header/Cell.vue, packages/nc-gui/components/smartsheet/header/VirtualCell.vue, packages/nc-gui/components/smartsheet/toolbar/KanbanStackEditOrAdd.vue, packages/nocodb/src/services/columns.service.ts
- Added lazyload to inner tabs of details view
- Added lazyload to calls of editOrAdd & removed from children
=> Nc feat: improve lazy loading for field edit or add 

packages/nc-gui/components/smartsheet/PlainCell.vue, packages/nc-gui/components/smartsheet/calendar/RecordCard.vue
=> fix(nc-gui): calendar tooltips not showing fix(nc-gui): handle ltar

packages/nc-gui/components/cell/Decimal.vue, packages/nocodb-sdk/src/lib/helperFunctions.ts
=> fix: update roundUpToPrecision function

packages/nocodb/src/db/BaseModelSqlv2.ts
- properly substitute column ids for LTAR
=> fix: substitute column ids for LTAR 

packages/noco-docs/docs/070.fields/010.fields-overview.md, packages/noco-docs/docs/070.fields/040.field-types/050.custom-types/070.specific-db-type.md, packages/noco-docs/docs/090.views/040.view-types/030.form.md
closes: [🐛 Doc: Properly document advanced field attributes](https://github.com/nocodb/nocodb/issues/7815)
closes: [🐛 Bug: Broken Links on https://docs.nocodb.com/fields/fields-overview/](https://github.com/nocodb/nocodb/issues/8611)
=> Nc docs/link fix2

packages/nc-gui/components/smartsheet/Details.vue
=> refactor: show webhook tab

packages/nc-gui/components/nc/MenuItem.vue, packages/nc-gui/components/nc/PaginationV2.vue
Add virtual scroll to pagination list
=> fix: add virtual scroll to pagination list

packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/components/smartsheet/expanded-form/RichComment.vue, packages/nc-gui/composables/useExpandedFormStore.ts
=> fix(nc-gui): update the audits design in expanded form

packages/nocodb/src/helpers/columnHelpers.ts
=> fix: avoid passing bt flag from user payload

packages/nc-gui/assets/style.scss, packages/nc-gui/components/smartsheet/Form.vue, packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/column/FormulaOptions.vue, packages/nc-gui/components/smartsheet/details/Fields.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/header/Cell.vue, packages/nc-gui/components/smartsheet/header/VirtualCell.vue, packages/nc-gui/components/smartsheet/toolbar/KanbanStackEditOrAdd.vue
- ref(Version - 1): #7690
- Fixed: Field edit/add modal border radius issue
=> Nc fix: MFE & Field modal UI/UX

packages/nc-gui/components/smartsheet/Gallery.vue, packages/nc-gui/components/smartsheet/Kanban.vue, packages/nc-gui/components/smartsheet/details/Fields.vue, packages/nc-gui/components/smartsheet/header/DeleteColumnModal.vue, packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue, packages/nc-gui/composables/useColumnCreateStore.ts, packages/nc-gui/store/views.ts, packages/nocodb/src/models/Column.ts, packages/nocodb/src/services/columns.service.ts
=> Nc fix: Reset gallery/kanban view cover image column id on deleting column

packages/nc-gui/components/account/HeaderWithSorter.vue, packages/nc-gui/components/account/UsersModal.vue, packages/nc-gui/components/smartsheet/toolbar/LockType.vue
- ref: #8881
- Fixed: Update Members table sort icon (same as audit table sort icons)
=> Nc fix: Org user role selector dropdown issue 

packages/nc-gui/components/cell/User.vue, packages/nocodb/src/db/BaseModelSqlv2.ts
- Fix stringified json detection regex
- Fix allow stringified json on cell level
=> fix: insert user from group by

packages/nc-gui/lang/en.json, tests/playwright/pages/Dashboard/Grid/Column/index.ts, tests/playwright/pages/Dashboard/common/Toolbar/Fields.ts, tests/playwright/tests/db/columns/columnMultiSelect.spec.ts, tests/playwright/tests/db/views/viewForm.spec.ts
=> Nc fix/kanban flaky

packages/nc-gui/components/dlg/ViewCreate.vue, packages/nc-gui/components/project/AccessSettings.vue, packages/nc-gui/components/smartsheet/expanded-form/Comments.vue, packages/nc-gui/components/smartsheet/expanded-form/RichComment.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/grid/PaginationV2.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/grid/index.vue, packages/nc-gui/components/smartsheet/header/DeleteColumnModal.vue, packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue, packages/nc-gui/composables/useExpandedFormStore.ts, packages/nc-gui/composables/useViewData.ts, packages/nc-gui/lang/en.json, packages/nc-gui/lib/acl.ts, packages/nocodb/src/controllers/audits.controller.ts, packages/nocodb/src/models/BaseUser.ts, packages/nocodb/src/utils/acl.ts, tests/playwright/pages/Dashboard/ExpandedForm/index.ts
=> fix: Audit records only available for super user

packages/nc-gui/helpers/parsers/ExcelTemplateAdapter.ts
=> fix: Error: `this.xlsx.read` is not a function while importing xlsx file in oss

tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts
=> Nc test/flaky filters

packages/nc-gui/components/dashboard/TreeView/AddNewTableNode.vue, packages/nc-gui/components/dashboard/TreeView/BaseOptions.vue, packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/dashboard/settings/DataSources.vue, packages/nc-gui/components/dashboard/settings/Erd.vue, packages/nc-gui/components/dashboard/settings/UIAcl.vue, packages/nc-gui/components/dlg/QuickImport.vue, packages/nc-gui/components/erd/View.vue, packages/nc-gui/components/project/ImportModal.vue, packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue, packages/nc-gui/components/smartsheet/toolbar/ViewActions.vue, packages/nc-gui/components/template/Editor.vue, packages/nc-gui/pages/index/[typeOrId]/[baseId]/index/index/index.vue
=> fix: Import CSV/Excel/JSON bug in non selected base

packages/nc-gui/components/dlg/ViewCreate.vue, packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue, packages/nc-gui/components/smartsheet/calendar/MonthView.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue, packages/nc-gui/components/smartsheet/calendar/index.vue, packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue, packages/nc-gui/composables/useCalendarViewStore.ts, packages/nc-gui/lib/types.ts, packages/nocodb/src/helpers/getAst.ts, packages/nocodb/src/services/columns.service.ts, tests/playwright/pages/Dashboard/Calendar/CalendarWeekDate.ts, tests/playwright/tests/db/views/viewCalendar.spec.ts
Closes https://github.com/nocodb/nocodb/issues/8873
=> Feat: support createdAt, updatedAt, formula for calendar

packages/nc-gui/components/dashboard/settings/UIAcl.vue, packages/nocodb/src/models/ModelRoleVisibility.ts
Closes https://github.com/nocodb/nocodb/issues/8905
=> fix: ui acl issue

README.md
=> chore: remove trailing space from docker command

.github/workflows/ci-cd.yml, .github/workflows/playwright-test-workflow.yml, .github/workflows/pre-build-for-playwright.yml, .github/workflows/release-docker.yml, .github/workflows/release-npm.yml, .github/workflows/sync-to-develop.yml, .github/workflows/unit-test.yml, .github/workflows/update-sdk-path.yml
Reference: https://github.com/pnpm/pnpm/issues/6424
- upgrade action as unit tests started failing
=> chore: upgrade pnpm install action

packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue, packages/nc-gui/components/general/MaintenanceAlert.vue, packages/nc-gui/composables/useServerConfig.ts, packages/nc-gui/plugins/a.dayjs.ts
=> maintenance ui

packages/noco-docs/docusaurus.config.js, packages/noco-docs/src/css/custom.scss, packages/noco-docs/src/modules/maintenance.js
=> feat: maintenance alert docs

packages/noco-docs/package-lock.json, packages/noco-docs/package.json
=> fix: sync docs dependencies

tests/playwright/tests/db/features/multiFieldEditor.spec.ts
=> test: disable MFE tests for SQLite & MySQL

packages/nc-gui/components/virtual-cell/BelongsTo.vue, packages/nc-gui/components/virtual-cell/HasMany.vue, packages/nc-gui/components/virtual-cell/ManyToMany.vue, packages/nc-gui/components/virtual-cell/OneToOne.vue, packages/nc-gui/components/virtual-cell/components/ItemChip.vue
=> fix: load expnaded form row on cliking on bt, ltar cell chip

packages/nc-gui/components/dlg/QuickImport.vue, packages/nc-gui/components/template/Editor.vue, packages/nc-gui/components/template/utils.ts, packages/nc-gui/helpers/parsers/CSVTemplateAdapter.ts, packages/nc-gui/helpers/parsers/ExcelTemplateAdapter.ts, packages/nc-gui/lang/en.json, tests/playwright/tests/db/features/import.spec.ts
- ref: #8796
- ref: https://github.com/nocodb/nocodb/issues/8928
=> Nc feature: Import CSV - skip field mapping during import 

packages/noco-docs/docs/070.fields/040.field-types/050.custom-types/050.barcode.md
=> docs: remove EAN from supported barcode type

packages/nocodb/src/models/Source.ts, packages/nocodb/src/services/sources.service.ts, packages/nocodb/src/version-upgrader/ncProjectConfigUpgrader.ts
=> fix: use update method for soft delete

packages/nc-gui/components/dashboard/View.vue, packages/nc-gui/composables/useGlobal/actions.ts, packages/nc-gui/composables/useGlobal/state.ts, packages/nc-gui/composables/useGlobal/types.ts, packages/nc-gui/store/sidebar.ts
=> Nc fix: sidebar width issue if user hide sidebar & reload page

packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
Enable table of contents in docs
=> fix: enable toc in docs

packages/nc-gui/plugins/tele.ts
=> fix: add telementry to cmd+j

packages/nc-gui/components/nc/PaginationV2.vue, packages/nc-gui/components/smartsheet/Toolbar.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/toolbar/FieldListAutoCompleteDropdown.vue, packages/nc-gui/components/smartsheet/toolbar/FieldListWithSearch.vue, packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue, packages/nc-gui/components/smartsheet/toolbar/RowHeight.vue, packages/nc-gui/composables/useSharedView.ts, packages/nc-gui/composables/useViewColumns.ts, packages/nc-gui/lib/types.ts, packages/nocodb/src/services/public-metas.service.ts
=> Nc fix: prevent commentor/viewer from enabling hidden columns

packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts, packages/nocodb/src/meta/migrations/v2/nc_055_junction_pk.ts
Add missing composite pk for base user tables
=> fix: missing pk for user junction table

packages/nc-gui/components/smartsheet/grid/Table.vue
=> fix(nc-gui): add new row btn width issue

packages/nc-gui/components/dlg/QuickImport.vue, packages/nc-gui/components/template/Editor.vue, packages/nc-gui/helpers/parsers/CSVTemplateAdapter.ts, packages/nc-gui/helpers/parsers/ExcelTemplateAdapter.ts, packages/nc-gui/utils/validation.ts
- ref(Record already exists): #8018
=> Nc fix: rename id column if exist in import table

packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/composables/useGlobal/actions.ts, packages/nc-gui/composables/useGlobal/state.ts, packages/nc-gui/composables/useGlobal/types.ts
=> feat(nc-gui): persist add new record mode (grid/form) in local storage

packages/nc-gui/components/cell/Json.vue
=> fix(nc-gui): json cell value visibility issue

packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/survey.vue
=> feat(nc-gui): add form header in each slide of survey form

packages/nc-gui/components/extensions/Details.vue, packages/nc-gui/components/extensions/Extension.vue, packages/nc-gui/components/extensions/Market.vue, packages/nc-gui/components/extensions/Pane.vue, packages/nc-gui/components/smartsheet/Toolbar.vue, packages/nc-gui/components/smartsheet/Topbar.vue, packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue, packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue, packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue, packages/nc-gui/components/smartsheet/toolbar/GroupByMenu.vue, packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue, packages/nc-gui/components/smartsheet/toolbar/StackedBy.vue, packages/nc-gui/components/tabs/Smartsheet.vue, packages/nc-gui/composables/useExtensions.ts, packages/nc-gui/context/index.ts
=> fix: Extensions TBD work items

packages/nc-gui/components/smartsheet/column/EditOrAdd.vue, packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue, packages/nocodb/src/services/columns.service.ts
=> Nc fix/links followup

packages/nc-gui/composables/useRoles/index.ts
=> fix: CSV Data Upload option not available for MySQL when Schema edit is disabled 

packages/noco-docs/docs/160.developer-resources/010.rest-APIs/050.upload-via-api.md
=> docs: typo fix

packages/nocodb/src/plugins/s3/S3.ts
=> feat: fileCreateByStream for S3

packages/nc-gui/composables/useViewGroupBy.ts
=> Nc fix/bulk api

packages/nc-gui/components/virtual-cell/Rollup.vue, packages/nocodb-sdk/src/lib/helperFunctions.ts, packages/nocodb/src/db/genRollupSelectv2.ts, packages/nocodb/src/models/RollupColumn.ts, packages/nocodb/src/schema/swagger-v2.json, packages/nocodb/src/schema/swagger.json
=> fix: rollup functions

packages/nocodb/src/helpers/dataHelpers.ts
=> fix(nc-gui): fix download csv/xlsx error

.github/ISSUE_TEMPLATE/--bug-report.yaml, .github/ISSUE_TEMPLATE/--feature-request.yaml
=> chore: improve GitHub issue templates

packages/nc-gui/components/api-client/Headers.vue, packages/nc-gui/components/api-client/Params.vue
Closes https://github.com/nocodb/nocodb/issues/9021
=> fix: add checkbox to toggle webhook parameter

packages/nc-gui/composables/useViewAggregate.ts
=> fix: load aggregations only on grid view

packages/nc-gui/utils/urlUtils.ts, packages/nocodb-sdk/src/lib/formulaHelpers.ts, packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
=> feat: add labels support for url

packages/nc-gui/utils/urlUtils.ts
=> fix: handle when url is empty

docker-compose/setup-script/noco.sh
=> Corrections in setup script

packages/nc-gui/components/dlg/AirtableImport.vue, packages/nocodb/src/modules/jobs/jobs/at-import/helpers/readAndProcessData.ts
=> Nc fix/at import issues

package.json, packages/nc-gui/package.json, packages/nocodb-sdk/src/lib/Api.ts, packages/nocodb/package.json, pnpm-lock.yaml
=> chore: bump xlsx package version

packages/nc-gui/components/dashboard/settings/DataSources.vue, packages/nc-gui/components/dashboard/settings/UIAcl.vue, packages/nocodb-sdk/src/lib/formulaHelpers.ts, packages/nocodb/src/models/Source.ts
=> fix: UI Acl & data sources

packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue, packages/nc-gui/composables/useMultiSelect/index.ts, packages/nocodb/src/db/BaseModelSqlv2.ts
=> Nc fix/3368 links followup

packages/nc-gui/store/views.ts
=> fix(nc-gui): view page title udpate issue

packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/models/FormView.ts, packages/nocodb/src/models/PresignedUrl.ts, packages/nocodb/src/modules/jobs/jobs/data-export/data-export.processor.ts, packages/nocodb/src/services/attachments.service.ts
Fixes #9057
- use original url if signed url not available
=> fix: use original url if signed url not available

packages/nocodb/src/models/PresignedUrl.ts
=> fix: remove extra slash from path

packages/nc-gui/components/smartsheet/FormulaWrapperCell.vue, packages/nc-gui/components/smartsheet/PlainCell.vue, packages/nc-gui/components/smartsheet/column/FormulaOptions.vue, packages/nc-gui/components/virtual-cell/Formula.vue, packages/nc-gui/lang/en.json, packages/nocodb-sdk/src/lib/UITypes.ts, packages/nocodb-sdk/src/lib/index.ts
Closes https://github.com/nocodb/nocodb/issues/6197
=> feat: formula formatting support

packages/nc-gui/components/cell/attachment/UploadProviders/Url.vue, packages/nocodb/src/services/attachments.service.ts
- Issues with the URL- Upload
- Handle the url signing
=> fix: attachment related issues

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/workspace/AuditLogs.vue, packages/nc-gui/composables/usePaginationShortcuts.ts, packages/nc-gui/store/workspace.ts
=> Nc feat: audit logs pagination keyboard shortcuts support 

packages/nc-gui/components/smartsheet/grid/GroupBy.vue, packages/nc-gui/components/smartsheet/grid/GroupByTable.vue, packages/nc-gui/components/smartsheet/grid/PaginationV2.vue, packages/nc-gui/composables/useSharedView.ts, packages/nc-gui/composables/useViewGroupBy.ts, packages/nc-gui/store/views.ts, packages/nocodb/src/controllers/data-table.controller.ts, packages/nocodb/src/controllers/public-datas.controller.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/db/sql-data-mapper/lib/BaseModel.ts, packages/nocodb/src/helpers/extractLimitAndOffset.ts, packages/nocodb/src/schema/swagger.json, packages/nocodb/src/services/data-table.service.ts, packages/nocodb/src/services/public-datas.service.ts, tests/playwright/pages/Dashboard/Grid/Group.ts, tests/playwright/pages/Dashboard/common/Toolbar/Groupby.ts
Use bulk Apis to fetch data in group by
=> feat: groupby bulk apis

packages/nc-gui/components/dashboard/TreeView/ViewsList.vue, packages/nc-gui/components/dashboard/settings/data-sources/CreateBase.vue, packages/nc-gui/components/dashboard/settings/data-sources/EditBase.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/workspace/AuditLogs.vue, packages/nc-gui/composables/usePaginationShortcuts.ts, packages/nc-gui/store/views.ts, packages/nc-gui/utils/baseCreateUtils.ts, packages/nocodb-sdk/src/lib/connectionConfigUtils.ts, packages/nocodb-sdk/src/lib/enums.ts, packages/nocodb-sdk/src/lib/index.ts, packages/nocodb/src/controllers/utils.controller.ts, packages/nocodb/src/services/sources.service.ts
=> Nc fix/ssl prop related

build-local-docker-image.sh
=> fix[build-local-docker-image.sh]: pnpm i -> pnpm bootstrap.

packages/nc-gui/composables/useSharedFormViewStore.ts
=> Nc feat/3424 prefill links

.github/workflows/release-executables.yml
=> Executable build action changes for supporting sharp library

packages/nc-gui/components/smartsheet/header/AddLookups.vue, packages/nc-gui/components/smartsheet/header/Menu.vue, packages/nc-gui/components/smartsheet/header/UpdateDisplayValue.vue, packages/nc-gui/lang/en.json
Allow adding lookups directly from the Links/LTAR Columns headers
=> feat: Add lookups from Link field context menu

packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts
Closes https://github.com/nocodb/nocodb/issues/9087
=> fix: thumbnail generation failing in Other S3 providers

packages/nocodb/src/models/Column.ts
=> fix: use same key while grouping insert records

packages/nc-gui/components/smartsheet/Form.vue, packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/index.vue
=> fix(nc-gui): if focus is on submit btn then only form should submit

packages/nocodb/src/controllers/attachments-secure.controller.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/helpers/attachmentHelpers.ts, packages/nocodb/src/models/FormView.ts, packages/nocodb/src/models/PresignedUrl.ts, packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts, packages/nocodb/src/plugins/s3/S3.ts, packages/nocodb/src/plugins/storage/Local.ts, packages/nocodb/src/services/attachments.service.ts, packages/nocodb/src/services/public-datas.service.ts
- Unify repetitive logic for attachment handling
=> fix: improve & unify attachment handling

packages/nc-gui/components/dashboard/TreeView/TableNode.vue, packages/nc-gui/composables/useTableNew.ts
=> Nc fix/duplicate default view

packages/noco-docs/docs/110.roles-and-permissions/010.roles-permissions-overview.md
`editor`s can add/update/delete table records.
=> docs: fix roles table

packages/nc-plugin/src/lib/IStorageAdapterV2.ts
Add fetchOptions to uploadViaUrl method in IStorageAdapterV2 interface
=> fix: add fetch-options

packages/nc-gui/app.vue, packages/nc-gui/components/smartsheet/Kanban.vue, packages/nc-gui/components/smartsheet/expanded-form/RichComment.vue, packages/nc-gui/composables/useExtensions.ts, packages/nc-gui/composables/useKanbanViewStore.ts, packages/nc-gui/composables/useSmartsheetStore.ts, packages/nc-gui/composables/useViewColumns.ts, packages/nc-gui/composables/useViewData.ts, packages/nc-gui/store/bases.ts
=> Nc fix/sentry errors

packages/nc-plugin/src/lib/IStorageAdapterV2.ts
- wrap options & allow extending storage adapter
=> chore: wrap options & allow extending storage adapter

packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/components/smartsheet/grid/useColumnDrag.ts, packages/nc-gui/components/virtual-cell/components/LinkedItems.vue, packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue, packages/nc-gui/composables/useViewColumns.ts
=> fix(nc-gui): Linked item fields show wrong order in popup

packages/nc-gui/components/smartsheet/details/Fields.vue
=> fix(nc-gui): Fields are missing in details if directly navigated

packages/nc-gui/composables/useViewGroupBy.ts
=> fix: aggregtaion not getting updated

packages/nocodb/src/services/meta-diffs.service.ts
=> fix: One-to-one meta sync issue 

packages/nc-gui/components/account/UserList.vue, packages/nc-gui/components/dashboard/settings/Metadata.vue, packages/nc-gui/components/dashboard/settings/UIAcl.vue, packages/nc-gui/components/general/MaintenanceAlert.vue, packages/nc-gui/components/nc/Table.vue, packages/nc-gui/components/project/AccessSettings.vue, packages/nc-gui/components/project/AllTables.vue, packages/nc-gui/components/template/Editor.vue, packages/nc-gui/components/template/utils.ts, packages/nc-gui/components/workspace/AuditLogs.vue, packages/nc-gui/components/workspace/CollaboratorsList.vue, packages/nc-gui/lib/types.ts, tests/playwright/pages/Account/Users.ts, tests/playwright/pages/Dashboard/Import/ImportTemplate.ts, tests/playwright/pages/Dashboard/ProjectView/Metadata.ts
=> Nc fix: replace ant design table

packages/nc-gui/components/smartsheet/grid/GroupBy.vue, packages/nc-gui/components/workspace/CollaboratorsList.vue, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/services/meta-diffs.service.ts
=> fix: Sub-group loading issue

packages/nc-gui/components/project/AccessSettings.vue, packages/nc-gui/components/roles/Selector.vue, packages/nc-gui/components/workspace/CollaboratorsList.vue, packages/nc-gui/lang/en.json
=> Nc fix/show inherited role in project members table

packages/nocodb/src/filters/global-exception/global-exception.filter.ts
=> Nc fix/throttler logging

packages/nocodb/src/services/bases.service.ts
=> fix: external source with project create

packages/nc-gui/components/dashboard/settings/data-sources/CreateBase.vue, packages/nc-gui/components/dashboard/settings/data-sources/EditBase.vue, packages/nc-gui/components/dashboard/settings/data-sources/SourceRestrictions.vue, packages/nc-gui/components/project/AllTables.vue, packages/nc-gui/components/project/SyncDataModal.vue, packages/nc-gui/components/workspace/integrations/List.vue, packages/nc-gui/components/workspace/integrations/newAvailableList.vue, packages/nc-gui/lang/en.json
=> Nc fix/integration corrections

packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue, packages/nocodb/src/db/BaseModelSqlv2.ts
=> fix(nc-gui): enable Limit record selection to a view in oss 

packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts, packages/nocodb/src/services/attachments.service.ts
=> fix: Load sharp package dynamically to handle loading error gracefully

packages/nc-gui/components/project/AllTables.vue, packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
=> Nc fix/minor bug fixes1

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue, packages/nocodb-sdk/src/lib/Api.ts, tests/playwright/pages/Dashboard/ProjectView/DataSourcePage.ts
=> fix: pw test fail issue

packages/nc-gui/components/dashboard/settings/DataSources.vue, packages/nc-gui/components/project/AllTables.vue, packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
=> Nc fix/minor bug fixes1 merge conflict

tests/playwright/pages/Account/Users.ts
=> test: fix user management flaky test

packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue
=> fix(nc-gui): show empty state if integration search list is empty

packages/nc-gui/components/dashboard/Sidebar.vue, packages/nc-gui/components/general/Gift.vue
=> Sidebar banner ui corrections

packages/nocodb/src/helpers/NcPluginMgrv2.ts, packages/nocodb/src/plugins/GenericS3/GenericS3.ts, packages/nocodb/src/plugins/backblaze/Backblaze.ts, packages/nocodb/src/plugins/s3/S3.ts, packages/nocodb/src/plugins/s3/index.ts
- Allows Minio to be configured as S3 Plugin from environmental variable
=> fix: s3 add forcePathStyle config

packages/nc-gui/components/smartsheet/Form.vue, packages/nc-gui/composables/useFormViewStore.ts, packages/nc-gui/composables/useSharedFormViewStore.ts, packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/index.vue, packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/survey.vue
=> Nc fix(nc-gui): Hide pre-filled fields form submit issue

packages/noco-docs/docs/095.integrations/010.overview.md
=> fix: docs link

packages/nocodb/src/db/sortV2.ts
=> fix: Formula order by issue with constant value

packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md, packages/nocodb/src/helpers/NcPluginMgrv2.ts, packages/nocodb/src/plugins/s3/S3.ts, packages/nocodb/src/plugins/s3/index.ts, packages/nocodb/src/utils/cloud/populateCloudPlugins.ts
Allow configure S3 ACL from Env
=> feat: configure S3 acl from envs

packages/nc-gui/components/smartsheet/Gallery.vue, packages/nc-gui/components/smartsheet/Kanban.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/components/smartsheet/grid/index.vue, packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue, packages/nc-gui/composables/useViewGroupBy.ts
=> Nc fix(nc-gui): grid view issues

packages/nc-gui/components/smartsheet/grid/GroupByTable.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/composables/useViewGroupBy.ts
=> fix: multiple troggering of expanded-record

packages/nc-gui/utils/syncDataUtils.ts
=> misc: reorder integrations

packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts, packages/nocodb/src/plugins/mino/Minio.ts, packages/nocodb/src/plugins/mino/index.ts, packages/nocodb/src/services/attachments.service.ts
fix: await upload
fix: allow useSSL to be false
fix: properly format key with slash
Closes https://github.com/nocodb/nocodb/issues/9203
Closes https://github.com/nocodb/nocodb/issues/9217
Closes https://github.com/nocodb/nocodb/issues/9218
=> fix: minio related issues

packages/nocodb/src/plugins/mino/Minio.ts, packages/nocodb/src/plugins/mino/index.ts
Closes https://github.com/nocodb/nocodb/issues/9201
=> feat: allow self-signed certificate for Minio 

packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue, packages/nc-gui/lang/en.json, packages/nc-gui/utils/syncDataUtils.ts, packages/nocodb-sdk/src/lib/enums.ts
=> misc: add spreadsheet category

.github/workflows/release-npm.yml
=> chore: skip sdk and lib-gui publish from action (TEMP)

.github/workflows/release-timely-executables.yml
=> chore: Timely executable build action related bug fixes

packages/noco-docs/docusaurus.config.js
=> fix(docs): incorrect github link

packages/nocodb/src/interface/Jobs.ts, packages/nocodb/src/meta/meta.service.ts, packages/nocodb/src/modules/jobs/fallback/fallback-queue.service.ts, packages/nocodb/src/modules/jobs/fallback/jobs.service.ts, packages/nocodb/src/modules/jobs/jobs-event.service.ts, packages/nocodb/src/modules/jobs/jobs-map.service.ts, packages/nocodb/src/modules/jobs/jobs-service.interface.ts, packages/nocodb/src/modules/jobs/jobs.controller.ts, packages/nocodb/src/modules/jobs/jobs.module.ts, packages/nocodb/src/modules/jobs/jobs.processor.ts, packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts, packages/nocodb/src/modules/jobs/jobs/attachment-clean-up/attachment-clean-up.ts, packages/nocodb/src/modules/jobs/jobs/data-export/data-export.processor.ts, packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.processor.ts, packages/nocodb/src/modules/jobs/jobs/meta-sync/meta-sync.processor.ts, packages/nocodb/src/modules/jobs/jobs/source-create/source-create.processor.ts, packages/nocodb/src/modules/jobs/jobs/source-delete/source-delete.processor.ts, packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts, packages/nocodb/src/modules/jobs/jobs/webhook-handler/webhook-handler.processor.ts, packages/nocodb/src/modules/jobs/migration-jobs/init-migration-jobs.ts, packages/nocodb/src/modules/jobs/migration-jobs/nc_job_002_thumbnail.ts, packages/nocodb/src/modules/jobs/redis/jobs.service.ts
=> feat: improve queue logic 

packages/nc-gui/components/nc/List.vue, packages/nc-gui/components/smartsheet/Form.vue, packages/nc-gui/components/virtual-cell/components/ListItem.vue, packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue, packages/nc-gui/composables/useSharedFormViewStore.ts
=> Nc feat: Prefill links using form builder

packages/nc-gui/components/smartsheet/Gallery.vue, packages/nc-gui/components/smartsheet/Kanban.vue
Closes https://github.com/nocodb/nocodb/issues/9272
=> fix: Button url open not working in gallery and kanban 

packages/nocodb/src/filters/global-exception/global-exception.filter.ts
=> fix: avoid setting ttl to 0

packages/nc-gui/components/account/AppStore.vue, packages/nc-gui/components/account/Profile.vue, packages/nc-gui/components/account/ResetPassword.vue, packages/nc-gui/components/account/SignupSettings.vue, packages/nc-gui/components/account/Token.vue, packages/nc-gui/components/account/UserList.vue, packages/nc-gui/components/nc/PageHeader.vue, packages/nc-gui/components/project/AccessSettings.vue, packages/nc-gui/components/project/View.vue, packages/nc-gui/components/workspace/AuditLogs.vue, packages/nc-gui/components/workspace/View.vue, packages/nc-gui/components/workspace/integrations/view.vue, packages/nc-gui/pages/account/index.vue, packages/nc-gui/windi.config.ts
=> Nc Fix: header ui changes

packages/nc-gui/components/monaco/formula.ts, packages/nc-gui/components/smartsheet/column/FormulaInputHelper.vue, packages/nocodb-sdk/src/lib/formulaHelpers.ts
=> Nc fix/3616 formula related bugs

packages/nocodb/src/services/hooks.service.ts
Move button triggers to workers
=> feat: move button trigger to workers

packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md, packages/nocodb/src/helpers/extractLimitAndOffset.ts
=> Env variable update

packages/nc-gui/components/project/AllTables.vue
=> fix: base home page table name font as normal

packages/nocodb/src/filters/global-exception/global-exception.filter.ts
=> fix: wrong logic for throtller counter

packages/nc-gui/components/cell/DatePicker.vue, packages/nc-gui/components/cell/DateTimePicker.vue, packages/nc-gui/components/nc/DatePicker.vue, packages/nc-gui/components/nc/DateWeekSelector.vue, packages/nc-gui/components/nc/MonthYearSelector.vue, packages/nc-gui/components/nc/TimeSelector.vue, packages/nc-gui/components/smartsheet/Cell.vue, packages/nc-gui/components/smartsheet/column/DefaultValue.vue, packages/nc-gui/lang/en.json, packages/nocodb-sdk/src/lib/sqlUi/DatabricksUi.ts, packages/nocodb-sdk/src/lib/sqlUi/MssqlUi.ts, packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts, packages/nocodb-sdk/src/lib/sqlUi/OracleUi.ts, packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts, packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts, packages/nocodb-sdk/src/lib/sqlUi/SqliteUi.ts, tests/playwright/pages/Dashboard/Grid/Column/UserOptionColumn.ts
=> Nc feat/date field current date as def

packages/nc-gui/components/cell/User.vue, packages/nc-gui/components/general/UserIcon.vue, packages/nc-gui/components/workspace/CollaboratorsList.vue, packages/nc-gui/store/base.ts
=> Nc feat/user mgmt followup

packages/nc-gui/middleware/02.auth.global.ts, packages/nc-gui/pages/index.vue, packages/nc-gui/plugins/redirect.ts
=> Nc fix/login redirect bug

packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts, packages/nocodb/src/modules/jobs/migration-jobs/init-migration-jobs.ts, packages/nocodb/src/modules/jobs/migration-jobs/nc_job_002_thumbnail.ts, packages/nocodb/src/providers/init-meta-service.provider.ts
- thumbnail generation migration
=> feat: thumbnail generation migration

packages/nc-gui/components/nc/form-builder/SampleModal.vue, packages/nc-gui/components/nc/form-builder/index.vue, packages/nc-gui/composables/useFormBuilder/index.ts, packages/nc-gui/lib/formBuilder.ts
=> Nc feat/form builder

packages/nc-gui/composables/useViewAggregate.ts, packages/nc-gui/composables/useViewGroupBy.ts
=> Fix: aggregation filter sync

packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue, packages/nc-gui/utils/colorsUtils.ts, packages/nc-gui/windi.config.ts
=> Nc Style: Add new light theme config in windicss config file

packages/nc-gui/components/smartsheet/header/Menu.vue
=> fix: hide description in expanded-view menu options

packages/nc-gui/utils/colorsUtils.ts
=> Nc chore/add Light Theme Configuration docs

packages/nocodb/src/db/BaseModelSqlv2.ts
Row delete throws error when record includes attachment.
=> fix: Row delete bug

docker-compose/setup-script/noco.sh, docker-compose/setup-script/tests/expects/install/redis.sh, docker-compose/setup-script/tests/expects/install/scale.sh, docker-compose/setup-script/tests/expects/install/watchtower.sh
Add Minio to installation script
=> feat: noco installaion script

packages/nocodb/src/db/aggregation.ts
Ignore aggregation in formula, If the formula is invalid
=> fix: load other aggregations even formula Column is error

packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/models/PresignedUrl.ts, packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts, packages/nocodb/src/plugins/mino/Minio.ts, packages/nocodb/src/plugins/storage/Local.ts
Fix attachment related issues in windows
Closes https://github.com/nocodb/nocodb/issues/9317
https://github.com/nocodb/nocodb/issues/8925
https://github.com/nocodb/nocodb/issues/8800
=> fix: handle attachment issues for windows

packages/nocodb/src/schema/swagger-v2.json, packages/nocodb/src/schema/swagger.json
fix: remove deprecated apis from swagger
=> fix: remove deprecated apis from swagger

packages/nc-gui/components/smartsheet/expanded-form/index.vue
=> fix(nc-gui): hide formula field in new record expanded form

packages/nc-gui/plugins/error-handler.ts
=> fix(nc-gui): append reload_attempt query param after hash url

packages/nc-gui/components/dlg/ViewCreate.vue, packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue, packages/nc-gui/components/smartsheet/calendar/MonthView.vue, packages/nc-gui/components/smartsheet/calendar/SideMenu.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue, packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue, packages/nc-gui/composables/useCalendarViewStore.ts, packages/nc-gui/lang/en.json, packages/nocodb/src/helpers/catchError.ts
Closes https://github.com/nocodb/nocodb/issues/9360
=> Nc misc fixes

packages/nc-gui/components/workspace/integrations/forms/EditOrAddDatabase.vue, packages/nocodb-sdk/src/lib/connectionConfigUtils.ts
=> fix: Test connection related bugs

packages/nc-gui/utils/colorsUtils.ts, packages/nc-gui/windi.config.ts
=> Nc fix(nc-gui): rename light theme colors shortcuts

markdown/readme/languages/french.md
=> docs: improve french doc

packages/nocodb/src/db/sql-client/lib/KnexClient.ts
=> chore: update KnexClient.ts

packages/nc-gui/components/smartsheet/calendar/index.vue
=> fix: add some docs to calendar code

packages/nc-gui/composables/useCalendarViewStore.ts
=> fix: add additional docs to calendar code

packages/nc-gui/utils/datetimeUtils.ts, packages/nocodb/src/models/BaseUser.ts
=> Nc fix: showing wrong date joined time from now in project members tab & for editor and below role it showing current date as date joined

packages/nocodb/src/helpers/webhookHelpers.ts, packages/nocodb/src/utils/common/formSubmissionEmailTemplate.ts
fix: form submission email attachments
=> fix: form submission email attachments

packages/nocodb/src/helpers/webhookHelpers.ts
fix: user fields filters not working in webhook 
Closes https://github.com/nocodb/nocodb/issues/9398
=> fix: user fields filters not working in webhook 

README.md, packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation/010.auto-upstall.md
=> update : refactor auto-upstall and installation methods

packages/nc-gui/components/cell/DatePicker.vue, packages/nc-gui/components/cell/DateTimePicker.vue, packages/nc-gui/components/cell/TimePicker.vue, packages/nc-gui/components/cell/YearPicker.vue, packages/noco-docs/docs/020.getting-started/040.keyboard-shortcuts.md
Closes https://github.com/nocodb/nocodb/issues/9372
=> feat: add today shortcut for Date related fields

packages/nocodb/src/db/CustomKnex.ts
=> fix: Handle date object as value and avoid treating it as nested condition

packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation/010.auto-upstall.md
=> Auto upstall docs

packages/nc-gui/components/cell/Json.vue, packages/nc-gui/composables/useApi/interceptors.ts, packages/nocodb/src/db/sql-mgr/code/models/xc/ModelXcMetaPg.ts
=> Nc fix/miscellaneous

packages/nocodb/src/controllers/old-datas/old-datas.service.ts, packages/nocodb/src/controllers/public-datas-export.controller.ts, packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/helpers/dataHelpers.ts, packages/nocodb/src/services/data-table.service.ts, packages/nocodb/src/services/datas.service.ts, packages/nocodb/src/services/public-datas.service.ts, packages/nocodb/src/utils/index.ts, packages/nocodb/src/utils/nocoExecute.ts
=> refactor: nocoExecute

packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts, packages/nocodb/src/meta/migrations/v2/nc_061_integration_is_default.ts, packages/nocodb/src/meta/migrations/v2/nc_062_integration_store.ts, packages/nocodb/src/utils/globals.ts
=> feat: integrations follow-up migration

packages/nocodb/src/db/aggregations/mysql2.ts, packages/nocodb/src/db/aggregations/pg.ts, packages/nocodb/src/db/aggregations/sqlite3.ts
Fix: aggregation related issues
=> fix: aggregation queries

packages/nc-gui/components/smartsheet/PlainCell.vue, packages/nc-gui/composables/useMultiSelect/index.ts
Related thread - https://discord.com/channels/661905455894888490/1282745446548246620
=> fix: Proper column meta null value handling

packages/nocodb/src/helpers/extractLimitAndOffset.ts
- Allow `DB_QUERY_LIMIT_MIN` value upto `1`
=> refactor: Pagination limit min value restriction

packages/nocodb-sdk/src/lib/helperFunctions.ts
=> fix(nc-gui): show decimal cell value with trailing zeros

packages/nocodb/src/db/BaseModelSqlv2.ts
Closes https://github.com/nocodb/nocodb/issues/9446
=> fix: aggregation not working in mariadb

packages/nocodb/src/schema/swagger-v2.json
=> Nc docs/v2 meta api reorg

packages/nocodb/src/db/BaseModelSqlv2.ts
Related thread - https://discord.com/channels/661905455894888490/1282682167012626453/1282682169332076627
=> fix: Post update extract new id since composite key can be changed in update

packages/nocodb/src/db/genRollupSelectv2.ts
Closes https://github.com/nocodb/nocodb/issues/9437
=> fix: add default value for rollup

packages/nc-gui/plugins/redirect.ts, packages/nocodb/src/controllers/api-docs/api-docs.controller.ts, packages/nocodb/src/controllers/api-docs/template/redocHtml.ts, packages/nocodb/src/controllers/api-docs/template/swaggerHtml.ts
=> fix: swagger UI blank page

packages/nocodb/src/controllers/users/users.controller.ts, packages/nocodb/src/modules/auth/auth.controller.ts, packages/nocodb/src/schema/swagger-v2.json
=> Nc feat/missing api v2

packages/nc-mail-templates/src/templates/Mention.vue, packages/nocodb/src/modules/auth/ui/auth/emailVerify.ts, packages/nocodb/src/modules/auth/ui/auth/resetPassword.ts, packages/nocodb/src/modules/auth/ui/emailTemplates/forgotPassword.ts, packages/nocodb/src/modules/auth/ui/emailTemplates/invite.ts, packages/nocodb/src/modules/auth/ui/emailTemplates/verify.ts, packages/nocodb/src/services/base-users/ui/auth/emailVerify.ts, packages/nocodb/src/services/base-users/ui/auth/resetPassword.ts, packages/nocodb/src/services/base-users/ui/emailTemplates/forgotPassword.ts, packages/nocodb/src/services/base-users/ui/emailTemplates/invite.ts, packages/nocodb/src/services/base-users/ui/emailTemplates/verify.ts, packages/nocodb/src/utils/common/formSubmissionEmailTemplate.ts
=> Nc fix/email template

packages/nocodb/src/schema/swagger-v2.json
=> docs: meta api v2 label and order

packages/nocodb/src/db/BaseModelSqlv2.ts
=> refactor: Sanitise method

packages/nocodb/src/schema/swagger-v2.json
=> docs: meta apis for base

packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue
=> fix: Disable form view creation only for data readonly source

packages/nocodb/src/plugins/gcs/Gcs.ts, packages/nocodb/src/plugins/mino/Minio.ts
Implement scanFiles for gcs and Minio
Closes https://github.com/nocodb/nocodb/issues/9450
=> feat: Implement scanFiles for gcs and Minio

packages/nocodb/src/controllers/old-datas/old-datas.service.ts, packages/nocodb/src/controllers/public-datas-export.controller.ts, packages/nocodb/src/helpers/dataHelpers.ts, packages/nocodb/src/modules/auth/auth.controller.ts, packages/nocodb/src/services/data-table.service.ts, packages/nocodb/src/services/datas.service.ts, packages/nocodb/src/services/public-datas.service.ts
Fixes - https://discord.com/channels/661905455894888490/1285462452481294438/1285472292377333770
=> fix: Apply view based filter if linkColumnId present in list api

packages/nocodb/src/schema/swagger-v2.json
=> docs: meta v2 fields description

packages/nocodb/src/db/BaseModelSqlv2.ts, packages/nocodb/src/models/Column.ts
Bug reported via email
- use asId prop to override `as` selector instead of modifying column obj
=> fix: barcode on formula

packages/nocodb/src/controllers/sources.controller.ts, packages/nocodb/src/models/Source.ts, packages/nocodb/src/services/sources.service.ts
=> fix: Query cache on source update

packages/nocodb/src/db/BaseModelSqlv2.ts
- Handle string & number diff while comparing
=> fix: handle type diff while comparing pks

packages/nocodb/src/schema/swagger-v2.json
=> docs: view & webhook APIs

README.md
Now it matches the pglite example, and works.
=> Fix $(pwd) invocation in readme example

packages/nocodb/src/models/Column.ts, packages/nocodb/src/modules/jobs/jobs.module.ts, packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts, packages/nocodb/src/modules/jobs/jobs/at-import/helpers/fetchAT.ts
Use async await instead of chaining with then
Filter data from response using stream-json
=> fix: at import stall issue

packages/nc-gui/components/smartsheet/details/Fields.vue
=> fix(nc-gui): show mfe save changes field error

packages/nc-gui/composables/useGlobal/actions.ts, packages/nc-gui/plugins/redirect.ts
=> Nc fix/9501 redirection issue

packages/nc-gui/components/dashboard/settings/app-store/AppInstall.vue, packages/nc-gui/components/smartsheet/grid/Table.vue
- div cannot be child of table
- div cannot be child of tr
=> Nc fix/dev warnings

packages/nc-gui/components/account/Token.vue, packages/nc-gui/components/tabs/auth/ApiTokenManagement.vue, packages/nocodb/src/controllers/api-tokens.controller.ts, packages/nocodb/src/controllers/org-tokens.controller.ts, packages/nocodb/src/models/ApiToken.ts, packages/nocodb/src/schema/swagger-v2.json, packages/nocodb/src/schema/swagger.json, packages/nocodb/src/services/api-tokens.service.ts, packages/nocodb/src/services/app-hooks/interfaces.ts, packages/nocodb/src/services/org-tokens.service.ts
=> Nc refactor/api token

charts/nocodb/values.yaml
=> chore[charts/nocodb/values.yaml]: Typo `https:/` -> `https://`.

packages/nc-gui/components/smartsheet/grid/Table.vue
=> Nc fix(nc-gui): grid column resize error

packages/nc-gui/components/smartsheet/details/Fields.vue
=> Nc fix(nc-gui): MFE show newly added column in same view and hide it in other views 

packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation/030.docker-compose.md, packages/nocodb/README.md
Updated the path to the relevant docker file; the directory named changed from `pg` -> `2_pg`
=> [docs] Fix docker compose setup path

packages/nocodb/src/Noco.ts, packages/nocodb/src/controllers/attachments-secure.controller.ts, packages/nocodb/src/controllers/attachments.controller.ts, packages/nocodb/src/helpers/attachmentHelpers.ts, packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts, packages/nocodb/src/modules/jobs/migration-jobs/nc_job_002_thumbnail.ts, packages/nocodb/src/services/attachments.service.ts
- Remove existsSync call
- Initialize sharp only once per instance
=> fix: optimizations to potential blockers

packages/nc-gui/components/dashboard/TreeView/TableNode.vue, packages/nc-gui/components/dlg/ViewCreate.vue, packages/nc-gui/components/smartsheet/details/Fields.vue, packages/nc-gui/composables/useTableNew.ts, packages/nc-gui/store/webhooks.ts, packages/nc-gui/utils/generateName.ts, packages/nocodb/src/services/integrations.service.ts, tests/playwright/tests/db/features/multiFieldEditor.spec.ts, tests/playwright/tests/db/views/viewKanban.spec.ts
=> Nc fix/duplicate name update

packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation/030.docker-compose.md
=> Adjusted path for 2_pg folder in  030.docker-compose.md

packages/nc-gui/components/dashboard/Sidebar/Feed.vue, packages/nc-gui/components/feed/Error.vue, packages/nc-gui/components/feed/Recents/index.vue, packages/nc-gui/components/feed/Twitter.vue, packages/nc-gui/composables/useProductFeed.ts
- Handle errors gracefully in twitter and reload
- Refactor newFeeds
=> fix: product feed fixes

packages/nc-gui/components/dashboard/Sidebar/Feed.vue, packages/nc-gui/components/feed/Recents/Card.vue, packages/nc-gui/components/feed/Social.vue, packages/nc-gui/components/feed/View.vue, packages/nc-gui/components/feed/Youtube/Player.vue, packages/nc-gui/components/feed/Youtube/index.vue
Update events for product feed
=> fix: events

packages/nocodb/src/models/BaseUser.ts, packages/nocodb/src/services/base-users/base-users.service.ts
=> Nc fix/add to fav bug

packages/nocodb/src/models/BaseUser.ts, packages/nocodb/src/services/base-users/base-users.service.ts
=> Nc fix/add to fav bug followup

packages/nc-gui/components/cell/Currency.vue, packages/nc-gui/components/cell/Decimal.vue, packages/nc-gui/components/cell/Duration.vue, packages/nc-gui/components/cell/Email.vue, packages/nc-gui/components/cell/Float.vue, packages/nc-gui/components/cell/Integer.vue, packages/nc-gui/components/cell/Json.vue, packages/nc-gui/components/cell/Percent.vue, packages/nc-gui/components/cell/PhoneNumber.vue, packages/nc-gui/components/cell/RichText.vue, packages/nc-gui/components/cell/Text.vue, packages/nc-gui/components/cell/TextArea.vue, packages/nc-gui/components/cell/Url.vue, packages/nc-gui/components/dashboard/TreeView/index.vue, packages/nc-gui/components/general/FullScreen.vue, packages/nc-gui/components/smartsheet/details/Fields.vue, packages/nc-gui/components/smartsheet/expanded-form/index.vue, packages/nc-gui/store/projectsShortcuts.ts, packages/nc-gui/utils/browserUtils.ts
=> fix(nc-gui): Prevent keyboard shortcuts if user is in cell edit mode or any other active input element 

packages/nc-gui/components/nc/ErrorBoundary.vue, packages/nc-gui/components/smartsheet/grid/Table.vue, packages/nc-gui/composables/useGlobal/types.ts, packages/nc-gui/nuxt-shim.d.ts, packages/nc-gui/plugins/error-reporting.ts, packages/nc-gui/plugins/sentry.ts, packages/nocodb-sdk/src/lib/Api.ts, packages/nocodb/src/controllers/utils.controller.ts, packages/nocodb/src/schema/swagger.json, packages/nocodb/src/services/utils.service.ts
=> refactor: GUI error handling

packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md, packages/nocodb/src/helpers/initBaseBehaviour.ts, packages/nocodb/src/services/bases.service.ts, packages/nocodb/src/utils/getInstance.ts
- Update `NC_DISABLE_BASE_AS_PG_SCHEMA` => `NC_DISABLE_PG_DATA_REFLECTION`
=> refactor: Change Postgres as schema environment key

packages/nocodb/src/helpers/initDataSourceEncryption.ts
=> fix: Integration encryption bug 

packages/nocodb/src/Noco.ts, packages/nocodb/src/helpers/initDataSourceEncryption.ts, packages/nocodb/src/version-upgrader/upgraders/0225002_ncDatasourceDecrypt.ts
=> refactor: Add logs for encryption - upgrader and init logic

packages/nocodb/src/helpers/initDataSourceEncryption.ts, packages/nocodb/src/utils/encryptDecrypt.ts
=> fix: Integration encryption - handle stringified config value

packages/nocodb/README.md
=> fix(docs): broken fenced code blocks and indentation

packages/nc-gui/components/cell/Currency.vue, packages/nc-gui/components/cell/Decimal.vue, packages/nc-gui/components/cell/Duration.vue, packages/nc-gui/components/cell/Email.vue, packages/nc-gui/components/cell/Float.vue, packages/nc-gui/components/cell/Integer.vue, packages/nc-gui/components/cell/Percent.vue, packages/nc-gui/components/cell/PhoneNumber.vue, packages/nc-gui/components/cell/Text.vue, packages/nc-gui/components/cell/TextArea.vue, packages/nc-gui/components/cell/Url.vue, packages/nc-gui/components/smartsheet/form/field-config-error.vue, packages/nc-gui/components/smartsheet/form/field-settings/visibility.vue, packages/nc-gui/composables/useFormViewStore.ts, packages/nc-gui/lib/form.ts, packages/nocodb/src/models/Filter.ts, tests/playwright/tests/db/views/viewForm.spec.ts
=> Nc feat/enable conditional field in oss

packages/nc-gui/lang/ar.json, packages/nc-gui/lang/bn_IN.json, packages/nc-gui/lang/da.json, packages/nc-gui/lang/de.json, packages/nc-gui/lang/en.json, packages/nc-gui/lang/eu.json, packages/nc-gui/lang/fa.json, packages/nc-gui/lang/fi.json, packages/nc-gui/lang/hi.json, packages/nc-gui/lang/hr.json, packages/nc-gui/lang/id.json, packages/nc-gui/lang/ja.json, packages/nc-gui/lang/ko.json, packages/nc-gui/lang/lv.json, packages/nc-gui/lang/nl.json, packages/nc-gui/lang/no.json, packages/nc-gui/lang/pt_BR.json, packages/nc-gui/lang/sk.json, packages/nc-gui/lang/sl.json, packages/nc-gui/lang/sv.json, packages/nc-gui/lang/th.json, packages/nc-gui/lang/tr.json, packages/nc-gui/lang/uk.json, packages/nc-gui/lang/vi.json, packages/nc-gui/lang/zh-Hant.json
In Crowdin side we started using AI pre-translations
Please feel free to fix any mistakes in your language by following [our guide](https://docs.nocodb.com/engineering/translation/)
If you think something is wrong in your language you can contact us via any channel (discussions, [community](https://community.nocodb.com/), [discord](https://discord.com/invite/c7GEYrvFtT)) as well.
=> chore: add AI mention to translations

packages/nc-gui/composables/useCalendarViewStore.ts, packages/nc-gui/composables/useKanbanViewStore.ts
Closes: https://github.com/nocodb/nocodb/issues/9615
=> fix: Encode id to handle special chars

.github/workflows/bats-test.yml
=> chore: Upstall script test file path correction

docker-compose/1_Auto_Upstall/tests/expects/install/redis.sh, docker-compose/1_Auto_Upstall/tests/expects/install/scale.sh, docker-compose/1_Auto_Upstall/tests/expects/install/watchtower.sh
https://github.com/sinanmohd/nocodb/actions/runs/11274102486/job/31352698849
=> test: fix upstall bats tests

packages/nc-gui/components/smartsheet/form/field-settings/visibility.vue, packages/nc-gui/components/smartsheet/toolbar/FieldListAutoCompleteDropdown.vue, packages/nc-gui/context/index.ts
=> fix(nc-gui): conditional fields, show field alias if configured instead of actual field name

.github/workflows/release-nightly-dev.yml, .github/workflows/release-pr.yml, .github/workflows/release-timely-docker.yml, packages/nocodb/Dockerfile.timely, packages/nocodb/src/run/timely.ts, packages/nocodb/src/services/utils.service.ts, packages/nocodb/src/utils/TeleBatchProcessor.ts, packages/nocodb/src/utils/tele.ts, packages/nocodb/webpack.timely.config.js
=> Chore/timely docker build 

packages/nc-gui/components/feed/Recents/Card.vue, packages/nc-gui/components/feed/Recents/index.vue, packages/nc-gui/lib/types.ts
=> Nc include cloud release

README.md
Created a one-click installation template enabling users to affordably deploy and scale NocoDB on RepoCloud's efficient cloud hosting platform.
Placing this link on the readme page qualifies the NocoDB team to 25% recurring affiliate commissions.
=> Added one-click deploy template for RepoCloud.io

README.md
This PR introduces new one-click deployment option - Elestio
Fixes #9481
=> feat: Added Elestio as one-click deploy option

packages/nc-gui/components/cell/MultiSelect.vue, packages/nc-gui/components/cell/SingleSelect.vue, packages/nc-gui/components/smartsheet/toolbar/FilterInput.vue
- Limit multi-select width in filter UI
- Add space between option and tick icon for selected options
=> fix: Single/Multi select filter GUI improvements

packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
=> fix: Resolve GUI hang issues in formula creation interface

packages/nc-gui/components/cell/Checkbox.vue, packages/nc-gui/components/cell/Rating.vue, packages/nc-gui/components/smartsheet/column/CheckboxOptions.vue, packages/nc-gui/components/smartsheet/column/RatingOptions.vue, packages/nc-gui/helpers/columnDefaultMeta.ts, packages/nc-gui/utils/columnUtils.ts, packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.controller.ts, packages/nocodb/src/schema/swagger-v2.json, packages/nocodb/src/schema/swagger.json, packages/nocodb/src/services/columns.service.ts, packages/nocodb/src/services/tables.service.ts, packages/nocodb/tests/unit/rest/tests/table.test.ts
=> Nc fix/api corrections

package.json, pnpm-lock.yaml
remove fs package from root package.json
It's a placeholder package that was probably installed accidentally: https://www.npmjs.com/package/fs
=> chore: remove fs package from root package.json

README.md, packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation/100.other-installations.md, packages/noco-docs/docusaurus.config.js, packages/noco-docs/src/css/custom.scss
=> docs: move providers to other installation methods

packages/nocodb-sdk/src/lib/Api.ts, packages/nocodb-sdk/src/lib/formulaHelpers.ts, packages/nocodb/src/db/functionMappings/mssql.ts, packages/nocodb/src/db/functionMappings/mysql.ts, packages/nocodb/src/db/functionMappings/pg.ts, packages/nocodb/src/db/functionMappings/sqlite.ts, packages/nocodb/src/helpers/catchError.ts, packages/nocodb/src/services/columns.service.ts
Implement formulas for interacting with JSON
- `JSON_EXTRACT` formula to extract value in `jq` like mode
Based on request from https://github.com/nocodb/nocodb/issues/2410
Drivers implementations documentation
- https://dev.mysql.com/doc/refman/8.0/en/json-function-reference.html
- https://www.postgresql.org/docs/14/functions-json.html
- https://docs.microsoft.com/en-us/sql/t-sql/functions/json-functions-transact-sql
- https://www.sqlite.org/json1.html
=> feat: Implement formulas for interacting with JSON

packages/nc-gui/components/cell/attachment/utils.ts, packages/nocodb/src/constants/index.ts, packages/nocodb/src/modules/noco.module.ts, packages/nocodb/src/services/utils.service.ts
=> fix: upload file size limit

markdown/readme/languages/README.md, markdown/readme/languages/vietnamese.md
=> docs/vietnamese: Add Vietnamese README docs
