nocodb/nocodb

README.md
docker-entrypoint.sh
dockerfile

create basic `dockerfile` with `docker-entrypoint.sh` and some documentation about it at the end of the `README.md`

add dockerfile and description about docker in README.md

---

README.md

#20 add notes about using a reverse proxy (e.g. nginx)

---

README.md

https://github.com/o1lab/xmysql/issues/5#issuecomment-341099409

Add minimum node version to readme

---

lib/util/cmd.helper.js

you can change mysql port ( 3306 by default )

add mysql port config

---

docker-entrypoint.sh

Wait for mysql to be up before executing

---

README.md

"Why we building this?" flows weirdly, adding an 'are' makes it sound better.

fixed grammar error in readme

---

docker-compose/traefik/.env
docker-compose/traefik/README.md
docker-compose/traefik/docker-compose.yml

As requested in this issue: https://github.com/nocodb/nocodb/issues/191

Traefik deployment example

---

packages/nocodb/src/lib/noco/rest/ui/auth/swagger-base.xc.json

Fixed super small bug: U**S**er became User in swagger docs

Small fix in swagger docs

---

README.md

run as daemon, use a name, automatic restart, access do host databases

docker start text improved - 

---

packages/nc-gui/components/project/spreadsheet/mixins/cell.js

added fix for date column in postgres

---

.github/workflows/dco-check.yml

Add DCO check in PR - Inspired by https://github.com/nocodb/nocodb/pull/239#issuecomment-855371462

feat: add dco check in Pull Request

---

packages/nc-gui/pages/user/authentication/signin.vue
packages/nc-gui/static/lang/en.json
packages/nc-gui/static/lang/ja.json
packages/nc-gui/static/lang/zh.json

The changes in this PR are focusing on Sign In Page only. Ref to #236.

feat: add i18n on Sign in Page

---

packages/nc-gui/pages/user/authentication/signup/index.vue

Signed-off-by: Ido David <idonkl100@gmail.com>

fixed loading indicator on signup button

---

packages/nc-gui/README.md
packages/nc-lib-gui/README.md
packages/nocodb/README.md

docs: update README.md

---

README.md
packages/nc-gui/components/changeEnv.vue
packages/nc-gui/components/createOrEditProject.vue
packages/nc-gui/components/project/graphqlClient.vue
packages/nc-gui/components/project/settings/env.vue
packages/nc-gui/components/project/spreadsheet/apis/gqlApi.js
packages/nc-gui/components/project/swaggerClient.vue
packages/nc-gui/components/project/xcInfo.vue
packages/nc-gui/layouts/default.vue
packages/nc-gui/nuxt.config.js
packages/nc-gui/pages/nc/_project_id.vue
packages/nc-gui/pages/project/id.vue
packages/nc-gui/pages/user/authentication/signin.vue
packages/nc-gui/pages/user/authentication/signup/_token.vue
packages/nc-gui/pages/user/authentication/signup/index.vue
packages/nc-gui/plugins/projectLoader.js
packages/nc-gui/store/graphqlClient.js
packages/nc-gui/store/project.js
packages/nc-gui/store/sqlMgr.js
packages/nc-gui/store/users.js

fix: hardcoded baseURL

---

.github/workflows/node.yml
docker-compose-cypress.yml

Added separate docker-compose and updated cypress job

chore: Github action - cypress

---

packages/nocodb/src/__tests__/noco/NcConfigFactory.test.ts
packages/nocodb/src/__tests__/noco/dbConfig.json
packages/nocodb/src/lib/utils/NcConfigFactory.ts

Related: https://github.com/nocodb/nocodb/issues/453#issuecomment-897821808

feat: allow specifying db config through JSON string or JSON file

---

packages/noco-docs/content/en/setup-and-usages/meta-management.md

Signed-off-by: Raju Udava <sivadstala@gmail.com>

metadata import & export example

---

README.md
markdown/readme/korean.md

Signed-off-by: Jinsik Jo <kunggom@gmail.com>
I recently saw [NocoDB introduced on GeekNews](https://news.hada.io/topic?id=5083). And I thought I'd like to contribute to the draft of the `README.md` for the Korean version. And I added some edits to the English version of `README.md`. Please make sure there is no problem.

docs(readme): korean correction, and some edits for README.md

---

packages/nc-gui/lang/zh_CN.json

Signed-off-by: tianchunfeng <tianchunfeng@gmail.com>

translate file  packages/nc-gui/lang/zh_CN.json to chinese simplified version .

---

packages/nocodb/src/lib/noco/plugins/adapters/email/SMTP.ts
packages/nocodb/src/lib/noco/plugins/smtp.ts
packages/nocodb/src/plugins/smtp/SMTP.ts
packages/nocodb/src/plugins/smtp/index.ts

Signed-off-by: Giulio Malventi <giulio.malventi@gmail.com>

Add ignoreTLS to email plugin

---

packages/nc-gui/components/project/spreadsheet/components/virtualCell/belogsToCell.vue

Signed-off-by: Md Ishtiaque Zafar <ishtiaque.zafar92@gmail.com>

[Bugfix] Fix linking records when tables have a string primary key field

---

packages/noco-docs/content/en/getting-started/installation.md
packages/nocodb/src/lib/dataMapper/lib/sql/BaseModelSql.ts

Fix : csv deleted column

---

packages/nc-gui/components/utils/language.vue
packages/nc-gui/lang/es.json

Signed-off-by: David Daza <03dazal@gmail.com>
Fix some text in spanish language.

Fix some spanish text

---

packages/noco-docs/content/en/getting-started/upgrading.md

I have the Heroku CLI installed, but the current instructions didn't work. I received the following error: 
```
!    Login failed with: Cannot find docker, please ensure docker is installed.
!    If you need help installing docker, visit https://docs.docker.com/install/#supported-platforms
```
I've used Heroku to deploy another app ([Listmonk](https://listmonk.app/docs/upgrade/)) and used this method to upgrade. I wanted to share this method here too, especially since Nocodb releases upgrades frequently.
Added instructions to upgrade NocoDB using GitHub automatic deploy for Heroku.

Updating Heroku Upgrade Instructions

---

packages/noco-docs/content/en/getting-started/installation.md

added  `cd nocodb` after git clone

---

packages/noco-docs/content/en/getting-started/upgrading.md

Added Heroku upgrade with Mac M1 chip

---

scripts/markdown/readme/languages/chinese.md

Optimizing the translation of Chinese.

Fix several mistakes on translating

---

packages/nocodb/src/lib/noco/rest/ui/auth/emailVerify.ts
packages/nocodb/src/lib/noco/rest/ui/auth/resetPassword.ts
packages/nocodb/src/lib/noco/rest/ui/auth/signin.ts
packages/nocodb/src/lib/noco/rest/ui/auth/signup.ts

Fix titles in 4 pages. Ref: #935 

fix: page title

---

packages/nocodb/src/plugins/backblaze/Backblaze.ts
packages/nocodb/src/plugins/gcs/Gcs.ts
packages/nocodb/src/plugins/linode/LinodeObjectStorage.ts
packages/nocodb/src/plugins/mino/Minio.ts
packages/nocodb/src/plugins/ovhCloud/OvhCloud.ts
packages/nocodb/src/plugins/s3/S3.ts
packages/nocodb/src/plugins/scaleway/ScalewayObjectStorage.ts
packages/nocodb/src/plugins/spaces/Spaces.ts
packages/nocodb/src/plugins/upcloud/UpoCloud.ts
packages/nocodb/src/plugins/vultr/Vultr.ts

Ref: #954 
remove leading slashes for object keys

fix: remove leading slashes for object keys

---

packages/nocodb/src/lib/noco/plugins/ses.ts

Fixed typo in SES Configuration page.

fix: SES typo

---

packages/nc-gui/components/ProjectTreeView.vue

fix: add proper spacing in left navigation drawer

---

packages/nc-gui/lang/zh_TW.json

Extended from #995
Google Spreadsheet: https://docs.google.com/spreadsheets/d/16Ra8EeREbTqOVdNXeSLpy7-16tr2WY7S9OhJP8OkJsw/edit?usp=sharing
Signed-off-by: pan93412 <pan93412@gmail.com>

l10n(zh_TW): reviewed and translated all

---

packages/nc-gui/components/project/spreadsheet/components/editableCell.vue

fix: save record on enter/shift-enter key press

---

.all-contributorsrc
.github/workflows/ci-cd.yml
README.md
packages/nc-gui/components/ProjectTreeView.vue
packages/nc-gui/components/project/spreadsheet/components/editableCell.vue
packages/nc-gui/components/project/spreadsheet/views/xcGridView.vue
packages/nc-gui/lang/zh_TW.json
packages/nc-lib-gui/package.json
packages/nocodb/package-lock.json
packages/nocodb/package.json

Release v0.84.8

---

packages/nc-gui/components/import/templateParsers/ExcelTemplateAdapter.js
packages/nc-gui/components/project/spreadsheet/components/cell/dateCell.vue
packages/nc-gui/components/project/spreadsheet/components/cell/dateTimeCell.vue
packages/nc-gui/components/project/spreadsheet/components/expandedForm.vue

Ref: #992 
- Change primary value format in expanded form
- Change Cell formatting for Date & DateTime
- Add logic to handle precision & timezone offset issues introduced by xlsx

fix: different date across views

---

packages/nc-gui/components/project/projectMetadata/sync/disableOrEnableTables.vue
packages/nocodb/src/lib/noco/common/BaseApiBuilder.ts
packages/nocodb/src/lib/noco/common/handlers/xcMetaDiffSync.ts
packages/nocodb/src/lib/noco/gql/GqlApiBuilder.ts
packages/nocodb/src/lib/noco/rest/RestApiBuilder.ts

closes #1049
re #1047
re #1046

fix: handle meta sync properly and keep proper column metadata

---

packages/nc-gui/helpers/sqlUi/PgUi.js
packages/nocodb/src/lib/sqlUi/PgUi.ts

fix : percent type in postgres.

---

packages/nc-gui/components/project/spreadsheet/public/xcTable.vue
packages/nc-gui/components/project/viewTabs/viewSpreadsheet.vue

Ref: #991 
- Include ``MoreActions`` in SQL Views. 
- Include & fix Search box bug in share view
- Fine-tune the UI
Before:
After:
Share View:

fix: SQL View Actions

---

packages/nc-gui/components/project/spreadsheet/components/importExport/columnMappingModal.vue
packages/nc-gui/components/project/spreadsheet/components/moreActions.vue
packages/nc-gui/components/project/spreadsheet/rowsXcDataTable.vue

Ref: #880 
fix some csv validation issues

fix: some csv import issues

---

scripts/cypress/cypress.json
scripts/cypress/integration/common/00_pre_configurations.js
scripts/cypress/integration/common/1a_table_operations.js
scripts/cypress/integration/common/1c_sql_view.js
scripts/cypress/integration/common/5a_user_role.js
scripts/cypress/integration/test/explicitLogin.js
scripts/cypress/integration/test/gqlMisc.js
scripts/cypress/integration/test/gqlRoles.js
scripts/cypress/integration/test/gqlTableOps.js
scripts/cypress/integration/test/gqlViews.js
scripts/cypress/integration/test/masterSuiteGql.js
scripts/cypress/integration/test/masterSuiteRest.js
scripts/cypress/integration/test/restMisc.js
scripts/cypress/integration/test/restRoles.js
scripts/cypress/integration/test/restTableOps.js
scripts/cypress/integration/test/restViews.js
scripts/cypress/integration/test/xcdb-gqlMisc.js
scripts/cypress/integration/test/xcdb-gqlRoles.js
scripts/cypress/integration/test/xcdb-gqlTableOps.js
scripts/cypress/integration/test/xcdb-gqlViews.js
scripts/cypress/integration/test/xcdb-restMisc.js
scripts/cypress/integration/test/xcdb-restRoles.js
scripts/cypress/integration/test/xcdb-restTableOps.js
scripts/cypress/integration/test/xcdb-restViews.js
scripts/cypress/support/page_objects/navigation.js
scripts/cypress/support/page_objects/projectConstants.js

cypress configuration file test mode configurations simplified
all pass in ci/cd

refactor: consistent api's for api/db type

---

packages/nc-gui/components/auth/roles.vue
packages/nc-gui/components/auth/userManagement.vue
packages/nc-gui/components/base/shareBase.vue
scripts/cypress/support/page_objects/mainPage.js

Use of string keys instead of direct text- to aid in better support for other language translation
Cypress based CI/CD completed
Work in progress. Changes are being pushed in phases

Refactor: i18n changes for roles & share view

---

packages/nc-gui/components/utils/dlgTableCreate.vue

enforces validation if table-name invalid. does not allow a table to be created if conditions for table name are not met
verified locally
similar to column name validation

fix: enforce validation if table name invalid

---

.github/workflows/release-close-issue.yml
.github/workflows/release-docker.yml
.github/workflows/release-draft.yml
.github/workflows/release-nocodb.yml
.github/workflows/release-npm.yml
.github/workflows/sync-to-develop.yml

Ref: #1139 
**Manual Action:**
1. PR & Merge ``develop`` to ``master``.  (at least one members review is required.)
2. Create a new release branch (says ``release/0.0.1``) from ``master``.
**Existing Release Workflow:**
3. Publish frontend (Existing Action)
4. Install frontend (Existing Action)
5. Publish backend (Existing Action)
6. Close all issues
7. Create a PR from release branch to ``master``
8. Prepare Release notes (Existing Action + Manual update draft notes)
9. Publish Docker & Release (Existing Action)
10. Sync changes back to develop branch 
**New Release Workflow:**
- Master Workflow (input: tag, prev_tag) on ``master`` branch
- Action 1: release-npm (input: tag, prev_tag) (covers step 3 - step 5)
- Action 2: close-issues (input: N/A) (covers step 6)
- Action 3: release-draft …

refactor: release workflows

---

docker-compose/nginx/certbot-challenge.conf
docker-compose/nginx/docker-compose.yml
docker-compose/nginx/nocodb.example.domain.conf
docker-compose/nginx/ssl.conf

Thanks to an end user who sent this.

docs : adding setup with nginx, certbot with domain config.

---

packages/noco-docs/content/en/developer-resources/share-base.md

Documentation for share base & embed iframe
Verified changes over localhost noco-docs build

docs: share base details

---

packages/noco-docs/content/en/developer-resources/webhooks.md

Additional details for configuring webhook.
Microsoft teams related details are provided by @marco-santulli
https://github.com/nocodb/nocodb/issues/1322
Formatting verified locally

chore: documentaion- webhook update

---

packages/nc-gui/components/ProjectTreeView.vue
packages/nc-gui/components/project/spreadsheet/components/editColumn.vue
packages/nc-gui/components/project/spreadsheet/components/editVirtualColumn.vue
packages/nc-gui/components/utils/dlgTableCreate.vue
packages/nc-gui/helpers/index.js

[REST API] Extended character support for table/ column name
Verified locally for character support. Cypress tests verified over CI/CD

feat: extended character support for table/column name with REST

---

packages/nc-gui/components/project/spreadsheet/components/editColumn/linkedToAnotherOptions.vue

- Put On Update, On Delete and Virtual Relation to accordion
- Put Child table outside it

feat: add show more to LinkToAnotherRecord

---

packages/nc-gui/components/project/spreadsheet/components/virtualCell/belongsToCell.vue
packages/nc-gui/components/project/spreadsheet/components/virtualCell/components/listItems.vue
packages/nc-gui/components/project/spreadsheet/components/virtualCell/hasManyCell.vue
packages/nocodb/src/lib/dataMapper/lib/sql/BaseModelSql.ts

Ref: #1299 
Changed belongsToCell & hasManyCell logic to cater display issue and avoid foreign key violation in grid view for real relation
```sql
create table "customer" (
"uid" bigserial not null,
"customer_email" varchar(255) unique,
constraint "user_pk" primary key ("uid")
);
create table "customer_phone" (
"uid" bigserial not null,
"customer_email" varchar(255),
"phone_number" varchar(255),
constraint "userphone_pk" primary key ("uid")
);
create table "customer_address" (
"uid" bigserial not null,
"customer_uid" bigint,
"address" varchar(255),
constraint "customer_address_pk" primary key ("uid")
);
alter table "customer_phone" add constraint "customer_phone_fk1" foreign key ("customer_email") references "customer"("customer_email") ON UPDATE CASCADE ON DELETE CASCADE;
alter table …
```

fix: bt & hm logic

---

packages/nocodb/src/lib/dataMapper/lib/BaseModel.ts
packages/nocodb/src/lib/dataMapper/lib/sql/BaseModelSql.ts

It fixes distinct API endpoint. Make it work as expected.

fix distinct api enpoint

---

packages/nc-gui/components/project/spreadsheet/components/editableCell.vue
packages/nc-gui/components/project/spreadsheet/components/editableCell/editableAttachmentCell.vue
packages/nc-gui/components/project/spreadsheet/components/expandedForm.vue
packages/nc-gui/components/project/spreadsheet/rowsXcDataTable.vue
packages/nc-gui/components/project/spreadsheet/views/galleryView.vue

ref: #1468 
- Fixed image overlap issue
- Fixed locked view issue
- Fixed image overlay issue

fix: gallery logic

---

packages/nc-gui/components/project/spreadsheet/rowsXcDataTable.vue
packages/nc-gui/plugins/ncApis/gqlApi.js
packages/nc-gui/plugins/ncApis/restApi.js
packages/nocodb/src/lib/noco/common/BaseModel.ts

-changed variable name to _ignoreWebhook
-if _ignoreWebhook not present fire the webhook as intended

fix: hotfix reverting breaking changes on webhook multiple-trigger

---

packages/nc-gui/components/project/spreadsheet/rowsXcDataTable.vue

fix: disable update call if column undefined

---

packages/nocodb/src/lib/noco-models/ModelRoleVisibility.ts

fix:  migration(v1 to v2) - map proper project id and base id in ui acl

---

packages/nc-gui/components/project/spreadsheet/views/xcGridView.vue

fix: force cell update on unload if unsaved

---

packages/nocodb/src/lib/utils/projectAcl.ts

fix: add bulk api permissions to editor

---

packages/nocodb/src/lib/noco-models/Column.ts
packages/nocodb/src/lib/noco-models/LinkToAnotherRecordColumn.ts
packages/nocodb/src/lib/noco/meta/api/columnApis.ts
packages/nocodb/src/lib/noco/meta/api/dataApis/dataAliasNestedApis.ts
packages/nocodb/src/lib/noco/meta/api/metaDiffApis.ts
packages/nocodb/src/lib/noco/upgrader/jobs/ncProjectUpgraderV2_0090000.ts
packages/nocodb/src/lib/utils/projectAcl.ts

Fix - Link To Another record migration bug

---

packages/noco-docs/content/en/developer-resources/rest-apis.md
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/lib/noco/meta/api/dataApis/dataAliasApis.ts
scripts/sdk/swagger.json

Added table rows count api `/api/v1/db/data/{orgs}/{projectName}/{tableName}/count` and updated swagger.json.

feat : Add table rows count api

---

packages/nocodb/src/lib/noco/upgrader/jobs/ncProjectUpgraderV2_0090000.ts

fix: ignore deleted projects audit while migrating metadata

---

packages/nocodb/src/lib/dataMapper/lib/sql/BaseModelSqlv2.ts
packages/nocodb/src/lib/dataMapper/lib/sql/CustomKnex.ts
packages/nocodb/src/lib/dataMapper/lib/sql/conditionV2.ts
packages/nocodb/src/lib/noco-models/Filter.ts
packages/nocodb/src/lib/utils/projectAcl.ts

- Added following editor permission
- Rows count
- ShowAllColumn
- HideAllColumns
- `isnot` operator support added in `where` query parameter

Fix - count api and acl

---

packages/nc-gui/components/ProjectTreeView.vue
packages/nc-gui/components/project/spreadsheet/components/extras.vue
packages/nc-gui/mixins/device.js
packages/nocodb/src/lib/noco/upgrader/NcUpgrader.ts

Added data APIs documentation in project dashboard navdrawer.

Add api documentation link in project dashboard

---

packages/nocodb/src/lib/noco/upgrader/NcUpgrader.ts
packages/nocodb/src/lib/noco/upgrader/jobs/ncProjectUpgraderV2_0090000.ts

Extract correct model id on audit export and ignore table audit if missing meta
re #1722

fix: Audit migration corrections

---

packages/nocodb/src/lib/noco/meta/helpers/catchError.ts

typo fix: basRequest => badRequest

chore: typo correction for better error update

---

packages/nc-gui/components/project/spreadsheet/components/moreActions.vue

Ref: #1737 
Change to the new API

fix: import csv issue

---

packages/nocodb/src/lib/noco/migrationsv2/nc_011.ts
packages/nocodb/src/lib/noco/migrationsv2/nc_012_alter_column_data_types.ts
packages/nocodb/src/lib/noco/upgrader/jobs/ncProjectUpgraderV2_0090000.ts

- Handle invalid formula
- Insert project user entry only if both project and user exist
- Skip shared view migration if the model or view name missing
- Migration down statement 
- Split alter statement into multiple to avoid MSSQL migration error

Fix - Migration bugs

---

packages/nc-gui/components/project/spreadsheet/rowsXcDataTable.vue

ref: #1773 
disable clear in locked view

fix: disable clear in locked view

---

packages/nc-gui/components/project/spreadsheet/views/formView.vue

fix: not showing lookup & rollup in form view

---

packages/nc-gui/lang/fa.json

Persian language corrections
CI/CD

i18n/translation farsi correction (@okaeiz)

---

packages/nc-gui/components/project/spreadsheet/components/virtualHeaderCell.vue

ref #1766
As with v0.90.0 handling of these columns changed, virtual-header-cell's functionality for showing related icons and proper tooltip broke.

fix: virtual-header-cell component

---

packages/nc-gui/components/auth/shareOrInviteModal.vue
packages/nc-gui/components/auth/userManagement.vue

re https://github.com/nocodb/nocodb/issues/1766#issuecomment-1103443112

fix: 'owner' role color

---

packages/nc-gui/pages/user/settings/index.vue
packages/nocodb/src/lib/noco/meta/api/userApi/userApis.ts

Ref: #1824 
Use the new API for changing password

fix: change password

---

scripts/cypress/integration/common/5a_user_role.js
scripts/cypress/integration/common/5b_preview_role.js

Cypress test suite correction after disabling export / import menu
CI/CD

test: remove access to export / import tab

---

packages/nc-gui/lang/zh_TW.json

Fix translation of "sponsor us" in zh_TW

Fix "sponsor us"'s text in zh_TW.json

---

packages/nc-gui/package.json
packages/noco-docs/content/en/developer-resources/rest-apis.md
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/package.json
packages/nocodb/src/lib/dataMapper/lib/sql/BaseModelSqlv2.ts
packages/nocodb/src/lib/noco/meta/api/dataApis/dataAliasApis.ts
scripts/sdk/swagger.json

ref: #1827 
- Add findOne API
- Update API Doc
```bash
curl -X 'GET' \
http://localhost:8080/api/v1/db/data/noco/sakila/TestTable/find-one \
--header "Content-Type: application/json" \
-H 'accept: application/json' \
-H 'xc-auth: <REDACTED>'
```
```bash
curl -X 'GET' \
http://localhost:8080/api/v1/db/data/noco/sakila/TestTable/views/TestTable/find-one \
--header "Content-Type: application/json" \
-H 'accept: application/json' \
-H 'xc-auth: <REDACTED>'
```
```bash
{"list":[{"Id":6,"Title":"A","CreatedAt":"2022-04-22 11:58:39","UpdatedAt":"2022-04-22 18:39:09","Title2":"A"}],"pageInfo":{"totalRows":1,"page":1,"pageSize":25,"isFirstPage":true,"isLastPage":true}}
```
```bash
curl -X 'GET' \
http://localhost:8080/api/v1/db/data/noco/sakila/TestTable/find-one?where=(Title,eq,C) \
--header …
```

feat: findOne

---

packages/nocodb/src/lib/utils/NcHelp.ts

Execute queries sequentially in case mssql to avoid transaction/ timeout issue.

fix: MSSQL migration bug

---

packages/nc-gui/components/createOrEditProject.vue
packages/nc-gui/lang/en.json

feat: show schema name option for mssql and pg project creation

---

packages/nc-gui/components/project/spreadsheet/components/virtualHeaderCell.vue

Show column name instead of 'undefined'

fix: belongs to header tooltip

---

scripts/cypress/cypress.json

disable cypress screenshots
CI/CD on PR

test: cypress disable screenshots/ suspecting flakyness

---

scripts/cypress/integration/spec/roleValidation.spec.js

test realignment post UI corrections
CI/CD on PR

test/cypress: UI corrections

---

packages/nocodb/src/lib/noco/meta/helpers/NcPluginMgrv2.ts

ref: #1822 
Return the correct adapter. 
File created by plugin setup test
Attachment Testing

fix: storage adapter issue

---

packages/nc-gui/components/project/table.vue
packages/nocodb/src/lib/noco/meta/api/tableApis.ts

Block table delete action if there is a relation column present.
re #1861

Fix - delete table bug

---

packages/nc-gui/helpers/treeViewDataSerializer.js
packages/nc-gui/helpers/xutils.js

ref: #1910 
- Update meta table list
- Filter out meta table in tree view
Before:
After:

fix: meta tables shown in tree view

---

.github/workflows/release-docker.yml
.github/workflows/release-npm.yml
.github/workflows/release-pr.yml
scripts/bumpNocodbSdkVersion.js
scripts/upgradeNcGui.js
scripts/upgradeNocodbSdk.js

- create a new workflow file for handling PR release
- version convention
```
nocodb-daily:<VERSION>-pr-<PR_NUMBER>-<DATE>-<TIME>.
Example: nocodb-daily:0.0.1-pr-1123-20220426-0506
nocodb-sdk-daily:<VERSION>-pr-<PR_NUMBER>-<DATE>-<TIME>.
Example: nocodb-sdk-daily:0.0.1-pr-1123-20220426-0506
nocodb-timely:<VERSION>-pr-<PR_NUMBER>-<DATE>-<TIME>
Example: nocodb-timely:0.0.1-pr-1123-20220426-0506
```
Bot commenter will be hid for time begin. Once the testing is finished, then uncomment `leave-comment`.

feat: PR Release

---

.github/workflows/release-nightly-dev.yml
.github/workflows/release-nocodb.yml
.github/workflows/update-sdk-path.yml

- update local sdk path after release - ref: #1925
- remove targetEnv option as the only option is 'DEV'

enhancement: gitHub actions

---

packages/nc-gui/components/project/spreadsheet/components/editColumn.vue
packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts

- add toast to show error for editColumn
- add default value sample label

refactor: error message / default value label 

---

scripts/cypress/support/commands.js

test/fix: wait for project tab to become visible (looks like more delay induced due to recent changes to open base view link)
CI/CD

test/fix: wait for project tab to become available

---

packages/nc-gui/components/createOrEditProject.vue
packages/nocodb/src/lib/dataMapper/lib/sql/helpers/getAst.ts
packages/nocodb/src/lib/noco-models/Base.ts

Populating proper knex configuration for external SQLite project.
Verified using SQLite file from https://github.com/nocodb/nocodb/issues/1956

Fix - SQLite project bug

---

packages/nocodb/src/lib/noco-models/ProjectUser.ts

ref: #1959 
- changing role in `${CacheScope.USER}:${email}`
- changing role in `${CacheScope.USER}:${email}___${projectId}`

fix: add missing upd cache logic when updating roles

---

packages/nocodb/src/lib/dataMapper/lib/sql/BaseModelSqlv2.ts

fix: use union all instead of union since rows will be unique

---

scripts/markdown/readme/languages/chinese.md

Improve the Chinese translation
Keeping README in sync with the English version
None

Docs: improve chinese translation

---

packages/nc-gui/components/import/ImportFromAirtable.vue
packages/nocodb/src/lib/dataMapper/lib/sql/BaseModelSqlv2.ts
packages/nocodb/src/lib/noco/meta/api/sync/helpers/job.ts
scripts/cypress/cypress.json
scripts/cypress/integration/common/7b_import_from_airtable.js

- fix: ignore rollup for the lookup column
- test/cypress: base configurations (WIP, not integrated)
- fix: multi-select as CSV string instead of array
- fix: ludicrous mode view data retrieval
- fix: use decimal if precision was configured in airtable
- fix: default form view data
- fix: support use of '?' in the column name
- refactor: migration logs
- migration tests carried out locally

Feat/at sync test: migration fixes

---

packages/nocodb/src/lib/noco/meta/api/sync/helpers/job.ts

Feat/at sync test - simple cleanups

---

packages/noco-docs/content/en/developer-resources/rest-apis.md
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/lib/dataMapper/lib/sql/BaseModelSqlv2.ts
packages/nocodb/src/lib/noco/meta/api/dataApis/dataAliasApis.ts
packages/nocodb/src/lib/utils/projectAcl.ts
scripts/sdk/swagger.json

- add Exist API in dbTableRow & dbViewRow - ref: #2064 
- update rest api in documentation
```
curl --request GET \
--url 'http://localhost:8080/api/v1/db/data/<org>/<projectName>/<tableName>/<ID>/exist' \
--header 'xc-auth: <REDACTED>'
```
```
curl --request GET \
--url 'http://localhost:8080/api/v1/db/data/<org>/<projectName>/<tableName>/views/<viewName>/<ID>/exist' \
--header 'xc-auth: <REDACTED>'
```
Result:
```
true
```
```
curl --request GET \
--url 'http://localhost:8080/api/v1/db/data/<org>/<projectName>/<tableName>/<somethingIDNotExist>/exist' \
--header 'xc-auth: <REDACTED>'
```
```
curl --request GET \
--url 'http://localhost:8080/api/v1/db/data/<org>/<projectName>/<tableName>/views/<viewName>/<somethingIDNotExist>/exist' \
--header 'xc-auth: <REDACTED>'
```
Result:
```
false …
```

feat: exist api

---

packages/noco-docs/content/en/developer-resources/rest-apis.md
packages/nocodb/src/lib/dataMapper/lib/sql/BaseModelSqlv2.ts
packages/nocodb/src/lib/noco/meta/api/dataApis/dataAliasApis.ts
packages/nocodb/src/lib/noco/meta/api/swagger/helpers/swagger-base.json
packages/nocodb/src/lib/noco/meta/api/swagger/helpers/templates/params.ts
packages/nocodb/src/lib/noco/meta/api/swagger/helpers/templates/paths.ts
packages/nocodb/src/lib/utils/projectAcl.ts

Group by API. Fixes https://github.com/nocodb/nocodb/issues/2065

group by api

---

packages/nocodb/src/lib/noco-models/Plugin.ts
packages/nocodb/src/lib/noco/meta/api/userApi/initStrategies.ts
packages/nocodb/src/lib/noco/meta/api/userApi/userApis.ts

PR to fix Google Oauth for the new version.

fix: google oauth2.0

---

packages/nc-gui/components/project/spreadsheet/components/editColumn/FormulaOptions.vue
packages/nc-gui/components/project/spreadsheet/components/virtualCell/FormulaCell.vue
packages/nc-gui/helpers/formulaList.js
packages/noco-docs/content/en/setup-and-usages/formulas.md

- Display information message when double clicking formula cell
- Add circular reference detection
Example: formula1 -> formula2 -> formula3 -> formula4 ("HELLO") 
Changing formula3 from `{formula4}` to `{formula2}` will throw as `formual2 <--> formula3` forms a cycle.
Similarly, changing formula3 from `{formula4}` to `{formula1}` will throw as `formual1 --> formula2 --> formula3 --> formula1 --> ...` forms a cycle.
- Add help text by hovering the function name
- Improve formula argument validations. Some examples are shown below.
- Fix some incorrect validation rules
- Revise formula documentation
- Refactor: some variable naming & add more comments
It may not cover all the cases but most basic ones should be there. Will follow up after some other tasks.

enhancement: formula

---

.github/workflows/ci-cd.yml
.github/workflows/publish-api-docs.yml
.github/workflows/publish-blog.yml
.github/workflows/publish-dev-docs.yml
.github/workflows/publish-docs.yml
.github/workflows/publish-noco-i18n.yml
.github/workflows/publish-prev-docs.yml
.github/workflows/release-docker.yml
.github/workflows/release-draft.yml
.github/workflows/release-nocodb.yml
.github/workflows/release-npm.yml
.github/workflows/update-sdk-path.yml

- include docs publishing in release-nocodb
- fix incorrect SHA (prev: HEAD from somewhere - now: the Auto PR from develop to master)
- nocodb-sdk to localpath - (bump to node v16 to include npm >= 7)

fix: github action issues

---

packages/nc-gui/components/project/spreadsheet/components/ColorPicker.vue
packages/nc-gui/components/project/spreadsheet/components/editColumn/CheckboxOptions.vue
packages/nc-gui/components/project/spreadsheet/components/editColumn/RatingOptions.vue

A custom color picker component supporting:
- array of colors as swatches (colors: Array)
- custom row size for swatches (row-size: Number)
- enable/disable advanced color picker (advanced: Boolean)
Integrated into RatingOptions and CheckboxOptions.

ColorPicker component

---

packages/nocodb/src/lib/noco/meta/api/columnApis.ts

Create an index on the creation of LTAR column in Postgres.
re #2142

enhancement: create index for foreign key in pg

---

packages/nocodb/src/lib/noco-jobs/JobsMgr.ts
packages/nocodb/src/lib/noco/meta/api/sync/importApis.ts

Use a separate queue and job for sending progress notifications back to client.

feat: Use a separate queue and job for progress

---

packages/nocodb/src/lib/noco/meta/api/sync/helpers/job.ts

- rollup fix
- store link record information to reduce at API access
- locally verified
- don't merge

Fix/at sync: store link records

---

packages/nc-gui/components/project/spreadsheet/components/FieldsMenu.vue

Show scrollbar in fields menu whenever necessary.
re #2181

enhancement: show scrollbar in fields menu

---

packages/nc-gui/components/project/spreadsheet/components/ColumnFilter.vue
packages/nc-gui/components/project/spreadsheet/components/FieldListAutoCompleteDropdown.vue
packages/nc-gui/components/project/spreadsheet/components/SortListMenu.vue
scripts/cypress/support/page_objects/mainPage.js

Replace the simple select dropdown of the column in filter and sort with autocomplete since it will help users search and select columns if there are many columns.
re #2180

enhancement: use autocomplete in sort or filter fields

---

packages/nocodb/src/lib/noco/meta/helpers/NcPluginMgrv2.ts
packages/nocodb/src/plugins/gcs/Gcs.ts
packages/nocodb/src/plugins/gcs/index.ts

- Solve error:0909006C:PEM routines:get_name:no start line. Ref: #2207 
- Include Project ID input to give flexibility.
Tested with [scgscorp](https://github.com/scgscorp)'s credentials.

fix: GCS plugin

---

packages/nc-gui/components/import/ImportFromAirtable.vue
packages/nc-gui/components/project/spreadsheet/components/editableCell/EditableAttachmentCell.vue
packages/nc-gui/components/project/spreadsheet/helpers/imageExt.js
packages/nocodb/src/lib/dataMapper/lib/sql/BaseModelSqlv2.ts
packages/nocodb/src/lib/noco/Noco.ts
packages/nocodb/src/lib/noco/meta/api/sync/helpers/job.ts
packages/nocodb/src/lib/noco/meta/api/sync/helpers/readAllATData.ts
packages/nocodb/src/lib/noco/meta/api/sync/helpers/readAndProcessData.ts

Feat - Import optimization

---

packages/nocodb/src/lib/noco/meta/helpers/webhookHelpers.ts

Ignore the logging webhook data if the condition is not satisfying.
re #2209

fix: skip hook log if condition is not matching

---

packages/nocodb/src/lib/noco/meta/api/swagger/helpers/templates/params.ts

Fix columnNameParam type
re: #2208

fix: swagger columnNameParam type

---

.gitignore

add vscode ide's ignore list

---

packages/nc-gui/components/project/spreadsheet/components/editableCell/DatePickerCell.vue

fix: DatePickerCell invalid date handling

---

packages/nc-gui/components/ProjectTreeView.vue
packages/nc-gui/helpers/rolePermissionsEE.js

disable api docs access for viewer role

fix: disable api docs access for viewer role

---

packages/nc-gui/components/project/spreadsheet/views/GridView.vue

Re https://github.com/nocodb/nocodb/issues/2240

fix: Persian language moving across table

---

packages/nc-gui/components/project/spreadsheet/components/FlipCard.vue
packages/nc-gui/components/project/spreadsheet/components/SpreadsheetNavDrawer.vue
packages/nc-gui/store/project.js
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/lib/meta/api/projectApis.ts
scripts/sdk/swagger.json

- New component: Flip Card
- Flip by hover(default), click, interval (on-hover, on-click, on-time)
- Front and back slots
- Predict cost for non-os (api)
- SpreadsheetNavDrawer extras merged into flip-card appending non-os prediction / support us

feat: compare with non-os products

---

packages/nocodb/package-lock.json
packages/nocodb/package.json
packages/nocodb/src/lib/meta/api/projectApis.ts

This PR is mainly tackling #2262 - Stored XSS.
Reference: https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html
For existing / missing sanitization will be submitted with another PR.

fix: sanitize project title

---

scripts/markdown/readme/languages/french.md

I aslo add some stuff according to the README (it was a different display so i didn't add a lot)

modification of the traduction

---

packages/nocodb/src/lib/meta/api/userApi/userApis.ts
packages/nocodb/src/lib/models/User.ts

Ref: #2288 
Previously the cache is not updated correctly. This PR is to make it work.

fix: change password cache logic

---

packages/nocodb/src/lib/meta/api/dataApis/dataAliasNestedApis.ts

Has many API pagination correction
re #2242

fix: hasmany pagination - api correction

---

packages/noco-docs/content/en/developer-resources/webhooks.md
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
packages/nocodb/src/lib/meta/helpers/webhookHelpers.ts

Remove user reference from webhook context.
ref: #2262

Fix: Remove user reference from webhook context

---

packages/nc-gui/pages/user/settings/index.vue
packages/nc-gui/plugins/axiosInterceptor.js
packages/nocodb/src/lib/meta/api/userApi/initStrategies.ts
packages/nocodb/src/lib/meta/api/userApi/userApis.ts
packages/nocodb/src/lib/meta/helpers/ncMetaAclMw.ts
packages/nocodb/src/lib/migrations/XcMigrationSourcev2.ts
packages/nocodb/src/lib/migrations/v2/nc_017_add_user_token_exp_column.ts
packages/nocodb/src/lib/migrations/v2/nc_017_add_user_token_version_column.ts
packages/nocodb/src/lib/models/User.ts
packages/nocodb/src/lib/v1-legacy/rest/RestAuthCtrl.ts

Added a new column `token_version` in User. Compare with the jwt token_version.
ref: #2262 
- Log into same account using two different browsers
- Change the password in browser A -> force logout
- Reload the page in browser B -> force logout
- Change the password in browser A -> force logout -> login again
- Reload the page in browser B -> force logout

fix: insufficient session expiration

---

packages/nc-gui/components/project/spreadsheet/components/editableCell/DateTimePickerCell.vue

avoid blocking table deletion. different formats will be handled in a separate PR.
ref: #2347

fix: show err message when input cannot be parsed

---

packages/nocodb/src/lib/meta/api/sync/helpers/job.ts

Continue migration even if user exist on project.
Re #2370

fix(sync): handle existing user on project

---

packages/nocodb/src/lib/models/User.ts

- If the user registered with the email `a@nocodb.com`, the following example `a@nocodb.com`, `A@nocodb.com`, `A@NoCoDb.com`, ...  values are valid for user login.
re #2361

fix: make email case-insensitive

---

packages/nocodb/src/lib/meta/api/projectUserApis.ts
packages/nocodb/src/lib/meta/api/userApi/helpers.ts
packages/nocodb/src/lib/meta/api/userApi/initStrategies.ts
packages/nocodb/src/lib/meta/api/userApi/userApis.ts
packages/nocodb/src/lib/meta/helpers/stringHelpers.ts

- add missing token_version when inserting to User
ref: #2396

fix: add missing token_version

---

packages/nc-gui/components/CreateOrEditProject.vue
packages/nc-gui/pages/project/id.vue
packages/nc-gui/pages/project/xcdb.vue
packages/nocodb/src/lib/meta/api/projectApis.ts

ref: Uncontrolled Resource Consumption
payload: https://drive.google.com/file/d/13IK67Sx93nvnb_3gLUBDLgoEC7XTQiso/view
xcdb:
external:

fix: large char on project name

---

packages/nc-gui/components/project/spreadsheet/views/FormView.vue

fix: revise form validations

---

packages/nc-gui/components/project/spreadsheet/components/editColumn/FormulaOptions.vue

ref: #2304
F: `CONCAT({Title}, " || ", {Date}, " || ", {Time}, " || ", {Boolean}, "||", {Lookup}, " || ", {Id})`

enhancement: allow CONCAT on anything

---

packages/nc-gui/components/import/templateParsers/ExcelTemplateAdapter.js

Handle BOM - ref: #2439 
Before 
After

fix: diacritics are garbled

---

.github/workflows/release-executables.yml
.github/workflows/release-nightly-dev.yml
.github/workflows/release-pr.yml
packages/nocodb/README.md

Action for generating executables

Build executable for pr

---

packages/nocodb/src/lib/jobs/RedisJobsMgr.ts

ref: #2452  - just do what it says.

fix: set maxRetriesPerRequest to null in redis

---

packages/noco-docs/content/en/setup-and-usages/primary-key.md

Summary of Primary Key during various scenario's is documented
NA

docs: primary key

---

packages/noco-docs/content/en/developer-resources/rest-apis.md
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/lib/meta/api/userApi/ui/auth/emailVerify.ts
packages/nocodb/src/lib/meta/api/userApi/userApis.ts
scripts/sdk/swagger.json

Update user/auth APIs path and update in documentation and swagger.json.
`/api/v1/db/auth/` => `/api/v1/auth/`

fix: api path correction

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
packages/nocodb/src/lib/meta/api/swagger/helpers/templates/paths.ts

PR is adding Find one endpoint that is missing from swagger docs. Also, it adds support for sorting.

Find one with sort

---

packages/nc-gui/components/project/spreadsheet/components/EditableCell.vue
packages/nc-gui/components/project/spreadsheet/components/editableCell/DurationCell.vue
packages/nc-gui/components/project/spreadsheet/components/editableCell/TimePickerCell.vue
packages/nc-gui/components/project/spreadsheet/mixins/cell.js

Re #2443
- Fixed webhook trigger
- mixins
- isAutoSaved: for columns that auto-saved while editing without triggering webhook
- isManualSaved: for columns that are not compatible with saving while editing (post formatting of cell ex. currency)
**Webhooks fired from every UIType successfully: **

fix: webhook triggers

---

packages/noco-docs/content/en/engineering/timely-build.md
packages/noco-docs/content/en/getting-started/installation.md

- add documentation for timely build (ref: #2447)

docs: timely build

---

packages/nc-gui/components/ProjectTabs.vue
packages/nc-gui/components/import/JSONImport.vue
packages/nc-gui/components/import/templateParsers/CSVTemplateAdapter.js
packages/nc-gui/components/import/templateParsers/JSONTemplateAdapter.js
packages/nc-gui/components/import/templateParsers/JSONUrlTemplateAdapter.js
packages/nc-gui/components/import/templateParsers/parserHelpers.js
packages/nc-gui/components/monaco/MonacoJsonEditor.js
packages/nocodb-sdk/src/index.ts
packages/nocodb-sdk/src/lib/TemplateGenerator.ts

Import data and table from a JSON array or object.
https://user-images.githubusercontent.com/61551451/174236263-d5f47682-6666-465a-b463-548f3d3856f8.mov

Feat: JSON import

---

packages/nocodb/src/__tests__/restv2.test.ts
packages/nocodb/src/lib/meta/api/columnApis.ts
packages/nocodb/src/lib/meta/api/metaDiffApis.ts
packages/nocodb/src/lib/meta/api/projectApis.ts
scripts/cypress/integration/common/1a_table_operations.js
scripts/cypress/integration/common/1c_sql_view.js
scripts/cypress/integration/common/1d_pg_table_view_drag_drop_reorder.js
scripts/cypress/integration/common/1d_table_view_drag_drop_reorder.js
scripts/cypress/integration/common/2a_table_with_belongs_to_colulmn.js
scripts/cypress/integration/common/2b_table_with_m2m_column.js
scripts/cypress/integration/common/4c_form_view_detailed.js
scripts/cypress/integration/common/4d_table_view_grid_locked.js
scripts/cypress/integration/common/4e_form_view_share.js
scripts/cypress/integration/common/4f_grid_view_share.js
scripts/cypress/integration/common/4f_pg_grid_view_share.js
scripts/cypress/integration/common/5a_user_role.js
scripts/cypress/integration/common/6b_downloadCsv.js
scripts/cypress/integration/common/6f_attachments.js
scripts/cypress/integration/spec/roleValidation.spec.js

- Add suffix `List` instead of `MMList` for many to many columns
- Use proper child table name while creating the column
- Cypress test case corrections
Other column name change
- `TableMMList` => `Table List` (MM)
- `TableList` => `Table List` (HM)
- `TableRead` => `Table` (BT)
re #2429

fix: LTAR column naming

---

.github/workflows/ci-cd.yml
scripts/cypress/cypress.json
scripts/cypress/integration/common/7b_import_from_airtable.js
scripts/cypress/integration/common/9a_QuickTest.js
scripts/cypress/integration/test/quickTest.js

Unified approach for Quick tests & AT import verification
CI/CD

test: import verification tests

---

packages/nc-gui/pages/project/edit.vue
packages/nc-gui/pages/projects/index.vue
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/lib/meta/api/projectApis.ts
scripts/sdk/swagger.json

- add project update api
- add a new edit page for users to edit project (currently only support project naming - ref: https://github.com/nocodb/nocodb/issues/1885)
- remove some unused code in `project/index.vue`
Go to Project Listing Page - Hover a project - Click Edit Project
Currently, only project renaming is supported.

enhancement: edit project

---

packages/nc-gui/components/project/spreadsheet/components/virtualCell/components/ItemChip.vue

Re #2538
Allow to remove link if user allowed to edit table

fix: permission to remove link

---

packages/nc-gui-v2/app.vue
packages/nc-gui-v2/components/dashboard/TabView.vue
packages/nc-gui-v2/components/dashboard/TreeView.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/composables/metas.ts
packages/nc-gui-v2/composables/user.ts
packages/nc-gui-v2/layouts/default.vue
packages/nc-gui-v2/nuxt.config.ts
packages/nc-gui-v2/package.json
packages/nc-gui-v2/pages/projects/create.vue
packages/nc-gui-v2/pages/projects/index.vue
packages/nc-gui-v2/plugins/api.ts
packages/nc-gui-v2/plugins/tele.ts

feat(gui-v2): nuxt 3 migration

---

packages/nc-gui/components/ProjectTabs.vue
packages/nc-gui/helpers/rolePermissionsEE.js
scripts/cypress/support/page_objects/projectConstants.js

- Allow all roles to view Themes
ref: #2539

fix: add missing settings permissions

---

packages/nc-gui/components/project/spreadsheet/components/ColumnFilter.vue
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/conditionV2.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/helpers/sanitize.ts

ref: #2516 
- check if input is string in sanitize / unsanitize
- revise ColumnFilter logic
- bt: `is null` & `is not null`
- hm / mm: `is empty` & `is not empty`
- lookup: disable `is null`, `is not null`, `is empty` & `is not empty`
- revise bt & hm condition logic
- revise operation & filter value display logic
Sheet 1: hm
Sheet 2: bt
Sheet 3 : mm
Sheet 4: mm
1. Choose the field first
2. Render corresponding operations
3. Render filter value if applicable

fix: filters / conditions

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/conditionV2.ts

Re #2517 #2523
Cast text type for like condition on postgres (similar to old customKnex)

fix: pg cast type for like condition

---

packages/nc-gui/components/project/spreadsheet/components/EditColumn.vue
packages/nc-gui/components/project/spreadsheet/components/EditableCell.vue
packages/nc-gui/components/project/spreadsheet/components/editColumn/DateOptions.vue
packages/nc-gui/components/project/spreadsheet/components/editableCell/DatePickerCell.vue
packages/nc-gui/helpers/dateFormatHelper.js

- packages/nc-gui/components/project/spreadsheet/components/EditColumn.vue
- packages/nc-gui/components/project/spreadsheet/components/EditableCell.vue
- packages/nc-gui/components/project/spreadsheet/components/editColumn/DateOptions.vue (new)
- packages/nc-gui/components/project/spreadsheet/components/editableCell/DatePickerCell.vue
- packages/nc-gui/helpers/dateFormatHelper.js (new)
https://user-images.githubusercontent.com/24416449/174604861-9f945b25-6def-4d06-8f87-36c0f93a377f.mp4
CC @wingkwong @pranavxc

Add date format option to DatePickerCell

---

packages/nocodb/src/lib/meta/api/userApi/userApis.ts

Re #2563
Dropped token_version check for password reset as it results in unwanted behavior / not really needed

fix: drop token_version check for password reset

---

packages/nc-gui/components/ProjectTreeView.vue
packages/nc-gui/components/project/Table.vue
packages/nc-gui/helpers/rightClickOptions.js

ref: #826 
- enable delete table on right click
- enable delte table on options
- add toast message after successful deletion

enhancement: delete table on tree view

---

packages/nc-gui/components/project/spreadsheet/components/editableCell/EditableAttachmentCell.vue
packages/nc-gui/components/project/spreadsheet/components/virtualCell/LookupCell.vue

Fixed Lookup cell image handling.
Earlier all the UI elements including images were pushed into VChip(pill). Now attachments are being handled seperatly.
Ref: [#2392](https://github.com/nocodb/nocodb/issues/2392)
UI:

fix: Fixed Lookup cell image handling

---

packages/nc-gui-v2/components/general/Language.vue
packages/nc-gui-v2/layouts/default.vue
packages/nc-gui-v2/nuxt.config.ts
packages/nc-gui-v2/package-lock.json
packages/nc-gui-v2/package.json
packages/nc-gui-v2/tsconfig.json

Add `unplugin-icons` to deps-dev.

feat(gui-v2,deps): add unplugin-icons

---

packages/nc-gui/components/project/spreadsheet/public/XcForm.vue

Removed Lookup, Rollup and Formula columns showing up in form
Ref: #2550 
Lookup field is correctly now not shown in form view.

Fix/2550 Removed Lookup, Rollup and Formula columns showing up in form

---

packages/nc-gui/components/project/spreadsheet/components/EditColumn.vue
packages/nc-gui/components/project/spreadsheet/components/ExpandedForm.vue
packages/nc-gui/components/project/spreadsheet/components/editColumn/DurationOptions.vue
packages/nc-gui/components/project/spreadsheet/components/editColumn/RatingOptions.vue

- Fixed dark mode styling bug with edit column.
- Fixed styling issues with toggle comments button.
- Fixed dark mode styling in RatingOptions and DuractionOptions.
Ref: [#1516 ](https://github.com/nocodb/nocodb/issues/1516)
Contrast issue left for now for v2.

Fixed dark mode styling bug with edit column and styling issues with toggle comments button

---

packages/nocodb/src/lib/version-upgrader/ncProjectUpgraderV2_0090000.ts

Skip meta migration if the associated project doesn't exist
re #2449

fix: skip meta migration if associated project doesn't exist

---

packages/nc-gui-v2/app.vue
packages/nc-gui-v2/assets/style-v2.css
packages/nc-gui-v2/assets/style.css
packages/nc-gui-v2/components/general/Sponsors.vue
packages/nc-gui-v2/layouts/default.vue
packages/nc-gui-v2/nuxt.config.ts
packages/nc-gui-v2/package-lock.json
packages/nc-gui-v2/package.json
packages/nc-gui-v2/windi.config.ts

* transition on page/layout change
* move v2 styles to separate file
* refactor layouts
Signed-off-by: Braks <78412429+bcakmakoglu@users.noreply.github.com>

feat(gui-v2): add page transitions

---

packages/nc-gui-v2/app.vue
packages/nc-gui-v2/composables/useGlobalState.ts
packages/nc-gui-v2/lib/types.ts
packages/nc-gui-v2/middleware/auth.global.ts
packages/nc-gui-v2/pages/signin.vue

Add signin action to global state.

feat(gui-v2): add signIn action to global state

---

packages/nc-gui-v2/components/cell/Attachment.vue
packages/nc-gui-v2/components/cell/Checkbox.vue
packages/nc-gui-v2/components/cell/DatePicker.vue
packages/nc-gui-v2/components/cell/DateTimePicker.vue
packages/nc-gui-v2/components/cell/Email.vue
packages/nc-gui-v2/components/cell/Float.vue
packages/nc-gui-v2/components/cell/Integer.vue
packages/nc-gui-v2/components/cell/MultiSelect.vue
packages/nc-gui-v2/components/cell/Rating.vue
packages/nc-gui-v2/components/cell/SingleSelect.vue
packages/nc-gui-v2/components/cell/Text.vue
packages/nc-gui-v2/components/cell/TextArea.vue
packages/nc-gui-v2/components/cell/Url.vue
packages/nc-gui-v2/components/smartsheet/Cell.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/components/smartsheet/Pagination.vue
packages/nc-gui-v2/components/smartsheet/VirtualCell.vue
packages/nc-gui-v2/components/tabs/Smartsheet.vue
packages/nc-gui-v2/components/virtual-cell/Formula.vue
packages/nc-gui-v2/components/virtual-cell/HasMany.vue
packages/nc-gui-v2/components/virtual-cell/components/ItemChip.vue

Some code style and type fixes.

chore(gui-v2): type and code-style fixes

---

packages/nc-gui-v2/app.vue
packages/nc-gui-v2/components/general/Language.vue
packages/nc-gui-v2/composables/useGlobalState.ts
packages/nc-gui-v2/lib/enums.ts
packages/nc-gui-v2/lib/types.ts
packages/nc-gui-v2/middleware/auth.global.ts
packages/nc-gui-v2/package-lock.json
packages/nc-gui-v2/package.json
packages/nc-gui-v2/pages/signin.vue
packages/nc-gui-v2/plugins/api.ts

Check jwt expiry when verifiying if signed in.

feat(gui-v2,deps): use jwt expiry to check if user is still signed in

---

packages/nc-gui-v2/composables/useGlobalState.ts
packages/nc-gui-v2/nuxt-shim.d.ts
packages/nc-gui-v2/plugins/i18n.ts
packages/nc-gui-v2/plugins/state.ts

Signed-off-by: Braks <78412429+bcakmakoglu@users.noreply.github.com>## Change Summary

fix(gui-v2): detect browser language & match against locale

---

packages/nc-gui-v2/components/general/Language.vue
packages/nc-gui-v2/pages/projects/index.vue
packages/nc-gui-v2/pages/projects/index/index.vue
packages/nc-gui-v2/pages/projects/index/list.vue

Signed-off-by: Braks <78412429+bcakmakoglu@users.noreply.github.com>## Change Summary

feat(gui-v2): add list view

---

packages/nc-gui-v2/app.vue
packages/nc-gui-v2/assets/style-v2.css
packages/nc-gui-v2/components/general/ColorModeSwitcher.vue
packages/nc-gui-v2/components/general/Sponsors.vue
packages/nc-gui-v2/composables/useColors.ts
packages/nc-gui-v2/composables/useGlobalState.ts
packages/nc-gui-v2/pages/projects/index.vue
packages/nc-gui-v2/pages/projects/index/list.vue
packages/nc-gui-v2/plugins/state.ts

Signed-off-by: Braks <78412429+bcakmakoglu@users.noreply.github.com>
Add dark mode switcher and some basic dark mode styles.

feat(gui-v2): add dark mode to state and some styles

---

packages/nc-gui-v2/app.vue
packages/nc-gui-v2/composables/useGlobalState.ts
packages/nc-gui-v2/lib/types.ts
packages/nc-gui-v2/pages/projects/index.vue
packages/nc-gui-v2/pages/projects/index/index.vue

Signed-off-by: Braks <78412429+bcakmakoglu@users.noreply.github.com>
Add sidebar switcher to app header and sidebar state to global state.

feat(gui-v2): add sidebar switcher to header

---

packages/nocodb/src/lib/meta/helpers/PagedResponse.ts

Re #2647
Fixed false logic for assigning null as @wingkwong suggested

fix: use nullish coalescing instead of OR on PagedResponseImpl

---

packages/nc-gui-v2/components/general/Sponsors.test.ts
packages/nc-gui-v2/package-lock.json
packages/nc-gui-v2/package.json
packages/nc-gui-v2/plugins/i18n.ts
packages/nc-gui-v2/plugins/vuetify.ts
packages/nc-gui-v2/test/vite.config.ts
packages/nc-gui-v2/test/vuetify.config.js

feat(gui-v2,testing): add vitest and a simple component test

---

packages/nc-gui-v2/components/cell/Duration.vue
packages/nc-gui-v2/components/smartsheet/Cell.vue
packages/nc-gui-v2/utils/durationHelper.ts
packages/nc-gui/helpers/viewIcons.js

- Rendering from second to corresponding format based on durationType
- Converting to second when saving

feat(gui-v2): duration cell

---

packages/nc-gui-v2/components/cell/Url.vue
packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
packages/nc-gui-v2/components/smartsheet/Cell.vue
packages/nc-gui-v2/utils/urlUtils.ts

- include url cell & revise url cell
- add icon for url cell
- add isValidURL to urlUtils
- reorder `<CellText/>` so that it won't be rendered as `<CellText/>` instead of `<CellUrl/>`

feat(gui-v2): url cell

---

packages/nc-gui/components/project/spreadsheet/components/SortListMenu.vue
packages/noco-docs/content/en/setup-and-usages/column-operations.md
scripts/cypress/integration/common/1c_sql_view.js
scripts/cypress/integration/common/1e_meta_sync.js
scripts/cypress/integration/common/1e_pg_meta_sync.js
scripts/cypress/integration/common/3a_filter_sort_fields_operations.js
scripts/cypress/integration/common/4f_grid_view_share.js
scripts/cypress/integration/common/4f_pg_grid_view_share.js
scripts/cypress/integration/common/9a_QuickTest.js

- Update sort menu option text based on the types - ref: #2683. 
Four types will be introduced.
- Text field (A -> Z) / (Z -> A)
- Numerical (1 -> 9) / (9 -> 1)
- Date & Time (1 -> 9) / (9 -> 1)
- Checkbox  (▢ → ✓)  / (✓ → ▢)
- ~~Single and Multiple select (First -> Last) / (Last -> First)~~ (on hold - need reorder of the options)

enhancement: sort menu

---

packages/nc-gui/components/ReleaseInfo.vue
packages/nc-gui/plugins/projectLoader.js
packages/nc-gui/store/app.js
packages/nocodb/src/lib/meta/api/utilApis.ts

- Append current package version into version api
- Drop extra api call
- Refactor variable names
- fix: Show latest release version on release alert

refactor: version api

---

packages/nc-gui/components/project/spreadsheet/components/ColumnFilter.vue
packages/nocodb/src/lib/models/Filter.ts

Grouped filter creation bug fix in manual sync mode.
https://user-images.githubusercontent.com/61551451/179342223-3954dc32-81cb-4da7-881f-78e61a6eb8d9.mov

fix: handle nested group save in filter manual sync

---

packages/nc-gui-v2/composables/useGlobalState.ts
packages/nc-gui-v2/pages/signin.vue
packages/nc-gui-v2/pages/signup.vue

Signed-off-by: Braks <78412429+bcakmakoglu@users.noreply.github.com>
Sign up form.

feat(gui-v2): update signup form

---

scripts/markdown/readme/languages/chinese.md

If you don't build it first, the local operation fails

docs: Update chinese.md

---

packages/nc-gui-v2/components/dashboard/TreeView.vue

Feat/project tree - add settings modal

---

packages/nc-gui-v2/app.vue
packages/nc-gui-v2/pages/index/index.vue

fix(gui-v2): sidebar showing when collapsed

---

packages/nc-gui/components/project/auditTab/Audit.vue

fix: [ui] Scrolling in the tables

---

packages/nc-gui-v2/nuxt.config.ts
packages/nc-gui-v2/package-lock.json
packages/nc-gui-v2/package.json

Update primary color in ant-design

chore(gui-v2): update theme primary color

---

packages/nc-gui-v2/app.vue
packages/nc-gui-v2/assets/style-v2.scss
packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/general/NocoIcon.vue
packages/nc-gui-v2/composables/useGlobalState.ts
packages/nc-gui-v2/package-lock.json
packages/nc-gui-v2/package.json
packages/nc-gui-v2/pages/forgot-password.vue
packages/nc-gui-v2/pages/index/index.vue
packages/nc-gui-v2/pages/index/user/index.vue
packages/nc-gui-v2/pages/index/user/index/index.vue
packages/nc-gui-v2/pages/signin.vue
packages/nc-gui-v2/pages/signup.vue

refactor(gui-v2): replace vuetify form with ant form

---

packages/nc-gui-v2/pages/index/index.vue
packages/nc-gui-v2/pages/index/index/index.vue
packages/nc-gui-v2/pages/index/index/list.vue
packages/nc-gui-v2/pages/index/user/index.vue
packages/nc-gui-v2/pages/index/user/index/index.vue

chore(gui-v2): cleanup user settings page 

---

packages/nc-gui-v2/app.vue
packages/nc-gui-v2/composables/useGlobalState.ts

* remove color mode toggle from header
* set preferred color scheme to light

refactor(gui-v2): disable dark mode

---

packages/nc-gui-v2/components/dashboard/TabView.vue
packages/nc-gui-v2/components/tabs/Auth.vue
packages/nc-gui-v2/composables/useTabs.ts
packages/nc-gui-v2/pages/nc/[projectId].vue

feat(gui-v2): load team and auth tab

---

packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/dashboard/settings/AuditTab.vue
packages/nc-gui-v2/utils/dateTimeUtils.ts

* load project before loading audits
* properly align pagination
* move reload button to pagination
* wrap elements
* prevent warnings of ant design by using functions as children
* add icon to reload

refactor(gui-v2): cleanup audit tab issues and styles

---

packages/nc-gui-v2/components/dashboard/settings/AppStore/AppInstall.vue

* add action enum to `AppInstall.vue`
* remove vuetify styles like `d-flex` and use windicss instead
* cleanup types

refactor(gui-v2): use enum for actions in AppInstall

---

packages/nc-gui-v2/composables/useProject.ts

refactor(gui-v2): accept projectId as arg in `useProject`

---

packages/nc-gui-v2/lib/enums.ts
packages/nc-gui-v2/lib/types.ts
packages/nc-gui-v2/pages/index/index.vue
packages/nc-gui-v2/pages/project/index/create-external.vue
packages/nc-gui-v2/pages/signin.vue
packages/nc-gui-v2/pages/signup.vue
packages/nc-gui-v2/utils/projectCreateUtils.ts

* move form type to utils file
* move ClientType enum to enums file
* use ClientType enum where appropriate
* add default host (localhost)
* lint files

refactor(gui-v2): cleanup project create utils

---

packages/nc-gui-v2/components/cell/Duration.vue
packages/nc-gui-v2/components/cell/JsonEditableCell.vue
packages/nc-gui-v2/components/cell/Time.vue
packages/nc-gui-v2/components/dlg/TableCreate.vue
packages/nc-gui-v2/components/smartsheet-header/VirtualCellIcon.vue
packages/nc-gui-v2/components/smartsheet-toolbar/LockMenu.vue
packages/nc-gui-v2/components/smartsheet-toolbar/MoreActions.vue
packages/nc-gui-v2/components/smartsheet-toolbar/SortListMenu.vue
packages/nc-gui-v2/components/virtual-cell/components/ListChildItems.vue
packages/nc-gui-v2/components/virtual-cell/components/ListChildItemsModal.vue
packages/nc-gui-v2/components/virtual-cell/components/ListItems.vue
packages/nc-gui-v2/composables/useViewCreate.ts
packages/nc-gui-v2/plugins/i18n.ts

* transform some components to script setup
* fix linting issues

chore(gui-v2): fix eslint issues

---

packages/nc-gui-v2/app.vue
packages/nc-gui-v2/components/general/Language.vue
packages/nc-gui-v2/pages/signin.vue
packages/nc-gui-v2/pages/signup.vue

Additional UI markers (ID / class names) required for Cypress tests
WIP

refactor: cypress markers

---

packages/nc-gui-v2/components/dashboard/TreeView.vue
packages/nc-gui-v2/composables/useGlobalState.ts

* force disable dark mode on app init
* properly align search icon in tree view (misaligned by half a px to the bottom)

fix(gui-v2): force disable dark mode

---

packages/nc-gui-v2/components/dashboard/TabView.vue
packages/nc-gui-v2/components/dashboard/TreeView.vue
packages/nc-gui-v2/components/dashboard/settings/AppStore.vue

test: cypress markers for tab & tree view; vue-3 related
Test suite update in progress

test: cypress markers for tab & tree view

---

packages/nc-gui-v2/components/dashboard/TreeView.vue
packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilterMenu.vue
packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
packages/nc-gui-v2/components/smartsheet-toolbar/SortListMenu.vue

cypress markers on spreadsheet tab
Verified locally with nc-gui-v2

test: cypress markers on spreadsheet tab

---

packages/nc-gui-v2/components/dashboard/settings/Metadata.vue
packages/nc-gui-v2/components/dashboard/settings/SettingsModal.vue
packages/nc-gui-v2/components/dashboard/settings/UIAcl.vue

feat(gui-v2): Project metadata

---

packages/nc-gui-v2/components/dlg/AirtableImport.vue
packages/nc-gui-v2/components/dlg/QuickImport.vue
packages/nc-gui-v2/components/dlg/TableCreate.vue

- menu resize for quick import options
verified locally

chore: menu resize

---

packages/nc-gui-v2/components/cell/Email.vue
packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
packages/nc-gui-v2/components/smartsheet/Cell.vue

- Include EmailCell in Cell
- Add Email Icon
- Email Cell Rendering

feat(gui-v2): Email Cell

---

packages/nc-gui-v2/components/cell/Currency.vue
packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
packages/nc-gui-v2/components/smartsheet/Cell.vue

ref: #2887
- Include CurrencyCell in Cell
- Add Currency Icon
- Currency Cell Rendering

feat(gui-v2): Currency Cell

---

packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/cell/YearPicker.vue
packages/nc-gui-v2/components/smartsheet/Cell.vue
packages/nc-gui-v2/composables/useColumn.ts
packages/nc-gui-v2/utils/dateTimeUtils.ts

refactor(gui-v2): Added YearPicker

---

packages/nc-gui-v2/components/cell/DateTimePicker.vue
packages/nc-gui-v2/utils/dateTimeUtils.ts

refactor(gui-v2): Added DateTime Picker

---

packages/nc-gui-v2/components/virtual-cell/Formula.vue
packages/nc-gui-v2/utils/dateTimeUtils.ts

ref: #2897
- Apply windicss
- Integrate with antdv
Sakila > City : `((ADD({CityId}, {CountryId}) + AVG({CityId}, {CountryId})) + LEN({City}))`

feat(gui-v2): Formula Cell

---

packages/nc-gui/components/project/spreadsheet/components/editColumn/FormulaOptions.vue

ref: #2929
Formula: `ADD({Currency}, 20)`

enhancement: support currency in formula

---

packages/nc-gui-v2/plugins/a.dayjs.ts
packages/nc-gui-v2/utils/dateTimeUtils.ts

* add dayjs plugin file so we can make sure all dayjs plugins are installed on app init

feat(gui-v2): add `dayjs` plugin file

---

packages/nc-gui-v2/plugins/a.dayjs.ts

chore(gui-v2): add plugin export from dayjs plugin file

---

packages/nc-gui-v2/components/smartsheet/sidebar/MenuBottom.vue
packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue

chore(gui-v2): update menu styles to fill height properly

---

packages/nc-gui-v2/composables/useInjectionState/index.ts

feat(gui-v2): accept keyname as arg for useInjectionState

---

packages/nc-gui-v2/components/cell/Float.vue
packages/nc-gui-v2/components/cell/Integer.vue
packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
packages/nc-gui-v2/components/smartsheet/Cell.vue

ref: #2913 
- include integer & float cells
- add icon for above cells

feat(gui-v2): number cell

---

packages/nc-gui-v2/components/cell/PhoneNumber.vue
packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
packages/nc-gui-v2/components/smartsheet/Cell.vue
packages/nc-gui-v2/composables/useColumn.ts

Ref: #2922 
This is just for the time being, a `Text` cell as it is in `nc-gui` v1.
UI:

vue3: Added phone number cell

---

packages/nc-gui-v2/components/virtual-cell/Rollup.vue

vue3: Added rollup cell

---

packages/nc-gui-v2/components/cell/Checkbox.vue

Ref: #2875 
Added checkbox cell
UI:

vue3: Added checkbox cell

---

packages/nc-gui-v2/components/cell/Text.vue

ref: #2957 
- add `watch` to focus
- apply windicss classes
- apply vModel

feat(gui-v2): SingleLineText Cell

---

packages/nc-gui-v2/components/cell/TextArea.vue

ref: #2958 
- apply vModel
- apply windicss
- add `watch` to focus

feat(gui-v2): LongText Cell

---

packages/nc-gui-v2/composables/useInjectionState/index.ts

The return type of provider should be the same as inject.

fix(gui-v2): return type correction of provider

---

packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
packages/nc-gui-v2/utils/columnUtils.ts

Ref: #2980 #2967 
Improved `Email`, `Json`, `Phonenumber`, `Url`, `Year` and `Time` column.
Added some missing icons and added `validation` option to `email`, `phonenumber` and `url` column.
UI:
email:
json:
phonenumber:
url:
Year:
Time:

vue3: Improved email, json, phonenumber, url, year, time column

---

packages/nocodb/src/lib/meta/api/sync/helpers/job.ts

lookup configuration, skip if lookup to an ignored column during import (formula/rollup for example)
- added additional check
tested on the development platform with credentials shared by the user
-

fix: nested lookup import failure

---

packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
packages/nc-gui-v2/components/smartsheet-header/Cell.vue
packages/nc-gui-v2/components/smartsheet-header/Menu.vue
packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue
packages/nc-gui-v2/components/smartsheet/Cell.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/composables/useGridViewColumnWidth.ts
packages/nc-gui-v2/composables/useViewData.ts

- Keyboard navigations
- Context menu
re #2911  #2962

feat(gui-v2): Grid operations

---

packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
packages/nc-gui-v2/components/smartsheet/Cell.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/composables/useColumnCreateStore.ts

EditEnabled value should be injected from the cell component to switch between editable state.

fix: Provide edit-enabled in cell level

---

packages/nc-gui-v2/components/cell/Text.vue
packages/nc-gui-v2/components/cell/TextArea.vue
packages/nc-gui-v2/components/smartsheet/Cell.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/components/smartsheet/VirtualCell.vue
packages/nc-gui-v2/components/tabs/Smartsheet.vue
packages/nc-gui-v2/composables/useColumnCreateStore.ts
packages/nc-gui-v2/composables/useViewColumns.ts
packages/nc-gui-v2/context/index.ts
packages/nc-gui-v2/lib/enums.ts

- Cell active outline correction
- Enter key-based navigation
- Option to toggle edit enabled

fix: grid view corrections

---

packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
packages/nc-gui-v2/components/smartsheet-column/LookupOptions.vue

vue3: Added lookup column

---

packages/nc-gui-v2/components/smartsheet/VirtualCell.vue
packages/nc-gui-v2/components/virtual-cell/BelongsTo.vue
packages/nc-gui-v2/components/virtual-cell/Formula.vue
packages/nc-gui-v2/components/virtual-cell/HasMany.vue
packages/nc-gui-v2/components/virtual-cell/Lookup.vue
packages/nc-gui-v2/components/virtual-cell/ManyToMany.vue
packages/nc-gui-v2/components/virtual-cell/Rollup.vue

vue3: Add lookup cell

---

packages/nc-gui-v2/components/smartsheet-column/DateOptions.vue
packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
packages/nc-gui-v2/utils/dateTimeUtils.ts

vue3: Added Date column

---

packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
packages/nc-gui-v2/components/smartsheet-column/RollupOptions.vue
packages/nc-gui-v2/composables/useColumnCreateStore.ts

vue3: Added rollup column

---

packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
packages/nc-gui-v2/components/smartsheet-column/LinkedToAnotherRecordOptions.vue

Ref: #3001 
Ignore the duplicate `show more`. Will be solved when this [PR](https://github.com/nocodb/nocodb/pull/2988) is merged.
UI:

vue3: Added LTAR column

---

packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
packages/nc-gui-v2/components/smartsheet-column/SpecificDBTypeOptions.vue
packages/nc-gui-v2/utils/columnUtils.ts

vue3: Added SpecificDBType column

---

packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
packages/nc-gui-v2/components/smartsheet-column/PercentOptions.vue

vue3: Added Percent column

---

packages/nc-gui-v2/assets/style-v2.scss

chore(gui-v2): apply theme scrollbar on ant modal

---

packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilterMenu.vue
packages/nc-gui-v2/composables/useGlobal/state.ts
packages/nc-gui-v2/composables/useGlobal/types.ts

fix: gui-v2 - sync filter auto save prop with localstorage

---

packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilterMenu.vue
packages/nc-gui-v2/composables/useViewData.ts

- Highlight the filter button if at least one filter exists
- Sync rows count on row insert/delete
re #2938

fix(gui-v2): filter and row count

---

packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/components/smartsheet/Row.vue
packages/nc-gui-v2/components/smartsheet/expanded-form/index.vue
packages/nc-gui-v2/components/virtual-cell/HasMany.vue
packages/nc-gui-v2/composables/useExpandedFormStore.ts
packages/nc-gui-v2/composables/useSmartsheetRowStore.ts

feat: guiv2 - Add store to keep row level state

---

packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/smartsheet-header/Cell.vue
packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue
packages/nc-gui-v2/components/smartsheet/Gallery.vue
packages/nc-gui-v2/composables/useViewData.ts

Ref: #2631 
Issues:
Known Scrolling has an offset 
UI:

vue3: Added gallery view

---

packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/cell/attachment/index.vue
packages/nc-gui-v2/components/smartsheet/Cell.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/layouts/base.vue

chore(gui-v2): fix dropzone ref

---

packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/cell/MultiSelect.vue
packages/nc-gui-v2/components/cell/SingleSelect.vue
packages/nc-gui-v2/components/general/ColorPicker.vue
packages/nc-gui-v2/components/smartsheet-column/CheckboxOptions.vue
packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
packages/nc-gui-v2/components/smartsheet-column/RatingOptions.vue
packages/nc-gui-v2/components/smartsheet-column/SelectOptions.vue
packages/nc-gui-v2/components/smartsheet-header/Menu.vue
packages/nc-gui-v2/components/smartsheet/Cell.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nocodb-sdk/src/lib/Api.ts
scripts/sdk/swagger.json

Re #2969 #2968
- Select options
- Single select cell
- Multi select cell

feat(gui-v2): Single/multi select

---

packages/nc-gui-v2/components/cell/attachment/index.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/composables/useSmartsheetStore.ts

* fix dropzone not activating
* fix overflow showing when unnecessary

chore(gui-v2): attachment cell fixes

---

packages/nc-gui-v2/components/tabs/auth/UserManagement.vue
packages/nc-gui-v2/components/tabs/auth/user-management/ShareBase.vue
packages/nc-gui-v2/components/tabs/auth/user-management/UsersModal.vue
packages/nc-gui-v2/composables/useUIPermission/rolePermissions.ts
packages/nc-gui-v2/lang/en.json
packages/nc-gui-v2/lib/enums.ts
packages/nc-gui-v2/utils/urlUtils.ts
packages/nc-gui-v2/utils/userUtils.ts

Ref: [Comment](https://github.com/nocodb/nocodb/issues/2825#issuecomment-1210200214)
- Fixed wrong roles
- Now roles pill shows color
- Added `isUIAllowed` to hide `Invite team` button when the user is not privileged.

vue3: Follow up on User management

---

packages/nc-gui-v2/components/dlg/ViewCreate.vue
packages/nc-gui-v2/components/smartsheet/Form.vue
packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
packages/nc-gui-v2/components/smartsheet/sidebar/RenameableMenuItem.vue
packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
packages/nc-gui-v2/composables/useViewData.ts

- put required label out of switcher
- add drag icon
- right nav bar: copy form view
- right nav bar: push the created view to router
- right nav bar: return to default view once the view is deleted

fix(gui-v2): form view follow-up issues

---

packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue

fix(gui-v2): call generateNewColumnMeta only once

---

packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/PreviewAs.vue
packages/nc-gui-v2/components/general/PreviewAs.vue
packages/nc-gui-v2/composables/useApi/interceptors.ts
packages/nc-gui-v2/composables/useGlobal/state.ts
packages/nc-gui-v2/composables/useGlobal/types.ts
packages/nc-gui-v2/composables/useUIPermission/index.ts
packages/nc-gui-v2/pages/nc/[projectId]/index.vue

vue3: Add preview as option

---

packages/nc-gui-v2/pages/nc/[projectId]/index.vue

* close menu on esc click
* add id as prefix 

feat(gui-v2): close dropdown menu on esc keydown

---

packages/nc-gui-v2/components/dashboard/settings/Metadata.vue
packages/nc-gui-v2/components/dashboard/settings/Modal.vue
packages/nc-gui-v2/components/dashboard/settings/UIAcl.vue

settings modal scroll overflow instead of extending

feat(gui-v2): settings modal overflow

---

packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/composables/useViewData.ts

refactor: remove group class from tr 

---

packages/nc-gui-v2/components/cell/TimePicker.vue

fix(gui-v2): close timepicker on outside click

---

packages/nocodb/src/lib/meta/api/projectApis.ts

fix(gui-v2): check if project title is being in use when renaming 

---

packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/dashboard/TreeView.vue
packages/nc-gui-v2/components/dashboard/settings/AppStore.vue
packages/nc-gui-v2/components/smartsheet-column/AdvancedOptions.vue
packages/nc-gui-v2/components/smartsheet-column/CheckboxOptions.vue
packages/nc-gui-v2/components/smartsheet-column/CurrencyOptions.vue
packages/nc-gui-v2/components/smartsheet-column/DateOptions.vue
packages/nc-gui-v2/components/smartsheet-column/DurationOptions.vue
packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
packages/nc-gui-v2/components/smartsheet-column/LinkedToAnotherRecordOptions.vue
packages/nc-gui-v2/components/smartsheet-column/LookupOptions.vue
packages/nc-gui-v2/components/smartsheet-column/PercentOptions.vue
packages/nc-gui-v2/components/smartsheet-column/RatingOptions.vue
packages/nc-gui-v2/components/smartsheet-column/RollupOptions.vue
packages/nc-gui-v2/components/smartsheet-column/SpecificDBTypeOptions.vue
packages/nc-gui-v2/components/smartsheet-header/Cell.vue
packages/nc-gui-v2/components/smartsheet-header/Menu.vue
packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/components/smartsheet/Toolbar.vue
packages/nc-gui-v2/components/tabs/Auth.vue
packages/nc-gui-v2/components/tabs/auth/ApiTokenManagement.vue
packages/nc-gui-v2/components/tabs/auth/UserManagement.vue
packages/nc-gui-v2/layouts/base.vue
packages/nc-gui-v2/pages/nc/[projectId]/index.vue
packages/nc-gui-v2/pages/nc/[projectId]/index/index.vue

refactor: gui v2 column header UI and nocodb logo

---

packages/nc-gui-v2/components/cell/MultiSelect.vue
packages/nc-gui-v2/components/cell/SingleSelect.vue
packages/nc-gui-v2/components/smartsheet-header/Menu.vue
packages/nocodb/src/lib/meta/api/columnApis.ts

- Fix empty option handling for multiselect
- Use column_name instead of title for queries
- Hide arrow from single select if a value already selected
- Multiselect cell overflow

fix(gui-v2): select improvements

---

packages/nc-gui-v2/components/smartsheet/Form.vue

fix(gui-v2): form layout

---

packages/nc-gui-v2/components/smartsheet-column/AdvancedOptions.vue
packages/nc-gui-v2/components/smartsheet-column/CheckboxOptions.vue
packages/nc-gui-v2/components/smartsheet-column/CurrencyOptions.vue
packages/nc-gui-v2/components/smartsheet-column/DateOptions.vue
packages/nc-gui-v2/components/smartsheet-column/DurationOptions.vue
packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
packages/nc-gui-v2/components/smartsheet-column/EditOrAddProvider.vue
packages/nc-gui-v2/components/smartsheet-column/FormulaOptions.vue
packages/nc-gui-v2/components/smartsheet-column/LinkedToAnotherRecordOptions.vue
packages/nc-gui-v2/components/smartsheet-column/LookupOptions.vue
packages/nc-gui-v2/components/smartsheet-column/PercentOptions.vue
packages/nc-gui-v2/components/smartsheet-column/RatingOptions.vue
packages/nc-gui-v2/components/smartsheet-column/RollupOptions.vue
packages/nc-gui-v2/components/smartsheet-column/SelectOptions.vue
packages/nc-gui-v2/components/smartsheet-column/SpecificDBTypeOptions.vue
packages/nc-gui-v2/components/smartsheet-header/Cell.vue
packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue
packages/nc-gui-v2/components/smartsheet/Form.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/composables/useColumn.ts
packages/nc-gui-v2/composables/useColumnCreateStore.ts
packages/nc-gui-v2/package.json

- Use local state for column options
- editOrAddProvider -> this way no unnecessary injections
- useColumn -> use computedRefs instead to make changes on column live

fix(gui-v2): column edit/add handling

---

packages/nc-gui-v2/components/cell/Currency.vue
packages/nc-gui-v2/components/cell/DatePicker.vue
packages/nc-gui-v2/components/cell/DateTimePicker.vue
packages/nc-gui-v2/components/cell/Decimal.vue
packages/nc-gui-v2/components/cell/Duration.vue
packages/nc-gui-v2/components/cell/Email.vue
packages/nc-gui-v2/components/cell/Float.vue
packages/nc-gui-v2/components/cell/Integer.vue
packages/nc-gui-v2/components/cell/Json.vue
packages/nc-gui-v2/components/cell/MultiSelect.vue
packages/nc-gui-v2/components/cell/Percent.vue
packages/nc-gui-v2/components/cell/Rating.vue
packages/nc-gui-v2/components/cell/SingleSelect.vue
packages/nc-gui-v2/components/cell/Text.vue
packages/nc-gui-v2/components/cell/TextArea.vue
packages/nc-gui-v2/components/cell/TimePicker.vue
packages/nc-gui-v2/components/cell/Url.vue
packages/nc-gui-v2/components/cell/YearPicker.vue
packages/nc-gui-v2/components/dashboard/TreeView.vue
packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/components/smartsheet/Pagination.vue
packages/nc-gui-v2/components/smartsheet/expanded-form/Header.vue
packages/nc-gui-v2/components/smartsheet/expanded-form/index.vue
packages/nc-gui-v2/composables/useViewColumns.ts
packages/nc-gui-v2/context/index.ts
packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index.vue

fix(gui-v2): ui corrections

---

packages/nc-gui-v2/components/cell/Checkbox.vue
packages/nc-gui-v2/components/cell/Currency.vue
packages/nc-gui-v2/components/cell/DatePicker.vue
packages/nc-gui-v2/components/cell/DateTimePicker.vue
packages/nc-gui-v2/components/cell/Decimal.vue
packages/nc-gui-v2/components/cell/Duration.vue
packages/nc-gui-v2/components/cell/Email.vue
packages/nc-gui-v2/components/cell/Float.vue
packages/nc-gui-v2/components/cell/Integer.vue
packages/nc-gui-v2/components/cell/MultiSelect.vue
packages/nc-gui-v2/components/cell/Percent.vue
packages/nc-gui-v2/components/cell/Rating.vue
packages/nc-gui-v2/components/cell/SingleSelect.vue
packages/nc-gui-v2/components/cell/Text.vue
packages/nc-gui-v2/components/cell/TextArea.vue
packages/nc-gui-v2/components/cell/TimePicker.vue
packages/nc-gui-v2/components/cell/Url.vue
packages/nc-gui-v2/components/cell/YearPicker.vue
packages/nc-gui-v2/components/virtual-cell/BelongsTo.vue
packages/nc-gui-v2/components/virtual-cell/HasMany.vue
packages/nc-gui-v2/components/virtual-cell/ManyToMany.vue
packages/nc-gui-v2/components/virtual-cell/components/ItemChip.vue
packages/nc-gui-v2/components/virtual-cell/components/ListChildItems.vue

refactor(gui-v2): use edit and readonly injection keys properly

---

packages/nc-gui-v2/composables/useTabs.ts

fix(gui-v2): update default active index

---

packages/nc-gui-v2/components/tabs/auth/user-management/UsersModal.vue

vue3: Added users reloading after user creation

---

packages/nc-gui-v2/composables/useProject.ts
packages/nc-gui-v2/lib/types.ts
packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
packages/nc-gui-v2/utils/urlUtils.ts

vue3: Swagger API URL, Project info copy and Auth token copy

---

packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/index.vue

- add @click.stop on toolbar buttons

fix(gui-v2): easter icons appear when toggling toolbar icons twice

---

packages/nc-gui-v2/components/cell/Json.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/components/virtual-cell/HasMany.vue
packages/nc-gui-v2/components/virtual-cell/ManyToMany.vue
packages/nc-gui-v2/components/virtual-cell/components/ItemChip.vue
packages/nc-gui-v2/components/virtual-cell/components/ListChildItems.vue

fix: avoid excessive requests related to LTAR

---

packages/nc-gui-v2/utils/NcAutocompleteTree.ts

fix(gui-v2): formula AC tree

---

packages/nc-gui-v2/components/cell/DatePicker.vue
packages/nc-gui-v2/components/cell/DateTimePicker.vue
packages/nc-gui-v2/components/cell/TimePicker.vue
packages/nc-gui-v2/components/cell/YearPicker.vue

chore(gui-v2): remove placeholders for *Picker cells

---

packages/nc-gui-v2/components/smartsheet/Form.vue
packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/index.vue
packages/nc-gui-v2/components/tabs/Smartsheet.vue

chore(gui-v2): hide some right toolbar buttons in form view

---

packages/nc-gui-v2/components/smartsheet/VirtualCell.vue

fix: Lookup, Rollup, Count

---

packages/nc-gui-v2/assets/style-v2.scss
packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/general/PreviewAs.vue
packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilter.vue
packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index/index.vue
packages/nc-gui-v2/pages/[projectType]/view/[viewId].vue
packages/nc-gui-v2/pages/forgot-password.vue
packages/nc-gui-v2/pages/index/index.vue
packages/nc-gui-v2/pages/signin.vue
packages/nc-gui-v2/pages/signup/[[token]].vue

chore(gui-v2): style and import cleanups 

---

packages/nc-gui-v2/app.vue
packages/nc-gui-v2/components/cell/Checkbox.vue
packages/nc-gui-v2/components/shared-view/Grid.vue
packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
packages/nc-gui-v2/components/smartsheet-toolbar/ShareView.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/composables/useSharedView.ts
packages/nc-gui-v2/composables/useViewColumns.ts
packages/nc-gui-v2/layouts/shared-view.vue
packages/nc-gui-v2/lib/types.ts
packages/nc-gui-v2/middleware/auth.global.ts
packages/nc-gui-v2/pages/[projectType]/view/[viewId].vue

Ref: #3038 
What's changed:
- Fixed redirections issues where shared view will be redirected to login page if not opened in incognito.
- Added project title to header.
- Removed default layout from the shared view which was causing double header issue.
- Improved showing ask password modal logic.
- Removed show system field check box from shared view.
- Disabled context-menu.
- Fixed reordering issue with columns.
- Added readonly mode to `Checkbox` cell.
- Added password toggle to shared view modal.

 Follow up on shared view

---

packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
packages/nc-gui-v2/composables/useViewColumns.ts

fix(gui-v2): fields menu

---

packages/nc-gui-v2/components/dashboard/settings/Modal.vue

Improved close button and its placement in settings modal
Prev UI:
New UI:

Settings modal close button placement improved

---

packages/nc-gui-v2/components/smartsheet-toolbar/MoreActions.vue

use ExportTypes from nocodb-sdk

refactor(gui-v2): use ExportTypes from nocodb-sdk

---

packages/nc-gui-v2/components/smartsheet/Form.vue

fix(gui-v2): disable lookup in form

---

packages/nc-gui-v2/pages/index/index.vue

* on project selection, navigate to auth tab

chore(gui-v2): navigate to auth tab on project select

---

packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/AddRow.vue

chore/typo fixed in AddRow button

---

packages/nc-gui-v2/components/general/MiniSidebar.vue
packages/nc-gui-v2/components/general/ShareBaseButton.vue
packages/nc-gui-v2/components/smartsheet/expanded-form/Comments.vue
packages/nc-gui-v2/components/smartsheet/expanded-form/Header.vue
packages/nc-gui-v2/components/smartsheet/sidebar/MenuBottom.vue
packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
packages/nc-gui-v2/layouts/base.vue

fix: cypress markers

---

packages/nc-gui-v2/assets/style-v2.scss
packages/nc-gui-v2/components/dashboard/TreeView.vue
packages/nc-gui-v2/components/general/MiniSidebar.vue
packages/nc-gui-v2/components/general/PreviewAs.vue
packages/nc-gui-v2/components/general/language/Menu.vue
packages/nc-gui-v2/components/general/language/index.vue
packages/nc-gui-v2/layouts/base.vue
packages/nc-gui-v2/layouts/shared-view.vue
packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index.vue

chore(gui-v2): fix menu style spacings and colorings

---

packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/dlg/TableCreate.vue
packages/nc-gui-v2/composables/useTable.ts
packages/nc-gui-v2/lib/constants.ts

Ref: #3061 
Table creation now takes in which system columns to add while table creation.

Fixed table column toggle while table creation

---

packages/nocodb/src/lib/meta/api/columnApis.ts
packages/nocodb/src/lib/models/Column.ts

fix: trailing space issue for enum/set options

---

packages/nc-gui-v2/components/general/PreviewAs.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue

fix(gui-v2): disable context menu

---

packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue

chore(gui-v2): fine tune EditOrAdd width

---

packages/nc-gui-v2/components/webhook/Drawer.vue
packages/nc-gui-v2/components/webhook/Editor.vue
packages/nc-gui-v2/components/webhook/List.vue

fix(gui-v2): webhook layout

---

packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue

fix(gui-v2): remove incorrect isUIAllowed

---

packages/nc-gui-v2/components/dashboard/settings/UIAcl.vue
packages/nocodb/src/lib/meta/api/tableApis.ts

fix(gui-v2): includeM2M display

---

packages/nc-gui-v2/assets/style.scss
packages/nc-gui-v2/components/general/SocialCard.vue
packages/nc-gui-v2/components/general/Sponsors.vue
packages/nc-gui-v2/composables/useTheme/index.ts
packages/nc-gui-v2/layouts/base.vue
packages/nc-gui-v2/layouts/default.vue
packages/nc-gui-v2/middleware/auth.global.ts
packages/nc-gui-v2/nuxt.config.ts
packages/nc-gui-v2/package-lock.json
packages/nc-gui-v2/package.json
packages/nc-gui-v2/pages/index/index.vue
packages/nc-gui-v2/pages/signup/[[token]].vue

feat(gui-v2): add google auth signup option

---

packages/nc-gui-v2/middleware/auth.global.ts

refactor(gui-v2): navigate to signup page if first user

---

packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilter.vue

fix(gui-v2): cannot read properties of undefined (reading 'length')

---

packages/nc-gui-v2/components/dashboard/TreeView.vue
packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
packages/nc-gui-v2/components/smartsheet/Pagination.vue
packages/nc-gui-v2/components/smartsheet/expanded-form/Header.vue
packages/nc-gui-v2/components/smartsheet/expanded-form/index.vue
packages/nc-gui-v2/components/virtual-cell/components/ItemChip.vue
packages/nc-gui-v2/composables/useExpandedFormStore.ts
packages/nc-gui-v2/composables/useViewColumns.ts
packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
packages/nc-gui-v2/pages/index/index.vue

fix: miscellaneous bug fixes

---

packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index.vue

fix(gui-v2): close correct tab on `x` icon click

---

packages/nc-gui-v2/components/dashboard/TreeView.vue
packages/nc-gui-v2/components/dlg/TableCreate.vue
packages/nc-gui-v2/layouts/shared-view.vue
packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index/index.vue
packages/nc-gui-v2/pages/project/index/create.vue

- Fixed project name text being black in SharedView
- Removed Add table button in Tree view.
- Added Create table button in the Welcome page
- 
UI:

vue3: Improved welcome page UI and some other UI fixes

---

packages/nc-gui-v2/components/smartsheet/Grid.vue

fix(gui-v2): context menu styles

---

packages/nc-gui-v2/components/dashboard/TreeView.vue
packages/nc-gui-v2/components/general/HelpAndSupport.vue
packages/nc-gui-v2/components/general/ShareBaseButton.vue
packages/nc-gui-v2/components/smartsheet-toolbar/SearchData.vue

Ref: https://github.com/nocodb/nocodb/issues/3284
Fixed styling of search button.
Fixed styling of `Invite team`
Fixed styling of `Api and support`
UI:

vue3: Fixed styling of search and bottom buttons of tree view

---

packages/nc-gui-v2/components/dashboard/settings/Modal.vue
packages/nc-gui-v2/components/general/HelpAndSupport.vue
packages/nc-gui-v2/components/smartsheet-toolbar/SearchData.vue
packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
packages/nc-gui-v2/windi.config.ts

chore(gui-v2): fix modal menu styles

---

packages/nc-gui-v2/layouts/base.vue

refactor(gui-v2): remove shared base btn from header

---

packages/nc-gui-v2/pages/index/index/create-external.vue
packages/nc-gui-v2/utils/projectCreateUtils.ts

chore(gui-v2): type fixes on create-external page

---

packages/nc-gui-v2/components/webhook/Editor.vue

fix(gui-v2): retain hook.notification.payload data

---

packages/nc-gui-v2/components/smartsheet/Cell.vue
packages/nc-gui-v2/components/smartsheet/Form.vue
packages/nc-gui-v2/components/smartsheet/Toolbar.vue
packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/index.vue
packages/nc-gui-v2/components/webhook/Editor.vue

re #3275 
- Title font size
- Option to hide the right navbar
- Remove add row and reload icon
- Help text positioning
- Submit button style
- Outer card overflow issue fix
- Remove primary value highlighting in form view

vue3: Form view ui updates

---

packages/nc-gui-v2/composables/useViewData.ts

fix(gui-v2): trigger reload in updateOrSaveRow

---

packages/nc-gui-v2/components/virtual-cell/components/ListChildItems.vue

fix(gui-v2): link to field correction

---

packages/nc-gui-v2/components/smartsheet/expanded-form/index.vue

Use drawer form expanded form
https://user-images.githubusercontent.com/61551451/186492241-abfacf59-d661-4d76-98ec-0dd3a07ee1e4.mov

enhancement: replace modal with drawer for expanded form

---

packages/nocodb/src/lib/meta/api/swagger/helpers/getSwaggerJSON.ts
packages/nocodb/src/lib/models/View.ts

fix(api): add view column if missing in view columns table

---

packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/components/smartsheet/expanded-form/index.vue
packages/nc-gui-v2/composables/useExpandedFormStore.ts
packages/nc-gui-v2/composables/useViewData.ts

- Expanded form - use entire height 
- On update reload comment/audit list
- 
re #3090

fix(gui-v2): log audit and reload audit list on row update

---

packages/nc-gui-v2/pages/index/index/create-external.vue
packages/nc-gui-v2/utils/projectCreateUtils.ts
packages/nc-gui-v2/utils/validation.ts
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/lib/meta/api/utilApis.ts
packages/nocodb/src/lib/utils/NcConfigFactory.ts
scripts/sdk/swagger.json

Re #3210
- Allow any customized parameter for external db configurations
- Added new SSL mode: Allowed
- Fixed edit json modal
- Use ant-design modal
- Only save if user accept the changes

feat: additional parameters for external database connections

---

packages/nc-gui-v2/components/smartsheet-header/Cell.vue
packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue
packages/nc-gui-v2/components/smartsheet/Form.vue
packages/nc-gui-v2/composables/useViewColumns.ts
packages/nc-gui-v2/pages/[projectType]/form/[viewId]/index.vue
packages/nocodb/src/lib/meta/api/swagger/helpers/getSwaggerJSON.ts
packages/nocodb/src/lib/models/View.ts

Fix: https://github.com/nocodb/nocodb/issues/3299

vue3: Fixed form view column syncing issue

---

packages/nc-gui-v2/components/smartsheet/expanded-form/index.vue
packages/nc-gui-v2/components/virtual-cell/HasMany.vue
packages/nc-gui-v2/components/virtual-cell/components/ListChildItems.vue
packages/nc-gui-v2/composables/useLTARStore.ts

fix(gui-v2) missing expand cell in shared view

---

packages/nc-gui-v2/components/smartsheet/Form.vue

fix(gui-v2): exclude col.cdf case

---

packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue

update route information immediately on view rename (@pranavxc)

fix: route update on rename view

---

packages/nc-gui-v2/composables/useLTARStore.ts

- ref: #3359
Need LTAR columns to test.

fix(gui-v2): undefined view in shared form

---

packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
packages/nc-gui-v2/composables/useViewData.ts

fix(gui-v2): navigate to default view if active view deleted

---

packages/nc-gui-v2/assets/style.scss
packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/general/ColorPicker.vue
packages/nc-gui-v2/composables/useProject.ts
packages/nc-gui-v2/composables/useTheme/index.ts
packages/nc-gui-v2/package-lock.json
packages/nc-gui-v2/package.json
packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
packages/nc-gui-v2/pages/index/index/[id].vue
packages/nc-gui-v2/pages/index/index/index.vue
packages/nocodb/src/lib/meta/api/projectApis.ts
packages/nocodb/src/lib/meta/helpers/extractProps.ts
packages/nocodb/src/lib/models/Base.ts
packages/nocodb/src/lib/models/FormViewColumn.ts
packages/nocodb/src/lib/models/FormulaColumn.ts
packages/nocodb/src/lib/models/GridViewColumn.ts
packages/nocodb/src/lib/models/HookLog.ts
packages/nocodb/src/lib/models/Project.ts
packages/nocodb/src/lib/models/SyncSource.ts
packages/nocodb/src/lib/models/User.ts
packages/nocodb/src/lib/models/View.ts

Re #3345
- Revised projectUpdate end-point / extended to support project meta updates
- Themes are project specific now
- Automatically use analogous accent color if choosed a predefined color
- Allow choosing a project color from edit menu

feat(gui-v2): project theme/color

---

packages/nc-gui-v2/nuxt.config.ts
packages/nc-gui-v2/package-lock.json
packages/nc-gui-v2/package.json
packages/nc-gui-v2/scripts/updateNuxtRouting.js

Enable hash-based routing instead of the default html5 web history based routing.

vue3: hash based routing

---

packages/nocodb-sdk/package-lock.json
packages/nocodb-sdk/package.json

- ref: #3382
This is just a temporary fix.

fix: typescript resolutions

---

packages/nc-gui-v2/components/shared-view/Grid.vue
packages/nc-gui-v2/components/smartsheet/Cell.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/composables/useGlobal/state.ts
packages/nc-gui-v2/composables/useUIPermission/rolePermissions.ts

Allows logged in users to edit data in shared views. This is a draft implementation, please lmk what you think!
Makes it possible insert and delete new rows, edit existing cells in shared views when the user is logged in. Enables the context menu.

Make shared views editable

---

packages/nc-gui-v2/components/smartsheet-toolbar/ShareView.vue
packages/nc-gui-v2/components/smartsheet-toolbar/SharedViewList.vue
packages/nc-gui-v2/components/tabs/auth/UserManagement.vue
packages/nc-gui-v2/components/tabs/auth/user-management/ShareBase.vue
packages/nc-gui-v2/components/tabs/auth/user-management/UsersModal.vue
packages/nc-gui-v2/package-lock.json
packages/nc-gui-v2/scripts/updateNuxtRouting.js
packages/nocodb/src/lib/meta/api/projectUserApis.ts
packages/nocodb/src/lib/v1-legacy/rest/RestAuthCtrl.ts

Update URLs with hash-based URL.
re #3377

refactor(gui-v2): replace with hash based url

---

packages/nc-gui-v2/components/smartsheet-toolbar/ExportSubActions.vue
packages/nc-gui-v2/components/smartsheet-toolbar/MoreActions.vue
packages/nocodb-sdk/package.json
packages/nocodb/src/lib/meta/api/dataApis/helpers.ts

- ref: #3373
Only select `City` column with `Z-A` on it.

fix(gui-v2): include fields, sortArrJson, and filterArrJson when extracting CSV data

---

packages/nc-gui-v2/composables/useInjectionState/index.ts
packages/nc-gui-v2/composables/useProject.ts
packages/nc-gui-v2/composables/useTheme/index.ts
packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
packages/nc-gui-v2/pages/index/index/[id].vue
packages/nc-gui-v2/pages/index/index/[projectId].vue
packages/nc-gui-v2/pages/index/index/index.vue

Re #3386 + Pick project theme color from badge

fix: project theme

---

.github/workflows/ci-cd-v2.yml

test: cicd wait

---

packages/nc-gui-v2/components/smartsheet-toolbar/ViewActions.vue
packages/nc-gui-v2/components/smartsheet/ApiSnippet.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/nuxt.config.ts
packages/nc-gui-v2/package-lock.json
packages/nc-gui-v2/package.json

fix(gui-v2): bring back api snippet and resolve build issues

---

scripts/markdown/readme/languages/japanese.md

Add and fix some translate in japanese.md.

docs: update japanese.md

---

packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
packages/nc-gui-v2/components/smartsheet/Gallery.vue
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/lib/models/View.ts
scripts/sdk/swagger.json

feat: gallery rework

---

packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue

fix(gui-v2): project tile correction in shared base

---

packages/nc-gui-v2/components/virtual-cell/BelongsTo.vue

fix(gui-v2): show bt add/link icon in shared form view

---

packages/nc-gui-v2/components/smartsheet/Gallery.vue
packages/nc-gui-v2/components/virtual-cell/ManyToMany.vue
packages/nc-gui-v2/components/virtual-cell/components/ListChildItems.vue
packages/nc-gui-v2/composables/useLTARStore.ts
packages/nocodb/src/lib/meta/api/dataApis/dataAliasNestedApis.ts
packages/nocodb/src/lib/meta/api/dataApis/helpers.ts
packages/nocodb/src/lib/meta/api/publicApis/publicDataApis.ts
packages/nocodb/src/lib/meta/helpers/PagedResponse.ts
packages/nocodb/src/lib/models/Column.ts

fix: expand option of hm and mm in shared view

---

packages/nc-gui-v2/components.d.ts
packages/nc-gui-v2/components/smartsheet/Toolbar.vue
packages/nc-gui-v2/components/smartsheet/expanded-form/Comments.vue
packages/nc-gui-v2/components/smartsheet/expanded-form/Header.vue
packages/nc-gui-v2/components/smartsheet/expanded-form/index.vue
packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/ToggleDrawer.vue
packages/nc-gui-v2/composables/useTable.ts

fix: handle deleting active table(tab)

---

packages/nocodb/src/lib/db/sql-mgr/code/models/xc/ModelXcMetaSqlite.ts
scripts/cypress-v2/cypress.json
scripts/cypress-v2/integration/common/00_pre_configurations.js
scripts/cypress-v2/support/page_objects/navigation.js

remove length value from datatype; enable screenshots; defer xcdb test start to avoid race condition with db migration

test: enable screenshots

---

packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index/index.vue

- ref: #3426
Use the mime types
Using the dummy test file provided by user in the above issue.

fix(gui-v2): check import file mime types

---

packages/nc-gui-v2/components/smartsheet/Pagination.vue
packages/nc-gui-v2/composables/useViewData.ts

- pagination issue - ref: #3360 
- refactor function declarations in useViewData to avoid scope problems in lint

fix(gui-v2): pagination logic

---

packages/nc-gui-v2/assets/style.scss
packages/nc-gui-v2/components/smartsheet-toolbar/ViewActions.vue
packages/nc-gui-v2/components/smartsheet/Grid.vue
packages/nc-gui-v2/components/smartsheet/Toolbar.vue
packages/nc-gui-v2/components/smartsheet/expanded-form/Header.vue
packages/nc-gui-v2/components/smartsheet/sidebar/MenuBottom.vue
packages/nc-gui-v2/composables/useSmartsheetStore.ts
packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index.vue

fix: hide irrelevant options from sql view tab

---

packages/nc-gui-v2/components/general/ColorPicker.vue
packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index/index.vue
packages/nc-gui-v2/pages/index/index/index.vue
packages/nc-gui-v2/utils/colorsUtils.ts

enhancement(gui-v2): provide new set of project theme colors

---

packages/nc-gui-v2/components/general/HelpAndSupport.vue
packages/nc-gui-v2/components/tabs/auth/user-management/FeedbackForm.vue
packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue

refactor: minor ui chnages

---

packages/nocodb/src/lib/meta/api/dataApis/dataAliasApis.ts
packages/nocodb/src/lib/meta/api/dataApis/dataApis.ts
packages/nocodb/src/lib/meta/api/publicApis/publicDataApis.ts

enhancement: add try catch for covering search mismatch type

---

packages/nc-gui-v2/components/smartsheet-column/AdvancedOptions.vue

fix(gui-v2): alignment correction in column edit

---

packages/nc-gui-v2/components/smartsheet/Grid.vue

fix(gui-v2): show record index always if grid in readonly mode

---

packages/nc-gui-v2/components/cell/DatePicker.vue
packages/nc-gui-v2/components/cell/DateTimePicker.vue
packages/nc-gui-v2/components/cell/TimePicker.vue
packages/nc-gui-v2/components/cell/YearPicker.vue
packages/nc-gui-v2/components/virtual-cell/Lookup.vue
packages/nc-gui-v2/composables/useViewData.ts

fix: lookup column rendering

---

packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue

https://user-images.githubusercontent.com/61551451/188212656-ea77726c-b453-40ea-b141-346facea730f.mov

fix(gui-v2): set accent color after updating theme meta successfully

---

packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue

fix(gui-v2): sync with db if view column order value updated

---

packages/nc-gui-v2/components/tabs/auth/UserManagement.vue
packages/nocodb-sdk/src/lib/Api.ts
scripts/sdk/swagger.json

fix(swagger): remove unnecessary request body arg from api

---

packages/nc-gui-v2/components/tabs/auth/UserManagement.vue
packages/nc-gui-v2/components/tabs/auth/user-management/ShareBase.vue
packages/nocodb/src/lib/meta/helpers/NcPluginMgrv2.ts

fix(api): throw not implemented if test method is not implemented

---

packages/nc-gui-v2/components/tabs/Auth.vue

fix(gui-v2): add missing isUIAllowed for UserManagement & ApiTokenManagement

---

packages/nc-gui-v2/components/smartsheet-column/FormulaOptions.vue

fix(gui-v2): skip system LTAR columns

---

packages/nc-gui-v2/components/dlg/TableRename.vue

fix(gui-v2): set metas with updated model after renaming tables

---

packages/nc-gui-v2/components/cell/attachment/index.vue

fix(gui-v2): re-find cell ref for attachment dropzone on order change

---

packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
packages/nc-gui-v2/components/smartsheet-header/Cell.vue
packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue

vue3: Fixed scroll issue with EditOrAdd component

---

packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue

Re #3485
- Used msg.info.editingPKnotSupported from i18n

fix: block attempts to edit primary key column

---

packages/nc-gui-v2/components/smartsheet/Form.vue
packages/nc-gui-v2/composables/useViewColumns.ts

fix(gui-v2): add reloadEventHook.trigger() to get the latest localColumn value

---

packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilterMenu.vue
packages/nc-gui-v2/composables/useViewColumns.ts

fix(gui-v2): avoid watch logic to trigger even after signout

---

packages/nc-gui-v2/components/dashboard/TreeView.vue
packages/nc-gui-v2/components/general/TruncateText.vue
packages/nc-gui-v2/components/smartsheet-toolbar/ViewActions.vue
packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index.vue

Re #3482
- Created TruncateText component
- Supports custom length and tooltip position through props (length | placement)
- Adds tooltip if text is shrinked
- Implemented for:
- TreeView
- Tab titles
- ViewActions title
- Project dropdown

feat: implement TruncateText component

---

packages/nc-gui/components/general/ReleaseInfo.vue

fix: release info style & hide menu

---

packages/nc-gui/composables/useApi/index.ts
packages/nc-gui/composables/useGlobal/state.ts
packages/nc-gui/lib/constants.ts
packages/nc-gui/pages/index/index/create-external.vue
packages/nocodb/src/__tests__/noco/NcConfigFactory.test.ts
packages/nocodb/src/lib/utils/NcConfigFactory.ts

Fix #3529 
Include the host value provided in the `NC_DB` URL while extracting knex connection config.

fix(gui-v2): include host from NC_DB url

---

packages/nc-gui/components.d.ts
packages/nc-gui/components/smartsheet-toolbar/ViewActions.vue
packages/nocodb/src/lib/meta/api/utilApis.ts

Re #3540
- Timeout for fetch latest version (5 sec)
- Cache fetched release info for 1 hour

fix: version info implement timeout and cache

---

packages/nc-gui/components/dlg/QuickImport.vue
packages/nc-gui/pages/signup/[[token]].vue

fix(gui): avoid unnecessary upload api call from upload component

---

scripts/sdk/swagger.json

Provide required props as an array to avoid failing all-apis docs initialisation.

chore(swagger): provide required props as an array

---

packages/nocodb/src/lib/utils/NcConfigFactory.ts

fix(nocodb): use port from connection URL

---

packages/nc-gui/components/tabs/auth/ApiTokenManagement.vue

Changed generate token to a form to make it more accessible for keyboard users.
Closes #3562 
Not required.
Not required. 

feat: added a form for creating tokens

---

packages/nc-gui/components/general/language/Menu.vue
packages/nc-gui/components/general/language/index.vue
packages/nc-gui/composables/useGlobal/state.ts
packages/nc-gui/layouts/base.vue
packages/nc-gui/lib/types.ts
packages/nc-gui/nuxt-shim.d.ts
packages/nc-gui/nuxt.config.ts
packages/nc-gui/package-lock.json
packages/nc-gui/package.json
packages/nc-gui/pages/signin.vue
packages/nc-gui/plugins/a.i18n.ts
packages/nc-gui/plugins/state.ts

fix(nc-gui): lazy load languages for initial load perf

---

packages/noco-docs/content/en/developer-resources/accessing-apis.md
packages/noco-docs/content/en/developer-resources/webhooks.md
packages/noco-docs/content/en/engineering/development-setup.md
packages/noco-docs/content/en/engineering/translation.md
packages/noco-docs/content/en/index.md
packages/noco-docs/content/en/setup-and-usages/audit.md
packages/noco-docs/content/en/setup-and-usages/code-snippets.md
packages/noco-docs/content/en/setup-and-usages/column-operations.md
packages/noco-docs/content/en/setup-and-usages/dashboard.md
packages/noco-docs/content/en/setup-and-usages/formulas.md
packages/noco-docs/content/en/setup-and-usages/import-airtable-to-sql-database-within-a-minute-for-free.md
packages/noco-docs/content/en/setup-and-usages/languages.md
packages/noco-docs/content/en/setup-and-usages/link-to-another-record.md
packages/noco-docs/content/en/setup-and-usages/lookup.md
packages/noco-docs/content/en/setup-and-usages/meta-management.md
packages/noco-docs/content/en/setup-and-usages/primary-key.md
packages/noco-docs/content/en/setup-and-usages/primary-value.md
packages/noco-docs/content/en/setup-and-usages/rollup.md
packages/noco-docs/content/en/setup-and-usages/sync-schema.md
packages/noco-docs/content/en/setup-and-usages/table-operations.md
packages/noco-docs/content/en/setup-and-usages/team-and-auth.md
packages/noco-docs/content/en/setup-and-usages/views.md

ref: #3264
- update screenshots in new UI
TODO:
- update nocodb version in Code Sandbox

docs: NocoDB Documentation for 0.96.0

---

packages/nc-gui/components/cell/Checkbox.vue

ref: #3613
- hover the input to show the checkbox
- either click the checkbox or click the input to tick / untick

fix(nc-gui): make checkbox visible on hover & more easy to tick

---

packages/nc-gui/components/dashboard/settings/Erd.vue
packages/nc-gui/package-lock.json
packages/nc-gui/package.json

refactor(nc-gui): reset ERD elements on option change and unmount 

---

packages/nc-gui/pages/[projectType]/form/[viewId]/index.vue

Bug related to shared form view component when the view is password protected.
re #3627

fix(gui): shared form view with password

---

packages/nc-gui/components/dlg/AirtableImport.vue
packages/nc-gui/composables/useGridViewColumnWidth.ts

fix(gui): Importing Airtable to SQL databases - scroll fix

---

packages/nc-gui/components/smartsheet/sidebar/index.vue
packages/nc-gui/components/smartsheet/sidebar/toolbar/ToggleDrawer.vue
packages/nc-gui/components/smartsheet/sidebar/toolbar/index.vue
packages/nc-gui/composables/useSidebar/index.ts

* use sync ref to sync sidebar state to storage
* use cb function for toggle

fix(nc-gui): right sidebar collapse not working

---

packages/nc-gui/components/general/MiniSidebar.vue
packages/nc-gui/components/smartsheet/Toolbar.vue
packages/nc-gui/components/smartsheet/sidebar/index.vue
packages/nc-gui/components/smartsheet/sidebar/toolbar/DeleteTable.vue
packages/nc-gui/components/smartsheet/sidebar/toolbar/ToggleDrawer.vue
packages/nc-gui/components/tabs/Smartsheet.vue
packages/nc-gui/composables/useSidebar/index.ts
packages/nc-gui/layouts/default.vue
packages/nc-gui/pages/[projectType]/[projectId]/index.vue
packages/nc-gui/pages/[projectType]/[projectId]/index/index.vue
packages/nc-gui/pages/[projectType]/form/[viewId].vue
packages/nc-gui/pages/index/index/[projectId].vue
packages/nc-gui/pages/index/index/create-external.vue
packages/nc-gui/pages/index/index/create.vue
packages/nc-gui/pages/index/index/index.vue
packages/nc-gui/pages/signin.vue
packages/nc-gui/utils/memStorage.ts

* use a sidebar id to identify the state
* use in memory storage to store the states
* use local storage to store persistent states
* add MemStorage class

feat(nc-gui): store sidebar states separately by id

---

packages/nc-gui/components/smartsheet-column/EditOrAdd.vue
packages/nc-gui/composables/useColumnCreateStore.ts
packages/nc-gui/composables/useSmartsheetRowStore.ts

* update EditOrAdd form style
* remove injection use on callbacks * fixes errors thrown while changing column type
* use `unref`

fix(nc-gui): remove injection usage in callback

---

packages/nc-gui/components/dashboard/settings/Modal.vue
packages/nc-gui/components/general/FullScreen.vue
packages/nc-gui/pages/[projectType]/[projectId]/index.vue

fix(gui): miscellaneous

---

packages/nc-gui/components/smartsheet-column/AdvancedOptions.vue
packages/nc-gui/composables/useColumnCreateStore.ts
packages/nocodb/src/lib/meta/api/columnApis.ts

fix: select column issue

---

packages/nc-gui/components/smartsheet/expanded-form/Header.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue

Fix: Expanded form - hide reload and  virtual columns if new record

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts

fix: drop wrapping select queries for mssql

---

packages/nocodb/src/lib/meta/api/columnApis.ts

- fix mysql empty option
- fix select column edit operations (if no options before)

fix: select column

---

scripts/cypress/integration/common/00_pre_configurations.js
scripts/cypress/integration/common/1b_table_column_operations.js
scripts/cypress/integration/common/3b_formula_column.js
scripts/cypress/integration/common/3c_lookup_column.js
scripts/cypress/integration/common/3d_rollup_column.js
scripts/cypress/integration/common/3e_duration_column.js
scripts/cypress/integration/common/3f_link_to_another_record.js
scripts/cypress/support/commands.js
scripts/cypress/support/page_objects/mainPage.js

CY-stability: column edit operations

test: cy-stability-column edit operations

---

packages/nc-gui/components/smartsheet-toolbar/ColumnFilter.vue
packages/nc-gui/components/webhook/Editor.vue
packages/nc-gui/composables/useViewFilters.ts

Fix: Filter - webhook and view filter bugs

---

packages/nc-gui/composables/useGlobal/index.ts
packages/nc-gui/composables/useGlobal/state.ts
packages/nc-gui/composables/useGlobal/types.ts

* Prevents modified local storage to assume unassigned roles

fix(nc-gui): reset roles on app load

---

scripts/cypress/support/page_objects/mainPage.js

test: use class names for menu & selection in filter & sort test

---

packages/nocodb/src/lib/meta/api/metaDiffApis.ts
packages/nocodb/src/lib/models/Column.ts

Apply column changes in order to avoid foreign key constraint errors.
re #3033

fix(api): apply column changes in order

---

packages/nc-gui/components/dlg/AirtableImport.vue
packages/nc-gui/components/dlg/QuickImport.vue
packages/nc-gui/components/template/Editor.vue
packages/nc-gui/components/webhook/Editor.vue
packages/nc-gui/lang/en.json
packages/nc-gui/pages/index/index/create-external.vue
packages/nc-gui/utils/validation.ts

i18n extension for validation messages

refactor: i18n validation error messages

---

packages/nc-gui/nuxt.config.ts

chore(gui): add cdn path as relative to load assets relative to the path

---

.github/workflows/ci-cd.yml

chore: skip cicd for draft PR

---

packages/nc-gui/nuxt.config.ts

chore(gui): Build error

---

packages/nc-gui/components/general/language/Menu.vue
packages/nc-gui/pages/[projectType]/[projectId]/index.vue

- Community translated badge on language item
- Move `Help Translate` to top (increase visibility)

fix: add community translated

---

.github/workflows/ci-cd.yml

chore: ci-cd trigger update

---

packages/nc-gui/components/general/SocialCard.vue
packages/nc-gui/components/general/language/Menu.vue

LTR for Arabic language
Verified locally

fix(i18n): rtl for ar

---

packages/nc-gui/components/smartsheet-header/CellIcon.vue

fix(nc-gui): cell icons & add duration icon

---

packages/nc-gui/components/general/MiniSidebar.vue
packages/nc-gui/layouts/base.vue
packages/nc-gui/layouts/shared-view.vue
packages/nc-gui/pages/[projectType]/[projectId]/index.vue

feat(nc-gui): add nc version

---

.github/workflows/ci-cd.yml
scripts/cypress/cypress.json
scripts/cypress/integration/common/00_pre_configurations.js
scripts/cypress/integration/common/4e_form_view_share.js
scripts/cypress/integration/common/4f_grid_view_share.js
scripts/cypress/integration/common/6d_language_validation.js
scripts/cypress/integration/common/6e_project_operations.js
scripts/cypress/integration/common/6f_attachments.js
scripts/cypress/integration/common/6g_base_share.js
scripts/cypress/integration/common/8a_webhook.js
scripts/cypress/integration/test/db-independent.js
scripts/cypress/integration/test/pg-restMisc.js
scripts/cypress/integration/test/restMisc.js
scripts/cypress/integration/test/xcdb-restMisc.js
scripts/cypress/support/commands.js
scripts/cypress/support/page_objects/navigation.js

- new suite `DB-independent`: currently only language verification tests are part of this. this will be used to place all db-independent tests.
- use search option in webhook header instead of manual scroll
- remove wait in selective places (wip)
CI-CD

test(misc): re-alignment & optimizations

---

packages/nc-gui/components/smartsheet/Gallery.vue

Fix(gui):  Gallery view bugs

---

scripts/cypress/integration/common/4g_table_view_expanded_form.js

test(expanded-form): wait for page load

---

packages/nc-gui/components/smartsheet-header/Menu.vue
scripts/cypress/integration/common/5a_user_role.js
scripts/cypress/integration/common/6f_attachments.js
scripts/cypress/integration/common/6g_base_share.js
scripts/cypress/integration/common/7a_create_project_from_excel.js
scripts/cypress/integration/common/8a_webhook.js
scripts/cypress/integration/common/9a_QuickTest.js
scripts/cypress/integration/spec/roleValidation.spec.js
scripts/cypress/support/commands.js
scripts/cypress/support/page_objects/mainPage.js

replace cy.wait() with appropriate DOM element wait or API intercept

test(misc): wait clean up

---

scripts/cypress/integration/common/00_pre_configurations.js
scripts/cypress/integration/common/1a_table_operations.js
scripts/cypress/integration/common/1b_table_column_operations.js
scripts/cypress/integration/common/2b_table_with_m2m_column.js
scripts/cypress/integration/common/3a_filter_sort_fields_operations.js
scripts/cypress/integration/common/3c_lookup_column.js
scripts/cypress/integration/common/3d_rollup_column.js
scripts/cypress/integration/common/3e_duration_column.js
scripts/cypress/integration/common/3f_link_to_another_record.js
scripts/cypress/integration/common/4a_table_view_grid_gallery_form.js
scripts/cypress/integration/common/4c_form_view_detailed.js
scripts/cypress/integration/common/4e_form_view_share.js
scripts/cypress/integration/common/4f_pg_grid_view_share.js
scripts/cypress/integration/common/5a_user_role.js
scripts/cypress/integration/common/5b_preview_role.js
scripts/cypress/integration/common/6f_attachments.js
scripts/cypress/integration/common/6g_base_share.js
scripts/cypress/integration/common/7a_create_project_from_excel.js
scripts/cypress/integration/common/8a_webhook.js
scripts/cypress/integration/spec/roleValidation.spec.js
scripts/cypress/integration/test/explicitLogin.js
scripts/cypress/support/commands.js
scripts/cypress/support/page_objects/mainPage.js
scripts/cypress/support/page_objects/navigation.js

test: cy wait cleanup

---

scripts/cypress/integration/common/9b_ERD.js
scripts/cypress/integration/test/pg-restMisc.js
scripts/cypress/integration/test/xcdb-restMisc.js
scripts/cypress/support/page_objects/projectConstants.js

test: enable ERD for PG, SQLite

---

packages/nc-gui/lib/enums.ts
packages/nc-gui/plugins/a.i18n.ts
packages/nc-gui/plugins/state.ts

* Fall back to EN if language cannot be matched to `Language` or `LanguageAlias`
* Use aliased language if match is found

feat(nc-gui): add LanguageAlias enum

---

packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/smartsheet/toolbar/SharedViewList.vue
packages/nc-gui/composables/useMultiSelect/index.ts

Add new file:
- packages/nc-gui/composables/useMultiSelect/index.ts
Update: 
- packages/nc-gui/components/smartsheet/Grid.vue
https://user-images.githubusercontent.com/24416449/192377362-c86a6539-6297-44b8-b0c6-364cf0a941de.mp4

feat(nc-gui): select multiple rows and copy

---

packages/nc-gui/components/general/PreviewAs.vue
scripts/cypress/integration/common/5b_preview_role.js
scripts/cypress/integration/common/5c_super_user_role.js
scripts/cypress/integration/test/pg-restRoles.js
scripts/cypress/integration/test/restRoles.js
scripts/cypress/integration/test/xcdb-restRoles.js

test: enable preview mode tests

---

scripts/cypress/integration/common/3e_duration_column.js
scripts/cypress/integration/test/pg-restTableOps.js
scripts/cypress/integration/test/restTableOps.js
scripts/cypress/integration/test/xcdb-restTableOps.js

test: enable duration column tests

---

scripts/cypress/integration/test/pg-restTableOps.js
scripts/cypress/integration/test/xcdb-restTableOps.js

Enable LTAR tests for SQLite & PG

test: enable LTAR tests in SQLite, PG

---

scripts/cypress/integration/common/6g_base_share.js

Intercept message correction for the shared base. Hoping this helps blank screen issue observed for shared base editor role

test: update intercept message during shared base load

---

packages/nc-gui/composables/useSharedView.ts
packages/nc-gui/composables/useViewData.ts

Fix: Shared grid view sort 

---

packages/nc-gui/components/smartsheet/toolbar/ExportSubActions.vue
packages/nc-gui/composables/useSharedView.ts

Fix: Shared grid - csv/excel export with filter and sort

---

packages/nc-gui/components/virtual-cell/components/ListChildItems.vue
scripts/cypress/integration/common/4f_grid_view_share.js
scripts/cypress/integration/common/4f_pg_grid_view_share.js
scripts/cypress/integration/test/pg-restViews.js
scripts/cypress/support/commands.js
scripts/cypress/support/page_objects/mainPage.js

test: pg grid view share

---

packages/nc-gui/components/smartsheet/column/AdvancedOptions.vue
packages/nc-gui/components/smartsheet/column/SelectOptions.vue

Re #3890
- Fixed unwanted behavior when you don't expand advanced options

fix: move default value handling for select column to SelectOptions

---

packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/components/smartsheet/Gallery.vue
packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/smartsheet/sidebar/MenuTop.vue
packages/nc-gui/components/smartsheet/sidebar/index.vue
packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
packages/nc-gui/composables/useViews.ts
packages/nc-gui/pages/[projectType]/[projectId]/index.vue
packages/nc-gui/pages/[projectType]/[projectId]/index/index.vue
packages/nc-gui/pages/[projectType]/[projectId]/index/index/[type]/[title]/[[viewTitle]].vue
packages/nc-gui/pages/[projectType]/form/[viewId]/index.vue
scripts/cypress/integration/common/00_pre_configurations.js
scripts/cypress/integration/common/4c_form_view_detailed.js
scripts/cypress/integration/common/5a_user_role.js
scripts/cypress/integration/common/9a_QuickTest.js
scripts/cypress/support/commands.js
scripts/cypress/support/page_objects/navigation.js

Fix : Avoid re-rendering smartsheet

---

packages/nocodb-sdk/src/lib/Api.ts
scripts/sdk/swagger.json

fix(nocodb-sdk): add missing offset & limit

---

scripts/pkg-executable/package.json

fix(scripts): use latest nocodb version in pkg-executable

---

.github/workflows/release-docker.yml
.github/workflows/release-npm.yml

ref: #3897  + PR Docker fail issue
tested in https://github.com/nocodb/nocodb/actions/runs/3172458611/jobs/5167088350

fix(workflow): increase max_old_space_size

---

README.md

Added the link to License in the ReadMe file along with the updation of table of content. 

[DOCS] Add LICENSE link to ReadMe

---

packages/nc-gui/assets/style.scss
packages/nc-gui/components/general/NocoIcon.vue
packages/nc-gui/pages/forgot-password.vue
packages/nc-gui/pages/index/index/[projectId].vue
packages/nc-gui/pages/index/index/create-external.vue
packages/nc-gui/pages/index/index/create.vue
packages/nc-gui/pages/signin.vue
packages/nc-gui/pages/signup/[[token]].vue

* update loading animation for new logo
https://user-images.githubusercontent.com/78412429/193344330-a8341c6c-3d73-4443-a4c4-edcae3c754c6.mov

refactor(nc-gui): update logo animation

---

scripts/cypress/integration/common/00_pre_configurations.js
scripts/cypress/integration/common/1b_table_column_operations.js
scripts/cypress/integration/common/3c_lookup_column.js
scripts/cypress/integration/common/3d_rollup_column.js
scripts/cypress/integration/common/3e_duration_column.js
scripts/cypress/integration/common/3f_link_to_another_record.js
scripts/cypress/integration/common/5a_user_role.js
scripts/cypress/integration/common/9a_QuickTest.js
scripts/cypress/support/commands.js
scripts/cypress/support/page_objects/mainPage.js
scripts/cypress/support/page_objects/navigation.js

test: remove wait from LTAR

---

packages/nc-gui/assets/style.scss
packages/nc-gui/components/cell/attachment/Carousel.vue
packages/nc-gui/components/cell/attachment/Modal.vue
packages/nc-gui/components/cell/attachment/index.vue
packages/nc-gui/components/dashboard/TreeView.vue
packages/nc-gui/components/general/MiniSidebar.vue
packages/nc-gui/layouts/base.vue
packages/nc-gui/pages/[projectType]/form/[viewId]/index.vue
packages/nc-gui/pages/forgot-password.vue
packages/nc-gui/pages/index/index/[projectId].vue
packages/nc-gui/pages/index/index/create.vue
packages/nc-gui/pages/index/index/index.vue
packages/nc-gui/pages/index/user/index.vue
packages/nc-gui/pages/signin.vue
packages/nc-gui/pages/signup/[[token]].vue
packages/nc-gui/windi.config.ts

* apply ring opacity
* remove duplicate scaling btn styles

fix(nc-gui): ring opacity

---

packages/nc-gui/components/dlg/TableRename.vue
packages/nc-gui/components/general/TruncateText.vue

fix(nc-gui): correctly update tab after renaming table

---

packages/nc-gui/components/smartsheet/Grid.vue

re #3768 
[Anything for maintainers to be made aware of](https://user-images.githubusercontent.com/61551451/194248700-41521ce8-4be0-4de3-b9c2-17150a8f1c4c.mov)

Enhancement: Scroll to the active cell on active cell change

---

packages/nc-gui/lang/en.json
packages/nc-gui/pages/signin.vue
packages/nc-gui/pages/signup/[[token]].vue

* add google auth btn to signin page
* update baseurl for google auth in signup page

fix(nc-gui): add google auth button to signin page

---

scripts/cypress/integration/common/1b_table_column_operations.js
scripts/cypress/integration/common/3a_filter_sort_fields_operations.js
scripts/cypress/integration/common/3e_duration_column.js
scripts/cypress/integration/common/3f_link_to_another_record.js
scripts/cypress/integration/common/4f_grid_view_share.js
scripts/cypress/integration/common/4f_pg_grid_view_share.js
scripts/cypress/integration/common/8a_webhook.js
scripts/cypress/support/page_objects/mainPage.js

test: ensure add new row tooltip disappears

---

packages/nc-gui/components/smartsheet/toolbar/FieldListAutoCompleteDropdown.vue

* filter options by label instead of option value
https://user-images.githubusercontent.com/78412429/194411983-428b2b9f-ed42-403c-8e0c-4d1b1abffb14.mov

fix(nc-gui): filter options by label

---

packages/nocodb/src/lib/meta/helpers/webhookHelpers.ts

If the test payload is an object convert it to JSON string and apply handlebar
re #3932

Fix: Webhook test with custom payload

---

packages/nocodb/src/lib/utils/NcConfigFactory.ts
packages/nocodb/src/lib/utils/common/NcConnectionMgrv2.ts

Fix for https://github.com/nocodb/nocodb/issues/3767

set min max for knex pool

---

README.md

docs: update logo and add kanban info

---

packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue
packages/nc-gui/composables/useGridViewColumnWidth.ts
packages/nc-gui/composables/useViewColumns.ts
packages/nc-gui/composables/useViewFilters.ts

Avoid unnecessary API calls while switching tabs or deleting the active tables.
re #3971

Fix:  Table delete - active table deletion

---

packages/nc-gui/components/smartsheet/toolbar/ShareView.vue

chore(nc-gui): disable theme for non form shared views

---

.github/workflows/ci-cd.yml

Configure default time-out CICD jobs to 30 mins

chore: default timeout experiment

---

packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/smartsheet/expanded-form/Header.vue
packages/nc-gui/components/smartsheet/header/VirtualCell.vue
packages/nc-gui/composables/useExpandedFormStore.ts
packages/nc-gui/composables/useSmartsheetRowStore.ts
packages/nc-gui/composables/useViewData.ts
packages/nc-gui/utils/columnUtils.ts
packages/nc-gui/utils/dataUtils.ts
packages/nocodb-sdk/package-lock.json
packages/nocodb/tests/pg-sakila-db/01-postgres-sakila-schema.sql

Fix: Grid view - save new row only when all required cell values provided

---

packages/nc-gui/components/dashboard/TreeView.vue
packages/nc-gui/components/tabs/Smartsheet.vue
packages/nc-gui/pages/[projectType]/[projectId]/index.vue

Fix: Avoid locking treeview operations based on view lock

---

packages/nc-gui/components/smartsheet/Kanban.vue

fix(nc-gui): add missing uncategorized title when stack is collapsed

---

packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/pages/[projectType]/form/[viewId]/index/survey.vue

Fix: Grid view - remove clear cell option from context menu for virtual cells

---

packages/nc-gui/pages/index/index/index.vue
packages/noco-docs/content/en/developer-resources/rest-apis.md
packages/nocodb-sdk/package-lock.json
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/lib/meta/NcMetaIO.ts
packages/nocodb/src/lib/meta/NcMetaIOImpl.ts
packages/nocodb/src/lib/meta/api/utilApis.ts
packages/nocodb/tests/unit/rest/tests/project.test.ts
scripts/sdk/swagger.json

Feat: Aggregated api for complete meta

---

packages/nc-gui/components/dlg/ViewCreate.vue
packages/nc-gui/components/smartsheet/Kanban.vue
packages/nc-gui/components/smartsheet/sidebar/RenameableMenuItem.vue
packages/nc-gui/components/smartsheet/toolbar/StackedBy.vue
packages/nc-gui/composables/useKanbanViewStore.ts
packages/nocodb-sdk/package-lock.json
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/lib/migrations/XcMigrationSourcev2.ts
packages/nocodb/src/lib/migrations/v2/nc_021_rename_kanban_grp_col_id.ts
packages/nocodb/src/lib/models/KanbanView.ts
packages/nocodb/src/lib/models/View.ts
scripts/sdk/swagger.json

- rename `grp_column_id` to `fk_grp_col_id`
- set fk_grp_col_id as foreign key

refactor: kanban grouping column id

---

packages/nc-gui/components/cell/attachment/Carousel.vue
packages/nc-gui/components/general/Overlay.vue

Provide proper z-index value to avoid blocking user table creation. 

Fix: Provide proper z-index value to avoid unexpected behaviour

---

packages/nc-gui/components/shared-view/Gallery.vue
packages/nc-gui/components/smartsheet/Toolbar.vue
packages/nc-gui/components/smartsheet/toolbar/ShareView.vue
packages/nc-gui/pages/[projectType]/gallery/[viewId]/index.vue
packages/nocodb/src/lib/meta/api/publicApis/publicDataApis.ts
packages/nocodb/src/lib/meta/api/publicApis/publicDataExportApis.ts

feat: gallery share view

---

packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/smartsheet/Row.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/composables/useLTARStore.ts
packages/nc-gui/context/index.ts

Fix: Grid view flickering on LTAR link/unlink

---

packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/cell/SingleSelect.vue

Choose light/dark font based on select option color
+fixed some type errors for select cells

feat: select option dynamic font

---

packages/nc-gui/components/smartsheet/Gallery.vue
packages/nc-gui/components/smartsheet/Kanban.vue

- fix gallery throwing errors if without nullable check

fix(nc-gui): prevent gallery cover img error

---

packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
packages/nc-gui/composables/useViewFilters.ts

fix: filter badge

---

packages/nc-gui/composables/useSharedFormViewStore.ts
packages/nc-gui/lang/en.json

fix(nc-gui): use column label or title for error msg in form view

---

packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/composables/useMultiSelect/index.ts

https://user-images.githubusercontent.com/61551451/195380374-79fdc393-6e93-4ea9-8458-2757cbe96450.mov

Fix: Grid view - avoid scroll to cell on click

---

packages/nocodb/src/lib/meta/api/swagger/helpers/templates/paths.ts

Fix: Swagger - OpenAPI spec corrections

---

packages/nc-cli/package-lock.json
packages/nc-cli/package.json
packages/nc-cli/webpack.config.js

Refactor: CLI - rename cli script alias to avoid conflict

---

packages/nocodb-sdk/src/lib/passwordHelpers.ts

Removes password character requirements as per https://github.com/nocodb/nocodb/issues/242
Not sure how to classify this correctly, could be both feat or fix :shrug: 
Also found some dead links so I fixed them

Remove password character requirements

---

packages/nc-gui/components/cell/Duration.vue
packages/nc-gui/components/cell/Percent.vue
packages/nc-gui/components/cell/Text.vue
packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/pages/[projectType]/form/[viewId]/index/survey.vue

fix(nc-gui): correct input style padding for form views

---

packages/nc-gui/pages/[projectType]/[projectId]/index/index.vue

* fixes issue where navigating between projects would load the previously opened project

fix(nc-gui): apply distinct key on page

---

packages/nc-gui/utils/columnUtils.ts

fix(gui): Row insert/update - ignore auto generated column from required

---

packages/nc-gui/composables/useTheme/index.ts
packages/nc-gui/pages/[projectType]/[projectId]/index.vue
packages/nc-gui/utils/colorsUtils.ts

refactor(nc-gui): add default nocodb theme color to picker

---

packages/nc-gui/components/smartsheet/column/EditOrAdd.vue

Fix: Edit column -  focus title field only if there is no focused input element

---

packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/dlg/ViewCreate.vue
packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/smartsheet/sidebar/MenuBottom.vue
packages/nc-gui/components/smartsheet/sidebar/MenuTop.vue
packages/nc-gui/components/smartsheet/sidebar/RenameableMenuItem.vue
packages/nc-gui/components/smartsheet/sidebar/index.vue
packages/nc-gui/components/tabs/Smartsheet.vue
packages/nc-gui/composables/useDialog/index.ts
packages/nc-gui/composables/useKanbanViewStore.ts
packages/nc-gui/composables/useViews.ts
packages/nc-gui/context/index.ts
packages/nc-gui/lang/en.json

fix(nc-gui): lazy load breaking views sidebar

---

packages/nc-gui/components/template/Editor.vue
packages/nc-gui/utils/parsers/ExcelTemplateAdapter.ts

ref: #3036
set the date format (guess from the data) when creating a date column

fix(nc-gui): handle date_format in import

---

packages/nc-gui/components/smartsheet/Cell.vue
packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/composables/useViewData.ts

- fixes injection error when adding new table and filling out fields

fix(nc-gui): remove `useMetas` from cb fn

---

packages/nc-gui/components/general/NocoIcon.vue
packages/nc-gui/components/general/PoweredBy.vue

- ping animation on logo click
https://user-images.githubusercontent.com/78412429/195593247-38120bc9-7173-4dc5-a3a8-8a453dcb4aff.mov

feat(nc-gui): add ping animation to logo on click

---

.github/workflows/ci-cd.yml
.github/workflows/release-pr.yml

Ref -https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre/67939898#67939898

Github action - Cancel any previous ci-cd action in same PR / branch

---

packages/nc-gui/assets/style.scss
packages/nc-gui/components/erd/Flow.vue
packages/nc-gui/components/erd/RelationEdge.vue
packages/nc-gui/components/erd/TableNode.vue
packages/nc-gui/components/erd/View.vue
packages/nc-gui/components/erd/utils.ts
packages/nc-gui/package-lock.json
packages/nc-gui/package.json

- update vue flow to latest pkg version
- use v-model for elements
- fixes issue where edges aren't rendered on initial erd mount
- check if table exists before creating corresponding edge
- defer fitView transition so it appears correctly
- add min/max zoom values so we can properly fit the view with multiple tables
- move erd element setup logic into a separate file

chore(nc-gui): update to latest vue flow pkg

---

packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/composables/useViewData.ts
packages/nc-gui/lib/types.ts
packages/nc-gui/pages/[projectType]/[projectId]/index/index/[type]/[title]/[[viewTitle]].vue

- Only allow expanding button after completing any ongoing insert/update on row.
- Show loading overlay while table meta is fetching
- Avoid duplicate row creation when editing a record while ongoing insert API call.
re #4087 , #4080

Fix: Grid view - miscellaneous bugs

---

packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/composables/useMultiSelect/index.ts

- Avoid overlapping with sticky header
- If first column include # column in view as well
- If last row include 'Add New Row' in view as well
https://user-images.githubusercontent.com/59797957/195978223-74d7104d-4390-49c3-ab56-db78e7414083.mp4

feat: better scroll for borders and sticky header

---

packages/nc-gui/components/cell/Currency.vue
packages/nc-gui/components/smartsheet/Cell.vue
packages/nc-gui/composables/useColumn.ts

fix: handle currency cell manual save

---

.gitignore
packages/nocodb/src/lib/Noco.ts
packages/nocodb/src/lib/meta/api/projectApis.ts

feat: NC_MINIMAL_DBS env variable

---

packages/nc-gui/composables/useViewData.ts

After update overwrite only required cells ( virtual columns )
re #4103

Fix: Grid view - avoid overwriting cell value after update

---

packages/nc-gui/components/virtual-cell/Formula.vue

fix(nc-gui): formula values unexpectedly wrapped by double quotes

---

packages/nc-gui/components/cell/Checkbox.vue

fix(nc-gui): checkbox unclickable

---

packages/nc-gui/components/template/Editor.vue

fix: template editor delete 

---

packages/nc-cli/package-lock.json
packages/nc-cli/package.json
packages/nc-cli/src/lib/mgr/NewMgr.ts

- remove unnecessary build commands
- remove unnecessary `t` flag in NC_DB

refactor: nc-cli

---

packages/nc-gui/components/cell/Duration.vue

fix: duration issues

---

packages/nocodb/src/lib/utils/projectAcl.ts

Signed-off-by: 诗人的咸鱼 <willnewii@163.com>

typo-galleryViewGet

---

packages/nc-gui/pages/index/index/create-external.vue
packages/nc-gui/utils/projectCreateUtils.ts

fix: ssl mode mapping

---

packages/nc-gui/components/smartsheet/ApiSnippet.vue
packages/nc-gui/components/smartsheet/Cell.vue
packages/nc-gui/components/smartsheet/column/EditOrAddProvider.vue
packages/nc-gui/components/smartsheet/header/Cell.vue
packages/nc-gui/components/smartsheet/header/VirtualCell.vue
packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue
packages/nc-gui/components/smartsheet/toolbar/ViewActions.vue
packages/nc-gui/components/tabs/auth/UserManagement.vue
packages/nc-gui/components/tabs/auth/user-management/UsersModal.vue
packages/nc-gui/components/virtual-cell/components/ListChildItems.vue
packages/nc-gui/composables/useSmartsheetStore.ts
packages/nc-gui/package-lock.json
packages/nc-gui/package.json
packages/nc-gui/pages/[projectType]/form/[viewId]/index/index.vue
packages/nc-gui/pages/forgot-password.vue
packages/nc-gui/pages/signup/[[token]].vue

chore(nc-gui): fix index access with undefined

---

packages/nc-gui/package-lock.json
packages/nc-gui/package.json

chore(nc-gui): update nuxt to latest RC

---

.github/workflows/release-timely-executables.yml

Executable build - generate sqlite binaries for multiple platforms

---

packages/nocodb/src/lib/db/sql-client/lib/mysql/mysql.queries.ts
packages/nocodb/src/lib/db/sql-client/lib/pg/PgClient.ts
packages/nocodb/src/lib/db/sql-client/lib/sqlite/SqliteClient.ts

Set default database encoding/charset to utf8

---

packages/nc-gui/components/cell/attachment/index.vue

Pass attachment cell data as JSON string.
re #4294

Fix: Attachment cell - removing attachment error

---

packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/composables/useViewData.ts

- Pass the correct column list to get the primary key
- Handle undefined as null in the update
re #4291

Fix: Grid view - tab switching error

---

packages/nc-gui/components/cell/attachment/Carousel.vue
packages/nc-gui/components/cell/attachment/index.vue
packages/nc-gui/components/cell/attachment/utils.ts
packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/composables/useViewData.ts

Miscellaneous bug fixes

---

packages/nc-gui/components/dashboard/TreeView.vue

Treeview: reset search input on close and focus on load

---

packages/nc-gui/components/smartsheet/Form.vue

Block only required column renaming event.
re #4304 

Fix: Form view - required column reordering

---

packages/nc-gui/composables/useViewFilters.ts

fix flitersync typo

---

packages/nc-gui/components/smartsheet/sidebar/index.vue
packages/nc-gui/composables/useProject.ts
scripts/cypress/integration/common/4c_form_view_detailed.js

When switching between tables, make it so that switching back to a table opens last opened view

Save and restore last opened view

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/mysql.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/sqlite.ts

ref: #4343
Formula: `RIGHT({ClientId}, LEN({ClientId})-SEARCH({ClientId}," "))`

fix(nocodb): wrap the second argument in formula RIGHT

---

packages/nc-gui/composables/useColumnCreateStore.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts

Validations on colunns like email is not working in backend. This PR fixes it. It also reset validation when you change column type, eg. email from singleLineText.

Fix column validations

---

packages/nc-gui/middleware/auth.global.ts

fix(nc-gui): ref access in auth middleware

---

packages/nocodb/src/lib/plugins/backblaze/Backblaze.ts
packages/nocodb/src/lib/plugins/gcs/Gcs.ts
packages/nocodb/src/lib/plugins/linode/LinodeObjectStorage.ts
packages/nocodb/src/lib/plugins/mino/Minio.ts
packages/nocodb/src/lib/plugins/ovhCloud/OvhCloud.ts
packages/nocodb/src/lib/plugins/s3/S3.ts
packages/nocodb/src/lib/plugins/scaleway/ScalewayObjectStorage.ts
packages/nocodb/src/lib/plugins/spaces/Spaces.ts
packages/nocodb/src/lib/plugins/upcloud/UpoCloud.ts
packages/nocodb/src/lib/plugins/vultr/Vultr.ts
packages/nocodb/src/lib/utils/pluginUtils.ts

As titled. Cater https://github.com/nocodb/nocodb/issues/4213#issuecomment-1307258844

feat(nocodb): write temp file to os.tmpdir() instead of process.cwd

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts

fix(nocodb): fail to update records with multiple primary keys

---

packages/nc-gui/components/smartsheet/expanded-form/Header.vue
tests/playwright/pages/Base.ts
tests/playwright/pages/Dashboard/ExpandedForm/index.ts
tests/playwright/pages/Dashboard/Grid/index.ts
tests/playwright/playwright.config.ts
tests/playwright/tests/expandedFormUrl.spec.ts

ref: #4328
e.g. 
```
/nc/p_rusa3xz42sgrqu/table/test%20table/test%20table?rowId=1
```

fix(nc-gui): encode copy record url

---

packages/nocodb/src/lib/plugins/backblaze/Backblaze.ts
packages/nocodb/src/lib/plugins/linode/LinodeObjectStorage.ts
packages/nocodb/src/lib/plugins/ovhCloud/OvhCloud.ts
packages/nocodb/src/lib/plugins/s3/S3.ts
packages/nocodb/src/lib/plugins/scaleway/ScalewayObjectStorage.ts
packages/nocodb/src/lib/plugins/spaces/Spaces.ts
packages/nocodb/src/lib/plugins/upcloud/UpoCloud.ts
packages/nocodb/src/lib/plugins/vultr/Vultr.ts

[#2918](https://github.com/nocodb/nocodb/issues/2918)

Add content-type to S3-compatible storages

---

packages/nocodb/src/lib/meta/api/swagger/swaggerApis.ts
packages/nocodb/src/lib/meta/api/swagger/swaggerHtml.ts
packages/nocodb/src/lib/utils/projectAcl.ts

Feat: Secure swagger endpoint

---

packages/nc-gui/components/general/language/Menu.vue
packages/nc-gui/components/smartsheet/toolbar/ShareView.vue
packages/nc-gui/lib/types.ts
packages/nc-gui/pages/[projectType]/form/[viewId].vue
packages/nc-gui/plugins/a.i18n.ts
packages/nc-gui/utils/viewUtils.ts

- apply locale direction on switch, regardless if language component is used
- add new option to force `rtl` direction on forms

fix(nc-gui): apply ltr/rtl direction on language switch

---

packages/nc-gui/assets/style.scss
packages/nc-gui/components.d.ts
packages/nc-gui/components/cell/Text.vue
packages/nc-gui/components/dlg/TableCreate.vue
packages/nc-gui/components/dlg/ViewCreate.vue
packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
packages/nc-gui/components/smartsheet/column/SelectOptions.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/components/smartsheet/toolbar/ShareView.vue
packages/nc-gui/components/tabs/auth/user-management/UsersModal.vue
packages/nc-gui/components/virtual-cell/Lookup.vue
packages/nc-gui/composables/useMultiSelect/index.ts
packages/nc-gui/pages/[projectType]/form/[viewId]/index/survey.vue
packages/nc-gui/pages/index/index/index.vue
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
packages/nocodb/src/lib/models/Model.ts
tests/playwright/pages/Dashboard/common/Toolbar/AddEditKanbanStack.ts

- enter key will create new option in select options
- opening expand form will focus first input(only if input field)
- optional validation was not working( email and phone num)
- some css changes
- create table input focus and selecting default name
- invite user focus to email field

UI improvements and corrections

---

packages/nc-gui/composables/useColumnCreateStore.ts

fix(nc-gui): avoid keeping unnecessary props when switching column type

---

packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue
packages/nc-gui/components/smartsheet/toolbar/ViewActions.vue
packages/nc-gui/composables/useMenuCloseOnEsc/index.ts

feat: Toolbar - close toolbar menu on escape key press

---

packages/nc-gui/components/dlg/TableRename.vue
packages/nc-gui/pages/index/index/create-external.vue
packages/nocodb-sdk/src/lib/Api.ts
scripts/sdk/swagger.json

Fix: Table rename - use user inputed value as alias

---

packages/nc-gui/components/cell/Percent.vue
packages/nc-gui/components/smartsheet/Cell.vue
packages/nc-gui/components/smartsheet/Grid.vue

Fix: Grid - percentage cell bugs

---

packages/nc-gui/components/smartsheet/Grid.vue

Fix: Grid view - tab switch bug

---

packages/nc-gui/composables/useExpandedFormStore.ts
packages/nc-gui/composables/useViewData.ts

fix: shared gallery view

---

packages/nc-gui/components/smartsheet/toolbar/KanbanStackEditOrAdd.vue
packages/nc-gui/components/smartsheet/toolbar/StackedBy.vue
packages/nc-gui/components/smartsheet/toolbar/ViewActions.vue

- follow up items from #4451
- fix playwright issue (dropdown is still visible after clicking menu item)

feat: toolbar followup

---

packages/nc-gui/components/shared-view/AskPassword.vue

Feat: autofocus password field in password protected shared view

---

packages/nc-gui/app.vue
packages/nocodb/src/lib/meta/api/swagger/redocHtml.ts

Fix: Re-render page if navigation error thrown

---

packages/noco-docs/content/en/engineering/development-setup.md
packages/noco-docs/content/en/engineering/repository-structure.md
packages/noco-docs/content/en/engineering/testing.md
packages/noco-docs/content/en/setup-and-usages/account-settings.md
packages/noco-docs/content/en/setup-and-usages/app-store.md
packages/noco-docs/content/en/setup-and-usages/audit.md
packages/noco-docs/content/en/setup-and-usages/expanded-form.md
packages/noco-docs/content/en/setup-and-usages/meta-management.md
packages/noco-docs/content/en/setup-and-usages/table-operations.md
packages/noco-docs/content/en/setup-and-usages/team-and-auth.md
packages/noco-docs/content/en/setup-and-usages/views.md

docs: nocodb documentation

---

packages/nc-gui/assets/style.scss
packages/nc-gui/components/account/UserList.vue
packages/nc-gui/components/account/UsersModal.vue
packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/cell/SingleSelect.vue
packages/nc-gui/components/smartsheet/column/SelectOptions.vue
packages/nc-gui/composables/useColumnCreateStore.ts

Refactor: Grid - Single/Multi select followup

---

packages/nc-gui/components/tabs/auth/user-management/UsersModal.vue
packages/nc-gui/pages/index/index/[projectId].vue
packages/nc-gui/pages/index/index/create.vue
packages/nc-gui/pages/index/index/user.vue
tests/playwright/pages/Account/ChangePassword.ts
tests/playwright/pages/Account/Users.ts
tests/playwright/pages/Account/index.ts
tests/playwright/pages/Dashboard/Grid/index.ts
tests/playwright/pages/Dashboard/Settings/Teams.ts
tests/playwright/pages/Dashboard/TreeView.ts
tests/playwright/pages/Dashboard/WebhookForm/index.ts
tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts
tests/playwright/pages/Dashboard/common/Toolbar/index.ts
tests/playwright/pages/Dashboard/index.ts
tests/playwright/pages/ProjectsPage/ChangePassword.ts
tests/playwright/pages/ProjectsPage/index.ts
tests/playwright/tests/accountUserSettings.spec.ts
tests/playwright/tests/authChangePassword.spec.ts
tests/playwright/tests/metaSync.spec.ts
tests/playwright/tests/toolbarOperations.spec.ts
tests/playwright/tests/viewGridShare.spec.ts
tests/playwright/tests/viewKanban.spec.ts

- Switched to `data-testid` as html attribute for Dom selection.
- Minor cleanups

refactor(test): Playwright followup

---

packages/nc-gui/components/smartsheet/toolbar/SearchData.vue
packages/nc-gui/composables/useFieldQuery.ts
packages/nc-gui/composables/useSmartsheetStore.ts

feat: useFieldQuery

---

packages/nc-gui/components/smartsheet/expanded-form/index.vue

fix(nc-gui): focus on the first input in expanded form nextTick

---

packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/cell/SingleSelect.vue

fix(nc-gui): set show-search always true

---

packages/nocodb/src/lib/models/SelectOption.ts

ref: #4429
with cache enabled. input a > b > c.

fix(nocodb): return select option in given order

---

packages/nc-gui/app.vue
packages/nc-gui/components/smartsheet/Gallery.vue
packages/nc-gui/components/smartsheet/Kanban.vue
packages/nc-gui/pages/account/index/users.vue
packages/nc-gui/pages/account/index/users/[[nestedPage]].vue
packages/nc-gui/pages/index/index/index.vue
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts

re #4494 + Gallery Display issue

fix(nc-gui): page swtich bug + gallery display bug

---

packages/nc-gui/layouts/default.vue

Fix: Sidebar - add key to sidebar slot to avoid duplicate wrapper elements

---

packages/nc-gui/app.vue
packages/nc-gui/components/smartsheet/header/CellIcon.ts
packages/nc-gui/components/virtual-cell/Lookup.vue
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
packages/nocodb/src/lib/meta/helpers/populateSamplePayload.ts

- change attachment sample payload to array of objects
- add missing convertAttachmentType in different calls
- return object if incoming data is object, else array of objects. 

fix(nocodb): attachment-related issues

---

packages/nocodb/src/lib/meta/api/swagger/helpers/getSwaggerColumnMetas.ts
packages/nocodb/src/lib/meta/api/swagger/helpers/swagger-base.json

fix(swagger): update attachment column type

---

packages/nc-gui/utils/cell.ts

Fix: exclude time and year cell from manual save

---

packages/nc-gui/components/dlg/AirtableImport.vue
packages/nocodb/src/lib/meta/api/index.ts
packages/nocodb/src/lib/meta/api/sync/helpers/readAndProcessData.ts
packages/nocodb/src/lib/meta/api/sync/importApis.ts
packages/nocodb/src/lib/v1-legacy/plugins/adapters/storage/Local.ts

Re #4326
- Job logs provided to room with jobid
- Users are able to (re)connect ongoing job log

feat: reconnect quick import logs

---

packages/nc-gui/components/cell/Currency.vue
packages/nc-gui/components/cell/Decimal.vue
packages/nc-gui/components/cell/Duration.vue
packages/nc-gui/components/cell/Email.vue
packages/nc-gui/components/cell/Float.vue
packages/nc-gui/components/cell/Integer.vue
packages/nc-gui/components/cell/Percent.vue
packages/nc-gui/components/cell/Text.vue
packages/nc-gui/components/cell/TextArea.vue
packages/nc-gui/components/cell/Url.vue

fix(gui): Miscellaneous GUI bugs

---

packages/noco-docs/content/en/setup-and-usages/keyboard-maneuver.md

Docs update about keyboard shortcuts and general usage

docs: keyboard maneuver

---

packages/nc-gui/components/cell/Checkbox.vue
packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/cell/SingleSelect.vue
packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/composables/useColumnCreateStore.ts
packages/nc-gui/composables/useMultiSelect/convertCellData.ts
packages/nc-gui/composables/useMultiSelect/index.ts
packages/nc-gui/lang/en.json
tests/playwright/pages/Dashboard/Grid/Column/index.ts
tests/playwright/pages/Dashboard/common/Cell/DateCell.ts
tests/playwright/pages/Dashboard/common/Cell/index.ts
tests/playwright/scripts/stressTestNewlyAddedTest.js
tests/playwright/tests/gridOperations.spec.ts

Feat: Grid - copy paste cell data

---

packages/nocodb/src/lib/db/sql-client/lib/KnexClient.ts
packages/nocodb/src/lib/db/sql-client/lib/mssql/MssqlClient.ts
packages/nocodb/src/lib/db/sql-client/lib/mysql/MysqlClient.ts
packages/nocodb/src/lib/db/sql-client/lib/oracle/OracleClient.ts
packages/nocodb/src/lib/db/sql-client/lib/pg/PgClient.ts
packages/nocodb/src/lib/db/sql-client/lib/sqlite/SqliteClient.ts
tests/playwright/scripts/stressTestNewlyAddedTest.js
tests/playwright/tests/viewKanban.spec.ts

- Alter table column function for SqliteClient
- Alter PK functions revised / made functional
- Drop PK
- Alter NOT NULL
ref: #869 #4380 #1263

feat: sqlite alter table change column

---

.github/workflows/ci-cd.yml
packages/nc-gui/components/smartsheet/header/Menu.vue
packages/nc-gui/lang/en.json
tests/playwright/pages/Dashboard/Grid/Column/index.ts
tests/playwright/pages/Dashboard/common/Cell/index.ts
tests/playwright/tests/columnDuplicate.spec.ts
tests/playwright/tests/columnMenuOperations.spec.ts

test: Field menu followup - playwright test

---

packages/nc-gui/composables/useMultiSelect/convertCellData.ts
packages/nc-gui/plugins/tele.ts

Add validation for rating field when pasting value to rating field

fix(gui): Grid - add rating validation while pasting

---

packages/nc-gui/components/smartsheet/Grid.vue

fix: Grid - Sync unsaved data properly when switching tab

---

packages/nc-gui/composables/useMultiSelect/index.ts
packages/nc-gui/utils/columnUtils.ts

Avoid clearing cell data if active cell is non-typable.
re #4493

fix(gui): avoid clearing cell data if it's a non-typable column

---

packages/nocodb/src/lib/meta/api/userApi/ui/auth/resetPassword.ts
packages/nocodb/src/lib/v1-legacy/rest/ui/auth/resetPassword.ts

ref: #4570 
- include error message

feat(nocodb): include error message for resetting password

---

packages/nc-gui/components/virtual-cell/components/ListItems.vue
packages/nc-gui/utils/browserUtils.ts

fix(nc-gui): unexpected focus on ListItem 

---

packages/nc-gui/components/smartsheet/column/FormulaOptions.vue

fix(nc-gui): retrieve the correct column name based on the formula

---

packages/nocodb-sdk/src/lib/formulaHelpers.ts

fix(nocodb-sdk): include node.value for literal case

---

.github/uffizzi/docker-compose.uffizzi.yml
packages/nocodb-sdk/.cspell.json

Add other DBs to Uffizzi preview

Add other DBs to uffizzi preview

---

packages/nc-gui/components/template/Editor.vue

fix(nc-gui): parse string date if date is not null

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts

when column_name is 'id' , title is 'Id'.  
call API '/api/v1/db/data/bulk/noco/:projectId/:tableId'  delete
body
```json
[{"Id":47}]
```
will get error 'delete from \"XXXX\" where \"Id\" = $1 - column \"Id\" does not exist'

fix: can’t find Id

---

.github/workflows/release-docker.yml
packages/nc-gui/components/general/ReleaseInfo.vue
packages/noco-docs/content/en/engineering/builds-and-releases.md
packages/nocodb/package-lock.json
packages/nocodb/package.json
packages/nocodb/src/lib/meta/api/utilApis.ts

- Release Docker Github Action
- if it is a pre-release, then we don't tag `latest` but `x.x.x-beta.latest`
- UI Component - Version Upgrade
- if it is a pre-release, then release info will not be shown.
The naming convention would be following given the actual release tag is `0.100.0`
- `0.100.0-beta.1` (first version of pre-release)
- `0.100.0-beta.2` (include bug fix changes on top of the previous version)
- `0.100.0-beta.3`(include bug fix changes on top of the previous version)
-  and so on ...
- `0.100.0` (actual release)
- `0.100.1` (minor bug fix release)
- `0.100.2` (minor bug fix release)

feat: pre-release

---

.github/uffizzi/docker-compose.uffizzi.yml

Add support for other DBs in Uffizzi instance of nocodb. 

Update uffizzi compose with other dbs

---

packages/nocodb/src/lib/meta/api/apiTokenApis.ts

Delete token is generating an error because of an incorrect parameter. This PR is fixing it.

Correct parameter in delete token

---

packages/nc-gui/components/tabs/auth/UserManagement.vue

Users Management search result can’t paging
https://user-images.githubusercontent.com/652003/209300037-67e59141-582d-4555-8e87-2c1648939a84.mp4

fix: search result can’t paging

---

packages/nocodb-sdk/src/lib/enums.ts
packages/nocodb/src/lib/meta/api/attachmentApis.ts
packages/nocodb/tests/unit/rest/index.test.ts
packages/nocodb/tests/unit/rest/tests/attachment.test.ts

fix(gui): GUI - allow attachment upload if user have permission

---

packages/nc-gui/components/dlg/AirtableImport.vue
packages/nc-gui/pages/[projectType]/[projectId]/index/index.vue
packages/nocodb/src/lib/meta/api/sync/helpers/fetchAT.ts
packages/nocodb/src/lib/meta/api/sync/helpers/job.ts
packages/nocodb/src/lib/meta/api/sync/importApis.ts

Re #3927
If baseId is not found in given URL (shared view etc.) raise an error including instructions to get proper link.

fix: proper error if provided url is not shared base

---

packages/nocodb/src/lib/meta/api/filterApis.ts

Filter get API is not working. This PR is fixing it.

fix get filter by id API

---

packages/nc-gui/components/dashboard/TreeView.vue
packages/nc-gui/components/smartsheet/toolbar/ShareView.vue
packages/nc-gui/pages/index/index/index.vue

Fix:  GUI Treeview - table icon toggling in multi datasource view

---

packages/nc-gui/components/dashboard/TreeView.vue
packages/nc-gui/composables/useProject.ts
packages/nc-gui/pages/index/index/[projectId].vue

Re #4722 
- Change useRoute in useProject composable to vue-router one (https://github.com/nuxt/framework/issues/6646)
- Disable lazy load in TreeView as it makes injectionState inconsistent for useProject

fix: route problems after editing project name

---

tests/playwright/pages/Dashboard/common/Cell/DateTimeCell.ts

date picker configuration for date-time column based tests
None

test: date picker configuration

---

packages/nc-gui/lib/enums.ts

Please, add Slovak language to Crowdin, too.

Add sk language

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/pg.ts

ref: #4732
```
SUBSTR({title5}, 1, 4)
```

fix(nocodb): SUBSTR for postgres

---

packages/nocodb/src/lib/meta/api/sync/helpers/job.ts

fix: at import barcode type

---

packages/nocodb/src/lib/db/sql-client/lib/mysql/mysql.queries.ts

ref: #4763 
Tested with DB created from PlanetScale

fix(nocodb): symbol col.table_name not found

---

packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/cell/SingleSelect.vue

fix(nc-gui): single multi select behaviours based on roles

---

packages/nc-gui/components/cell/Currency.vue
packages/nc-gui/components/cell/Json.vue
packages/nc-gui/components/cell/Percent.vue
packages/nc-gui/composables/useMultiSelect/index.ts

Fix - Miscellaneous bugs

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/sqlite.ts
tests/playwright/tests/columnFormula.spec.ts

ref: #4778 
- cater `NOW()` case
- cater literal case
- add test cases

fix(nocodb): formula datetime diff for sqlite

---

packages/nc-gui/components/smartsheet/Gallery.vue
packages/nc-gui/components/smartsheet/Kanban.vue

fix(nc-gui): show LTAR record in view for users to add even it is empty

---

packages/nc-gui/composables/useSharedFormViewStore.ts
packages/nocodb-sdk/src/lib/Api.ts
scripts/sdk/swagger.json

Fix:Broken shared form view

---

.github/workflows/release-executables.yml

- add the missing `draft` to `softprops/action-gh-release@v1`. otherwise it will create a new release.

fix(workflow): add draft mode

---

markdown/readme/languages/korean.md

docs(readme): fix korean expressions

---

packages/nc-gui/components/smartsheet/toolbar/ShareView.vue

Updates iframe snippet of the embedded shared view. Makes it possible to place multiple iframes on a single page.
- [ x ] fix: (bug fix for the user, not a fix to a build script)

fix iframe issue with multiple embedded views

---

packages/nc-gui/composables/useViewData.ts

fix(nc-gui): get public gallery data from sharedView.view

---

.github/workflows/release-nightly-dev.yml

chore(action): extract current version from package.json

---

packages/nc-gui/components.d.ts
packages/nc-gui/components/cell/Checkbox.vue
packages/nc-gui/components/dashboard/settings/Modal.vue
packages/nc-gui/components/smartsheet/Gallery.vue
packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/smartsheet/expanded-form/Header.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
packages/nc-gui/composables/useApi/interceptors.ts
packages/nc-gui/composables/useGlobal/actions.ts
packages/nc-gui/composables/useSharedView.ts
packages/nc-gui/composables/useViewData.ts
packages/nc-gui/lang/en.json
packages/nc-gui/lib/enums.ts
packages/nc-gui/pages/[projectType]/form/[viewId]/index/index.vue
packages/nc-gui/utils/filterUtils.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/conditionV2.ts
packages/nocodb/src/lib/meta/helpers/webhookHelpers.ts
packages/nocodb/src/lib/models/Filter.ts
packages/nocodb/src/lib/utils/projectAcl.ts
packages/nocodb/src/lib/version-upgrader/ncFilterUpgrader.ts
tests/playwright/pages/Account/AppStore.ts
tests/playwright/pages/Account/index.ts
tests/playwright/pages/Dashboard/Settings/index.ts
tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts
tests/playwright/tests/columnCheckbox.spec.ts
tests/playwright/tests/viewForm.spec.ts

fix: Miscellaneous bugs

---

tests/playwright/pages/Dashboard/Grid/Column/SelectOptionColumn.ts
tests/playwright/pages/Dashboard/Grid/Column/index.ts
tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts
tests/playwright/pages/Dashboard/common/Toolbar/Sort.ts
tests/playwright/tests/columnCheckbox.spec.ts
tests/playwright/tests/columnMultiSelect.spec.ts
tests/playwright/tests/columnSingleSelect.spec.ts
tests/playwright/tests/keyboardShortcuts.spec.ts
tests/playwright/tests/metaSync.spec.ts
tests/playwright/tests/toolbarOperations.spec.ts
tests/playwright/tests/viewGridShare.spec.ts
tests/playwright/tests/viewKanban.spec.ts

refactor: tests better org & clean-up

---

packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/utils/filterUtils.ts
packages/nocodb-sdk/src/lib/sqlUi/MssqlUi.ts
packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
packages/nocodb-sdk/src/lib/sqlUi/OracleUi.ts
packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts
packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts
packages/nocodb-sdk/src/lib/sqlUi/SqliteUi.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/conditionV2.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/sortV2.ts
tests/playwright/tests/columnCheckbox.spec.ts
tests/playwright/tests/columnRating.spec.ts

- In descending order show `null` values at bottom 
- In ascending order show `null` values at top 

fix: Set sort order of nulls in postgres

---

packages/nocodb/src/lib/db/sql-client/lib/mysql/MysqlClient.ts

Re #4625
- Change NULL as text to NULL for MariaDB

fix: MariaDB default value

---

tests/playwright/tests/columnCheckbox.spec.ts
tests/playwright/tests/columnMultiSelect.spec.ts

filter & sort for multiselect
Verified for SQLite

test: filter & sort for multiselect

---

packages/nc-gui/components/account/License.vue
packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/composables/useGlobal/actions.ts
packages/nc-gui/composables/useGlobal/types.ts
packages/nc-gui/composables/useMultiSelect/index.ts
packages/nc-gui/pages/account/index.vue

- Allow arrow key navigation in input fields in filter/fields search/search
- Allow whitespace key in input fields in filter/fields search/search
- Ctrl/Cmd + Arrow navigation correction
re #4916 

Fix: Grid view - keydown event handler issues

---

.run/test-debug.run.xml
tests/playwright/pages/Account/License.ts
tests/playwright/pages/Account/index.ts
tests/playwright/tests/accountLicense.spec.ts

test case for enterprise key addition & verification (check if snowflake menu appears)
Locally verified for SQLite

test: enterprise key verification

---

packages/nc-gui/components/dashboard/settings/DataSources.vue
packages/nc-gui/components/dashboard/settings/Erd.vue
packages/nc-gui/components/dashboard/settings/Modal.vue
packages/nc-gui/components/erd/FullScreenToggle.vue
packages/nc-gui/components/erd/View.vue
packages/nc-gui/components/erd/utils.ts

Ref: #4616
- Fixed issue where ERD was being overflowed due to incorrect height
- Fixed close button styling issue on settings modal
- Added fullscreen toggle button to the top left corner

feat(nc-gui): Added fullscreen support to ERD

---

packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/cell/SingleSelect.vue
packages/nc-gui/composables/useMultiSelect/index.ts

isPg, isMysql etc. from useProject are functions, corrected some typos related to that.

fix: isPg, isMysql calls

---

packages/nc-gui/components/cell/ClampedText.vue

Error when trying to access Film table in PG

test: clamped text issue with pg

---

packages/nocodb/src/lib/version-upgrader/ncAttachmentUpgrader.ts

fix: handle invalid attachment json in migrator

---

packages/nc-gui/composables/useKanbanViewStore.ts

ref: #4895
- add missing field query logic to kanban view
[screen-capture (12).webm](https://user-images.githubusercontent.com/35857179/215242441-f346c279-dd88-440e-b5ce-064ce67de22a.webm)

fix(nc-gui): field query in kanban view

---

tests/playwright/pages/Dashboard/Grid/index.ts

cell selection copy paste tests often are flaky. hence introducing retry logic
Retry logic added; locally verified

test: cell selection retry logic to avoid flakiness

---

packages/nocodb/src/lib/version-upgrader/ncAttachmentUpgrader.ts

- Skip missing columns and tables
- Ignore errors thrown by deleted projects
re #4819

fix: upgrader errors

---

packages/nc-gui/components/smartsheet/Grid.vue

The conditions are lacking reactivity which leads to stale data.
https://user-images.githubusercontent.com/31967149/215182027-709ae1a3-2be2-4891-98f5-78cf1f41eaee.mov

fix condition for row-column adding

---

packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/smartsheet/Cell.vue
packages/nc-gui/components/smartsheet/TableDataCell.vue
packages/nc-gui/context/index.ts

#4968 
https://github.com/nocodb/nocodb/pull/4957#issuecomment-1411614532

fix: Grid view - multi select improvements and fixes

---

packages/nc-gui/components/cell/Checkbox.vue
packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/cell/SingleSelect.vue
packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/smartsheet/TableDataCell.vue
packages/nc-gui/composables/useProject.ts
packages/nc-gui/context/index.ts
tests/playwright/tests/columnMultiSelect.spec.ts

fix: Grid view - Single-select/Multi-select related bugs and improvements

---

packages/nc-gui/components/smartsheet/Grid.vue

fix(gui): on new row creation using shortcut set the first cell as active

---

packages/nc-gui/components/cell/ClampedText.vue

fix(gui): use key to re-render whenever the cell value changes

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/genRollupSelectv2.ts

fix(gui): use a unique alias in rollup query to avoid conflict

---

packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/smartsheet/VirtualCell.vue
packages/nc-gui/components/virtual-cell/components/ListItems.vue
packages/nc-gui/context/index.ts

fix(gui): save new row even if user set LTAR column first

---

packages/nc-gui/components/cell/ClampedText.vue
packages/nc-gui/components/cell/TextArea.vue
packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/virtual-cell/QrCode.vue
packages/nc-gui/components/virtual-cell/barcode/Barcode.vue
packages/nc-gui/context/index.ts

Re #4992 #5020
- RowHeightInj to share row height setting between components
- Use debounced refresh on resize observer call (ClampedText)
- Use text length instead of full text as key (ClampedText)

fix: row height optimization

---

packages/noco-docs/content/en/getting-started/upgrading.md
packages/noco-docs/content/en/setup-and-usages/app-store.md

Update upgrading details to prevent accidental data deletion.
Update App Store details.

docs: update upgrading and app store details

---

packages/nc-gui/assets/style.scss
packages/nc-gui/components/account/Token.vue
packages/nc-gui/components/account/UserList.vue
packages/nc-gui/components/account/UsersModal.vue
packages/nc-gui/components/smartsheet/ApiSnippet.vue
packages/nc-gui/components/smartsheet/toolbar/ShareView.vue
packages/nc-gui/components/smartsheet/toolbar/SharedViewList.vue
packages/nc-gui/components/tabs/auth/ApiTokenManagement.vue
packages/nc-gui/components/tabs/auth/UserManagement.vue
packages/nc-gui/components/tabs/auth/user-management/ShareBase.vue
packages/nc-gui/components/tabs/auth/user-management/UsersModal.vue
packages/nc-gui/components/template/Editor.vue
packages/nc-gui/composables/useCopy.ts
packages/nc-gui/pages/[projectType]/[projectId]/index.vue
packages/nc-gui/pages/index/index/index.vue

fix: if copy failed show error message and show content in dialog(optional)

---

packages/nc-gui/components/smartsheet/header/Menu.vue

fix: reload table data after duplicating a column

---

packages/nc-gui/components.d.ts
packages/nc-gui/components/template/Editor.vue
packages/nc-gui/composables/useApi/interceptors.ts
packages/nc-gui/composables/useGlobal/actions.ts
packages/nc-gui/composables/useGlobal/index.ts
packages/nc-gui/middleware/auth.global.ts
packages/nocodb/src/lib/meta/api/userApi/userApis.ts

- Open token generation api(remove acl)
- On route change try to get a new token using the refresh token API before navigating to login page
fixes #3792

fix: Refresh token based token generation not working

---

.github/workflows/cleanup-caches-by-branch.yml

feat(workflow): cleanup github action caches after pr merge

---

packages/nc-gui/components/smartsheet/header/Menu.vue

-  [x] feat: (new feature for the user, not a new feature for build script)

feat: Allow user to set formula as display value

---

packages/nc-gui/components/smartsheet/Grid.vue

feat: row numbering based on page

---

.github/workflows/ci-cd.yml
tests/playwright/scripts/docker-compose-mysql-playwright.yml

- Increase CI-CD timeout
- docker compose for mysql configured with port numbers

test: increase ci-cd timeout, docker compose correction

---

packages/nc-gui/assets/style.scss
packages/nc-gui/components.d.ts
packages/nc-gui/components/smartsheet/expanded-form/Header.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/composables/useExpandedFormStore.ts
tests/playwright/pages/Dashboard/ExpandedForm/index.ts
tests/playwright/tests/expandedFormUrl.spec.ts

refactor(gui): Expanded form header changes

---

packages/noco-docs/content/en/engineering/playwright.md
packages/nocodb/package-lock.json
packages/nocodb/package.json
tests/playwright/pages/Account/ChangePassword.ts
tests/playwright/pages/Base.ts
tests/playwright/pages/Dashboard/ExpandedForm/index.ts
tests/playwright/pages/Dashboard/Grid/Column/LTAR/ChildList.ts
tests/playwright/pages/Dashboard/Grid/Column/index.ts
tests/playwright/pages/Dashboard/Grid/index.ts
tests/playwright/pages/Dashboard/Import/ImportTemplate.ts
tests/playwright/pages/Dashboard/Settings/Acl.ts
tests/playwright/pages/Dashboard/Settings/Miscellaneous.ts
tests/playwright/pages/Dashboard/TreeView.ts
tests/playwright/pages/Dashboard/ViewSidebar/index.ts
tests/playwright/pages/Dashboard/WebhookForm/index.ts
tests/playwright/pages/Dashboard/common/Cell/RatingCell.ts
tests/playwright/pages/Dashboard/common/Cell/index.ts
tests/playwright/pages/Dashboard/common/Toolbar/Fields.ts
tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts
tests/playwright/pages/Dashboard/common/Toolbar/Sort.ts
tests/playwright/pages/Dashboard/common/Toolbar/index.ts
tests/playwright/pages/ProjectsPage/index.ts
tests/playwright/pages/SharedForm/index.ts

Make flaky playwright tests stable.

chore(test): playwright test 

---

tests/playwright/pages/Base.ts
tests/playwright/tests/filters.spec.ts

PW tests for LTAR, Lookup, Rollup filters

test: filters for ltar, lookup

---

packages/nc-gui/components/template/Editor.vue
packages/nc-gui/composables/useColumnCreateStore.ts
packages/nc-gui/lang/en.json
packages/nc-gui/utils/validation.ts
packages/nocodb/src/lib/meta/api/columnApis.ts
packages/nocodb/src/lib/meta/api/tableApis.ts
packages/nocodb/src/lib/models/Column.ts

Add missing validator to check the column length
- closes: #1387 
- closes #5130

feat(nc-gui): fieldLengthValidator

---

.github/workflows/release-executables.yml
.github/workflows/release-timely-executables.yml
packages/nocodb/Dockerfile
packages/nocodb/docker/webpack.config.js
packages/nocodb/src/lib/meta/api/dataApis/dataAliasApis.ts
packages/nocodb/src/lib/meta/api/helpers/apiHelpers.ts
packages/nocodb/src/lib/meta/api/helpers/index.ts
packages/nocodb/webpack.config.js

- Disable replacing `__dirname` while taking build
- Update public file copy path
- Exclude nocodb repo from modclean
re #5125

fix: production build wrong public files path 

---

tests/playwright/pages/Dashboard/index.ts
tests/playwright/tests/swagger.spec.ts

test: swagger

---

packages/noco-docs/content/en/FAQs.md
packages/noco-docs/content/en/index.md
packages/noco-docs/content/en/setup-and-usages/app-store.md

Update docs: app store directory correction, add social links.

[docs]: Update docs: app store directory correction, add social links.

---

packages/nocodb/src/lib/meta/api/attachmentApis.ts
packages/nocodb/src/lib/meta/api/helpers/cacheHelpers.ts
packages/nocodb/src/lib/meta/api/helpers/index.ts

Set cache header for attachments for faster loading.

feat(nocodb): set cache header for attachment urls

---

packages/nocodb/src/lib/version-upgrader/ncAttachmentUpgrader.ts
packages/nocodb/src/lib/version-upgrader/ncAttachmentUpgrader_0104002.ts
packages/nocodb/src/lib/version-upgrader/ncUpgradeErrors.ts

- revise upgrade error message for timeout case

feat: upgrade timeout msg

---

packages/nocodb/src/lib/db/sql-client/lib/oracle/OracleClient.ts
packages/nocodb/src/lib/db/sql-mgr/SqlMgr.ts
packages/nocodb/src/lib/db/sql-mgr/v2/SqlMgrv2.ts
packages/nocodb/src/lib/db/sql-mgr/v2/SqlMgrv2Trans.ts
packages/nocodb/src/lib/db/sql-migrator/lib/KnexMigratorv2.ts
packages/nocodb/src/lib/db/sql-migrator/lib/KnexMigratorv2Tans.ts
packages/nocodb/src/lib/meta/NcMetaMgr.ts
packages/nocodb/src/lib/meta/api/tableApis.ts
packages/nocodb/src/lib/utils/common/BaseApiBuilder.ts
packages/nocodb/src/lib/utils/common/NcConnectionMgr.ts
packages/nocodb/src/lib/utils/common/NcConnectionMgrv2.ts

- Correct types instead of any
- fix broken clientType calls

fix: ts types for sql clients

---

packages/nc-gui/lib/constants.ts

fix(nc-gui): add missing filterChildrenRead permission

---

packages/nc-gui/components/virtual-cell/components/ListItems.vue

Avoid closing the LTAR model if the element is added by holding ALT/OPT key.

feat(gui): Support multiple record mapping without closing LTAR modal

---

.github/workflows/release-timely-executables.yml

chore(action): setup node version

---

packages/nc-gui/components/cell/SingleSelect.vue

- sync with multi-select
- fix focus issue (closes #5179)

fix(nc-gui): single select issues

---

packages/nc-gui/components/smartsheet/expanded-form/index.vue

fix: Nested expanded form single/multi select field issue

---

packages/nc-gui/composables/useMultiSelect/index.ts
tests/playwright/tests/keyboardShortcuts.spec.ts

fix: Grid - avoid toggling editEnabled on mouse down event

---

packages/nc-gui/components/dlg/TableCreate.vue
packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
packages/nc-gui/pages/index/index/create.vue

fix: Disable button to avoid duplicate api call when creating column, project and table

---

packages/noco-docs/content/en/setup-and-usages/column-types.md

docs: update column types

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/formulav2/formulaQueryBuilderv2.ts

- closes #5220
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.105.3**

fix(nocodb): escape ? for raw sql query

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/conditionV2.ts

fix(nocodb): blank logic for LTAR columns

---

packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
packages/nc-gui/components/smartsheet/toolbar/FilterInput.vue
tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts

fix(nc-gui): reset filter value to null instead

---

packages/nc-gui/components/webhook/Drawer.vue

webhook no reset when addHook
https://user-images.githubusercontent.com/652003/221913441-a0108195-1a82-4394-9475-ebda289629f4.mp4

fix: webhook no reset when addHook

---

packages/nc-gui/components/smartsheet/expanded-form/index.vue

ref:  #5049
Autosave record when press next row.
https://www.loom.com/share/7baa328ca53f4ab8a98ed96fe14845e7

fix: No autosave when moving to "Next Row" in expanded record view

---

packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/lib/models/GridView.ts
packages/nocodb/src/lib/models/KanbanView.ts
packages/nocodb/src/lib/models/KanbanViewColumn.ts
packages/nocodb/src/schema/swagger.json

refactor(nocodb): APIs

---

packages/nc-gui/components/webhook/Editor.vue
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/schema/swagger.json

fix: Missing slack channel list in webhook 

---

packages/nocodb/src/lib/models/GridViewColumn.ts

fix(nocodb): add missing insert props

---

packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
packages/nc-gui/components/webhook/Editor.vue
packages/nc-gui/composables/useGlobal/state.ts
packages/nc-gui/composables/useGlobal/types.ts
packages/nc-gui/pages/account/index.vue
packages/nc-gui/pages/account/index/[page].vue
packages/nocodb/src/lib/controllers/plugin.ctl.ts
packages/nocodb/src/lib/services/column.svc.ts
packages/nocodb/src/lib/services/hook.svc.ts
packages/nocodb/src/lib/services/util.svc.ts

Refactor: disable app store and hasmany relation based on env

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts

fix(nocodb): sanitize / unsanitize logic

---

.github/workflows/ci-cd.yml
packages/nocodb/package.json
packages/nocodb/tests/unit/.pg.env
packages/nocodb/tests/unit/TestDbMngr.ts
packages/nocodb/tests/unit/factory/column.ts
packages/nocodb/tests/unit/factory/project.ts
packages/nocodb/tests/unit/init/cleanupMeta.ts
packages/nocodb/tests/unit/init/cleanupSakila.ts
packages/nocodb/tests/unit/init/db.ts
packages/nocodb/tests/unit/model/tests/baseModelSql.test.ts
packages/nocodb/tests/unit/rest/tests/tableRow.test.ts
packages/nocodb/tests/unit/rest/tests/viewRow.test.ts

UT in CI-CD was on SQLite. UT for MySQL was supported (but is disabled)
This PR prepares UT for PG

test: ut on pg

---

README.md

chore: readme typos

---

packages/nc-gui/composables/useAttachment.ts

fix(nc-gui): return attachment url even fetch fails

---

packages/nc-gui/components/smartsheet/Grid.vue

fixes: https://github.com/nocodb/nocodb/issues/5304
Locally verified over SQLite root DB

fix: row numbering based on page size configured

---

packages/nc-gui/layouts/base.vue

Removed white text class so that the menu icon is visible.

fix: unhide language menu

---

packages/nc-gui/components/virtual-cell/components/ItemChip.vue
tests/playwright/pages/Account/Users.ts
tests/playwright/pages/Dashboard/Grid/Column/SelectOptionColumn.ts
tests/playwright/pages/Dashboard/Grid/Column/index.ts
tests/playwright/pages/Dashboard/Import/ImportTemplate.ts
tests/playwright/pages/Dashboard/Settings/Metadata.ts
tests/playwright/pages/Dashboard/Settings/Teams.ts
tests/playwright/pages/Dashboard/SurveyForm/index.ts
tests/playwright/pages/Dashboard/TreeView.ts
tests/playwright/pages/Dashboard/ViewSidebar/index.ts
tests/playwright/pages/Dashboard/WebhookForm/index.ts
tests/playwright/pages/Dashboard/common/Cell/index.ts
tests/playwright/pages/Dashboard/common/Toolbar/Actions/index.ts
tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts
tests/playwright/pages/Dashboard/common/Toolbar/ShareView.ts
tests/playwright/pages/Dashboard/common/Toolbar/Sort.ts
tests/playwright/pages/Dashboard/common/Toolbar/ViewMenu.ts
tests/playwright/pages/Dashboard/common/Toolbar/index.ts
tests/playwright/tests/columnLinkToAnotherRecord.spec.ts
tests/playwright/tests/columnMenuOperations.spec.ts
tests/playwright/tests/filters.spec.ts
tests/playwright/tests/metaSync.spec.ts
tests/playwright/tests/rolesPreview.spec.ts
tests/playwright/tests/utils/general.ts

Thin icon related corrections for test suite
Locally verified over SQLite

test: corrections for new icons suite

---

packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/smartsheet/header/VirtualCellIcon.ts
packages/nc-gui/components/smartsheet/toolbar/ShareView.vue
packages/nc-gui/components/webhook/Editor.vue
packages/nc-gui/pages/[projectType]/[projectId]/index.vue
packages/nc-gui/utils/iconUtils.ts

fix: Rollup column icon missing and number column width issue

---

tests/playwright/package-lock.json
tests/playwright/package.json
tests/playwright/pages/Dashboard/TreeView.ts
tests/playwright/tests/filters.spec.ts

use dayjs library to compute oneMonthAgo & oneMonthAfter

test: use dayjs

---

packages/nc-gui/components/smartsheet/expanded-form/index.vue

fix: Expanded form next/prev icon position

---

markdown/readme/languages/README.md

Update link for Portuguese language

Update link for portuguese language

---

packages/nc-gui/components/cell/ClampedText.vue
packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/cell/SingleSelect.vue
packages/nc-gui/components/cell/attachment/index.vue
packages/nc-gui/components/smartsheet/Cell.vue
packages/nc-gui/components/smartsheet/TableDataCell.vue
packages/nc-gui/components/smartsheet/VirtualCell.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/components/smartsheet/toolbar/AddRow.vue
packages/nc-gui/composables/useSmartsheetStore.ts
packages/nc-gui/composables/useViewData.ts
packages/nc-gui/context/index.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/commonFns.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/mssql.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/mysql.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/pg.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/functionMappings/sqlite.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/mapFunctionName.ts
tests/playwright/pages/Dashboard/Kanban/index.ts
tests/playwright/pages/Dashboard/common/Cell/AttachmentCell.ts
tests/playwright/pages/Dashboard/common/Cell/RatingCell.ts
tests/playwright/pages/Dashboard/common/Cell/SelectOptionCell.ts
tests/playwright/pages/Dashboard/common/Cell/index.ts
tests/playwright/tests/columnAttachments.spec.ts
tests/playwright/tests/megaTable.spec.ts

refactor: Formula query builder optimization

---

packages/nc-gui/components/cell/MultiSelect.vue

fix: Maintain multi select option order

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/formulav2/formulaQueryBuilderv2.ts

#5420
- Avoid querying incomplete queries

fix: formula LTAR column references

---

packages/nc-gui/composables/useGlobal/actions.ts
packages/nocodb/src/lib/controllers/user/user.ctl.ts
packages/nocodb/src/lib/services/user/index.ts

- add missing sign out logic 
- closes: #5361 
- closes: #5459
TODO:
- sync to nest branch after merge

fix(nc-gui): sign out issue

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/helpers/convertDateFormat.ts
packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/helpers/formulaFnHelper.ts

fix: formula concat

---

packages/nocodb/src/lib/plugins/vultr/Vultr.ts
packages/nocodb/src/lib/plugins/vultr/index.ts

fix: vultr plugin

---

tests/playwright/tests/columnFormula.spec.ts

test: formula verification for OR, AND, IF, SEARCH

---

packages/nc-gui/components/dlg/TableCreate.vue

fix(nc-gui): table alias across bases

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts

- the error occurs when we start a transaction with calls like readByPk. This PR is to move the transaction logic after that.
- closes: #5467 
See the linked issue for the command

fix(nocodb): bulk update transaction

---

packages/nc-gui/components/smartsheet/DivDataCell.vue
packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/pages/[projectType]/form/[viewId]/index/index.vue
packages/nc-gui/pages/[projectType]/form/[viewId]/index/survey.vue

fix(nc-gui): drag n drop attachment cell

---

packages/nc-gui/components/smartsheet/DivDataCell.vue
packages/nc-gui/components/smartsheet/TableDataCell.vue

fix(nc-gui): select issue in grid view

---

packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/helpers/getAst.ts

- if a column is pv, then we should show it anyway
- closes: #5424

fix(nocodb): extract pv object

---

packages/nocodb/src/lib/migrations/XcMigrationSourcev2.ts
packages/nocodb/src/lib/migrations/v2/nc_030_add_description_field.ts

Add description field to following tables

feat: add description field to meta tables

---

packages/nocodb-nest/src/app.module.ts

fix: create meta db if missing

---

packages/nocodb-nest/src/guards/global/global.guard.ts
packages/nocodb-nest/src/strategies/authtoken.strategy/authtoken.strategy.ts
packages/nocodb-nest/src/strategies/jwt.strategy.ts

fix: api-token strategy correction

---

packages/nocodb-nest/src/db/BaseModelSqlv2.ts
packages/nocodb-nest/src/services/public-datas.service.ts

fix(nocodb): allow gallery to access hm / bt / mm list

---

packages/nocodb/src/Noco.ts
packages/nocodb/src/app.module.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/modules/event-emitter/event-emitter.interface.ts
packages/nocodb/src/modules/event-emitter/event-emitter.module.ts
packages/nocodb/src/modules/event-emitter/fallback-event-emitter.ts
packages/nocodb/src/modules/event-emitter/nestjs-event-emitter.ts
packages/nocodb/src/modules/metas/metas.module.ts
packages/nocodb/src/services/hook-handler.service.spec.ts
packages/nocodb/src/services/hook-handler.service.ts
tests/playwright/tests/db/01-webhook.spec.ts

feat: Use event emitter for webook

---

.gitignore
build-local-docker-image.sh
packages/nocodb/.gitignore
packages/nocodb/Dockerfile.local
packages/nocodb/src/run/local.ts

fix local docker and utility image build script

---

packages/nocodb/src/filters/global-exception/global-exception.filter.ts

Add error logging to the global exception filter of new nest.js backend. 
Will enable terminal error logging of the BE. 

add error logging in nest global exception filter

---

packages/nocodb/src/db/functionMappings/sqlite.ts

- introduced by previous query optimisation PR 
- add missing await and builder
```
DATEADD({d}, 1, "day")
```

fix(nocodb): DATEADD formula in sqlite

---

packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts

fix(nocodb): dateadd formula with negative offset

---

packages/nocodb/src/db/functionMappings/sqlite.ts

fix(nocodb): datetime diff result format in sqlite

---

packages/nc-gui/composables/useSharedFormViewStore.ts

- Previously columns were using model columns while help text is in form column. 
- closes: #5633

fix(nc-gui): incorrect columns in shared form

---

packages/nocodb/src/schema/swagger.json

- closes: #5606
- previously the input is bounded to 255 characters while it could be longer. hence, unset the max length.

fix(nocodb): plugin input type

---

packages/nc-gui/components/cell/SingleSelect.vue
packages/nocodb/src/Noco.ts

- Singleselect new Option create based on click event
- Singleselect search input width issue
Includes an unrelated change - missing middleware added.

Fix: GUI - search input field width issue and option create issue

---

tests/playwright/pages/Dashboard/common/Cell/SelectOptionCell.ts
tests/playwright/pages/Dashboard/common/Toolbar/index.ts
tests/playwright/tests/db/undo-redo.spec.ts

- Undo-redo: increase delay (kludge)
- Select : wait for response to ensure new in-cell insert option is completed before validation
- Attachment : wait for field toggle dropdown menu to appear explicitly

test: remove PW flakyness - undo-redo, attachment, select column

---

packages/nocodb/src/Noco.ts
packages/nocodb/src/app.module.ts
packages/nocodb/src/modules/global/global.module.ts
packages/nocodb/src/services/app-init.service.spec.ts
packages/nocodb/src/services/app-init.service.ts
packages/nocodb/src/utils/NcConfigFactory.ts

fix: Load JWT secret from store on app init

---

packages/nocodb/src/Noco.ts

fix: Read env file on app app load

---

packages/nc-gui/components/cell/DateTimePicker.vue
packages/nc-gui/composables/useMultiSelect/index.ts
packages/nc-gui/utils/cell.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/db/functionMappings/mssql.ts
packages/nocodb/src/models/Model.ts

fix: datetime followup

---

packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
packages/nocodb-sdk/src/lib/formulaHelpers.ts
packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/db/mapFunctionName.ts
tests/playwright/tests/db/columnFormula.spec.ts

enhancement: case insensitive formula

---

packages/nocodb/src/strategies/authtoken.strategy/authtoken.strategy.ts

fix(nocodb): assign dbuser id n roles to user

---

packages/nocodb/src/db/BaseModelSqlv2.ts

fix: rollback transaction if bulk insert errors

---

packages/nocodb/src/utils/nc-config/NcConfig.ts

fix: Set fallback dashboard path while creating config

---

packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/schema/swagger.json

fix: filter groups

---

packages/nc-gui/components/smartsheet/Gallery.vue
packages/nc-gui/components/smartsheet/header/Cell.vue
packages/nc-gui/components/virtual-cell/BelongsTo.vue
packages/nc-gui/components/virtual-cell/HasMany.vue
packages/nc-gui/components/virtual-cell/Lookup.vue
packages/nc-gui/components/virtual-cell/ManyToMany.vue
packages/nc-gui/composables/useApi/interceptors.ts
packages/nc-gui/context/index.ts
packages/nocodb/src/services/public-metas.service.ts

closes #5766
- Extract all necessary metas
- Avoid redirecting to sign in page if user is in a public page

fix: include lookup related metas in shared view meta api

---

packages/nc-gui/composables/useGridViewColumnWidth.ts

fix: Allow changing column width in shared grid view

---

packages/nocodb/src/Noco.ts
packages/nocodb/src/utils/nc-config/NcConfig.ts

fix: remove envs props from config which is no longer in use

---

tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts
tests/playwright/tests/db/filters.spec.ts

test: filter groups

---

packages/nc-gui/components/cell/Currency.vue
packages/nc-gui/components/cell/DateTimePicker.vue
packages/nc-gui/components/cell/Decimal.vue
packages/nc-gui/components/cell/Duration.vue
packages/nc-gui/components/cell/Email.vue
packages/nc-gui/components/cell/Float.vue
packages/nc-gui/components/cell/Integer.vue
packages/nc-gui/components/cell/Percent.vue
packages/nc-gui/components/cell/Text.vue
packages/nc-gui/components/cell/TextArea.vue
packages/nc-gui/components/cell/Url.vue
packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
packages/nocodb-sdk/src/lib/sqlUi/MssqlUi.ts
packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
packages/nocodb-sdk/src/lib/sqlUi/OracleUi.ts
packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts
packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts
packages/nocodb/src/controllers/caches.controller.ts

- Provide a default value for inject
- Handle null cases for datatype props
- Make property optional
- Use reactive variable properly with `.value`
- Add missing authguard ( backend)
- Remove non-existing component refrence

fix: Browser console warnings/errors

---

packages/noco-docs/content/en/setup-and-usages/column-types.md

fix(noco-docs): apply NuxtLink on incorrect links

---

packages/nocodb/src/models/Model.ts
packages/nocodb/src/models/View.ts
packages/nocodb/src/modules/datas/helpers.ts
packages/nocodb/tests/unit/rest/tests/viewRow.test.ts

fix: Clear alias cache when renaming table/view

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/tests/unit/model/tests/baseModelSql.test.ts

fix: Read api - if record is missing return null

---

packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/composables/useMultiSelect/index.ts

fix: make cell selectable and skip paste behaviour if not permitted

---

packages/nc-gui/components/smartsheet/Grid.vue

Re #5838
Note: we might consider changing selected range to activeCell only as well, waiting feedback from @dstala on this

fix: avoid clearing selected range on expand

---

packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/smartsheet/Pagination.vue
packages/nc-gui/composables/useMultiSelect/index.ts
tests/playwright/pages/Dashboard/Grid/index.ts
tests/playwright/tests/db/tableColumnOperation.spec.ts

enhancement: sticky add new row

---

packages/nc-gui/components/dashboard/TreeView.vue
packages/nc-gui/components/smartsheet/Gallery.vue
packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
packages/nc-gui/components/smartsheet/column/EditOrAddProvider.vue
packages/nc-gui/components/tabs/Smartsheet.vue
packages/nc-gui/components/virtual-cell/HasMany.vue
tests/playwright/tests/db/columnLtarDragdrop.spec.ts

feat: Drag n drop LTAR and Lookup creation

---

packages/nocodb/src/controllers/test/TestResetService/resetMetaSakilaSqliteProject.ts

For non-sakila db projects, create them as meta db projects instead of existing external DB projects

test: use meta-db project for non-sakila db

---

packages/nc-gui/components/smartsheet/Grid.vue
tests/playwright/pages/Dashboard/Grid/index.ts

Remove delete confirm dialog

---

packages/nocodb/src/services/datas.service.ts
packages/nocodb/tests/unit/rest/tests/tableRow.test.ts
packages/nocodb/tests/unit/rest/tests/viewRow.test.ts

on delete fail due to presence of links, return error instead of 200 OK

fix: on delete fail, return error instead of 200 OK

---

packages/nocodb/src/db/sql-client/lib/mssql/MssqlClient.ts
packages/nocodb/src/db/sql-client/lib/pg/PgClient.ts

fix: Filter view list based on current schema in pg and mssql

---

packages/nc-gui/composables/useViewData.ts

fix: avoid adding undo if delete fails

---

packages/nc-gui/composables/useUIPermission/index.ts
packages/nc-gui/pages/index/index/index.vue
packages/nocodb/src/models/ProjectUser.ts

fix: Show project action icons based project role

---

packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/composables/useViewData.ts

- Save any unsaved data on tab close, view switch, table switch or data reload
- Fix error related to adding an empty row and switching to another table(sometimes it used to show an error message)

fix: save any unsaved data on tab close, view switch, table switch or data reload

---

packages/nc-gui/components/virtual-cell/Links.vue
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/genRollupSelectv2.ts
packages/nocodb/src/helpers/columnHelpers.ts
packages/nocodb/src/models/Column.ts
packages/nocodb/src/models/LinkToAnotherRecordColumn.ts
packages/nocodb/src/models/LinksColumn.ts
packages/nocodb/src/models/index.ts
packages/nocodb/src/services/columns.service.ts
packages/nocodb/src/services/data-alias-nested.service.ts

refactor: Avoid extra LTAR column creation and make Links as an extended version of LTAR

---

packages/nc-gui/pages/index/index/index.vue
tests/playwright/pages/ProjectsPage/index.ts
tests/playwright/tests/db/rolesCreate.spec.ts

project menu role access verification

test: project menu role access

---

packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
packages/nc-gui/composables/useColumnCreateStore.ts
packages/nc-gui/composables/useTable.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/sql-client/lib/sqlite/SqliteClient.ts
packages/nocodb/src/db/sql-mgr/v2/ProjectMgrv2.ts
packages/nocodb/src/db/sql-mgr/v2/SqlMgrv2.ts
packages/nocodb/src/meta/meta.service.ts
packages/nocodb/src/middlewares/extract-project-id/extract-project-id.middleware.ts
packages/nocodb/src/models/Column.ts
packages/nocodb/src/models/Model.ts
packages/nocodb/src/models/Project.ts
packages/nocodb/src/models/View.ts
packages/nocodb/src/modules/global/init-meta-service.provider.ts
packages/nocodb/src/services/columns.service.ts
packages/nocodb/src/services/datas.service.ts
packages/nocodb/src/services/tables.service.ts
packages/nocodb/src/version-upgrader/NcUpgrader.ts
packages/nocodb/src/version-upgrader/ncFilterUpgrader_0104004.ts
packages/nocodb/src/version-upgrader/ncXcdbLTARUpgrader.ts
packages/nocodb/tests/unit/rest/tests/tableRow.test.ts
packages/nocodb/tests/unit/rest/tests/viewRow.test.ts
tests/playwright/pages/Dashboard/Grid/index.ts
tests/playwright/setup/xcdbProject.ts
tests/playwright/tests/db/metaLTAR.spec.ts
tests/playwright/tests/db/timezone.spec.ts

refactor: MetaDB LTAR revamp 

---

packages/nocodb/src/version-upgrader/ncFilterUpgrader_0104004.ts

fix: revert commit changes made on ncFilterUpgrader_0104004

---

packages/nc-gui/composables/useGlobal/actions.ts
packages/nocodb/src/controllers/users/users.controller.ts
packages/nocodb/src/services/users/users.service.ts

fix: signOut API

---

packages/nocodb/src/version-upgrader/ncXcdbLTARUpgrader.ts

While deleting foreign key provide constraint name if available

fix:  LTAR upgrader bug

---

packages/nc-gui/composables/useLTARStore.ts

fix: Instead of title/alias use id with nested apis to avoid unexpected behaviour

---

packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/cell/SingleSelect.vue
packages/nc-gui/components/dashboard/TreeView.vue
packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
packages/nc-gui/composables/useColumnCreateStore.ts
packages/nc-gui/composables/useMetas.ts
packages/nc-gui/pages/[projectType]/form/[viewId]/index/index.vue
packages/nc-gui/pages/[projectType]/form/[viewId]/index/survey.vue
packages/nocodb/src/db/sql-mgr/v2/ProjectMgrv2.ts
packages/nocodb/src/meta/meta.service.ts
packages/nocodb/src/models/Model.ts
packages/nocodb/src/models/View.ts
packages/nocodb/src/services/columns.service.ts
packages/nocodb/src/services/tables.service.ts
packages/nocodb/src/services/users/users.service.ts

fix: Skip relation delete if it's a virtual relation

---

tests/playwright/setup/demoTable.ts
tests/playwright/tests/db/filters.spec.ts

Re-usable table creation routines for PW tests

test: add demo table as sub routine

---

packages/nc-gui/composables/useViewData.ts
tests/playwright/tests/db/undo-redo.spec.ts

feat: recover LTAR when undoing delete

---

packages/nc-gui/components/cell/DatePicker.vue
packages/nc-gui/components/cell/DateTimePicker.vue

fix: On selecting day close Datepicker

---

.github/workflows/playwright-test-workflow.yml
packages/nocodb/package.json

mysql as root DB for mysql suite

test: mysql as root DB for mysql suite

---

tests/playwright/tests/db/projectOperations.spec.ts
tests/playwright/tests/db/tableOperations.spec.ts
tests/playwright/tests/utils/objectCompareUtil.ts

Import https://github.com/nocodb/nocodb/pull/5848/commits/586ec48872a849d2e04165d5ebc7743b59760f7a

test/fix: project duplicate suite

---

packages/nocodb/src/version-upgrader/ncXcdbLTARUpgrader.ts

fix: LTAR upgrader bug

---

packages/nc-gui/components/cell/Currency.vue
packages/nc-gui/components/cell/Decimal.vue
packages/nc-gui/components/cell/Duration.vue
packages/nc-gui/components/cell/Email.vue
packages/nc-gui/components/cell/Float.vue
packages/nc-gui/components/cell/Integer.vue
packages/nc-gui/components/cell/Percent.vue
packages/nc-gui/components/cell/Text.vue
packages/nc-gui/components/cell/TextArea.vue
packages/nc-gui/components/cell/Url.vue

Disable UI undo while editing a cell

fix: prevent undo while editing

---

packages/nc-gui/components/cell/DatePicker.vue
packages/nc-gui/components/cell/DateTimePicker.vue
packages/nc-gui/components/cell/TimePicker.vue
packages/nc-gui/components/cell/YearPicker.vue
packages/nc-gui/components/smartsheet/Grid.vue
packages/nc-gui/components/smartsheet/TableDataCell.vue
packages/nc-gui/composables/useMultiSelect/cellRange.ts
packages/nc-gui/composables/useMultiSelect/index.ts
tests/playwright/pages/Dashboard/common/Cell/AttachmentCell.ts
tests/playwright/pages/Dashboard/common/Cell/RatingCell.ts
tests/playwright/pages/Dashboard/common/Cell/SelectOptionCell.ts
tests/playwright/pages/Dashboard/common/Cell/TimeCell.ts
tests/playwright/setup/xcdb-records.ts
tests/playwright/tests/db/verticalFillHandle.spec.ts

- fill handle on selected range corner
- allow filling records vertically using handle

feat: vertical fill using handle

---

packages/nc-gui/components/cell/attachment/index.vue
packages/nc-gui/components/smartsheet/header/Icon.vue
packages/nc-gui/components/smartsheet/toolbar/SearchData.vue
packages/nc-gui/composables/useExpandedFormStore.ts

General UI/UX - enhancement/bugs

---

README.md

Missing "OutFile" to save the Windows binaries.

Update README.md - Missing "OutFile" to save the Windows binaries.

---

packages/nc-gui/components/smartsheet/expanded-form/Header.vue

fix: use custom useCopy composable for copy

---

packages/nocodb/src/models/Column.ts
packages/nocodb/src/services/meta-diffs.service.ts

feat: Identify removed/added primary key in meta sync

---

packages/nocodb/src/services/users/users.service.ts

fix: Avoid generating invalid token after signout

---

packages/nc-gui/components/smartsheet/Pagination.vue

Here is the GitStart Ticket for this pull request: [NCDBOSS-57](https://developers.gitstart.com/client/nocodb-oss/ticket/NCDBOSS-57)
- Please mark your PR as "ready for review" when you have completed all requirements.
- Please ensure that your PR is reviewed by at least 2 people after you have completed it.
- Comments for review or requested changes from the upstream client will be notified to you by email and will also show on the [ticket page](https://developers.gitstart.com/client/nocodb-oss/ticket/NCDBOSS-57).
- After the PR is merged on the upstream, please merge this PR.
- If there exist merge conflicts on your current PR and you have to close the PR instead of merging it, please go to the [ticket page](https://developers.gitstart.com/client/nocodb-oss/ticket/NCDBOSS-57) to …

NCDBOSS-57 - 🐛 Bug: the position of "next" and "previous" buttons in forms is confusing for RTL languages

---

packages/noco-docs/content/en/developer-resources/upload-via-api

Documentation : Upload and Upload via API

chore: upload api documentation

---

build-local-docker-image.sh

chore : remove prev container & build

---

packages/nc-gui/components/smartsheet/Grid.vue

fix: GUI performance issue when switching from grid view to a non-grid view

---

packages/nocodb/src/helpers/webhookHelpers.ts

fix: test webhook on condition

---

packages/noco-docs/content/en/setup-and-usages/display-value.md

typos display-value

---

packages/noco-docs/content/en/setup-and-usages/table-operations.md

Fix a typo. Clarify. Add LibreOffice ODS import.

typos. Import ODS

---

.github/workflows/playwright-test-workflow.yml

- [ x] chore: (updating grunt tasks etc; no production code change)

pw tests on sh runner

---

markdown/readme/languages/indonesian.md

README is up-to-date and translated on sync with the English Version

docs(readme): update readme translation for Indonesian

---

packages/nocodb/src/utils/projectAcl.ts

fix(nocodb): allow filterChildrenList to editor role

---

packages/nocodb/src/db/BaseModelSqlv2.ts

- closes: #6186
- add missing convertDateFormat logic in groupedList data

fix(nocodb): apply convertDateFormat in groupedList data

---

packages/nocodb/src/db/BaseModelSqlv2.ts

fix(nocodb): pg datetime

---

packages/nc-gui/pages/signin.vue
packages/nc-gui/pages/signup/[[token]].vue

Autocomplete Email Login & Signup

---

packages/nc-gui/components/smartsheet/Gallery.vue

Implemented search for gallery view

fix(nc-gui): search implemented for gallery view

---

packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/components/smartsheet/header/Cell.vue

fix: removed edit option of cell in locked view

---

.github/workflows/playwright-test-workflow.yml

- [x ] chore: (updating grunt tasks etc; no production code change)

pw logs in self hosted runner

---

packages/nc-gui/components/smartsheet/sidebar/MenuTop.vue
packages/nc-gui/components/smartsheet/sidebar/index.vue
packages/nc-gui/utils/domUtils.ts

Closes https://github.com/nocodb/nocodb/issues/6301

 Fixed view scroll not coming and auto scroll on active view

---

packages/nc-gui/components/dashboard/settings/DataSources.vue
packages/nc-gui/components/dashboard/settings/data-sources/CreateBase.vue
packages/nc-gui/components/dlg/ViewCreate.vue
packages/nc-gui/components/nc/Button.vue
packages/nc-gui/components/nc/Tabs.vue
packages/nc-gui/components/project/AccessSettings.vue
packages/nc-gui/components/project/AllTables.vue
packages/nc-gui/components/project/InviteProjectCollabSection.vue
packages/nc-gui/components/smartsheet/toolbar/GroupByMenu.vue
packages/nc-gui/components/workspace/CollaboratorsList.vue

fix: warnings in ui

---

packages/nocodb/src/controllers/caches.controller.ts
packages/nocodb/src/utils/acl.ts

fix: acl for cache apis

---

packages/nocodb/src/cache/RedisCacheMgr.ts
packages/nocodb/src/cache/RedisMockCacheMgr.ts
packages/nocodb/src/controllers/tables.controller.ts
packages/nocodb/src/models/ModelRoleVisibility.ts
packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
packages/nocodb/src/services/tables.service.ts
packages/nocodb/src/services/views.service.ts

Fix  : Broken UI ACL

---

packages/nocodb/src/middlewares/extract-ids/extract-ids.middleware.ts
packages/nocodb/src/strategies/authtoken.strategy/authtoken.strategy.ts

fix: assign project_roles for apitoken
