nocodb/nocodb

packages/nc-gui/components/feed/Changelog/Item.vue
packages/nc-gui/components/feed/Recents/Card.vue
packages/nc-gui/lib/types.ts

fix: changelog images

---

packages/nc-gui/components/cell/attachment/utils.ts

Attachment followup

---

packages/nc-gui/composables/useData.ts
packages/nc-gui/composables/useKanbanViewStore.ts
packages/nc-gui/composables/useLTARStore.ts
packages/nc-gui/utils/dataUtils.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/helpers/catchError.ts
packages/nocodb/src/services/data-table.service.ts
packages/nocodb/src/strategies/base-view.strategy/base-view.strategy.ts

fix: Handle primary key value with 3 or more consecutive underscore

---

packages/nc-gui/components/general/FormBranding.vue
packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/components/smartsheet/details/Fields.vue

fix(nc-gui): allow user to submit form in locked view

---

packages/nc-gui/components/nc/MenuItem.vue
packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue

fix(nc-gui): UI Error on toggle locked view

---

packages/nc-gui/components/cell/TextArea.vue
packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
packages/nc-gui/components/dashboard/TreeView/index.vue
packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
packages/nc-gui/components/smartsheet/column/EditOrAddProvider.vue
packages/nc-gui/components/smartsheet/details/Fields.vue
packages/nc-gui/components/smartsheet/header/VirtualCell.vue
packages/nc-gui/components/smartsheet/toolbar/ViewInfo.vue
packages/nc-gui/components/virtual-cell/components/ItemChip.vue
packages/nc-gui/components/workspace/Menu.vue
packages/nc-gui/utils/cell.ts

Miscellaneous fixes and improvements

---

packages/nc-gui/utils/dataUtils.ts

fix: Grid view expanded form next and prev button bug

---

packages/nc-gui/components/dashboard/settings/data-sources/CreateBase.vue
packages/nc-gui/components/dashboard/settings/data-sources/EditBase.vue
packages/nc-gui/components/workspace/integrations/forms/EditOrAddDatabase.vue
packages/nc-gui/utils/baseCreateUtils.ts
packages/nocodb/src/db/util/Result.ts
packages/nocodb/src/filters/global-exception/global-exception.filter.ts
packages/nocodb/src/helpers/catchError.ts

Test connection improvements

---

packages/nc-gui/components/dlg/share-and-collaborate/SharePage.vue
packages/nc-gui/components/nc/MenuItem.vue
packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue
packages/nc-gui/composables/useSharedFormViewStore.ts

fix(nc-gui): prefill form decode query param issue

---

packages/nc-gui/components/cell/attachment/Preview/Pdf.vue

Disable open with Google Docs for PDF

feat: load pdf with browser by default

---

packages/nocodb/src/services/columns.service.ts

Nc refactor/bettter jn table name

---

packages/nc-gui/composables/useCalendarViewStore.ts

fix: data in sidebar not getting updated

---

packages/nocodb/src/plugins/gcs/Gcs.ts
packages/nocodb/src/plugins/gcs/index.ts

Closes https://github.com/nocodb/nocodb/issues/9712

fix: gcs uniform bucket_level access

---

packages/nocodb/src/services/columns.service.ts

fix: Handle duplicate column name issue in junction table

---

packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue
packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue

Closes https://github.com/nocodb/nocodb/issues/9558

fix: Calendar current time cursor is in the wrong place

---

packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/survey.vue

fix:submit button blocking issue in survey form

---

packages/nc-gui/components/cell/attachment/Carousel.vue
packages/nc-gui/components/cell/attachment/Preview/Image.vue
packages/nc-gui/components/cell/attachment/Preview/MiscOffice.vue
packages/nc-gui/components/cell/attachment/Preview/Pdf.vue
packages/nc-gui/components/cell/attachment/Preview/Video.vue
packages/nc-gui/utils/attachmentUtils.ts

[Provide summary of changes with issue number if any.
](fix: reload row if the attachments are expired)

fix: reload row if the attachments are expired

---

packages/nocodb/src/db/conditionV2.ts

Fixes blank and not blank filter for formula

fix: handle blank and notblank for formulas

---

packages/nocodb/src/services/columns.service.ts

- Closes https://github.com/nocodb/nocodb/issues/9760

fix: Populate index name to avoid duplicate index names for long table names

---

packages/noco-docs/docs/070.fields/040.field-types/060.formula/050.conditional-expressions.md

docs: operator list mentioend explicitly

---

packages/nc-gui/components/monaco/formula.ts

fix: Formula - special character in identifier bug

---

packages/nc-gui/composables/useMultiSelect/index.ts

fix: copy rows is broken in infinite scroll

---

packages/nc-gui/components/dlg/ExpandTable.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/components/smartsheet/grid/index.vue
packages/nc-gui/composables/useGridViewData.ts
packages/nc-gui/composables/useInfiniteData.ts
packages/nc-gui/composables/useMultiSelect/index.ts
packages/nc-gui/lang/en.json
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/controllers/bulk-data-alias.controller.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/schema/swagger.json
packages/nocodb/src/services/bulk-data-alias.service.ts
packages/nocodb/src/utils/tsUtils.ts
tests/playwright/pages/Dashboard/Grid/ExpandTable.ts
tests/playwright/pages/Dashboard/Grid/index.ts
tests/playwright/tests/db/features/keyboardShortcuts.spec.ts

feat: row expansion

---

packages/nc-gui/components/smartsheet/Topbar.vue
packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/composables/useExtensionHelper.ts
packages/nc-gui/composables/useExtensions.ts
packages/nc-gui/lib/enums.ts

Nc extension url preview

---

packages/nc-gui/composables/useMultiSelect/index.ts

fix: remove selection

---

packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue

fix(extensions): url-preview: emit event from `<InfiniteTable/>`

---

packages/nc-gui/composables/useApi/interceptors.ts
packages/nc-gui/composables/useGlobal/actions.ts
packages/nc-gui/composables/useGlobal/index.ts
packages/nc-gui/composables/useGlobal/types.ts
packages/nc-gui/middleware/02.auth.global.ts
packages/nc-gui/store/notification.ts
packages/nc-gui/utils/ncUtils.ts
packages/nocodb/src/constants/index.ts
packages/nocodb/src/db/CustomKnex.ts
packages/nocodb/src/models/UserRefreshToken.ts
packages/nocodb/src/services/users/helpers.ts
packages/nocodb/src/services/users/users.service.ts

closes: https://github.com/nocodb/nocodb/issues/9311

refactor: Token generation improvements and corrections 

---

packages/nc-gui/components/smartsheet/header/VirtualCell.vue

fix: Resolve bug in computed tooltip extraction logic

---

packages/nc-gui/components/general/Gift.vue
packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
packages/nc-gui/composables/useApi/interceptors.ts
packages/nc-gui/composables/useGlobal/types.ts
packages/nc-gui/utils/dataUtils.ts
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/helpers/populateSamplePayload.ts
packages/nocodb/src/models/Column.ts
packages/nocodb/src/services/hooks.service.ts

Nc fix/miscellaneous bug fixes

---

packages/nc-gui/components/dashboard/settings/DataSources.vue
packages/nc-gui/components/dashboard/settings/UIAcl.vue
packages/nc-gui/lang/en.json

Nc fix/misc UI changes

---

packages/nocodb/src/services/calendars.service.ts
packages/nocodb/src/services/forms.service.ts
packages/nocodb/src/services/galleries.service.ts
packages/nocodb/src/services/maps.service.ts

- Expect user object to be null while populating default base.

fix: Default base creation bug

---

README.md
markdown/readme/languages/chinese.md
markdown/readme/languages/dutch.md
markdown/readme/languages/french.md
markdown/readme/languages/german.md
markdown/readme/languages/hindi.md
markdown/readme/languages/indonesian.md
markdown/readme/languages/italian.md
markdown/readme/languages/japanese.md
markdown/readme/languages/korean.md
markdown/readme/languages/portuguese.md
markdown/readme/languages/russian.md
markdown/readme/languages/spanish.md
markdown/readme/languages/ukrainian.md
markdown/readme/languages/vietnamese.md

fix: update installation instructions

---

packages/nocodb/Dockerfile

Re: https://github.com/nocodb/nocodb/actions/runs/11907802586/job/33184131324

chore: Add `py3-setuptools` for sqlite3 binary build

---

packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
packages/nocodb/src/meta/migrations/v2/nc_068_user_delete.ts

feat: account delete migration

---

packages/nc-gui/components/dlg/ViewCreate.vue
packages/nc-gui/components/smartsheet/PlainCell.vue
packages/nc-gui/components/smartsheet/calendar/DateTimeSpanningContainer.vue
packages/nc-gui/components/smartsheet/calendar/DayView/DateField.vue
packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue
packages/nc-gui/components/smartsheet/calendar/MonthView.vue
packages/nc-gui/components/smartsheet/calendar/RecordCard.vue
packages/nc-gui/components/smartsheet/calendar/SideMenu.vue
packages/nc-gui/components/smartsheet/calendar/SideRecordCard.vue
packages/nc-gui/components/smartsheet/calendar/VRecordCard.vue
packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue
packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
packages/nc-gui/components/smartsheet/toolbar/Calendar/Mode.vue
packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue
packages/nc-gui/composables/useBetaFeatureToggle.ts
packages/nc-gui/lang/en.json
packages/nc-gui/lib/types.ts
tests/playwright/pages/Dashboard/Calendar/CalendarMonth.ts
tests/playwright/tests/db/views/viewCalendar.spec.ts

Add support for calendar end Date
Closes https://github.com/nocodb/nocodb/issues/9785

Nc calendar end date

---

packages/nc-gui/components/smartsheet/Form.vue

fix(nc-gui): form view elements over the attachment/pdf viewer

---

packages/noco-docs/docs/140.account-settings/030.authentication/030.SAML-SSO/040.azure-ad.md

docs: Nested list and commented lines corrections

---

packages/nc-gui/composables/useApi/interceptors.ts
packages/nc-gui/composables/useSharedExecutionFn.ts

fix: Handle sharedExecution timeout error in interceptor

---

packages/nc-gui/components/feed/View.vue

fix: hide twitter feed

---

packages/nocodb/src/db/BaseModelSqlv2.ts

- Closes https://github.com/nocodb/nocodb/issues/9439

fix: One-to-one excluded list filter bug

---

packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/cell/SingleSelect.vue

Closes https://github.com/nocodb/nocodb/issues/9902

fix: data is missing when select option is added via cell

---

packages/nocodb/src/services/base-users/base-users.service.ts
packages/nocodb/src/services/base-users/ui/emailTemplates/org-invite.ts
packages/nocodb/src/services/org-users.service.ts

- Re https://github.com/nocodb/nocodb/pull/8529#issuecomment-2120168307
- Closes https://github.com/nocodb/nocodb/issues/8460

fix: Base invite email related issues

---

packages/nc-gui/components/cell/Decimal.vue

fix(nc-gui): decimal cell thousands separator display issue

---

packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/nc/Select.vue
packages/nc-gui/composables/useExtensionHelper.ts
packages/nc-gui/composables/useExtensions.ts
packages/nc-gui/utils/dataUtils.ts

Nc org chart extension

---

packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts

fix: disable unsupported arg

---

packages/nc-gui/assets/style.scss
packages/nc-gui/components/account/UserList.vue
packages/nc-gui/components/account/UsersModal.vue

fix(nc-gui): org role selector input display issue

---

packages/nc-gui/components/smartsheet/Kanban.vue
packages/nc-gui/composables/useKanbanViewStore.ts

fix(nc-gui): hide `uncategorized` stack if grouping field is required field

---

packages/nc-gui/components/cell/User.vue
packages/nc-gui/components/dlg/ReAssign/UserItem.vue
packages/nc-gui/components/general/UserIcon.vue
packages/nc-gui/components/project/AccessSettings.vue
packages/nc-gui/components/smartsheet/expanded-form/Sidebar/Audits.vue
packages/nc-gui/components/smartsheet/form/LimitOptions.vue
packages/nc-gui/components/workspace/AuditLogs.vue
packages/nc-gui/components/workspace/CollaboratorsList.vue
packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue

fix(nc-gui): user logo bg color is not same in all the places

---

packages/noco-docs/docs/040.bases/065.snapshots.md

docs : updated Snapshots docs

---

packages/nc-gui/.patches/splitpanes@3.1.5.patch
packages/nc-gui/composables/useExtensions.ts

Persist width and toggle state of extension sidebar, in local storage
feat: (new feature for the user, not a new feature for build script)
For patch details: Ref:
https://github.com/nuxt/learn.nuxt.com/issues/129

feat(ui): persist extension sidebar state per base

---

packages/nc-gui/composables/useExtensions.ts

Add typing for extension's KV Store
chore: (updating grunt tasks etc; no production code change)

fix(extensions): typings for KvStore

---

packages/nc-gui/components/cell/attachment/IconView.vue
packages/nc-gui/components/cell/attachment/Modal.vue
packages/nc-gui/components/cell/attachment/index.vue
packages/nc-gui/components/smartsheet/expanded-form/Sidebar/Audits.vue
packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue
packages/nc-gui/composables/useAttachmentIcon.ts

Nc fix/grid view attachment cell icon size

---

packages/nc-gui/components/cell/RichText.vue

Resolves #9896
fix: (bug fix for the user, not a fix to a build script)

fix(rich-text): map `\n` to `<br/>`

---

packages/nc-gui/components/extensions/Extension/Header.vue
packages/nc-gui/components/extensions/Market.vue
packages/nc-gui/components/extensions/Market/ExtensionsTab.vue
packages/nc-gui/components/extensions/Pane.vue
packages/nc-gui/composables/useExtensions.ts
packages/nc-gui/extensions/data-exporter/index.vue

eventing on extensions
chore: (updating grunt tasks etc; no production code change)

chore(extensions): eventing on extension

---

packages/nocodb/src/models/Base.ts
packages/nocodb/src/models/Source.ts

Nc fix/delete ws

---

packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue

fix: hide calendar

---

packages/nocodb/src/services/columns.service.ts

fix(nc-gui): trim whitespace while converting from string data type to user

---

packages/nc-gui/components/nc/MenuItem.vue

fix (nc-gui): resolve warnings when opening grid header dropdown

---

packages/nc-gui/composables/useInfiniteData.ts

Row ID needs to be encoded to accommodate special characters in the primary key.
The id is encoded before sending the request.

fix: encoded primary key #9615

---

packages/nc-gui/components/cell/SingleSelect.vue
packages/nc-gui/components/cell/TextArea.vue
packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
packages/nc-gui/components/smartsheet/column/FormulaInputHelper.vue
packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/composables/useViewAggregate.ts
packages/nocodb/src/models/Column.ts

- ref: #9912 
- ref(load aggregation on dependency field value change): #9897

fix(nocodb): Bug fixes

---

packages/nc-gui/assets/style.scss
packages/nc-gui/components/cell/RichText.vue
packages/nc-gui/components/cell/RichText/SelectedBubbleMenu.vue
packages/nc-gui/components/cell/TextArea.vue
packages/nc-gui/components/general/WorkspaceIcon.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue

Nc fix/bug fix 5 dec

---

packages/nc-gui/pages/signin.vue
packages/nc-gui/pages/signup/[[token]].vue

fix (nc-gui): use autocomplete attributes on non-ee auth components

---

packages/nc-gui/components/smartsheet/column/ButtonOptions.vue
packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
packages/nc-gui/components/smartsheet/column/LongTextOptions.vue

chore: hide beta

---

packages/nc-gui/components/dlg/share-and-collaborate/ShareBase.vue
packages/nc-gui/components/dlg/share-and-collaborate/SharePage.vue
packages/nocodb/src/run/cloud.ts

fix: Shared url and dashboard url corrections

---

packages/nc-gui/components/cell/DatePicker.vue
packages/nc-gui/components/cell/DateTimePicker.vue
packages/nc-gui/components/cell/TimePicker.vue
packages/nc-gui/components/cell/YearPicker.vue

fix(nc-gui): on blur save cell value of date related fields

---

packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/cell/User.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/components/tabs/auth/user-management/UsersModal.vue
packages/nc-gui/composables/useSelectedCellKeyupListener/index.ts
packages/nc-gui/utils/browserUtils.ts

Nc fix: if cell is active and document.activeElement is different then prevent selectedCellKeyupListner event

---

packages/nc-gui/components/dashboard/FeatureExperimentation.vue
packages/nc-gui/composables/useBetaFeatureToggle.ts

Nc chore(nc-gui): new feature changes

---

packages/nc-gui/components/nc/List/index.vue
packages/nc-gui/components/smartsheet/column/ButtonOptions.vue
packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
packages/nc-gui/components/smartsheet/column/LongTextOptions.vue
packages/nc-gui/components/smartsheet/column/UITypesOptionsWithSearch.vue
packages/nc-gui/components/smartsheet/header/Menu.vue
packages/nc-gui/components/smartsheet/header/UpdateDisplayValue.vue
packages/nocodb-sdk/src/lib/UITypes.ts
packages/nocodb-sdk/src/lib/helperFunctions.ts
packages/nocodb-sdk/src/lib/index.ts

Nc fix/limit display value col

---

packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/cell/Rating.vue
packages/nc-gui/components/cell/TextArea.vue
packages/nc-gui/components/cell/User.vue
packages/nc-gui/components/smartsheet/column/UITypesOptionsWithSearch.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/lib/types.ts
packages/nc-gui/utils/cell.ts
packages/nc-gui/utils/commonUtils.ts

Nc fix/nc longtext cell focus input cell issue

---

packages/nocodb/src/services/meta-diffs.service.ts

Closes https://github.com/nocodb/nocodb/issues/9985
Fix: meta sync for buttons

fix: metas sync 

---

packages/nc-gui/components/cell/Duration.vue
packages/nc-gui/components/nc/List/index.vue

fix(nc-gui): auto same duration cell value

---

packages/nc-gui/components/smartsheet/grid/GroupByTable.vue

Closes https://github.com/nocodb/nocodb/issues/9875

fix: expanded-form not triggering when grouped with number

---

packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue
packages/nc-gui/components/nc/List/index.vue
packages/nc-gui/components/smartsheet/header/UpdateDisplayValue.vue
packages/nc-gui/components/smartsheet/topbar/ViewListDropdown.vue
packages/nc-gui/lang/en.json

Nc fix/create form option visibility issue

---

packages/nc-gui/components/cell/DatePicker.vue
packages/nc-gui/components/cell/DateTimePicker.vue
packages/nc-gui/components/cell/TimePicker.vue
packages/nc-gui/components/cell/YearPicker.vue
packages/nc-gui/components/dlg/share-and-collaborate/SharePage.vue
packages/nc-gui/store/workspace.ts

chore(nc-gui): lint

---

.github/workflows/release-npm.yml

Increase delay between npm publish and install

---

packages/nc-gui/components/cell/TextArea.vue
packages/nc-gui/components/cell/attachment/index.vue

fix (nc-gui): restrict height of cells in short view

---

docker-compose/1_Auto_Upstall/noco.sh

Upstall script - Initialising default settings

---

.github/workflows/release-npm.yml

chore: increase delay between publish and install

---

packages/nc-gui/components/cell/RichText.vue
packages/nc-gui/components/cell/RichText/SelectedBubbleMenu.vue
packages/nc-gui/components/cell/RichText/SelectedBubbleMenuPopup.vue
packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/composables/useTemplatedMessage.ts
packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/index.vue
packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/survey.vue

Nc feat/form mode template message

---

packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/virtual-cell/components/LinkedItems.vue
packages/nc-gui/components/virtual-cell/components/ListItem.vue
packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
packages/nc-gui/composables/useMultiSelect/index.ts
tests/playwright/tests/db/columns/columnBarcode.spec.ts

Nc fix/link record selection

---

packages/nc-gui/components/cell/RichText.vue

fix(nc-gui): richtext render issue

---

packages/nc-gui/composables/useColumnCreateStore.ts
packages/nc-gui/lang/en.json
packages/nocodb/src/models/Column.ts
packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
packages/nocodb/src/services/columns.service.ts

suppress invalid col validation while duplicating
fix: (bug fix for the user, not a fix to a build script)

fix(nocodb): suppress invalid col validation while duplicating

---

packages/nc-gui/components/cell/MultiSelect.vue
packages/nc-gui/components/cell/SingleSelect.vue
packages/nc-gui/components/cell/User.vue
packages/nc-gui/components/nc/List/RecordItem.vue
packages/nc-gui/components/smartsheet/Cell.vue
packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
packages/nc-gui/components/virtual-cell/components/ListItem.vue

fix(nc-gui): Select cell related issues

---

packages/nc-gui/components/smartsheet/grid/index.vue
packages/nc-gui/composables/useBetaFeatureToggle.ts

Closes https://github.com/nocodb/nocodb/issues/10070

fix: expanded row nav fix

---

packages/nc-gui/components/cell/RichText.vue
packages/nc-gui/components/cell/Text.vue
packages/nc-gui/components/cell/User.vue
packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue
packages/nc-gui/components/smartsheet/topbar/ViewListDropdown.vue
packages/nc-gui/components/virtual-cell/components/LinkedItems.vue
packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
packages/nc-gui/composables/useColumnCreateStore.ts
tests/playwright/pages/Dashboard/ExpandedForm/index.ts

Nc fix/expanded record single line multiline

---

packages/nc-gui/components/cmd-j/index.vue

fix(nc-gui): cmd-j modal border radius issue

---

packages/nocodb-sdk/src/lib/sqlUi/DatabricksUi.ts
packages/nocodb-sdk/src/lib/sqlUi/MssqlUi.ts
packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
packages/nocodb-sdk/src/lib/sqlUi/OracleUi.ts
packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts
packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts
packages/nocodb-sdk/src/lib/sqlUi/SqliteUi.ts
packages/nocodb/src/Upgrader.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/sql-client/lib/mssql/MssqlClient.ts
packages/nocodb/src/db/sql-client/lib/mysql/MysqlClient.ts
packages/nocodb/src/db/sql-client/lib/oracle/OracleClient.ts
packages/nocodb/src/db/sql-client/lib/sqlite/SqliteClient.ts
packages/nocodb/src/interface/Jobs.ts
packages/nocodb/src/meta/meta.service.ts
packages/nocodb/src/modules/jobs/jobs.module.ts
packages/nocodb/src/modules/jobs/migration-jobs/init-migration-jobs.ts
packages/nocodb/src/modules/jobs/migration-jobs/nc_job_005_order_column.ts
packages/nocodb/src/modules/jobs/migration-jobs/nc_job_no_op.ts
packages/nocodb/src/providers/init-meta-service.provider.ts
packages/nocodb/src/services/columns.service.ts
packages/nocodb/src/services/meta-diffs.service.ts

fix: upgrader mode

---

packages/nocodb/src/db/util/Debug.ts

fix: colors library related bug

---

.github/workflows/release-npm.yml

chore: poll npm instead of static sleep

---

packages/nc-gui/components/cell/SingleSelect.vue
packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/composables/useInfiniteData.ts
packages/nc-gui/composables/useSmartsheetLtarHelpers.ts

fix: links menu closing on link
fix: on typing while record being saved, the typed data is overwritten from server

fix: grid bug fixes

---

packages/nc-gui/components/smartsheet/toolbar/GroupByMenu.vue
packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue

fix(nc-gui): update sort toolbar menu dropdown UI same as groupby

---

packages/nocodb/src/db/BaseModelSqlv2.ts

Fix: HM Linking failed
Closes https://github.com/nocodb/nocodb/issues/10056

fix: One-to-many relation "Linking failed" 

---

packages/nocodb/src/Upgrader.ts
packages/nocodb/src/interface/Jobs.ts
packages/nocodb/src/modules/jobs/jobs.module.ts
packages/nocodb/src/modules/jobs/migration-jobs/init-migration-jobs.ts
packages/nocodb/src/modules/jobs/migration-jobs/nc_job_005_order_column.ts
packages/nocodb/src/modules/jobs/migration-jobs/nc_job_007_recover_order_column.ts
packages/nocodb/src/providers/init-meta-service.provider.ts
packages/nocodb/src/utils/cache.ts

fix: order migration recovery

---

packages/nc-gui/app.vue
packages/nc-gui/assets/nc-icons/snow.svg
packages/nc-gui/assets/style.scss
packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
packages/nc-gui/components/general/Snowfall.vue
packages/nc-gui/components/project/View.vue
packages/nc-gui/components/smartsheet/Topbar.vue
packages/nc-gui/components/smartsheet/topbar/SnowfallTrigger.vue
packages/nc-gui/components/workspace/View.vue
packages/nc-gui/components/workspace/integrations/view.vue
packages/nc-gui/lang/en.json
packages/nc-gui/lib/enums.ts
packages/nc-gui/utils/iconUtils.ts

feat: snowflake animation 

---

packages/nc-gui/components/general/Snowfall.vue
packages/nc-gui/components/smartsheet/grid/Table.vue

Nc fix/snowflake item selection issue

---

packages/nc-gui/app.vue
packages/nc-gui/components/general/Snowfall.vue
packages/nc-gui/components/smartsheet/topbar/SnowfallTrigger.vue
packages/nc-gui/nuxt.config.ts
packages/nc-gui/plugins/error-reporting.ts
packages/nc-gui/plugins/sentry.ts

- Use canvas to avoid DOM overload
- Use pixel based calcs to avoid layout recalculations
- Update animations from single source using RAF
- Throttle mouse handler
- Stop animation if tab is not active
- Stop animation for PW

fix: snowflakes

---

packages/nocodb/src/services/columns.service.ts

- Closes https://github.com/nocodb/nocodb/issues/10109

fix: Column update related bugs

---

docker-compose/1_Auto_Upstall/noco.sh
docker-compose/1_Auto_Upstall/tests/configure/setup.sh
docker-compose/1_Auto_Upstall/tests/configure/stop.bats
docker-compose/1_Auto_Upstall/tests/configure/upgrade.bats
docker-compose/1_Auto_Upstall/tests/expects/configure/stop.sh
docker-compose/1_Auto_Upstall/tests/expects/configure/upgrade.sh
docker-compose/1_Auto_Upstall/tests/expects/install/default.sh
docker-compose/1_Auto_Upstall/tests/expects/install/ip.sh
docker-compose/1_Auto_Upstall/tests/expects/install/redis.sh
docker-compose/1_Auto_Upstall/tests/expects/install/scale.sh
docker-compose/1_Auto_Upstall/tests/expects/install/ssl.sh
docker-compose/1_Auto_Upstall/tests/expects/install/watchtower.sh

Tested Scenarios
| NocoDB | MinIO | Works | Notes |
|--------|--------|--------|--------|
| IP | IP | ✅ | No additional configuration needed |
| IP | Domain - No SSL | ✅ |  |
| IP | Domain + SSL | ✅ |  |
| Domain - No SSL | IP | ✅  | |
| Domain - No SSL | Domain - No SSL | ✅ | |
| Domain - No SSL | Domain + SSL | ✅ | |
| Domain + SSL | IP | ⚠️ | Show Warning. Asks User to Update the Domain Name and SSL |
| Domain + SSL | Domain - No SSL | ✅ | SSL will be auto enabled |
| Domain + SSL | Domain + SSL | ✅ | |

fix: update auto upstall script

---

packages/nc-gui/components/smartsheet/expanded-form/Sidebar/Comments.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue

fix(nc-gui): use useCopy instead of useClipboard

---

packages/nc-gui/assets/nc-icons/table-current.svg
packages/nc-gui/components/dlg/TableDescriptionUpdate.vue
packages/nc-gui/components/general/TableIcon.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/utils/iconUtils.ts

Nc fix/update table icon

---

packages/nc-gui/composables/useInfiniteData.ts

Closes https://github.com/nocodb/nocodb/issues/10132

fix: Error in Grid when pageInfo is undefined in list api

---

packages/nc-gui/assets/nc-icons-v2/webhook.svg
packages/nc-gui/assets/style.scss
packages/nc-gui/components/account/ResetPassword.vue
packages/nc-gui/components/cell/User.vue
packages/nc-gui/components/dashboard/settings/DataSources.vue
packages/nc-gui/components/dashboard/settings/base/index.vue
packages/nc-gui/components/general/IconSelector.vue
packages/nc-gui/components/general/TableIcon.vue
packages/nc-gui/components/nc/Badge.vue
packages/nc-gui/components/project/AccessSettings.vue
packages/nc-gui/components/roles/Badge.vue
packages/nc-gui/components/smartsheet/Details.vue
packages/nc-gui/components/smartsheet/Topbar.vue
packages/nc-gui/components/smartsheet/header/Menu.vue
packages/nc-gui/components/tabs/Smartsheet.vue
packages/nc-gui/components/webhook/index.vue
packages/nc-gui/components/workspace/CollaboratorsList.vue
packages/nc-gui/pages/account/index.vue
packages/nc-gui/utils/iconUtils.ts
tests/playwright/disabledTests/docs/keybaordShortcutsAndDragDrop.spec.ts
tests/playwright/pages/Dashboard/Grid/Column/index.ts
tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts

Nc fix/User account pages related UI changes

---

packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/composables/useInfiniteData.ts

fix(nc-gui): new record visibility issue in new table

---

packages/nc-gui/components/smartsheet/expanded-form/Detached.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/components/smartsheet/grid/useColumnDrag.ts
packages/nc-gui/components/smartsheet/header/Menu.vue
packages/nc-gui/components/smartsheet/header/UpdateDisplayValue.vue
packages/nc-gui/components/virtual-cell/components/ItemChip.vue
packages/nc-gui/components/virtual-cell/components/LinkedItems.vue
packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
packages/nc-gui/composables/useExpandedFormDetached/index.ts
packages/nc-gui/composables/useViewColumns.ts
packages/nc-gui/lang/en.json
packages/nocodb/src/models/Column.ts

Nc/fix: Nested Create Record Modal - Hide Fields

---

packages/nc-gui/components/account/Profile.vue

fix(nc-gui): user profile save issue

---

packages/nocodb-sdk/src/lib/Api.ts
tests/playwright/pages/Account/index.ts

test: fix selector for sign out

---

packages/nocodb/Dockerfile.local
packages/nocodb/Dockerfile.timely

chore: add missing py3-setuptools dep

---

packages/noco-docs/docs/090.views/010.views-overview.md

docs: mark personal view as cloud only

---

packages/nc-gui/components/smartsheet/column/DateOptions.vue
packages/nc-gui/components/smartsheet/column/DateTimeOptions.vue
packages/nc-gui/components/smartsheet/column/DefaultValue.vue
packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
packages/nc-gui/components/smartsheet/column/NumberOptions.vue
packages/nc-gui/components/smartsheet/column/TimeOptions.vue
packages/nc-gui/components/smartsheet/column/UITypesOptionsWithSearch.vue
packages/nc-gui/components/smartsheet/details/Fields.vue
packages/nc-gui/components/smartsheet/grid/GroupByTable.vue
packages/nc-gui/composables/useColumnCreateStore.ts
packages/nocodb/src/services/columns.service.ts
tests/playwright/tests/db/features/multiFieldEditor.spec.ts

Closes #9264
feat: (new feature for the user, not a new feature for build script)

feat(nc-gui): Multi field editor - show system fields

---

packages/nc-gui/components/smartsheet/column/DecimalOptions.vue
packages/nc-gui/components/smartsheet/column/RollupOptions.vue
packages/nc-gui/components/virtual-cell/Rollup.vue
packages/nc-gui/helpers/columnDefaultMeta.ts
packages/nc-gui/lang/en.json
packages/nocodb-sdk/src/lib/helperFunctions.ts

Closes https://github.com/nocodb/nocodb/issues/5312
feat: (new feature for the user, not a new feature for build script)

feat(nc-gui): number format options for rollup column

---

packages/nc-gui/components/smartsheet/header/AddLookups.vue
packages/nc-gui/components/smartsheet/toolbar/AddLookupsDropdown.vue
packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue

Nc fix add lookup

---

docker-compose/1_Auto_Upstall/noco.sh

Upstall script - add worker service for ee edition

---

packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/header/AddLookups.vue
packages/nc-gui/components/smartsheet/toolbar/AddLookupsDropdown.vue
packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
packages/nc-gui/components/smartsheet/toolbar/RowHeight.vue

fix(nc-gui): prevent loading column hash in public or localMode

---

docker-compose/1_Auto_Upstall/noco.sh

Upstall script: remove duplicate service prop

---

.github/workflows/release-timely-docker.yml
packages/nocodb/Dockerfile
packages/nocodb/Dockerfile.timely

Sync master with develop brach

---

packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
packages/nc-gui/components/general/language/index.vue
packages/nc-gui/components/smartsheet/Topbar.vue
packages/nc-gui/composables/useBetaFeatureToggle.ts
packages/nc-gui/layouts/base.vue
packages/nc-gui/pages/account/index.vue

feat: enable  i18n in ee

---

packages/nc-gui/assets/style.scss

fix(nc-gui): form view logo alignment issue

---

packages/noco-docs/docs/070.fields/040.field-types/060.formula/040.date-functions.md
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb-sdk/src/lib/formulaHelpers.ts
packages/nocodb-sdk/src/lib/sqlUi/SqliteUi.ts
packages/nocodb/src/db/functionMappings/mysql.ts
packages/nocodb/src/db/functionMappings/pg.ts
packages/nocodb/src/db/functionMappings/sqlite.ts

feat: introduce date fns for other dbs
- Add missing YEAR fn for formulas
- Add date fns for MySQL & SQLite

feat: year fn for formula

---

packages/nocodb/Dockerfile
packages/nocodb/Dockerfile.timely

Added wget to the Docker runner as it is required for health checks in Coolify. This ensures backward compatibility with existing configurations.
Related discord thread - https://discord.com/channels/661905455894888490/1323730041871532082

Include wget in docker runner

---

packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/useRowDragging.ts
packages/nocodb-sdk/src/lib/sqlUi/DatabricksUi.ts
packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/tests/unit/rest/tests/readOnlySource.test.ts

fix: mysql reorder fixes

---

packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue

fix(nc-gui): disable fieldsMenu add new field and show/hide all field switch in locked view

---

packages/nc-gui/components/smartsheet/FormulaWrapperCell.vue
packages/nc-gui/components/smartsheet/VirtualCell.vue
packages/nc-gui/components/smartsheet/calendar/MonthView.vue
packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/Columns.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/components/virtual-cell/Rollup.vue

fix(nc-gui): record editor and calendar fixes

---

.github/workflows/release-executables.yml
scripts/pkg-executable/package.json

Revert to Node.js 18 due to lack of pkg support for Node.js 22

---

packages/nocodb/src/Noco.ts
packages/nocodb/src/utils/appUrl.ts

Print correct app url on init based on env

---

packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
packages/nocodb/src/meta/migrations/v2/nc_072_col_button_pk.ts

fix: add missing pks

---

packages/nc-gui/components/ai/WizardTabs.vue
packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue
packages/nc-gui/components/dlg/TableCreate.vue
packages/nc-gui/components/dlg/ViewCreate.vue
packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
packages/nc-gui/components/smartsheet/column/FormulaInputHelper.vue
packages/nc-gui/components/smartsheet/column/SelectOptions.vue
packages/nc-gui/components/smartsheet/topbar/ViewListDropdown.vue
packages/nc-gui/components/workspace/project/CreateMode.vue
packages/nc-gui/composables/usePredictFields.ts

chore: AI features follow up

---

packages/nocodb/src/filters/global-exception/global-exception.filter.ts

Handle & suppress not valid json error.

fix: suppress not valid json errors

---

packages/nc-gui/lib/enums.ts

I fixed the way of writing the language name
- [x ] fix: (bug fix for the user, not a fix to a build script)

better language name

---

packages/nocodb/src/models/Column.ts
packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
packages/nocodb/src/services/columns.service.ts

Closes https://github.com/nocodb/nocodb/issues/7428

fix: duplicate fails if there is an invalid formula or button

---

packages/nocodb/src/modules/jobs/fallback/jobs.service.ts
packages/nocodb/src/modules/jobs/redis/jobs.service.ts

fix: job with empty data

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
packages/nocodb/src/meta/migrations/v2/nc_073_file_reference_indexes.ts
packages/nocodb/src/models/FileReference.ts

Add context index for file_references table

fix: missing file references index

---

packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/PlaceholderRow.vue
packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/composables/useViewAggregate.ts
packages/nc-gui/helpers/tiptap/extensions/functionality/markdown/md-strike-ext.ts

Nc fix(nc-gui): grid view blank screen issue on scroll

---

packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
packages/nocodb/src/meta/migrations/v2/nc_074_missing_context_indexes.ts

fix: add missing indexes

---

packages/nocodb/src/Noco.ts
packages/nocodb/src/cache/CacheMgr.ts
packages/nocodb/src/cache/NocoCache.ts
packages/nocodb/src/helpers/redisHelpers.ts
packages/nocodb/src/modules/jobs/jobs.module.ts
packages/nocodb/src/redis/pubsub-redis.ts
packages/nocodb/src/utils/tele.ts

feat: redis helper

---

packages/nc-gui/composables/useInfiniteData.ts

fix: long text data disappear

---

packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
packages/nc-gui/components/smartsheet/header/AddLookups.vue
packages/nc-gui/components/smartsheet/toolbar/AddLookupsDropdown.vue
packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
packages/nc-gui/composables/useBetaFeatureToggle.ts
packages/nocodb/src/models/Model.ts
packages/nocodb/src/schema/swagger.json

fix: fields menu reload

---

packages/nocodb/src/init.ts

fix: dynamic ref

---

packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue

fix: Mark as new record while creating new record from links list

---

packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/rspack.dev.config.js
packages/nocodb/src/db/sql-client/lib/pg/PgClient.ts
packages/nocodb/src/db/sql-migrator/lib/KnexMigratorv2.ts

fix: avoid create db call on connect existing external

---

packages/nocodb/src/helpers/webhookHelpers.ts

fix: properly null check for apiMeta

---

packages/nc-gui/plugins/monaco.ts

- Types are not working for Scripts in staging

Fix: Misc Issues

---

packages/nocodb/src/helpers/webhookHelpers.ts
packages/nocodb/src/services/hooks.service.ts

- Closes https://github.com/nocodb/nocodb/issues/10268
- Handle hook log insertion error
- Include context information with hook job payload

fix: Webhook log insertion bug

---

packages/nc-gui/components/smartsheet/expanded-form/Sidebar/index.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Discussion/index.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/Columns.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/MiniColumnsWrapper.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/index.vue

Refactor: Do not pass expanded form store as prop

---

packages/nocodb/src/services/meta-diffs.service.ts

- Closes https://github.com/nocodb/nocodb/issues/10255

fix: Metadata sync - typo correction

---

packages/nc-gui/components/cell/Json.vue
packages/nc-gui/components/smartsheet/Cell.vue
packages/nc-gui/components/smartsheet/column/DefaultValue.vue
packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index.vue

fix: json default value field

---

packages/nc-gui/composables/useRowComments.ts

fix(nc-gui): comment mention broken issue

---

packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue

Data Reflection is shown in the integrations tab, irrespective of feature toggle

fix: hide data reflection 

---

packages/nc-gui/components/smartsheet/column/AiButtonOptions.vue

fix(nc-gui): Error on click select output fields/ preview record from AIButton Config modal

---

packages/nocodb/src/db/conditionV2.ts

- use datetime conditions for createdTime and lastModifiedTime
- use date instead of datetime for conditions

fix: datetime filter issues

---

packages/nc-gui/components/smartsheet/expanded-form/index.vue

Nc nc fix/kanban order

---

packages/nc-gui/composables/useBetaFeatureToggle.ts

chore: sub-text change for LTAR feature toggle

---

docker-compose/1_Auto_Upstall/noco.sh

fixes #10320
- [] fix: (bug fix for the user, not a fix to a build script)

fix(upstall): public ip lookup

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/helpers/getAst.ts
packages/nocodb/src/utils/nocoExecute.ts

Nc refactor/noco execute type definition

---

packages/nc-gui/components/account/UserList.vue
packages/nc-gui/components/account/UsersModal.vue
packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
packages/nc-gui/components/smartsheet/Topbar.vue
packages/nc-gui/composables/useGlobal/state.ts
packages/nc-gui/composables/useGlobal/types.ts
packages/nc-gui/layouts/base.vue
packages/nc-gui/pages/account/index.vue
packages/nc-gui/pages/account/index/[page].vue
packages/nc-gui/utils/debug.ts
packages/nocodb/src/Noco.ts
packages/nocodb/src/app.config.ts
packages/nocodb/src/controllers/org-users.controller.ts
packages/nocodb/src/providers/init-meta-service.provider.ts
packages/nocodb/src/run/cloud.ts
packages/nocodb/src/services/org-users.service.ts
packages/nocodb/src/services/users/users.service.ts
packages/nocodb/src/services/utils.service.ts
packages/nocodb/src/utils/cloud/populateCloudPlugins.ts
packages/nocodb/src/utils/index.ts

Nc on-prem related changes

---

flake.nix
nix/module.nix

closes #10339
works on my nixos (we're deterministic and reproducible )

fix(nix/module): use callPackage from flake

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/relation-update-webhook-handler.ts
packages/nocodb/src/db/update-webhook-handler.ts
packages/nocodb/src/helpers/getAst.ts
packages/nocodb/tests/unit/model/tests/baseModelSql.test.ts
packages/nocodb/tests/unit/rest/tests/tableRow.test.ts

Nc nc fix/relation webhook not firing

---

packages/nc-gui/composables/useInfiniteData.ts
packages/nocodb/src/db/BaseModelSqlv2.ts

Fix undo operation on tables with relation fields.

fix : undo relation

---

packages/nocodb/src/controllers/v3/base-users-v3.controller.ts
packages/nocodb/src/schema/swagger-v3.json
packages/nocodb/src/services/base-users/base-users.service.ts
packages/nocodb/src/services/v3/base-users-v3.service.ts
packages/nocodb/src/services/v3/bases-v3.service.ts
packages/nocodb/src/services/v3/views-v3.service.ts
packages/nocodb/tests/unit/init/index.ts
packages/nocodb/tests/unit/model/index.test.ts
packages/nocodb/tests/unit/rest/index.test.ts
packages/nocodb/tests/unit/rest/tests/metaApiV3/base.test.ts
packages/nocodb/tests/unit/rest/tests/metaApiV3/baseUsers.test.ts

Nc tests/api v3 ut

---

packages/nc-gui/pages/account/index.vue

Nc on prem app store

---

packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts

handle error if linked row display value is formula

---

packages/nc-gui/components/dlg/share-and-collaborate/SharePage.vue
packages/nc-gui/composables/useSharedView.ts
packages/nc-gui/pages/index/[typeOrId]/form/[viewId].vue

feat: language for shared views

---

packages/nc-gui/assets/nc-icons/align-vertical-bottom.svg
packages/nc-gui/assets/nc-icons/align-vertical-center.svg
packages/nc-gui/assets/nc-icons/align-vertical-top.svg
packages/nc-gui/assets/nc-icons/angle-rotate-cw.svg
packages/nc-gui/components/ai/PromptWithFields.vue
packages/nc-gui/components/extensions/Extension.vue
packages/nc-gui/components/extensions/Extension/Wrapper.vue
packages/nc-gui/components/general/AdvanceColorPicker.vue
packages/nc-gui/components/n/RecordPicker/Item.vue
packages/nc-gui/components/n/RecordPicker/Records.vue
packages/nc-gui/components/n/RecordPicker/index.vue
packages/nc-gui/components/smartsheet/PlainCell.vue
packages/nc-gui/composables/useInfiniteData.ts
packages/nc-gui/lib/types.ts
packages/nc-gui/utils/commonUtils.ts
packages/nc-gui/utils/iconUtils.ts
packages/nc-gui/utils/syncDataUtils.ts

Sync with ee

---

packages/nc-gui/composables/useGridViewData.ts
packages/nocodb/src/db/BaseModelSqlv2.ts

Nc fix/delete all with filter

---

.github/workflows/publish-api-docs.yml

Update action to copy v3 swagger

---

packages/nocodb/src/db/functionMappings/pg.ts

Escape regex pattern with parameterized sql. Closes https://github.com/nocodb/nocodb/issues/9847

escape regex pattern

---

packages/nocodb/Dockerfile
packages/nocodb/Dockerfile.local
packages/nocodb/Dockerfile.timely

chore: use fixed version of pnpm instead of latest

---

packages/nocodb-sdk/jest.config.js
packages/nocodb-sdk/src/lib/formulaHelpers.spec.ts
packages/nocodb-sdk/src/lib/formulaHelpers.ts
packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/db/functionMappings/pg.ts

Fix datetime_diff error when used with time field. Closes https://github.com/nocodb/nocodb/issues/9511

fix (nocodb): fix datetime_diff error when used with time field

---

packages/nc-gui/components/cell/Checkbox/Editor.vue
packages/nc-gui/components/cell/Date/Editor.vue
packages/nc-gui/components/cell/DateTime/Editor.vue
packages/nc-gui/components/cell/MultiSelect/Editor.vue
packages/nc-gui/components/cell/Rating/Editor.vue
packages/nc-gui/components/cell/SingleSelect/Editor.vue
packages/nc-gui/components/cell/Time/Editor.vue
packages/nc-gui/components/cell/User/Editor.vue
packages/nc-gui/components/cell/Year/Editor.vue

Nc fix(nc-gui): Expanded form field value edit issue in non grid view

---

packages/nc-gui/components/smartsheet/column/RollupOptions.vue
packages/nocodb-sdk/src/lib/helperFunctions.ts
packages/nocodb/src/db/genRollupSelectv2.ts
packages/nocodb/src/db/relation-manager.ts

Enable rollup to use formula column. Closes https://github.com/nocodb/nocodb/issues/10144

feat : using formula as rollup column

---

.github/workflows/bats-test.yml
.github/workflows/cleanup-caches-by-branch.yml
.github/workflows/dco-check.yml
.github/workflows/dispatch-oss.yml
.github/workflows/on-event-issue-closed.yml
.github/workflows/pr-to-master.yml
.github/workflows/publish-api-docs.yml
.github/workflows/publish-blog.yml
.github/workflows/publish-dev-docs.yml
.github/workflows/publish-docs-index-typesense.yml
.github/workflows/publish-docs.yml
.github/workflows/publish-noco-i18n.yml
.github/workflows/publish-prev-docs.yml
.github/workflows/release-close-issue.yml
.github/workflows/release-docker.yml
.github/workflows/release-draft.yml
.github/workflows/release-executables.yml
.github/workflows/release-nightly-dev.yml
.github/workflows/release-nocodb.yml
.github/workflows/release-npm.yml
.github/workflows/release-pr.yml
.github/workflows/release-previous-docker.yml
.github/workflows/release-secret-cli.yml
.github/workflows/release-timely-docker.yml
.github/workflows/release-timely-executables.yml
.github/workflows/sync-to-develop.yml
.github/workflows/uffizzi-preview.yml
.github/workflows/unit-test.yml
.github/workflows/update-sdk-path.yml

Update runner os to ubuntu-22.04

---

.github/workflows/bats-test.yml
.github/workflows/cleanup-caches-by-branch.yml
.github/workflows/dco-check.yml
.github/workflows/dispatch-oss.yml
.github/workflows/on-event-issue-closed.yml
.github/workflows/pr-to-master.yml
.github/workflows/publish-api-docs.yml
.github/workflows/publish-blog.yml
.github/workflows/publish-dev-docs.yml
.github/workflows/publish-docs-index-typesense.yml
.github/workflows/publish-docs.yml
.github/workflows/publish-noco-i18n.yml
.github/workflows/publish-prev-docs.yml
.github/workflows/release-close-issue.yml
.github/workflows/release-docker.yml
.github/workflows/release-draft.yml
.github/workflows/release-executables.yml
.github/workflows/release-nightly-dev.yml
.github/workflows/release-nocodb.yml
.github/workflows/release-npm.yml
.github/workflows/release-pr.yml
.github/workflows/release-previous-docker.yml
.github/workflows/release-secret-cli.yml
.github/workflows/release-timely-docker.yml
.github/workflows/release-timely-executables.yml
.github/workflows/sync-to-develop.yml
.github/workflows/uffizzi-preview.yml
.github/workflows/unit-test.yml
.github/workflows/update-sdk-path.yml
SECURITY.md

chore: Update runner os to ubuntu-22.04

---

.github/workflows/nix-bumper.yml

chore(github/workflow/bumper): switch to the new nix runner

---

packages/nocodb/src/plugins/minio/index.ts

fix: Add help text for hostname error in Minio

---

packages/nc-gui/components/dlg/KeyboardShortcuts.vue
packages/nc-gui/components/smartsheet/Pagination.vue
packages/nc-gui/components/smartsheet/details/Fields.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/components/smartsheet/grid/PaginationV2.vue
packages/nc-gui/components/webhook/CallLog/Details.vue
packages/nc-gui/components/webhook/CallLog/List.vue
packages/nc-gui/components/webhook/CallLog/ReqResDetailCard.vue
packages/nc-gui/components/webhook/CallLog/index.vue
packages/nc-gui/components/webhook/index.vue
packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue
packages/nc-gui/lang/en.json
packages/nc-gui/utils/datetimeUtils.ts
packages/nc-gui/utils/shortcutUtils.ts
packages/nc-gui/windi.config.ts
packages/nocodb/src/helpers/webhookHelpers.ts
packages/nocodb/src/models/HookLog.ts
packages/nocodb/src/services/v3/filters-v3.service.ts

Nc hook logs

---

packages/nc-gui/components/smartsheet/Cell.vue

fix: avoid lazy loading of typeable editor cell component

---

packages/nc-gui/components/smartsheet/expanded-form/Sidebar/index.vue
packages/nc-gui/composables/useBetaFeatureToggle.ts
packages/nc-gui/composables/useExpandedFormStore.ts
packages/nocodb/src/db/BaseModelSqlv2.ts

Nc data audit enable

---

packages/nocodb/src/helpers/getAst.ts

Ref: https://discord.com/channels/661905455894888490/1336582696431915109

fix: Include foreign key if system fields is enabled at view level

---

packages/nocodb-sdk/src/lib/parser/common-token.ts
packages/nocodb-sdk/src/lib/parser/queryFilter/query-filter-parser.spec.ts
packages/nocodb-sdk/src/lib/regex/token.ts

fix internationalization

---

packages/nocodb-sdk/src/lib/filterHelpers.ts
packages/nocodb-sdk/src/lib/parser/queryFilter/query-filter-cst-parser.ts

Nc fix/date filter bug

---

packages/nc-gui/components/dashboard/settings/Metadata.vue
packages/nc-gui/components/dlg/AirtableImport.vue
packages/nc-gui/components/general/ProgressPanel.vue
packages/nocodb/src/modules/jobs/jobs/meta-sync/meta-sync.processor.ts
packages/nocodb/src/services/meta-diffs.service.ts
tests/playwright/pages/Dashboard/ProjectView/Metadata.ts

Nc fix/progress meta sync

---

packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue

fix: cache calculated value

---

packages/nocodb-sdk/src/lib/filterHelpers.ts
packages/nocodb-sdk/src/lib/filterHelpers_withparser.ts
packages/nocodb-sdk/src/lib/parser/common-token.ts
packages/nocodb-sdk/src/lib/regex/token.ts
packages/nocodb/tests/unit/rest/tests/dataAPIsV3.test.ts

fix: rollback the query filter to previous implementation

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/helpers/columnHelpers.ts
packages/nocodb/src/models/Audit.ts

fix: Bulk update - order record list same as input data

---

packages/nc-gui/components/cell/Checkbox/index.vue

Add unsynced changes from ee (missing comment deletion)

refactor: add unsynced changes from ee

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/relation-manager.ts
packages/nocodb/src/db/update-webhook-handler.ts
packages/nocodb/src/helpers/getAst.ts
packages/nocodb/tests/unit/model/tests/baseModelSql.test.ts
packages/nocodb/tests/unit/rest/tests/tableRow.test.ts

- Duplicate was missing links bc of broken logic
- Revert getHiddenColumn overload & use v3 pattern for webhook payload
- Recover unlink webhook which missed out on earlier refactor

fix: broken is requested logic

---

nix/package.nix
packages/nocodb/package.json
pnpm-lock.yaml

It was happening constantly, found the culprit package update -> run-script-webpack-plugin@0.2.1 introduces so I downgraded to 0.2.0

fix: port in use on code change

---

packages/nc-gui/components/cell/attachment/Modal.vue
packages/nc-gui/components/cell/attachment/index.vue
packages/nc-gui/components/cell/attachment/sort.ts

Fix broken image attachment ordering. Closes https://github.com/nocodb/nocodb/issues/10483

Nc fix/image attachment reordering

---

packages/nc-gui/components/cell/attachment/Card.vue
packages/nc-gui/utils/fileUtils.ts

treat mp3 as video. closes https://github.com/nocodb/nocodb/issues/10492

make entire square clickable treat mp3 as video

---

packages/nc-gui/components/smartsheet/Kanban.vue

can move cards if view is locked

---

packages/nc-gui/components/cell/attachment/Preview/Video.vue

closes https://github.com/nocodb/nocohub/issues/4423

make the video player has auto height instead of 100%

---

packages/nc-gui/components/dlg/QuickImport.vue
packages/nc-gui/composables/useMultiSelect/convertCellData.ts
packages/nc-gui/composables/useMultiSelect/index.ts
packages/nc-gui/error/computed-type-paste.error.ts
packages/nc-gui/error/select-type-conversion.error.ts
packages/nc-gui/error/silent-type-conversion.error.ts
packages/nc-gui/error/suppressed.error.ts
packages/nc-gui/error/type-conversion.error.ts
packages/nc-gui/utils/colorsUtils.ts
packages/nc-gui/utils/selectUtils.ts
packages/nc-gui/utils/validation.ts
packages/nocodb-sdk/src/lib/UITypes.ts
packages/nocodb-sdk/src/lib/globals.ts

fix url import and json string import. Closes https://github.com/nocodb/nocodb/issues/10499, https://github.com/nocodb/nocodb/issues/10498

fix (nc-gui): fix url import and json string import

---

packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
packages/nocodb/src/models/Model.ts
packages/nocodb/src/services/columns.service.ts

Nc fix(nc-gui): Lookup field creation via fields menu fails 

---

packages/nc-gui/components/nc/SelectTab.vue
packages/nc-gui/components/smartsheet/expanded-form/Sidebar/AuditMiniItem.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Discussion/AuditInfoExpressive.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Discussion/EntryComment.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Discussion/index.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/MiniColumnsWrapper.vue
packages/nc-gui/components/smartsheet/toolbar/SearchData.vue
packages/nc-gui/composables/useMultiSelect/index.ts
packages/nc-gui/composables/useSmartsheetStore.ts

feat: add query based filter support in view url

---

packages/nc-gui/components/dashboard/settings/base/Migrate.vue
packages/nc-gui/components/dashboard/settings/base/index.vue
packages/nc-gui/lib/acl.ts
packages/nocodb/src/modules/jobs/jobs.module.ts
packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
packages/nocodb/src/modules/jobs/jobs/export-import/migrate.controller.ts
packages/nocodb/src/modules/jobs/jobs/export-import/migrate.service.ts

feat: cloud exp

---

packages/nc-gui/components/template/Editor.vue
packages/nc-gui/composables/useExtensionHelper.ts
packages/nc-gui/lang/en.json
packages/nc-gui/utils/colorsUtils.ts
packages/nocodb-sdk/src/lib/globals.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/helpers/catchError.ts
packages/nocodb/src/models/Column.ts
packages/nocodb/src/services/bulk-data-alias.service.ts
packages/nocodb/src/services/data-table.service.ts

Nc feat/auto add select option

---

packages/nocodb-sdk/src/lib/formulaHelpers.ts
packages/nocodb/src/db/formulav2/formula-query-builder.types.ts
packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts

Add type definitions to formula query builders

refactor: add type definitions to formula query builders

---

packages/nc-gui/components/smartsheet/grid/GroupBy.vue
packages/nc-gui/components/smartsheet/grid/GroupByTable.vue
packages/nc-gui/composables/useViewGroupBy.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/services/meta-diffs.service.ts

chore: sync various

---

packages/nc-gui/components/dashboard/FeatureExperimentation.vue

fix: feature preview height to be same as toolbar

---

packages/nocodb/src/controllers/meta-diffs.controller.ts
packages/nocodb/src/modules/jobs/jobs/meta-sync/meta-sync.controller.ts

fix: block api token access to meta-diff

---

packages/nc-gui/components/smartsheet/grid/canvas/utils/canvas.ts
packages/nc-gui/components/smartsheet/grid/canvas/utils/markdownUtils.ts

fix: square bracket rich text

---

packages/nc-gui/components/nc/Switch.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/canvas/utils/canvas.ts
tests/playwright/pages/Dashboard/Grid/Column/index.ts
tests/playwright/pages/Dashboard/ProjectView/Metadata.ts
tests/playwright/pages/Dashboard/common/Toolbar/Fields.ts
tests/playwright/tests/db/views/viewKanban.spec.ts

Nc fix/rich perf

---

packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useDataFetch.ts

- Group adjacent chunks to use single api request
- Only fetch next or previous record based on scroll direction

feat: optimize number of api calls

---

packages/nc-gui/components/cell/SingleSelect/Readonly.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/Attachment.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/Lookup.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/virtual-cell/Lookup.vue

fix(nc-gui): instead of rendering multiple lookup attachment cell render only 1

---

packages/nc-gui/components/smartsheet/grid/canvas/index.vue

fix(nc-gui): expand row issue in canvas

---

packages/noco-docs/docs/145.cloud-enterprise-edition/010.community-vs-paid-editions.md

docs: update comments for coming soon items

---

packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/ColumnList.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/grid/index.vue

feat: enable canvas for mobile mode

---

packages/nc-gui/components/cell/Date/Editor.vue
packages/nc-gui/components/cell/Url/Editor.vue
packages/nc-gui/components/cell/attachment/index.vue

fix: edit interaction for url, date and attachment

---

packages/nc-gui/components/cell/User/utils.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/User.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useColumnReorder.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useColumnResize.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useMouseSelection.ts
packages/nc-gui/components/smartsheet/grid/canvas/context/Cell.vue
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/grid/canvas/utils/cell.ts
packages/nc-gui/composables/useGridViewData.ts

Nc canvas fixes 2

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useMouseSelection.ts

fix: mouseup listener not working properly

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/Checkbox.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/Email.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/Formula.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/PhoneNumber.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/Url.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/index.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCopyPaste.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useKeyboardNavigation.ts
packages/nc-gui/components/smartsheet/grid/canvas/utils/constants.ts
packages/nc-gui/components/smartsheet/header/AddLookups.vue
packages/nc-gui/components/smartsheet/header/ColumnMenu.vue
packages/nc-gui/components/smartsheet/header/UpdateDisplayValue.vue
packages/nc-gui/lib/types.ts

- Cannot Paste in SingleSelect, MultiSelect, User

fix: canvas related issues

---

packages/noco-docs/docs/060.table-operations/030.filter.md

docs: remove inaccessible link

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCopyPaste.ts

fix(nc-gui): on paste in mm cell max call stack error

---

packages/nocodb-sdk/src/lib/formulaHelpers.spec.ts
packages/nocodb-sdk/src/lib/formulaHelpers.ts

data type string when operator is & sign. Closes https://github.com/nocodb/nocodb/issues/10567

fix (nc-gui): data type string when operator is & sign

---

package.json

Add support for breaking change on [pnpm v10](https://github.com/pnpm/pnpm/releases/tag/v10.0.0)
Fixes #10544

chore: add onlyBuiltDependencies to support pnpm v10

---

packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
packages/nocodb-sdk/src/lib/sqlUi/DatabricksUi.ts
packages/nocodb-sdk/src/lib/sqlUi/MssqlUi.ts
packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
packages/nocodb-sdk/src/lib/sqlUi/OracleUi.ts
packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts
packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts
packages/nocodb-sdk/src/lib/sqlUi/SqlUI.types.ts
packages/nocodb-sdk/src/lib/sqlUi/SqlUiFactory.ts
packages/nocodb-sdk/src/lib/sqlUi/SqliteUi.ts

Nc refactor/sqlui static removal

---

packages/nc-gui/components/dlg/QuickImport.vue
packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/Lookup.ts
packages/nc-gui/components/smartsheet/grid/canvas/utils/canvas.ts
packages/nc-gui/components/smartsheet/grid/index.vue
packages/nc-gui/helpers/columnDefaultMeta.ts

fix(nc-gui): On open edit formula field dropdown throw error if formula column default meta is missing

---

packages/nc-gui/components/cell/Time/index.vue
packages/nocodb-sdk/src/lib/UITypes.ts

closes https://github.com/nocodb/nocodb/issues/10506

add Time as formatting when formula datatype result is number

---

packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue

fix: remove unused type validation for links

---

packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/ColumnList.vue

Fix the styles of QRCode and MultiSelect Lookup in Expanded Form.

style: fix qrcode and multiselect lookup styles in expanded form

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCopyPaste.ts

Global search should allow pasting.
Closes https://github.com/nocodb/nocodb/issues/10570

fix: global search should allow paste

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue

Closes https://github.com/nocodb/nocodb/issues/10577

fix: column order is different in firefox

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCopyPaste.ts
packages/nc-gui/utils/browserUtils.ts

Base rename and table rename can't be pasted into. This PR fixes it.

fix: sidebar node rename paste

---

packages/nc-gui/components/extensions/Extension/Header.vue
packages/nc-gui/components/extensions/Pane.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Discussion/EntryAudit.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/ColumnList.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/Checkbox.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/tabs/Smartsheet.vue

Nc fix/common bug fixes

---

packages/nc-gui/components/cell/GeoData.vue
packages/nc-gui/composables/useMultiSelect/convertCellData.ts

handle geodata paste

---

packages/nc-gui/components/dlg/share-and-collaborate/SharePage.vue
packages/nc-gui/components/dlg/share-and-collaborate/View.vue
packages/nc-gui/components/smartsheet/Kanban.vue
packages/nc-gui/lang/en.json

fix(nc-gui): Kanban stacks are expandable in Locked view mode 

---

packages/nc-gui/composables/useCalendarViewStore.ts
packages/nc-gui/composables/useKanbanViewStore.ts

- records appear empty in kanban view.
Closes https://github.com/nocodb/nocodb/issues/10614#issuecomment-2680279265

fix: kanban related issues

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCopyPaste.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useKeyboardNavigation.ts
packages/nc-gui/utils/browserUtils.ts

In extensions pane and in extensions themselves, paste won't work, keys won't work, backspace won't work. This PR fixes it.

fix: keyboard interactions in extensions

---

markdown/readme/languages/chinese.md

The Chinese translation should be kept in sync with the original ones.  
Instead of assuming the user's preference, even using "recommend" to mislead.
Ping @dstala

revert[06bb1aa]: Remove promotion of aaPanel/BaoTa.

---

packages/nc-gui/components/smartsheet/grid/GroupBy.vue
packages/nc-gui/components/smartsheet/grid/index.vue

fix: can't add new record if group by is enabled & all records are filtered out
Closes https://github.com/nocodb/nocodb/issues/9715

fix: can't add new record if group by is enabled & all records are filtered out

---

packages/nc-gui/components/ai/Settings.vue

Model name and integration name is not truncated properly and causes the UI to break. Before and after images attached.
Before
After

fix: integration and model name truncation

---

packages/nc-gui/components/template/Editor.vue

Nc fix: blacklist several Uidt as target column

---

packages/nc-gui/components/smartsheet/column/RollupOptions.vue
packages/nocodb/src/db/genRollupSelectv2.ts

Provide summary of changes with issue number if any. https://github.com/nocodb/nocodb/issues/9114

able to use created / last modified time as rollup

---

packages/nc-gui/components/smartsheet/grid/canvas/Scroller.vue

fix: custom scroll behaviour for windows

---

packages/nc-gui/components/cell/GeoData.vue
packages/nc-gui/composables/useMultiSelect/convertCellData.ts
packages/nc-gui/utils/geoDataUtils.ts

Provide summary of changes with issue number if any. Closes https://github.com/nocodb/nocodb/issues/7219

use same conversion for lat long limit input into 10 digit after decimal

---

packages/nocodb-sdk/src/lib/numberUtils.spec.ts
packages/nocodb-sdk/src/lib/numberUtils.ts
packages/nocodb-sdk/src/lib/sqlUi/DatabricksUi.ts
packages/nocodb-sdk/src/lib/sqlUi/MssqlUi.ts
packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.spec.ts
packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
packages/nocodb-sdk/src/lib/sqlUi/OracleUi.ts
packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts
packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts
packages/nocodb-sdk/src/lib/sqlUi/SqlUI.types.ts
packages/nocodb-sdk/src/lib/sqlUi/SqliteUi.ts
packages/nocodb/src/helpers/getColumnPropsFromUIDT.ts
packages/nocodb/src/services/columns.service.ts

Mysql decimal length now follow scale.

Squashed commit of the following:

---

packages/nocodb/src/services/columns.service.ts

column update, detect dt based on uidt if dt is not provided. Closes https://github.com/nocodb/nocodb/issues/10515

fix (nocodb): column update, detect dt based on uidt if dt is not provided

---

packages/nocodb/src/services/columns.service.ts

fix: tests

---

packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts

Formula builder type corrections

---

packages/nc-gui/helpers/tiptap-markdown/extensions/marks/link.ts

Nc fix(nc-gui): remove link mark on adding space at the end

---

packages/nc-gui/components/cell/GeoData.vue
packages/nc-gui/components/smartsheet/Cell.vue

fix: geodata form input broken

---

packages/nocodb-sdk/src/lib/is.ts
packages/nocodb/src/constants/index.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/models/PresignedUrl.ts
packages/nocodb/src/plugins/backblaze/Backblaze.ts
packages/nocodb/src/plugins/s3/S3.ts

Signed Urls were not working for profilePics, workspacePics and organizationPics, if forcePathStyle enabled for S3 plugin

fix: signed url not working for s3 based providers

---

nix/docker/all_in_one/init/s6-services/services/acme-srv/shell_up.sh

feat(nix/docker/aio/ssl): support for adhoc certs

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/Lookup.ts
packages/nc-gui/components/virtual-cell/Lookup.vue

feat: badged formula lookup

---

packages/nc-gui/components/smartsheet/grid/canvas/utils/canvas.ts

fix: rich text font weight

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/Formula.ts

- When URL format it was rendering links but not opening on click

fix: formula URL format click

---

packages/nc-gui/components/smartsheet/toolbar/ExportSubActions.vue
packages/nc-gui/components/template/Editor.vue
packages/nc-gui/composables/useSharedView.ts
packages/nocodb/src/controllers/data-alias-export.controller.ts
packages/nocodb/src/controllers/public-datas-export.controller.ts
packages/nocodb/src/helpers/catchError.ts

fix: excel export using api. Closes https://github.com/nocodb/nocodb/issues/7215#top
also Closes https://github.com/nocodb/nocodb/issues/10421

fix: excel export using api

---

packages/nc-gui/components/dlg/TableDelete.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/User.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/grid/canvas/loaders/TableMetaLoader.ts
packages/nc-gui/composables/useColumnCreateStore.ts
packages/nc-gui/composables/useGridViewData.ts
packages/nc-gui/composables/useInfiniteData.ts
packages/nc-gui/composables/useMetas.ts
packages/nocodb/src/services/base-users/base-users.service.ts
packages/nocodb/src/services/columns.service.ts

Nc fix prod issues

---

packages/nocodb/src/interface/Jobs.ts
packages/nocodb/src/modules/jobs/jobs.module.ts
packages/nocodb/src/modules/jobs/migration-jobs/init-migration-jobs.ts
packages/nocodb/src/modules/jobs/migration-jobs/nc_job_008_recover_disconnected_table_name.ts
packages/nocodb/src/providers/init-meta-service.provider.ts
packages/nocodb/src/services/tables.service.ts

Add validation for ? and $ symbol in table name. Ref: https://github.com/nocodb/nocodb/issues/10477

fix: add validation for ? and $ symbol in table name #4564

---

packages/nc-gui/components/extensions/Extension.vue
packages/nc-gui/composables/useJobs.ts
packages/nc-gui/extensions/data-exporter/index.vue
packages/nc-gui/extensions/data-exporter/manifest.json

Nc fix/extension cleanup

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/services/columns.service.ts

fix: ltar follow model / view sort

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/helpers/addFormulaErrorIfMissingColumn.ts

- Closes https://github.com/nocodb/nocodb/issues/10688

fix: Self link BT link issue in expanded form

---

packages/nc-gui/composables/useExpandedFormStore.ts
packages/nocodb/src/helpers/getAst.ts

fix: No-record found error in expanded form

---

packages/nc-gui/components/template/Editor.vue

fix: upload title matching. Ref https://github.com/nocodb/nocodb/issues/10686

fix: upload title matching

---

packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
packages/nocodb/.gitignore
packages/nocodb/src/db/IBaseModelSqlV2.ts
packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/helpers/dbHelpers.ts
packages/nocodb/src/models/Column.ts
packages/nocodb/src/modules/noco.module.ts
packages/nocodb/src/services/columns.service.ts
packages/nocodb/src/services/columns.service.type.ts
packages/nocodb/src/services/formula-column-type-changer.service.ts
packages/nocodb/src/services/formula-column-type-changer.types.ts
packages/nocodb/src/services/formula-column-type-changer/index.ts
packages/nocodb/src/services/formula-column-type-changer/mysql-data-migration.ts
packages/nocodb/src/services/formula-column-type-changer/pg-data-migration.ts
packages/nocodb/src/services/formula-column-type-changer/sqlite-data-migration.ts

Change formula column to single line text while retaining data. Ref https://github.com/nocodb/nocodb/issues/7639

feat: change formula column to single line text while retaining data

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/helpers/dbHelpers.ts

Provide summary of changes with issue number if any. Closes https://github.com/nocodb/nocodb/issues/10691

Nc fix/external db audit log

---

nix/package.nix
packages/nc-gui/components/smartsheet/details/Fields.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useColumnResize.ts
packages/nc-gui/components/smartsheet/grid/canvas/context/Aggregation.vue
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/header/Cell.vue
packages/nc-gui/components/smartsheet/header/ColumnMenu.vue
packages/nc-gui/components/smartsheet/header/Menu.vue
packages/nc-gui/components/smartsheet/header/VirtualCell.vue
packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue
packages/nc-gui/plugins/resizeDirective.ts
packages/nocodb-sdk/src/lib/Api.ts
pnpm-lock.yaml
tests/playwright/package.json
tests/playwright/pages/Dashboard/Grid/columnHeader.ts

Nc fix/locked view

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/Url.ts

fix: do not show invalid tooltip over url field if it is empty

---

packages/nc-gui/components/cell/attachment/Card.vue
packages/nc-gui/components/cell/attachment/index.vue
packages/nc-gui/components/dashboard/settings/sync/Edit.vue
packages/nc-gui/components/n/RecordPicker/Item.vue
packages/nc-gui/components/nc/List/RecordItem.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/Attachment.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/LTAR/BelongsTo.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/loaders/ImageLoader.ts
packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue
packages/nc-gui/utils/urlUtils.ts

Nc fix(nc-gui): use object-fit contain property to render attachment cell

---

packages/nc-gui/components/smartsheet/calendar/MonthView.vue

fix: last week of decemeber is cut off

fix: last week of decemeber is cut off

---

packages/nocodb-sdk/src/lib/formulaHelpers.ts
packages/nocodb/src/db/formulav2/formula-query-builder.types.ts
packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/schema/swagger.json

- Closes https://github.com/nocodb/nocohub/issues/4745

fix: Formula - Check for circular reference

---

packages/nocodb/src/controllers/notifications.controller.ts
packages/nocodb/src/helpers/migrationJobs.ts
packages/nocodb/src/modules/jobs/fallback/fallback-queue.service.ts
packages/nocodb/src/modules/jobs/jobs.controller.ts
packages/nocodb/src/modules/jobs/migration-jobs/init-migration-jobs.ts
packages/nocodb/src/utils/TeleBatchProcessor.ts
packages/nocodb/src/utils/tele.ts

Add unref to potential open handles to unblock delay on graceful shutdown.

fix: unref potential open handles

---

packages/nc-gui/components/dashboard/TreeView/TableNode.vue
packages/nc-gui/components/smartsheet/header/Cell.vue

fix: add missing optional chain

---

packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts

These fields were missing data on duplicate

fix: duplicate for columns with comma 

---

packages/nc-gui/components/cell/Currency/Editor.vue
packages/nc-gui/components/cell/Currency/index.vue
packages/nc-gui/components/virtual-cell/Lookup.vue

Nc fix/currency number format in expanded form

---

packages/nocodb/src/Noco.ts
packages/nocodb/src/controllers/notifications.controller.ts
packages/nocodb/src/modules/jobs/jobs.controller.ts

fix: use custom shutdown hook for long polling connections

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/Lookup.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/Plain.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/grid/canvas/utils/cell.ts

- Closes https://github.com/nocodb/nocodb/issues/10710

fix: Handle rendering of Lookup to HM/MM column in grid

---

packages/nocodb/src/Noco.ts
packages/nocodb/src/controllers/notifications.controller.ts
packages/nocodb/src/modules/jobs/jobs.controller.ts

fix: local port hang issue

---

packages/nc-gui/composables/useColumnCreateStore.ts
packages/nocodb/src/models/CalendarRange.ts
packages/nocodb/src/services/columns.service.ts

fix: clear calendar range if one col is deleted

fix: clear calendar range if one col is updated

---

packages/nc-gui/components/dlg/QuickImport.vue
packages/nc-gui/plugins/import-worker.ts

Fix upload dialog sometimes stuck on loading spinner. Closes https://github.com/nocodb/nocodb/issues/10713#top

Fix (nc-gui): upload dialog sometimes stuck on loading spinner

---

packages/nc-gui/components/template/Editor.vue
packages/nocodb/src/helpers/dataHelpers.ts

fix: after import, do not set incorrect column as display value from frontend

fix: after import, do not set incorrect column as display value from frontend

---

packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
packages/nc-gui/composables/useColumnCreateStore.ts
packages/nc-gui/lib/enums.ts

fix: on field update trigger filter reload

---

packages/nocodb/src/controllers/filters.controller.ts

Closes https://github.com/nocodb/nocodb/issues/10741

fix: invalid filter acl

---

packages/nc-gui/components/virtual-cell/Lookup.vue

fix(nc-gui): disable horizontal scroll in lookup cell

---

packages/nc-gui/components/smartsheet/column/RollupOptions.vue

add import getRenderAsTextFunForUiType

---

packages/nc-gui/utils/dataUtils.ts

Time format is not applied to Lookup DateTime
Sync PR

fix: datetime lookup bug

---

packages/nocodb/src/db/conditionV2.ts

Nc fix/condition column name amb

---

packages/nc-gui/components/cell/TextArea.vue
packages/nc-gui/components/smartsheet/FormulaWrapperCell.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/ColumnList.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/Formula.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/LongText.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/virtual-cell/Formula.vue
packages/nc-gui/context/index.ts

Nc Fix: Allow expand cell option for formula field when content length is more

---

packages/nc-gui/components/nc/List/RecordItem.vue
packages/nc-gui/components/virtual-cell/QrCode.vue
packages/nc-gui/components/virtual-cell/barcode/Barcode.vue
packages/nc-gui/components/virtual-cell/components/LinkedItems.vue
packages/nc-gui/components/virtual-cell/components/ListItem.vue
packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
packages/nc-gui/composables/useLTARStore.ts
packages/nc-gui/composables/useSharedFormViewStore.ts
packages/nc-gui/composables/useViewData.ts
packages/nc-gui/context/index.ts
packages/nocodb/src/services/public-datas.service.ts

Nc Fix: Only display value field info is visible in link record dropdown of form view

---

packages/nc-gui/components/dlg/NocoDbImport.vue
packages/nocodb/src/decorators/use-worker.decorator.ts
packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts

Sync missing changes

---

packages/nocodb/src/db/conditionV2.ts
packages/nocodb/src/utils/tsUtils.ts

Closes https://github.com/nocodb/nocodb/issues/10452

fix: filters for json

---

packages/nocodb/src/services/formula-column-type-changer.service.ts
packages/nocodb/src/services/formula-column-type-changer/data-migration.helper.ts
packages/nocodb/src/services/formula-column-type-changer/index.ts
packages/nocodb/src/services/formula-column-type-changer/mysql-data-migration.ts
packages/nocodb/src/services/formula-column-type-changer/pg-data-migration.ts
packages/nocodb/src/services/formula-column-type-changer/sqlite-data-migration.ts
packages/nocodb/src/utils/audit.ts

Nc feat/formula change column audit

---

packages/nc-gui/components/template/Editor.vue

allow foreign key to be imported

---

packages/nocodb/src/run/docker.ts
packages/nocodb/src/run/dockerEntry.ts
packages/nocodb/src/run/dockerRunMysql.ts
packages/nocodb/src/run/dockerRunPG.ts
packages/nocodb/src/run/dockerRunPG_CyQuick.ts
packages/nocodb/src/run/local.ts
packages/nocodb/src/run/testDocker.ts
packages/nocodb/src/run/timely.ts
packages/nocodb/src/utils/index.ts
packages/nocodb/src/utils/processUtils.ts

Nc fix/string too long error

---

packages/nc-gui/components/virtual-cell/components/LinkedItems.vue
packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
packages/nc-gui/composables/useLTARStore.ts

Provide summary of changes with issue number if any. Closes https://github.com/nocodb/nocodb/issues/7185

track different injected row when link / unlink

---

packages/nc-gui/components/cell/attachment/index.vue
packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue
packages/nc-gui/components/erd/HistogramPanel.vue
packages/nc-gui/components/general/SourceRestrictionTooltip.vue
packages/nc-gui/components/smartsheet/Details.vue
packages/nc-gui/components/smartsheet/expanded-form/Sidebar/index.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/ColumnList.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/index.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCopyPaste.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/header/Cell.vue
packages/nc-gui/components/smartsheet/header/ColumnMenu.vue
packages/nc-gui/components/smartsheet/header/VirtualCell.vue
packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue
packages/nc-gui/components/smartsheet/topbar/ViewListDropdown.vue
packages/nc-gui/composables/useExpandedFormStore.ts
packages/nc-gui/composables/useMultiSelect/index.ts
packages/nc-gui/lang/en.json

Nc Fix: ExtDB / SQL View fixes

---

packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
packages/nc-gui/lang/en.json

feat: move info message to i18n and add tooltip

---

packages/nc-gui/components/cell/MultiSelect/Editor.vue
packages/nc-gui/components/smartsheet/column/SelectOptions.vue
packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
packages/nc-gui/composables/useLTARStore.ts
packages/nocodb/src/services/columns.service.ts

Nc fix: trim whitespace of single select cell value on type conversion

---

packages/nc-gui/components/notification/Item.vue

fix: ws user invite notification is not shown in ui

---

packages/nocodb-sdk/src/lib/filterHelpers_old.spec.ts
packages/nocodb-sdk/src/lib/filterHelpers_withparser.spec.ts
packages/nocodb-sdk/src/lib/filterHelpers_withparser.ts

fix: query filter with parser

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/helpers/dbHelpers.ts
packages/nocodb/src/services/formula-column-type-changer.service.ts

Enable data audit for external db(ee)

---

packages/nocodb/src/plugins/GenericS3/GenericS3.ts
packages/nocodb/src/plugins/r2/R2.ts
packages/nocodb/src/plugins/spaces/Spaces.ts

Closes https://github.com/nocodb/nocodb/issues/10484
Closes https://github.com/nocodb/nocodb/issues/10373

fix: R2 and Spaces related bug

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts

fix: required field indicator

---

packages/nc-gui/components/cell/TextArea.vue

Nc fix(nc-gui): LongText modal size changes on visible

---

packages/nc-gui/utils/dataUtils.ts

re https://github.com/nocodb/nocodb/pull/10757

Handle nested lookup in filter

---

packages/nc-gui/components/cell/Date/Editor.vue
packages/nc-gui/components/cell/Date/Readonly.vue
packages/nc-gui/components/cell/Date/index.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/Date.ts
packages/nc-gui/composables/useExpandedFormStore.ts
packages/nc-gui/utils/dataUtils.ts
packages/nc-gui/utils/datetimeUtils.ts

Closes https://github.com/nocodb/nocodb/issues/10296

fix: sqlite invalid format for DD/MM/YYYY format

---

packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/db/functionMappings/pg.ts

Nc fix/formula question mark

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/LTAR/BelongsTo.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/LTAR/HasMany.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/LTAR/ManyToMany.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/LTAR/OneToOne.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/index.ts
packages/nc-gui/components/virtual-cell/components/ItemChip.vue
packages/nc-gui/composables/useExpandedFormDetached/index.ts
packages/nc-gui/lib/types.ts

fix(nc-gui): ltar item chip click issue in canvas

---

packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useKeyboardNavigation.ts
tests/playwright/pages/Dashboard/ExpandedForm/index.ts
tests/playwright/tests/db/views/viewKanban.spec.ts

fix(test): kanban view test fail issue

---

packages/nc-gui/components/cell/Decimal/DecimalInput.vue
packages/nc-gui/components/cell/Decimal/Editor.vue
packages/nocodb-sdk/src/lib/columnHelper/utils/decimal.spec.ts
packages/nocodb-sdk/src/lib/columnHelper/utils/decimal.ts
packages/nocodb-sdk/src/lib/columnHelper/utils/index.ts

Nc fix/decimal scientific notation

---

packages/nc-gui/components/dlg/ReAssign/UserItem.vue
packages/nc-gui/components/dlg/ReAssign/index.vue
packages/nc-gui/lang/en.json

Nc fix/personal view followup

---

packages/nc-gui/components/cell/Percent/Editor.vue
packages/nc-gui/components/cell/Percent/ProgressBar.vue
packages/nc-gui/components/cell/Percent/Readonly.vue
packages/nc-gui/components/smartsheet/FormulaWrapperCell.vue
packages/nc-gui/components/smartsheet/Gallery.vue
packages/nc-gui/components/smartsheet/Kanban.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/Percent.ts

show percent as progress bar at several missing places. https://github.com/nocodb/nocodb/issues/10737

fix: progress bar not shown in several places

---

nix/package.nix
packages/nc-gui/components/cell/Email/Editor.vue
packages/nc-gui/components/cell/PhoneNumber/Editor.vue
packages/nc-gui/components/cell/TextArea.vue
packages/nc-gui/components/cell/Url/Editor.vue
packages/nc-gui/components/cell/Url/Readonly.vue
packages/nc-gui/components/smartsheet/FormulaWrapperCell.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/Attachment.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/Url.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/index.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useKeyboardNavigation.ts
packages/nc-gui/composables/useCopy.ts
packages/nc-gui/composables/useInfiniteData.ts
packages/nc-gui/lang/en.json
packages/nc-gui/utils/dataUtils.ts
packages/nc-gui/utils/urlUtils.ts
packages/nocodb-sdk/package.json
packages/nocodb-sdk/src/lib/columnHelper/utils/index.ts
packages/nocodb-sdk/src/lib/columnHelper/utils/url.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/sql-data-mapper/lib/BaseModel.ts
packages/nocodb/src/db/util/customValidators.ts
pnpm-lock.yaml

Nc fix: url cell related bug fixes

---

packages/nc-gui/composables/useViewGroupBy.ts

Colour of selection  update in group headers

fix: color is not updating

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/BaseModelSqlv2/nested-link-preparator.ts
packages/nocodb/src/db/IBaseModelSqlV2.ts
packages/nocodb/src/helpers/dbHelpers.ts

Nc refactor/prepare nested link qb

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/LongText.ts
packages/nc-gui/components/smartsheet/grid/canvas/utils/canvas.ts
packages/nc-gui/components/smartsheet/grid/canvas/utils/types.ts

Nc Fix: Rich text doesn't wrap for change in row height

---

packages/nocodb/src/db/BaseModelSqlv2.ts

fix (nocodb): perform convertDateTime to created and last modified time. Closes https://github.com/nocodb/nocodb/issues/8593

fix (nocodb): perform convertDateTime to created and last modified time

---

packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts

- Update filter add button selector, use data-* atribute.

test: update filter add button selector

---

packages/nc-gui/components/smartsheet/expanded-form/Detached.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/components/virtual-cell/components/ItemChip.vue
packages/nc-gui/components/virtual-cell/components/LinkedItems.vue
packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
packages/nc-gui/composables/useExpandedFormDetached/index.ts
packages/nc-gui/context/index.ts

Nc Fix: Same record can be opened multiple times simultaneously in Expanded Form 

---

packages/nc-gui/utils/iconUtils.ts

- closes: https://github.com/nocodb/nocodb/issues/10568

fix: replace initially loading material font icons with svg icons

---

packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts

send table alias for lookup formula

---

packages/nc-gui/components/smartsheet/expanded-form/index.vue

fix: Expanded form title

---

packages/nc-gui/components/cell/Date/Editor.vue

Nc fid/date tab save value format

---

packages/nc-gui/components/cell/attachment/index.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue

fix: Upload popup window closes 'Create and Link' window after file uploaded

---

packages/nc-gui/components/dlg/QuickImport.vue
packages/nc-gui/helpers/parsers/CSVTemplateAdapter.ts
packages/nc-gui/workers/importWorker.ts

if existing column found during upload, use the column uidt

---

packages/nc-gui/components/dlg/View/Create.vue
packages/nc-gui/components/smartsheet/Kanban.vue
packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
packages/nocodb/src/services/kanbans.service.ts

Kanban - If at least one attachment column exist mark it as cover

---

packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCopyPaste.ts
packages/nc-gui/components/smartsheet/grid/canvas/context/Cell.vue
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/grid/canvas/utils/constants.ts
packages/nc-gui/components/smartsheet/grid/index.vue
packages/nc-gui/composables/useGridViewData.ts
packages/nc-gui/composables/useInfiniteData.ts
packages/nc-gui/composables/useMultiSelect/index.ts

fix: id not found error when bulkUpdate

fix: id not found error when bulkUpdate

---

packages/nocodb/src/models/View.ts
packages/nocodb/tests/unit/factory/viewColumns.ts
packages/nocodb/tests/unit/rest/tests/viewRow.test.ts

Nc fix/10839 gallery attachent field

---

packages/nocodb/src/db/formulav2/formula-query-builder.types.ts
packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts

aliasToColumns now accept parentColumns as parameter

---

packages/nocodb/src/db/BaseModelSqlv2.ts

Fix: Bulk update related issue

fix: bulk update related issue

---

packages/nc-gui/composables/useInfiniteData.ts

Nc fix/10868 expanded form next prev

---

packages/nc-gui/composables/useInfiniteData.ts
packages/nocodb/src/controllers/data-alias.controller.ts
packages/nocodb/src/controllers/data-table.controller.ts
packages/nocodb/src/helpers/getAst.ts
packages/nocodb/src/services/data-table.service.ts
packages/nocodb/src/services/datas.service.ts

Nc fix clear sort indicator

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/index.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts

fix: ai button is disabled in synced table

---

packages/nc-gui/components/smartsheet/calendar/SideMenu.vue
packages/nc-gui/components/smartsheet/calendar/SideRecordCard.vue

Closes https://github.com/nocodb/nocodb/issues/10864

fix: sidebar card ux

---

packages/nocodb/Dockerfile
packages/nocodb/Dockerfile.local
packages/nocodb/Dockerfile.timely

fix: skip modclean for @react-email 

---

packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
packages/nc-gui/composables/useInfiniteData.ts
packages/nc-gui/composables/useSmartsheetStore.ts
packages/nocodb-sdk/src/lib/filterHelpers.ts
packages/nocodb-sdk/src/lib/ncTypes.ts
packages/nocodb/src/db/BaseModelSqlv2.ts

feat: use filter parser for v3 api

feat: use filter parser for v3 api

---

packages/nc-gui/components/cell/Currency/Editor.vue
packages/nc-gui/components/cell/Currency/index.vue

fix: currency not working in normal grid.

---

packages/nc-gui/components/smartsheet/toolbar/GroupByMenu.vue
packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue
packages/nc-gui/utils/sortUtils.ts

Nc fix/group sort formula

---

packages/nc-gui/components/cell/Decimal/Editor.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/Decimal.ts

Handle canvas keyboard key

---

packages/nc-gui/helpers/tiptap-markdown/extensions/marks/link.ts

fix(nc-gui): At the end of link, if we continue to type - stop formatting as link

---

packages/nocodb/src/helpers/populateSamplePayload.ts

Nc fix/webhook user sample

---

packages/nc-gui/components/smartsheet/grid/canvas/utils/canvas.ts
packages/nc-gui/components/virtual-cell/Formula.vue

fix: formula not gettign truncated

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/Button.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/virtual-cell/Button.vue
packages/nocodb/src/services/mail/mail.service.ts

Closes https://github.com/nocodb/nocohub/issues/4840
https://github.com/nocodb/nocohub/issues/4854

fix: Misc Fixes

---

build-local-docker-image.sh

Ref - https://discord.com/channels/661905455894888490/1350999467872223346

Update build command in local docker build bash file

---

packages/nc-gui/components/smartsheet/expanded-form/RichComment.vue

fix(nc-gui): don't remove selected text on enter press

---

packages/nc-gui/components/dashboard/TreeView/TableNode.vue
packages/nc-gui/composables/useBetaFeatureToggle.ts

Nc fix/opts vis

---

packages/nc-gui/composables/useLTARStore.ts

fix: where query param syntax

---

packages/nc-gui/composables/useLTARStore.ts
packages/nocodb/src/services/utils.service.ts

refactor: add debounce for list api call to avoid unnecessary api calls

---

packages/nc-gui/components/smartsheet/grid/canvas/utils/canvas.ts
packages/nc-gui/utils/urlUtils.ts
packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts

Nc fix formula renderer

---

packages/nocodb/src/helpers/dbHelpers.ts
packages/nocodb/src/services/utils.service.ts

fix: Enable data audit by default and disable only if explicitly disabled using env

---

packages/nocodb/src/db/generateLookupSelectQuery.ts

fix: Group by - Formula lookup correction

---

packages/nc-gui/components/smartsheet/Details.vue
packages/nc-gui/composables/useRoles/index.ts

fix: Do permission check only after loading the base roles

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts

Nc fix/10962 unintended filter from related table view

---

packages/nc-gui/components/general/ReleaseInfo.vue

Updated "how to upgrade?" link, per #10973 
Updated "how to upgrade?" link, per #10973 to https://docs.nocodb.com/getting-started/self-hosted/upgrading

fixes #10973: how to upgrade link

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/conditionV2.ts
packages/nocodb/src/db/formulav2/formula-query-builder.types.ts
packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/db/functionMappings/commonFns.ts
packages/nocodb/src/db/functionMappings/databricks.ts
packages/nocodb/src/db/functionMappings/mssql.ts
packages/nocodb/src/db/functionMappings/mysql.ts
packages/nocodb/src/db/functionMappings/pg.ts
packages/nocodb/src/db/functionMappings/sqlite.ts
packages/nocodb/src/db/genRollupSelectv2.ts
packages/nocodb/src/db/generateLookupSelectQuery.ts
packages/nocodb/src/db/mapFunctionName.ts
packages/nocodb/src/db/sortV2.ts
packages/nocodb/src/services/columns.service.ts
packages/nocodb/src/services/formula-column-type-changer/mysql-data-migration.ts
packages/nocodb/src/services/formula-column-type-changer/pg-data-migration.ts
packages/nocodb/src/services/formula-column-type-changer/sqlite-data-migration.ts

Nc refactor/remove formula alias

---

packages/nocodb/src/db/formulav2/formula-query-builder.helpers.ts
packages/nocodb/src/db/formulav2/formula-query-builder.types.ts
packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/db/formulav2/lookup-or-ltar-builder.ts
packages/nocodb/src/db/formulav2/parsed-tree-builder.ts
packages/nocodb/src/db/genRollupSelectv2.ts

refactor: formula builder parsed tree and ltar builder

refactor: formula builder parsed tree and ltar builder

---

packages/nc-gui/assets/style.scss
packages/nc-gui/components/dashboard/TreeView/BaseOptions.vue
packages/nc-gui/components/dlg/AirtableImport.vue
packages/nc-gui/components/dlg/NocoDbImport.vue
packages/nc-gui/components/dlg/QuickImport.vue
packages/nc-gui/components/nc/Alert.vue
packages/nc-gui/components/nc/Checkbox.vue
packages/nc-gui/components/nc/List/index.vue
packages/nc-gui/components/project/ImportModal.vue
packages/nc-gui/components/template/Editor.vue
packages/nc-gui/components/template/utils.ts
packages/nc-gui/components/virtual-cell/Formula.vue
packages/nc-gui/helpers/parsers/CSVTemplateAdapter.ts
packages/nc-gui/helpers/parsers/ExcelTemplateAdapter.ts
packages/nc-gui/helpers/parsers/JSONTemplateAdapter.ts
packages/nc-gui/lang/en.json
packages/nc-gui/plugins/ant.ts

Nc fix/import data modal followup items

---

packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/db/functionMappings/sqlite.ts

fix sqlite dateadd formula

---

packages/nocodb/src/models/BaseUser.ts

fix: add order as result for list base

fix: add order as result for list base

---

packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCopyPaste.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useKeyboardNavigation.ts
packages/nc-gui/components/smartsheet/grid/canvas/context/Cell.vue
packages/nc-gui/components/smartsheet/header/ColumnMenu.vue
packages/nc-gui/composables/useLTARStore.ts
packages/nocodb-sdk/src/lib/columnHelper/columns/LTAR/BelongsTo.ts
packages/nocodb-sdk/src/lib/columnHelper/columns/LTAR/ManyToMany.ts
packages/nocodb-sdk/src/lib/columnHelper/columns/LTAR/OneToOne.ts

Nc Fix: Links and Ltar cell copy paste issue

---

packages/nc-gui/components/cell/attachment/Card.vue
packages/nc-gui/components/cell/attachment/Carousel.vue
packages/nc-gui/utils/fileUtils.ts

add support for audio change file icon for audio and video on card

---

packages/nocodb/src/db/conditionV2.ts

fix: send table alias to formula. fixes https://github.com/nocodb/nocodb/issues/10972#top

fix: send table alias to formula

---

packages/nocodb/src/db/BaseModelSqlv2.ts

fix(nocodb): re-export getAs from BaseModelSqlv2

---

packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/components/smartsheet/grid/index.vue
packages/nc-gui/composables/useMultiSelect/index.ts

Nc Fix: Expanded form navigation and group paste issue if infiniteScroll is disabled

---

packages/nocodb/src/db/field-handler/handlers/date-time/date-time.general.handler.ts
packages/nocodb/src/db/field-handler/handlers/decimal/decimal.general.handler.ts
packages/nocodb/src/db/field-handler/handlers/single-line-text/single-line-text.general.handler.ts

add gb_eq and gb_null for filter verify

---

packages/nc-gui/components/cell/Percent/Readonly.vue

fox non infinite percent 0

---

packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/db/formulav2/parsed-tree-builder.ts

fix: formula handle divide by zero. Fix https://github.com/nocodb/nocodb/issues/11002

fix: formula handle divide by zero

---

packages/nc-cli/src/lib/mgr/MigrationMgr.ts
packages/nc-cli/src/lib/util/Util.ts
packages/nc-gui/components/dlg/InviteDlg.vue
packages/nc-gui/components/workspace/InviteSection.vue
packages/noco-docs/versioned_docs/version-0.109.7/030.setup-and-usages/230.team-and-auth.md
packages/nocodb-sdk/src/lib/columnHelper/utils/decimal.spec.ts
packages/nocodb/src/db/sql-migrator/lib/KnexMigratorv2.ts
packages/nocodb/src/plugins/GenericS3/GenericS3.ts
packages/nocodb/src/services/formula-column-type-changer/mysql-data-migration.ts
packages/nocodb/src/services/formula-column-type-changer/pg-data-migration.ts
packages/nocodb/src/services/formula-column-type-changer/sqlite-data-migration.ts
packages/nocodb/tests/unit/rest/tests/meta-apis/table.test.ts

fix: typos

---

packages/nocodb/src/constants/controllers.ts
packages/nocodb/src/controllers/v3/columns-v3.controller.ts
packages/nocodb/src/controllers/v3/comments-v3.controller.ts
packages/nocodb/src/controllers/v3/data-v3.controller.ts
packages/nocodb/src/controllers/v3/filters-v3.controller.ts
packages/nocodb/src/controllers/v3/hooks-v3.controller.ts
packages/nocodb/src/controllers/v3/sorts-v3.controller.ts
packages/nocodb/src/controllers/v3/tables-v3.controller.ts
packages/nocodb/src/controllers/v3/views-v3.controller.ts
packages/nocodb/src/middlewares/extract-ids/extract-ids.middleware.ts
packages/nocodb/src/modules/noco.module.ts
packages/nocodb/src/services/datas.service.ts

Nc feat/baseid partition v3api

---

packages/nc-gui/components/account/Profile.vue

fix(nc-gui): add explicit save btn to save user name

---

packages/nc-gui/components/cell/attachment/Modal.vue

show upload indicator when attachment list empty

---

packages/nc-gui/components/cell/Percent/ProgressBar.vue
packages/nc-gui/components/cell/Percent/Readonly.vue
packages/nc-gui/components/smartsheet/FormulaWrapperCell.vue

fix formula height

---

packages/nc-gui/composables/useViewGroupBy.ts
packages/nocodb/src/db/field-handler/handlers/checkbox/checkbox.general.handler.ts

fix: load comment meta for groupby children data. Closes https://github.com/nocodb/nocodb/issues/11049

fix: load comment meta for groupby children data

---

packages/nocodb/src/db/field-handler/handlers/checkbox/checkbox.general.handler.ts
packages/nocodb/src/db/formulav2/formula-query-builder.types.ts
packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/db/formulav2/lookup-or-ltar-builder.ts

fix: formula lookup with depth more than 1. Closes https://github.com/nocodb/nocodb/issues/11032

fix: formula lookup with depth more than 1

---

packages/nc-gui/components/dlg/AirtableImport.vue

fix (nc-gui): airtable add close button when import complete 

---

packages/nc-gui/lib/constants.ts

fix(nc-gui): decrease toast msg timeout to 6 sec

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCopyPaste.ts
packages/nc-gui/composables/useGridViewData.ts

fix: prod issues related to paste

---

packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/db/formulav2/lookup-or-ltar-builder.ts
packages/nocodb/src/models/ButtonColumn.ts
packages/nocodb/src/models/FormulaColumn.ts
packages/nocodb/src/utils/modelUtils.ts

fix: Generate and update parsed_tree column data if missing 

---

packages/nocodb/src/db/conditionV2.ts
packages/nocodb/src/db/field-handler/handlers/formula/formula.general.handler.ts
packages/nocodb/src/db/field-handler/handlers/links/links.general.handler.ts
packages/nocodb/src/db/field-handler/handlers/rollup/rollup.general.handler.ts
packages/nocodb/src/db/field-handler/index.ts

Nc refactor/field handler formula rollup

---

packages/nocodb/src/interface/Jobs.ts
packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.processor.ts
packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts

fix: exclude users flag

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/Currency.ts

fix (nc-gui): currency 0 not displayed. Closes https://github.com/nocodb/nocodb/issues/11074

fix (nc-gui): currency 0 not displayed

---

markdown/readme/languages/chinese.md

Fix the issue where the App Store link in the Chinese documentation could not be opened.
Fix the issue where the App Store link in the Chinese documentation could not be opened.
no need
no

docs: fix chinese.md app store link.

---

packages/nc-gui/components/webhook/index.vue

Resolves issue #11081
This video shows the selection after the fix.
https://github.com/user-attachments/assets/ef33d9a6-08cb-439c-a492-be3a9c1ef151

fix: webhook channel selection when no items

---

packages/nc-gui/components/smartsheet/grid/canvas/components/AddNewRowMenu.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useKeyboardNavigation.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/grid/canvas/utils/constants.ts
packages/nc-gui/components/smartsheet/toolbar/GroupByMenu.vue
packages/nc-gui/composables/useGridViewData.ts
packages/nc-gui/composables/useInfiniteData.ts
packages/nc-gui/composables/useInfiniteGroups.ts

Nc canvas groupby followup

---

packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/ColumnList.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/Columns.vue

Fixes issue - https://github.com/nocodb/nocodb/issues/11094
https://github.com/user-attachments/assets/d305e9db-a148-4405-a1a1-6d9f28cb6623

Fix: Hidden column menu rendering incorrectly

---

packages/nc-gui/utils/dataUtils.ts
packages/nocodb-sdk/src/lib/columnHelper/utils/get-lookup-column-type.ts
packages/nocodb-sdk/src/lib/columnHelper/utils/index.ts
packages/nocodb-sdk/src/lib/filter/index.ts
packages/nocodb-sdk/src/lib/filter/validate-row-filters.ts
packages/nocodb-sdk/src/lib/index.ts

Nc refactor/validate row filters

---

packages/nocodb/src/db/BaseModelSqlv2.ts

We allow linking multiple records at a time via API, in that scenario we were calling Audit insertion one by one which leads to huge amount of connections to be occupied (+we populate missing display values one by one)
With this change we will both read in batches & insert in batches.
TBD:
will restrict maximum number of links to be added with one call to 100

feat: bulk audit for bulk link creation

---

packages/nocodb/src/db/BaseModelSqlv2.ts

Follow up for https://github.com/nocodb/nocodb/pull/11105

feat: bulk audit for bulk link remove

---

nix/docker/all_in_one/init/env-processor/env_processor.sh

feat(nix/docker/aio/minio): disable minio by default

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts
packages/nc-gui/composables/useInfiniteData.ts

> expand record -- navigation breaks after current page limit
https://github.com/nocodb/nocohub/issues/5112
> group by field label overflow needs fix
> Count & aggregation font same size? They appear not to be in same line
> Closes https://github.com/nocodb/nocodb/issues/11118
> row moved line is partial

fix: grid related issues

---

packages/noco-docs/docs/145.cloud-enterprise-edition/010.community-vs-paid-editions.md

docs: update expected timelines for upcoming features

---

.github/workflows/ci-cd.yml
.github/workflows/docker-readme-publish.yml

Ref https://github.com/actions/runner-images/issues/11101

chore: upgrade runner version

---

packages/nocodb/src/meta/meta.service.ts

feat: single transaction invite

---

packages/nc-gui/components/dashboard/View.vue
packages/nc-gui/components/dashboard/topbar/index.vue
packages/nc-gui/components/extensions/Details.vue
packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/workspace/CollaboratorsList.vue
packages/nc-gui/components/workspace/View.vue
packages/nc-gui/composables/useEeConfig.ts

Nc fix/billing page UI fixes

---

packages/nc-gui/components/smartsheet/expanded-form/index.vue

fix(nc-gui): use view id instead of view title in record url

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useDataFetch.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/grid/canvas/utils/groupby.ts

fix: cannot make cell editable

---

packages/nocodb/src/db/sql-client/lib/pg/PgClient.ts

fix (nocodb): json cdf when passed value is number or boolean

fix (nocodb): json cdf when passed value is number or boolean

---

packages/nc-gui/components/project/View.vue

fix: payment follow ups

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/composables/useInfiniteData.ts

Nc groupby pending

---

packages/nocodb/src/db/BaseModelSqlv2.ts

Fix: https://github.com/nocodb/nocohub/commit/d06877da3a0fe76eb5b91e42c2e7678879c5fead#r155640073

fix: reorder switch case

---

packages/nc-gui/components/smartsheet/expanded-form/Sidebar/AuditMiniItem.vue

fix(nc-gui): Audit column title overflow issue

---

packages/nc-gui/ant.d.ts
packages/nc-gui/components/nc/Alert.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCopyPaste.ts
packages/nc-gui/composables/useEeConfig.ts
packages/nc-gui/composables/useMultiSelect/index.ts
packages/nc-gui/lang/en.json
packages/nc-gui/lib/ncMessage.ts
packages/nc-gui/plugins/ant.ts

Nc Feat: simple toast message on cell copy

---

packages/nc-gui/lang/en.json
packages/nc-gui/middleware/04.payment.global.ts

feat: upgrade status

---

packages/nocodb/src/plugins/backblaze/Backblaze.ts
packages/nocodb/src/plugins/s3/S3.ts

Fixes nocodb#10942
See:
https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/checksums/ResponseChecksumValidation.html
https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/checksums/RequestChecksumCalculation.html

nc fix: Compatibility flag to fix Backblaze S3

---

packages/noco-docs/src/modules/maintenance.js

Improve timezone extraction regex

---

packages/nc-gui/components/general/IconSelector.vue
packages/nc-gui/components/general/WorkspaceIcon.vue
packages/nc-gui/composables/useEeConfig.ts
packages/nc-gui/lang/en.json
packages/nocodb-sdk/src/lib/payment/index.ts

feat(nc-gui): show default ws logo as nocodb logo

---

packages/nc-gui/components/smartsheet/topbar/TableListDropdown.vue
packages/nc-gui/components/smartsheet/topbar/ViewListDropdown.vue
packages/nc-gui/components/template/Editor.vue
packages/nc-gui/utils/validation.ts

fix(nc-gui): table/view list dropdown content width issue

---

packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useRowReOrder.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/grid/canvas/utils/groupby.ts
packages/nc-gui/composables/useInfiniteData.ts
packages/nc-gui/lib/types.ts
tests/playwright/pages/Dashboard/Grid/index.ts

Nc Refactor(nc-gui): Grid index cell UI 

---

packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/composables/useGridViewData.ts
packages/nc-gui/composables/useInfiniteData.ts

Closes https://github.com/nocodb/nocodb/issues/11194

fix: scroll handling when height changes

---

packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
packages/nc-gui/components/smartsheet/toolbar/FieldListAutoCompleteDropdown.vue
packages/nc-gui/components/smartsheet/toolbar/GroupByMenu.vue
packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue
tests/playwright/pages/Dashboard/common/Toolbar/Groupby.ts
tests/playwright/tests/db/general/groupCRUD.spec.ts

Closes https://github.com/nocodb/nocohub/issues/5202

fix: filter field selection overflow

---

packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index.vue

fix: Dark mode problem with form in iFrame

---

packages/nc-gui/components.d.ts
packages/nocodb/src/utils/acl.ts

Closes https://github.com/nocodb/nocohub/issues/5185#top

fix: webhookPluginList permission

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/QRCode.ts
packages/nc-gui/components/virtual-cell/QrCode.vue

Nc qr code error

---

packages/nc-gui/components/dlg/WorkspaceSsoRedirectConfirm.vue
packages/nocodb-sdk/src/lib/UITypes.ts
packages/nocodb-sdk/src/lib/index.ts
packages/nocodb/src/db/sql-client/lib/pg/PgClient.ts
packages/nocodb/src/helpers/columnHelpers.ts
packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
packages/nocodb/src/meta/migrations/v2/nc_077_column_index_name.ts
packages/nocodb/src/models/Column.ts
packages/nocodb/src/services/columns.service.ts

Nc fix/custom link index creation

---

packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/header/ColumnMenu.vue
packages/nocodb/src/services/columns.service.ts

fix: sync fields ui

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useColumnResize.ts
packages/nocodb/src/plugins/storage/Local.ts

Closes https://github.com/nocodb/nocodb/issues/10980
Closes https://github.com/nocodb/nocodb/issues/10230

fix: Closes Misc Issues

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts
packages/nocodb/src/db/BaseModelSqlv2.ts

fix: lookup to an LTAR field shows Blank Chip

---

packages/nc-gui/components/smartsheet/toolbar/SearchData.vue

fix: search is not triggered on field change

---

packages/nocodb/src/db/BaseModelSqlv2.ts

fix: handle primitive values in transformation

---

packages/nc-gui/components/smartsheet/Cell.vue

fix(nc-gui): number cell is broken

---

packages/nocodb-sdk/src/lib/payment/index.ts
packages/nocodb/tests/unit/rest/tests/dataApiV3/error-handling.test.ts

Nc fix/hot pricing

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/LongText.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/index.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/utils/canvas.ts
packages/nc-gui/components/smartsheet/grid/canvas/utils/markdownUtils.ts
packages/nc-gui/lib/types.ts

Nc fix user markdown

---

packages/nc-gui/components/cell/RichText/LinkOptions.vue
packages/nc-gui/utils/is.ts
packages/nc-gui/utils/urlUtils.ts

Nc codegen bot/fix leaving nocodb notification

---

packages/nc-gui/components/smartsheet/Toolbar.vue
packages/nc-gui/components/smartsheet/Topbar.vue
packages/nc-gui/components/smartsheet/toolbar/SearchData.vue
packages/nc-gui/components/smartsheet/toolbar/ViewInfo.vue

fix(nc-gui): enable toolbar seach in mobile view

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCopyPaste.ts
packages/nc-gui/composables/useMultiSelect/index.ts
packages/nocodb-sdk/src/lib/columnHelper/columns/Currency.ts
packages/nocodb-sdk/src/lib/columnHelper/columns/Decimal.ts
packages/nocodb-sdk/src/lib/columnHelper/columns/Number.ts
packages/nocodb-sdk/src/lib/columnHelper/columns/SingleLineText.ts

Nc Fix: empty cells from Number fields converted to 'null' text when pasted into SingleLineText fields

---

packages/nc-gui/components/nc/form-builder/index.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/QRCode.ts
packages/nc-gui/composables/useEeConfig.ts
packages/nc-gui/lang/en.json
packages/nocodb-sdk/src/lib/payment/index.ts
packages/nocodb/src/helpers/catchError.ts
packages/nocodb/src/modules/noco.module.ts

chore: sync changes

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts

Nc fix/grid row lines issue

---

packages/nocodb/src/models/BaseUser.ts

fix: Starred base persistence issue

---

packages/nc-gui/components/smartsheet/Pagination.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/components/smartsheet/grid/GroupByTable.vue
packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/components/smartsheet/grid/index.vue
packages/nc-gui/lang/en.json

Nc Fix/limit record in group by if it is external source

---

packages/nc-gui/components/nc/DateWeekSelector.vue
packages/nc-gui/components/nc/MonthYearSelector.vue
packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue
packages/nc-gui/components/smartsheet/calendar/MonthView.vue
packages/nc-gui/components/smartsheet/calendar/SideMenu.vue
packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
packages/nc-gui/components/smartsheet/calendar/YearView/Month.vue
packages/nc-gui/components/smartsheet/toolbar/Calendar/Header.vue
packages/nc-gui/components/smartsheet/toolbar/Calendar/Today.vue
packages/nc-gui/composables/useCalendarViewStore.ts
packages/nc-gui/utils/worker/datetimeUtils.ts
packages/nocodb-sdk/src/lib/dateTimeHelper.ts
packages/nocodb/src/db/conditionV2.ts

fix: calendar filter related issues

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts
packages/nc-gui/composables/useInfiniteGroups.ts
packages/nocodb/src/db/BaseModelSqlv2/group-by.ts

- Compare Path error
- GroupBy not working in date field as sub group

fix: using columnId as alias causes the value to transformed

---

packages/nocodb/src/services/mail/mail.service.ts

Closes https://github.com/nocodb/nocodb/issues/11231#issue-3022946889

fix: remove dashboard path in reset password and token verify url

---

packages/nc-gui/components/general/JoinCloud.vue
packages/nc-gui/components/webhook/index.vue
packages/nc-gui/composables/useEeConfig.ts
packages/nc-gui/lib/types.ts
packages/nocodb-sdk/src/lib/Api.ts
packages/nocodb/src/controllers/utils.controller.ts
packages/nocodb/src/schema/swagger.json
packages/nocodb/src/services/utils.service.ts
packages/nocodb/src/utils/globals.ts

Fix: Update join cloud card

---

packages/nocodb-sdk/src/lib/dateTimeHelper.ts

fix : Filter year playwright test

fix : Filter year playwright test

---

packages/nocodb/src/db/field-handler/handlers/json/json.general.handler.ts
packages/nocodb/src/db/field-handler/handlers/json/json.mysql.handler.ts
packages/nocodb/src/db/field-handler/handlers/json/json.pg.handler.ts

fix: enable is and isnot operator on JSON

fix: enable is and isnot operator on JSON

---

packages/nc-gui/components/dlg/QuickImport.vue

fix(nc-gui): use import to base tables instead of active base tables

---

packages/nocodb/src/helpers/dbHelpers.ts

fix: handle pk ag columns

---

packages/nc-gui/components/dlg/InviteDlg.vue
packages/nc-gui/composables/useEeConfig.ts

fix(nc-gui): Alert msg visibility issue in invite dlg

---

packages/nocodb-sdk/src/lib/columnHelper/columns/LongText.ts
packages/nocodb-sdk/src/lib/columnHelper/columns/SingleLineText.ts
packages/nocodb-sdk/src/lib/columnHelper/utils/serializer.ts

Fix copy paste trims space

---

packages/nc-gui/components/account/Token.vue

Nc codegen bot/allow multiple api tokens

---

packages/nocodb/src/controllers/api-version-not-found.controller.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/BaseModelSqlv2/group-by.ts
packages/nocodb/src/helpers/catchError.ts

fix: improve types for NcError

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts
packages/nc-gui/components/smartsheet/grid/index.vue
packages/nc-gui/components/smartsheet/toolbar/CreateSort.vue
packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue
packages/nc-gui/composables/useInfiniteGroups.ts
packages/nc-gui/composables/useViewGroupBy.ts
packages/nc-gui/utils/dataUtils.ts

x## Change Summary
Closes https://github.com/nocodb/nocodb/issues/11289

fix: groupby rendering issue with nested lookups

---

packages/nocodb/src/db/field-handler/handlers/formula/formula.general.handler.ts

- Closes https://github.com/nocodb/nocodb/issues/11266

fix: Formula filter - avoid mutating column object

---

packages/nc-gui/components/dlg/View/Create.vue
packages/nc-gui/components/nc/DateWeekSelector.vue
packages/nc-gui/components/nc/MonthYearSelector.vue
packages/nc-gui/components/smartsheet/Toolbar.vue
packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue
packages/nc-gui/components/smartsheet/calendar/MonthView.vue
packages/nc-gui/components/smartsheet/calendar/RecordCard.vue
packages/nc-gui/components/smartsheet/calendar/SideMenu.vue
packages/nc-gui/components/smartsheet/calendar/SideRecordCard.vue
packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue
packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
packages/nc-gui/components/smartsheet/calendar/YearView/Month.vue
packages/nc-gui/components/smartsheet/calendar/YearView/index.vue
packages/nc-gui/components/smartsheet/calendar/index.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/DateTime.ts
packages/nc-gui/components/smartsheet/toolbar/Calendar/Header.vue
packages/nc-gui/components/smartsheet/toolbar/Calendar/Mode.vue
packages/nc-gui/components/smartsheet/toolbar/Calendar/NextPrev.vue
packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue
packages/nc-gui/components/smartsheet/toolbar/Calendar/Today.vue
packages/nc-gui/components/smartsheet/toolbar/Calendar/ToggleSideBar.vue
packages/nc-gui/composables/useBetaFeatureToggle.ts
packages/nc-gui/composables/useCalendarViewStore.ts
packages/nc-gui/composables/useSharedView.ts
packages/nocodb/src/controllers/calendars-datas.controller.ts
packages/nocodb/src/schema/swagger.json
packages/nocodb/src/services/calendar-datas.service.ts
packages/nocodb/tests/unit/rest/tests/viewRow.test.ts
tests/playwright/pages/Dashboard/Calendar/CalendarSideMenu.ts

Calendar DateTime
Closes https://github.com/nocodb/nocohub/issues/2429
Closes https://github.com/nocodb/nocodb/issues/11273#event-17507718432

feat: Calendar end Date (DateTime)

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue

Nc fix: Cursor pointer issue in row meta column (Index column)

---

packages/nocodb/src/db/field-handler/handlers/formula/formula.general.handler.ts
packages/nocodb/src/db/field-handler/index.ts
packages/nocodb/src/db/formulav2/formula-query-builder.types.ts
packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
packages/nocodb/src/db/formulav2/lookup-or-ltar-builder.ts
packages/nocodb/src/db/mapFunctionName.ts

fix: lookup-formula-nested. Closes https://github.com/nocodb/nocodb/issues/11299

fix: lookup-formula-nested

---

packages/nocodb/src/middlewares/extract-ids/extract-ids.middleware.ts
packages/nocodb/tests/unit/rest/tests/dataApiV3/error-handling.test.ts
packages/nocodb/tests/unit/rest/tests/dataApiV3/get-list.test.ts
packages/nocodb/tests/unit/rest/tests/dataApiV3/get-record.test.ts

fix: base & model extract

---

packages/nc-gui/components/dashboard/View.vue
packages/nc-gui/components/workspace/View.vue
packages/nocodb-sdk/src/lib/payment/index.ts

fix: sidebar

---

packages/nc-gui/components/project/View.vue
packages/nc-gui/components/smartsheet/Kanban.vue
packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
packages/nc-gui/components/tabs/Smartsheet.vue
packages/nc-gui/composables/useColumnFilteredOrSorted.ts
packages/nc-gui/composables/useSmartsheetStore.ts
packages/nocodb-sdk/src/lib/columnHelper/utils/url.ts
packages/nocodb/src/db/field-handler/index.ts

Nc fix/checkbox issue

---

nix/package.nix
nix/shell.nix

fix(nix): hash bump

---

packages/nc-gui/composables/useGalleryViewData.ts
packages/nocodb-sdk/src/lib/columnHelper/utils/date-time.spec.ts
packages/nocodb-sdk/src/lib/columnHelper/utils/date-time.ts
packages/nocodb-sdk/src/lib/columnHelper/utils/index.ts
packages/nocodb-sdk/src/lib/columnHelper/utils/parser.ts
packages/nocodb-sdk/src/lib/columnHelper/utils/serializer.ts
packages/nocodb/src/db/relation-manager.ts

fix: gallery search & date copy paste. Closes: https://github.com/nocodb/nocodb/issues/11306, https://github.com/nocodb/nocodb/issues/11323, https://github.com/nocodb/nocodb/issues/11324

fix: gallery search & date copy paste Nc fix/gallery search date copy paste

---

packages/nc-gui/components/smartsheet/grid/canvas/loaders/ActionManager.ts

fix: avoid calling loadIntegrations, instead use derived from workspace

---

packages/nocodb/src/db/BaseModelSqlv2/group-by.ts

fix: user group by for user count > 25. Closes https://github.com/nocodb/nocodb/issues/11318

fix: user group by for user count > 25

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/Button.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/index.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/lib/types.ts

Perf issues with canvas in SingleSelect Field

fix: canvas perf regression

---

tests/playwright/pages/Dashboard/common/Cell/UserOptionCell.ts
tests/playwright/tests/db/features/expandedFormModeFiles.spec.ts

test: skip expand modes in OSS

---

packages/nocodb/src/schema/swagger-v3.json

fix single line text not valid for field schema

---

packages/nocodb/src/db/BaseModelSqlv2/group-by.ts
packages/nocodb/src/db/aggregations/pg.ts
packages/nocodb/src/db/aggregations/sqlite3.ts

fix (nocodb): multi user replace for order

fix (nocodb): multi user replace for order

---

packages/nc-gui/components/dlg/MCP/Delete.vue
packages/noco-docs/docs/080.records/030.expand-record.md

Nc Fix: add missing docs link of supported preview file type in expanded form file mode

---

packages/nc-gui/components/extensions/Market.vue
packages/nc-gui/components/project/View.vue
packages/nc-gui/composables/useExtensions.ts
packages/nc-gui/composables/usePlugin/index.ts
packages/nc-gui/composables/usePlugin/interface.ts
packages/nc-gui/lang/en.json

feat: script templates

---

packages/nc-gui/components/dlg/Table/Delete.vue

- Closes https://github.com/nocodb/nocohub/issues/5526

fix: Table delete - handle scenarios when user not in table page

---

packages/nc-gui/components/dashboard/Sidebar.vue
packages/nc-gui/components/dashboard/Sidebar/Version.vue

feat: add version in sidebar - sync

---

packages/nocodb/src/mcp/mcp.service.ts

Alllow mcp to access row audits
- can be used to build timeseries charts

feat: audit logs support

---

docker-compose/1_Auto_Upstall/noco.sh

this pr introduces a key value store in pure posix shell to store the upstall state 
and a state version for future migrations 
closes #10159
tested on Ubuntu 22.04.3 LTS

fix(upstall): kvstore init

---

nix/package.nix

chore(nix/package/pnpmDeps): bump hash

---

packages/nocodb/src/db/aggregations/pg.ts
packages/nocodb/src/db/aggregations/sqlite3.ts

fix: User group-by bug

---

packages/nc-gui/utils/treeviewUtils.ts

Improve choice of language for base hover info.
None.

refactor: tweak strings

---

packages/nc-gui/components/dashboard/FeatureExperimentation.vue
packages/nc-gui/lang/en.json

Nc codegen bot/add search to experimental features

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/helpers/dbHelpers.ts

Closes https://github.com/nocodb/nocodb/issues/11406#top

fix: preserve non-aliased fields in result mapping

---

packages/nc-gui/composables/useInfiniteData.ts

fix (nc-gui): ui sorting

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/BaseModelSqlv2/select-object.ts

refactor: out selectObject from baseModel

refactor: out selectObject from baseModel

---

packages/nc-gui/components/cmd-k/index.vue
packages/nc-gui/components/dashboard/FeatureExperimentation.vue
packages/nc-gui/components/dashboard/MiniSidebar.vue
packages/nc-gui/components/dashboard/Sidebar/MiniSidebarItemWrapper.vue
packages/nc-gui/components/dashboard/TreeView/Project/ActionMenu.vue
packages/nc-gui/components/dashboard/TreeView/Project/Home.vue
packages/nc-gui/components/dashboard/TreeView/Project/List.vue
packages/nc-gui/components/dashboard/TreeView/Project/SearchInput.vue
packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
packages/nc-gui/components/dashboard/TreeView/TableList.vue
packages/nc-gui/components/dashboard/TreeView/index.vue
packages/nc-gui/components/project/AllTables.vue
packages/nc-gui/components/smartsheet/topbar/TableListDropdown.vue
packages/nc-gui/composables/useBetaFeatureToggle.ts
packages/nc-gui/lang/en.json

Nc fix/mini sidebar followup

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/Plain.ts
packages/nc-gui/utils/dataUtils.ts

Nc fix(nc-gui): parse numeric field plain cell value issue if value is 0

---

packages/noco-docs/docs/070.fields/040.field-types/070.date-time-based/010.date-time.md
packages/noco-docs/docs/070.fields/040.field-types/070.date-time-based/020.date.md
packages/nocodb-sdk/src/lib/dateTimeHelper.ts
packages/nocodb/src/helpers/convertDateFormat.ts

Added new date formates requested in - #9652 
If im missing something please mention it i will do it

Fea: new date formates 9652

---

packages/nocodb/src/schema/swagger-v2.json

fix: swagger status code for nested link add. closes https://github.com/nocodb/nocodb/issues/11140

fix: swagger status code for nested link add

---

packages/nocodb/src/db/field-handler/handlers/json/json.general.handler.ts

Provide summary of changes with issue number if any. Closes https://github.com/nocodb/nocodb/issues/11423

fix json like on sqlite connection

---

packages/nc-gui/components/smartsheet/grid/canvas/context/Cell.vue
packages/nc-gui/components/smartsheet/grid/canvas/loaders/ActionManager.ts
packages/nc-gui/utils/Queue.ts

fix: queuing for bulk execution

---

packages/nc-gui/components/smartsheet/PlainCell.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/components/smartsheet/toolbar/OpenedViewAction.vue
packages/nc-gui/utils/dataUtils.ts
packages/nc-gui/utils/urlUtils.ts

Fixed:
Old plain cell value:
```ts
URI::( https://github.com/nocodb/nocodb/pull/9686 ) LABEL::( Fea: new date formates 9652 )
```
New plain cell value:
```ts
Fea: new date formates 9652
```

fix(nc-gui): formula field parse link text display issue

---

packages/nocodb/src/schema/swagger-v3.json
packages/nocodb/src/utils/api-v3-data-transformation.builder.ts
packages/nocodb/src/utils/transformProperties.ts

Fix: Missing v3 Meta props and corrections

fix: v3 meta api corrections

---

packages/noco-docs/docs/145.cloud-enterprise-edition/010.community-vs-paid-editions.md

Docs calendar end date

---

packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue

Closes https://github.com/nocodb/nocohub/issues/5574

fix:keyboard field interactions broken after filter is modified

---

packages/nc-gui/composables/useInfiniteData.ts

Closes https://github.com/nocodb/nocohub/issues/5599

fix: filter not applied on count

---

packages/nocodb/src/db/field-handler/handlers/json/json.general.handler.ts

fix (nocodb): re-add null filter in json. Closes: https://github.com/nocodb/nocodb/issues/11261

fix (nocodb): re-add null filter in json

---

packages/nocodb/src/db/conditionV2.ts
packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts

fix (nocodb): like/nlike user field use new replacement. Fixes: https://github.com/nocodb/nocodb/issues/11351

fix (nocodb): like/nlike user field use new replacement

---

packages/nocodb/src/db/BaseModelSqlv2.ts

fix: record audit log when new value is null. Closes: https://github.com/nocodb/nocodb/issues/11415

fix: record audit log when new value is null

---

packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue

fix(nc-gui): filter test fail issue

---

packages/nc-gui/components/monaco/formula-type-validation.ts
packages/nc-gui/components/smartsheet/column/ButtonOptions/index.vue
packages/nc-gui/components/smartsheet/column/FormulaInputHelper.vue

feat: better formula input handler

---

packages/nc-gui/components/cell/User/Editor.vue
packages/nc-gui/components/smartsheet/column/FormulaInputHelper.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
packages/nc-gui/composables/useColumnFilteredOrSorted.ts

Nc fix/user filter followup changes

---

packages/nc-gui/components/smartsheet/expanded-form/index.vue

fix(nc-gui): record view mode not visible

---

packages/nocodb/build-utils/registerIntegrations.js

chore: register integrations

---

packages/nc-gui/composables/useBetaFeatureToggle.ts
packages/nc-gui/store/sidebar.ts

Enable Improved SideBar for all Users

feat: enable improved sidebar for all users

---

packages/nc-gui/components/erd/FullScreenToggle.vue
packages/nc-gui/components/nc/List/index.vue
packages/nc-gui/extensions/data-exporter/index.vue
packages/nc-gui/utils/fileUtils.ts
packages/noco-docs/docs/.135.extensions/050.url-preview.md
packages/nocodb/src/modules/jobs/jobs/data-export/data-export.controller.ts

Nc fix/extension followup items

---

tests/playwright/tests/utils/config.ts

fix: failing tests

---

nix/docker/all_in_one/init/s6-services/services/acme-log/run
nix/docker/all_in_one/init/s6-services/services/minio-log/run
nix/docker/all_in_one/init/s6-services/services/nginx-log/run
nix/docker/all_in_one/init/s6-services/services/nocodb-log/run
nix/docker/all_in_one/init/s6-services/services/postgresql-log/run
nix/docker/all_in_one/init/s6-services/services/valkey-log/run

support for docker logs
nix build github:nocodb/nocodb/aio-logs#docker_aio
https://alinafs.com/V.png

chore(nix/docker/aio): support docker logs

---

packages/nc-gui/composables/useExtensionHelper.ts

Nc fix/pagination sync

---

packages/nc-gui/components/smartsheet/Topbar.vue
packages/nc-gui/composables/usePlugin/index.ts
packages/nc-gui/composables/usePlugin/interface.ts

Nc feat/enable ext

---

packages/nc-gui/components/smartsheet/grid/canvas/index.vue

Nc fix/hide canvas element tooltip on mouse leave

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/services/data-table.service.ts

fix: add missing typecast to update

---

packages/nc-gui/composables/useInfiniteGroups.ts

Closes https://github.com/nocodb/nocodb/issues/11531

fix:  Group by shared view with password is broken

---

packages/nocodb/src/helpers/getAst.ts

fix: v3 api now return foreign key column when list data

fix: v3 api now return foreign key column when list data

---

packages/nocodb-sdk/src/lib/index.ts
packages/nocodb-sdk/src/lib/sqlUi/DatabricksUi.ts
packages/nocodb-sdk/src/lib/sqlUi/MssqlUi.ts
packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
packages/nocodb-sdk/src/lib/sqlUi/OracleUi.ts
packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts
packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts
packages/nocodb-sdk/src/lib/sqlUi/SqlUI.types.ts
packages/nocodb-sdk/src/lib/sqlUi/SqliteUi.ts
packages/nocodb-sdk/src/lib/stringHelpers.spec.ts
packages/nocodb-sdk/src/lib/stringHelpers.ts
packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.controller.ts

fix: duplicate table long name

fix: duplicate table long name

---

packages/nocodb-sdk/src/lib/error-handler/nc-error-base.ts
packages/nocodb/src/constants/index.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/field-handler/handlers/email/email.general.handler.ts
packages/nocodb/src/db/field-handler/handlers/json/json.general.handler.ts
packages/nocodb/src/db/field-handler/handlers/long-text/long-text.general.handler.ts
packages/nocodb/src/db/field-handler/handlers/phone-number/phone-number.general.handler.ts
packages/nocodb/src/db/field-handler/index.ts
packages/nocodb/tests/unit/rest/tests/dataApiV3/error-handling.test.ts

Nc feat/text limit 100k

---

packages/nc-gui/components/smartsheet/grid/GroupByTable.vue
packages/nc-gui/composables/useInfiniteData.ts
packages/nc-gui/utils/filterUtils.ts

fix: @me user filter new row default value

fix: @me user filter new row default value

---

packages/nc-gui/components/smartsheet/expanded-form/ViewModeSelector.vue
packages/nc-gui/components/smartsheet/expanded-form/index.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/index.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/LTAR/BelongsTo.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/LTAR/HasMany.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/LTAR/ManyToMany.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/LTAR/OneToOne.ts
packages/nc-gui/components/virtual-cell/components/ItemChip.vue
packages/nc-gui/components/virtual-cell/components/LinkedItems.vue
packages/nc-gui/components/virtual-cell/components/ListItem.vue

Nc Feat: Allow commenter/viewer to expand linked record

---

packages/nocodb/src/db/field-handler/handlers/long-text/long-text.general.handler.ts
packages/nocodb/tests/unit/rest/tests/dataApiV3/error-handling.test.ts

Nc fix/loosen text validation

---

packages/nc-gui/components/smartsheet/form/field-settings.vue
packages/nc-gui/components/smartsheet/form/field-settings/LinkRecordDropdownExtraFieldVisibility.vue
packages/nc-gui/components/smartsheet/form/field-settings/visibility.vue
packages/nc-gui/components/smartsheet/header/Cell.vue
packages/nc-gui/components/smartsheet/header/VirtualCell.vue
packages/nc-gui/components/virtual-cell/components/ListItem.vue
packages/nc-gui/composables/useLTARStore.ts
packages/nc-gui/lang/en.json
packages/nc-gui/lib/form.ts
packages/nocodb-sdk/src/lib/form.ts

Nc Feat: Limit information visible in linked record field in form view 

---

packages/nc-gui/components/dlg/InviteDlg.vue
packages/nc-gui/components/project/AccessSettings.vue
packages/nc-gui/components/workspace/CollaboratorsList.vue
packages/nc-gui/lang/en.json

Nc fix/5780 user invite existing user

---

packages/nc-gui/components/cell/attachment/Modal.vue

- Couldn't open attachment in modal

fix: prevent attachment cell exit on modal open

---

packages/nc-gui/utils/dataUtils.ts

fix: Skip attachment field while pre-populating data using default value

---

packages/nc-gui/utils/commonUtils.ts
packages/nc-gui/utils/storageUtils.ts

fix(nc-gui): Move ncLastVisitedBase fn in storageUtils file

---

packages/nc-gui/components/dashboard/TreeView/Project/List.vue
packages/nc-gui/store/bases.ts

fix(nc-gui): sidebar keeps loading when we don't have any bases or user don't have access to any base

---

packages/nc-gui/components/virtual-cell/Lookup.vue
packages/nc-gui/store/bases.ts

Nc Fix: Alignment issue in lookup field 

---

packages/nc-gui/components/smartsheet/expanded-form/presentors/Discussion/EntryComment.vue

Nc fix: Update comment box border color for user's own comments

---

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue

Nc fix(nc-gui): just toggle sidebar baselist if clicked base is already active 

---

packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue
packages/nc-gui/components/dlg/View/Create.vue
packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/components/smartsheet/Gallery.vue
packages/nc-gui/components/smartsheet/Kanban.vue
packages/nc-gui/components/smartsheet/calendar/DayView/DateField.vue
packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue
packages/nc-gui/components/smartsheet/calendar/MonthView.vue
packages/nc-gui/components/smartsheet/calendar/SideMenu.vue
packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue
packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
packages/nc-gui/components/smartsheet/topbar/ViewListDropdown.vue
packages/nc-gui/components/virtual-cell/components/LinkedItems.vue
packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
packages/nc-gui/composables/useCalendarViewStore.ts
packages/nc-gui/composables/useSmartsheetStore.ts
packages/nc-gui/lang/en.json
packages/nc-gui/store/views.ts
packages/nocodb/src/services/forms.service.ts

Nc Fix: disable form view creation in synced table & disable add record from other views

---

packages/nc-gui/components/smartsheet/grid/canvas/components/Scroller.vue

Nc fix(nc-gui): grid horizontal scroll issue using shift + mouse scroll in linux

---

packages/nc-gui/composables/useColumnFilteredOrSorted.ts

fix: Avoid blocking pointer events with pseudo elements

---

tests/playwright/tests/db/general/views.spec.ts

test(pw): update view search test pw cases

---

docker-compose/1_Auto_Upstall/noco.sh

closes https://github.com/nocodb/nocodb/issues/11635

fix(upstall): x86-64-v1 target compatibility

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCopyPaste.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useKeyboardNavigation.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useMouseSelection.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useRowReOrder.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/composables/useMultiSelect/cellRange.ts
packages/nc-gui/lib/types.ts

Nc Fix: fields move around during vertical navigation using down-arrow key

---

packages/nocodb/src/db/aggregations/pg.ts
packages/nocodb/src/db/aggregations/sqlite3.ts

Nc fix: user like quick search

---

packages/nc-gui/components/smartsheet/toolbar/SearchData.vue
packages/nc-gui/composables/useLTARStore.ts

Nc fix/consider extra link record fields also in search

---

packages/nc-gui/components/ai/Erd/Flow.vue
packages/nc-gui/components/ai/Erd/utils.ts
packages/nc-gui/components/erd/Flow.vue
packages/nc-gui/components/erd/View.vue
packages/nc-gui/components/erd/utils.ts
tests/playwright/tests/db/features/erd.spec.ts

Nc refactor/erd

---

packages/nocodb/src/plugins/minio/Minio.ts

closes https://github.com/nocodb/nocodb/issues/11614

fix(nocodb/plugins/minio): server crash on test

---

packages/nocodb/src/db/BaseModelSqlv2.ts

fix: knex raw dbdriver issue for mysql

fix: knex raw dbdriver issue for mysql

---

.github/workflows/release-docker.yml
.github/workflows/release-npm.yml

chore: Build action change

---

.github/workflows/release-docker.yml
.github/workflows/release-npm.yml

chore: Add build Noco integration step

---

.github/workflows/release-docker.yml

Typo correction

---

packages/nc-gui/components/dashboard/Sidebar.vue

fix: new maintenance ui

---

packages/nocodb-sdk/src/lib/error-handler/nc-error-base.ts
packages/nocodb-sdk/src/lib/error-handler/preset-error-codex-map.ts
packages/nocodb-sdk/src/lib/globals.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/services/forms.service.ts

fix: dedicated error for PROHIBITED_SYNC_TABLE_OPERATION

fix: dedicated error for PROHIBITED_SYNC_TABLE_OPERATION

---

packages/nc-gui/components/smartsheet/toolbar/FieldListWithSearch.vue

fix: avoid locking search

---

packages/nocodb-sdk/src/lib/columnHelper/columns/Date.ts
packages/nocodb-sdk/src/lib/columnHelper/columns/DateTime.spec.ts
packages/nocodb-sdk/src/lib/columnHelper/columns/DateTime.ts

Closes https://github.com/nocodb/nocodb/issues/11667

fix datetime for single value

---

packages/nc-gui/components/extensions/Extension.vue
packages/nc-gui/composables/useBetaFeatureToggle.ts
packages/nc-gui/composables/usePlugin/index.ts

Nc fix(nc-gui): Beta extension load issue

---

packages/nocodb-sdk/src/lib/columnHelper/utils/serializer.ts
packages/nocodb-sdk/src/lib/currencyHelpers.spec.ts
packages/nocodb-sdk/src/lib/currencyHelpers.ts
packages/nocodb-sdk/src/lib/index.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/field-handler/handlers/currency/currency.general.handler.ts
packages/nocodb/src/db/field-handler/handlers/currency/currency.mysql.handler.ts
packages/nocodb/src/db/field-handler/handlers/currency/currency.pg.handler.ts
packages/nocodb/src/db/field-handler/handlers/currency/currency.sqlite.handler.ts
packages/nocodb/src/db/field-handler/index.ts

fix: handle currency locale via api

fix: handle currency locale via api

---

packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue

fix(nc-gui): base navigation issue on click chevron arrow btn

---

packages/nocodb-sdk/src/lib/audit/v1.ts
packages/nocodb-sdk/src/lib/enums.ts

- Script Duplicate
- Script Audits

feat: duplicate script & script audit

---

packages/nc-gui/components/cell/Decimal/DecimalInput.vue
packages/nc-gui/components/cell/Decimal/Editor.vue

fix: vmodel update on decimal input. Closes: https://github.com/nocodb/nocodb/issues/11684

fix vmodel update on decimal input

---

nix/package.nix
nix/workflows/bumper/bumper.sh

someone skipped the bumper workflow before merge, 
fixes https://github.com/nocodb/nocodb/issues/11332#issuecomment-2981283323

chore(nix): bump hash

---

packages/nc-gui/app.vue
packages/nc-gui/assets/nc-icons/enter.svg
packages/nc-gui/assets/nc-icons/stop-circle.svg
packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
packages/nc-gui/components/dlg/Base/Duplicate.vue
packages/nc-gui/components/n/Select/Field.vue
packages/nc-gui/components/n/Select/Table.vue
packages/nc-gui/components/n/Select/View.vue
packages/nc-gui/components/nc/Menu/Item.vue
packages/nc-gui/components/project/View.vue
packages/nc-gui/components/smartsheet/Automation/ActionPane.vue
packages/nc-gui/components/smartsheet/Topbar.vue
packages/nc-gui/composables/useBetaFeatureToggle.ts
packages/nc-gui/lang/en.json
packages/nc-gui/store/automation.ts
packages/nc-gui/utils/Queue.ts
packages/nc-gui/utils/iconUtils.ts
packages/nocodb/src/interface/Jobs.ts
packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.processor.ts
packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.service.ts
packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts

fix: beta toggle related issues

---

packages/nocodb/src/models/View.ts

fix: map definition

---

packages/nc-gui/components/smartsheet/toolbar/SearchData.vue

Closes https://github.com/nocodb/nocodb/issues/11726

fix: update aggregation on search changes

---

packages/nc-gui/components/monaco/Editor.vue
packages/nc-gui/components/webhook/index.vue
packages/nc-gui/lang/en.json
packages/nocodb/src/controllers/hooks.controller.ts
packages/nocodb/src/helpers/populateSamplePayload.ts
packages/nocodb/src/helpers/webhookHelpers.ts
packages/nocodb/src/services/hooks.service.ts
packages/nocodb/src/services/utils.service.ts
tests/playwright/pages/Dashboard/WebhookForm/index.ts
tests/playwright/tests/db/features/webhook.spec.ts

Nc feat/webhook user obj

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/Number.ts

fix(nc-gui): In canvas blank number cell value is displayed as zero

---

packages/nc-gui/store/bases.ts

fix(nc-gui): new sidebar baselist visibility issue on page reload

---

packages/nc-gui/components/nc/Table.vue
packages/nc-gui/components/project/AccessSettings.vue
packages/nc-gui/components/workspace/CollaboratorsList.vue

fix(nc-gui): add pagination support in member list table (Workspace & base user list table) 

---

packages/nc-gui/components/smartsheet/toolbar/SearchData.vue
packages/nc-gui/composables/useViewData.ts

Nc fix/view search count issue

---

packages/nc-gui/helpers/tiptap-markdown/extensions/marks/link.ts

fix(nc-gui): rich text link related issues

---

packages/nc-gui/components/cell/MultiSelect/Editor.vue
packages/nc-gui/components/cell/SingleSelect/Editor.vue
packages/nc-gui/components/cell/SingleSelect/Readonly.vue
packages/nc-gui/components/cell/SingleSelect/utils.ts
packages/nc-gui/components/cell/TextArea.vue
packages/nc-gui/components/cell/User/Editor.vue
packages/nc-gui/components/cell/attachment/index.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/MultiSelect.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/SingleSelect.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/User.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/virtual-cell/BelongsTo.vue
packages/nc-gui/components/virtual-cell/HasMany.vue
packages/nc-gui/components/virtual-cell/Links.vue
packages/nc-gui/components/virtual-cell/Lookup.vue
packages/nc-gui/components/virtual-cell/ManyToMany.vue
packages/nc-gui/components/virtual-cell/OneToOne.vue
packages/nc-gui/lib/constants.ts

Nc fix/select cell interaction

---

packages/nocodb/src/services/api-docs/swagger/getSwaggerColumnMetas.ts
packages/nocodb/src/services/api-docs/swaggerV2/getSwaggerColumnMetas.ts

fix: Map UITypes to correct swagger types

---

packages/nc-gui/composables/useBetaFeatureToggle.ts

chore: enable perm & scripts

---

packages/nc-gui/components/dlg/Record/Upsert.vue
packages/nc-gui/components/project/View.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
tests/playwright/pages/Dashboard/ExpandedForm/index.ts
tests/playwright/pages/Dashboard/Grid/Column/UserOptionColumn.ts
tests/playwright/pages/Dashboard/Grid/ExpandTable.ts
tests/playwright/pages/Dashboard/Grid/Group.ts
tests/playwright/pages/Dashboard/Grid/index.ts
tests/playwright/pages/Dashboard/common/Cell/index.ts

Nc test(nc-gui): PW test fail issue

---

packages/nc-gui/components/smartsheet/grid/canvas/index.vue

fix(nc-gui): canvas cursor pointer issue on hover empty area and reset row hover on mouseleave canvas area

---

packages/nc-gui/components/general/LockedViewFooter.vue
packages/nc-gui/components/smartsheet/toolbar/Filter/FilterRow.vue

Nc fix/row colouring config issue

---

packages/nc-gui/components/smartsheet/column/EditOrAddProvider.vue
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
packages/nc-gui/composables/useColumnCreateStore.ts

Nc fix/links related bugs

---

packages/nc-gui/composables/useBetaFeatureToggle.ts

fix: fix-beta-toggle recursion

---

packages/nc-gui/components/payment/upgrade/Badge.vue
packages/nc-gui/middleware/04.payment.global.ts

Nc fix/undefined upgrade feature req

---

packages/nocodb/src/db/sql-mgr/code/routers/xc-ts/SwaggerTypes.ts
packages/nocodb/src/models/Base.ts
packages/nocodb/src/services/api-docs/swagger/getSwaggerColumnMetas.ts
packages/nocodb/src/services/api-docs/swaggerV2/getSwaggerColumnMetas.ts
packages/nocodb/src/utils/dataUtils.ts

- Re https://community.nocodb.com/t/bug-report-id-not-showing-up-in-request-types-in-openapi-json/1973
- Re https://community.nocodb.com/t/bug-report-decimal-columns-labeled-as-string-in-openapi-json/1942/3
- Add missing decimal case in postgres(swagger schema extraction)
- Proper db type extraction based on column source
- Remove unnecessary switch cases for non-virtual uidt

fix: Corrections in swagger schema extraction

---

packages/nocodb/src/models/Hook.ts
packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
packages/nocodb/src/services/hooks.service.ts

Nc fix/hooks v2 duplicate

---

packages/nc-gui/assets/nc-icons-v2/crown.svg
packages/nc-gui/components/workspace/CollaboratorsList.vue
packages/nc-gui/utils/iconUtils.ts

Nc fix: use crown icon istead of star

---

nix/package.nix
packages/nocodb/package.json
pnpm-lock.yaml

- Dependencies were not bumped in https://github.com/nocodb/nocodb/pull/11796

chore: bump mcp

---

packages/nc-gui/components/cell/TextArea.vue
packages/nc-gui/components/cell/attachment/Preview/Image.vue
packages/nc-gui/components/smartsheet/Gallery.vue
packages/nc-gui/components/smartsheet/Kanban.vue

Nc fix/gallery view issue

---

packages/nocodb/src/services/utils.service.ts

filter out version outside ###.###.### format

---

packages/nocodb/src/helpers/dbHelpers.ts

Nc fix/get value

---

packages/nocodb-sdk/src/lib/payment/index.ts

fix: color theme

---

packages/nc-gui/components/cell/attachment/Carousel.vue

CLoses https://github.com/nocodb/nocohub/issues/6119

fix: attachment carousel overlay

---

packages/nc-gui/components/cell/User/Editor.vue

fix: User field - missing first char in search field on pressing key

---

packages/nocodb/src/helpers/apiHelpers.ts
packages/nocodb/src/helpers/ncError.ts

fix: api version optional following ncContext

fix: api version optional following ncContext

---

packages/nc-gui/composables/useGlobal/state.ts
packages/nc-gui/composables/useGlobal/types.ts
packages/nocodb/src/services/utils.service.ts

refactor: or key to env

---

packages/nocodb/src/services/columns.service.ts

fix: Links - create the current column before the ref table column creation

---

packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
packages/nc-gui/components/dlg/share-and-collaborate/View.vue
packages/nc-gui/components/nc/Menu/ItemLabel.vue
packages/nc-gui/components/project/AccessSettings.vue
packages/nc-gui/components/tabs/Smartsheet.vue
packages/nc-gui/lib/types.ts

Fix(nc-gui): Add user info in user profile menu

---

packages/nocodb/src/utils/internal-type.ts

fix: remove unrefernece types

---

packages/nocodb/src/db/getColumnNameQuery.ts

fix: query corrections

---

packages/nocodb/tests/unit/rest/tests/aggregation.test.ts

test: unit tests for some virtual columns

---

packages/nc-gui/components/cell/attachment/utils.ts
packages/nc-gui/components/dlg/InviteDlg.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCopyPaste.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useFillHandler.ts
packages/nc-gui/composables/useAttachment.ts
packages/nc-gui/composables/useEeConfig.ts
packages/nc-gui/composables/useMultiSelect/convertCellData.ts
packages/nc-gui/composables/useMultiSelect/index.ts
packages/nc-gui/lang/en.json
packages/nocodb-sdk/src/lib/payment/index.ts

Nc fix(nc-gui): Provide unlimited attachments in a file attachment field for paid users

---

packages/nc-gui/components/cell/MultiSelect/LayoutList.vue
packages/nc-gui/components/cell/SingleSelect/LayoutList.vue
packages/nc-gui/components/cell/User/Editor.vue

Nc refactor: improve search clearing in select type field selection

---

packages/nocodb/src/db/sql-client/lib/pg/PgClient.ts
packages/nocodb/src/services/meta-diffs.service.ts

- Closes https://github.com/nocodb/nocodb/issues/11854

fix: Postgres - Meta-diff related issue

---

packages/nc-gui/components/dashboard/TreeView/Project/List.vue
packages/nc-gui/components/dashboard/TreeView/Project/ListSkeleton.vue

Nc Fix: Base home page sidebar loading issue

---

packages/nc-gui/components/dashboard/MiniSidebar.vue
packages/nc-gui/components/dashboard/Sidebar/TopSection.vue
packages/nc-gui/components/dashboard/TreeView/Project/List.vue
packages/nc-gui/components/workspace/View.vue

fix(nc-gui): ws members tab access issue

---

packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts

fix: hook duplicate does not duplicate nested filters

---

packages/nc-gui/components/dlg/Base/Duplicate.vue
packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue
packages/nc-gui/context/index.ts
packages/nc-gui/lang/en.json
packages/nc-gui/lib/constants.ts
packages/nc-gui/store/dashboard.ts
packages/nocodb-sdk/src/lib/dashboard/index.ts
packages/nocodb/src/db/widgets/index.ts
packages/nocodb/src/interface/Jobs.ts
packages/nocodb/src/models/Dashboard.ts
packages/nocodb/src/models/Filter.ts
packages/nocodb/src/models/index.ts
packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.controller.ts
packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.processor.ts
packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.service.ts
packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
packages/nocodb/src/modules/jobs/jobs/export-import/migrate.service.ts

chore: nc sync

---

packages/nc-gui/app.vue
packages/nc-gui/components/nc/NuxtLoadingIndicator.vue
packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/survey.vue

Nc feat(nc-gui): Page loading indicator

---

packages/nocodb/src/db/widgets/base-widget.handler.ts
packages/nocodb/src/db/widgets/index.ts
packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts

fix: type error

---

packages/nocodb-sdk/src/lib/error-handler/nc-error-base.ts
packages/nocodb-sdk/src/lib/error-handler/preset-error-codex-map.ts
packages/nocodb/src/helpers/NcErrorV1.ts
packages/nocodb/src/helpers/ncErrorV3.ts
packages/nocodb/src/schema/swagger-v3.json
packages/nocodb/src/services/tables.service.ts
packages/nocodb/src/services/v3/tables-v3.service.ts
packages/nocodb/src/utils/api-v3-data-transformation.builder.ts
packages/nocodb/tests/unit/rest/tests/metaApiV3/error-handling/index.test.ts
packages/nocodb/tests/unit/rest/tests/metaApiV3/error-handling/table.test.ts
packages/nocodb/tests/unit/rest/tests/metaApiV3/index.test.ts
packages/nocodb/tests/unit/rest/tests/metaApiV3/table.test.ts

Nc feat/v3 meta error handling table

---

packages/nc-gui/components/dashboard/TreeView/Project/List.vue
packages/nc-gui/components/project/View.vue
packages/nc-gui/pages/index/[typeOrId]/[baseId]/index/index/index.vue

fix(nc-gui): UI error on initial load if user has role editor or below

---

packages/nocodb/src/middlewares/extract-ids/extract-ids.middleware.ts
packages/nocodb/src/services/base-users/base-users.service.ts
packages/nocodb/src/services/mail/mail.service.ts
packages/nocodb/tests/unit/formula/tests/formula-lookup-ltar.test.ts
packages/nocodb/tests/unit/init/cleanupMeta.ts
packages/nocodb/tests/unit/processor/duplicate/duplicate-base.test.ts
packages/nocodb/tests/unit/rest/tests/metaApiV3/error-handling/table.test.ts
packages/nocodb/tests/unit/rest/tests/metaApiV3/table.test.ts

fix: skip tests when not postgres

---

packages/nc-gui/components/project/View.vue

fix(nc-gui): table navigation issue

---

packages/nocodb/src/models/View.ts
packages/nocodb/src/services/view-row-color.service.ts

fix: rowColoringInfo get deleted from view meta on view icon change 

---

packages/nc-gui/components/n/RecordPicker/Records.vue
packages/nc-gui/components/n/RecordPicker/index.vue
packages/nc-gui/components/smartsheet/calendar/SideMenu.vue
packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
packages/nc-gui/components/smartsheet/column/LookupOptions.vue
packages/nc-gui/components/smartsheet/column/RollupOptions.vue
packages/nc-gui/components/smartsheet/toolbar/SearchData.vue
packages/nc-gui/composables/useCalendarViewStore.ts
packages/nc-gui/composables/useFieldQuery.ts
packages/nc-gui/composables/useKanbanViewStore.ts
packages/nc-gui/composables/useLTARStore.ts
packages/nc-gui/composables/useSmartsheetStore.ts
packages/nc-gui/lang/en.json

- Refactor getValidSearchQueryForColumn function
- Move it from useSmartsheetStore to useFieldQuery so that we can use it anywhere without depending on smartsheetStore
- Kanban & calendar view search issue

Nc refactor(nc-gui): getValidSearchQueryForColumn function

---

packages/nc-gui/components/dashboard/FeatureExperimentation.vue
packages/nc-gui/composables/useBetaFeatureToggle.ts

Nc chore(nc-gui): add isOnPrem toggle support in feature flag

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/AILongText.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/Attachment.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/Barcode.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/Button.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/Formula.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/Json.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/LTAR/HasMany.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/LTAR/ManyToMany.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/LongText.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/Url.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/index.ts
packages/nc-gui/components/smartsheet/grid/canvas/context/Cell.vue
packages/nc-gui/components/smartsheet/grid/canvas/loaders/ActionManager.ts
packages/nc-gui/components/virtual-cell/Button.vue
packages/nc-gui/lib/types.ts
packages/nc-gui/utils/columnUtils.ts

- ref: Show tooltip if url is invalid
- ref: #11969
- Button activation : spinning and not clickable.
- Button success : show an ephemeral success icon. And then it reverts back.
- Button error : error icon with an error message on hover. This is also ephemeral.

Nc Fix: button field related issues

---

packages/nc-gui/composables/useBetaFeatureToggle.ts

feat: enable dashboard

---

packages/nocodb/src/helpers/columnHelpers.ts

fix: Rollup validation - validate function against rollup column

---

packages/nc-gui/components/smartsheet/grid/canvas/components/GroupHeaderMenu.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/grid/index.vue
packages/nc-gui/composables/useGridViewData.ts
packages/nc-gui/composables/useInfiniteData.ts
packages/nc-gui/composables/useInfiniteGroups.ts
packages/nocodb/src/Noco.ts
packages/nocodb/src/db/BaseModelSqlv2/group-by.ts
packages/nocodb/src/services/data-table.service.ts

feat: expand all

---

packages/nc-gui/components/smartsheet/details/Webhooks.vue

chore(nc-gui): add missing docs links

---

packages/nocodb/Dockerfile

Ref: https://github.com/nocodb/nocodb/actions/runs/16566645108/job/46849371081

chore: Revert Dockerfile changes since it's breaking arm/v7 build

---

packages/nocodb-sdk/src/lib/dashboard/index.ts

fix: layout order randomizes

---

packages/nocodb/src/models/Column.ts
packages/nocodb/src/services/meta-diffs.service.ts

fix: Correct alias column handling in meta-sync

---

packages/nc-gui/components/dashboard/MiniSidebar.vue
packages/nc-gui/components/dashboard/settings/base/index.vue
packages/nc-gui/components/project/View.vue
packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue
packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue
packages/nc-gui/components/workspace/integrations/view.vue

Nc Fix: Integration page UI issues

---

packages/nocodb/src/models/Column.ts

Nc fix/6365 mm rename bug

---

packages/nc-gui/components/nc/List/AggregationSelector.vue
packages/nc-gui/components/nc/List/ColumnSelector.vue
packages/nc-gui/components/nc/List/TableSelector.vue
packages/nc-gui/components/nc/List/ViewSelector.vue
packages/nocodb-sdk/src/lib/aggregationHelper.ts

NcList Helper components for dashboards

feat: nc list helper components

---

packages/nocodb/src/controllers/v3/bases-v3.controller.ts
packages/nocodb/tests/unit/rest/tests/metaApiV3/error-handling/base.test.ts

fix: define proper scope

---

packages/nocodb/src/db/BaseModelSqlv2.ts

show attachment without id

---

packages/nc-gui/utils/storageUtils.ts

fix(nc-gui): Use local storage instead of session storage to keep last visited base id

---

packages/nocodb-sdk-v2/src/lib/Api.ts
packages/nocodb/src/schema/swagger-v3.json

docs: operationId for meta APIs

---

packages/nocodb/src/models/User.ts

fix(nocodb): dont set is_new_user value to true for now else on merging onboarding flow later existing user also see onboaring flow on login

---

packages/nc-gui/composables/useGridViewData.ts

fix: search broken

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/Formula.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts

Nc fix: show timezone doesn't work in formula date time formatting #6436

---

packages/nc-gui/app.vue
packages/nc-gui/components/dashboard/MiniSidebar/Theme.vue
packages/nc-gui/composables/useAntDvTheme.ts
packages/nc-gui/composables/useTheme.ts

Nc fix: hide darkmode in ui

---

packages/nc-gui/components/dashboard/FeatureExperimentation.vue

Closes https://github.com/nocodb/nocodb/issues/12070

fix: change experimental features shortcut

---

packages/nocodb/src/models/Base.ts

Clear file references from deleted bases

fix: Clear file references when base is deleted

---

packages/nocodb-sdk/src/lib/payment/index.ts

add FEATURE_API_MEMBER_MANAGEMENT plan

---

packages/nc-gui/components/dlg/View/Create.vue
packages/nc-gui/composables/useLTARStore.ts

Nc fix: enable search for date selection dropdown

---

packages/nocodb/src/schema/swagger-v3.json

Nc docs/swagger fix 0814

---

packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue
packages/nc-gui/components/workspace/CollaboratorsList.vue

fix(nc-gui): Cannot read properties of undefined (reading 'workspace-level-owner')

---

packages/nocodb-sdk/src/lib/audit/v1.ts
packages/nocodb-sdk/src/lib/enums.ts
packages/nocodb/src/models/Permission.ts
packages/nocodb/src/models/index.ts
packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts

feat: include permissions on duplicates

---

packages/nc-gui/components/smartsheet/column/SelectOptions.vue

fix(Sentry TypeError): Cannot read properties of null (reading 'scrollHeight')

---

packages/nc-gui/assets/css/theme-overrides.scss
packages/nc-gui/components/nc/Button.vue

Nc Style: Dark mode empty state svg and ghost button type color issue

---

packages/nc-gui/components/smartsheet/column/FormulaInputHelper.vue
packages/nc-gui/composables/useColumnCreateStore.ts

fix(UI): Cannot read properties of undefined (reading 'getDataTypeForUiType')

---

packages/nocodb/src/helpers/webhookHelpers.ts

fix: Apply condition check for prev data in bulk operation hook

---

packages/nocodb/src/db/sql-client/lib/pg/PgClient.ts

fix: extrct unique constraint as boolean

---

packages/nc-gui/components/cell/attachment/UploadProviders/Local.vue
packages/nc-gui/components/nc/List/ColumnSelector.vue
packages/nc-gui/components/nc/List/TableSelector.vue
packages/nc-gui/components/nc/List/ViewSelector.vue
packages/nc-gui/components/nc/List/index.vue
packages/nc-gui/composables/useLTARStore.ts
packages/nc-gui/pages/playground/components/filter/filter-group/index.vue
packages/nc-gui/pages/playground/components/row-color-picker-toolbar/using-filter-panel/index.vue
packages/nc-gui/utils/domUtils.ts

- Cannot read properties of undefined (reading 'length')
- Cannot read properties of null (reading 'appendChild')

Nc Fix: Sentry TypeError

---

packages/nc-gui/utils/baseCreateUtils.ts

fix: compare error message after converting to lowercase

---

packages/nc-gui/components/dashboard/MiniSidebar/CreateNewActionMenu.vue
packages/nc-gui/components/workspace/CreateProjectDlg.vue
packages/nc-gui/components/workspace/project/AiCreateProject.vue
packages/nc-gui/pages/index.vue
packages/nc-gui/pages/index/[typeOrId]/[baseId]/index/index/index.vue
packages/nc-gui/store/bases.ts
packages/nc-gui/store/tables.ts
packages/nc-gui/utils/baseUtils.ts
packages/nc-gui/utils/browserUtils.ts
packages/nocodb-sdk/src/lib/stringHelpers.ts

Nc Feat(nc-gui): Use basePrompt & baseName query params to directly open AI base create modal with prefilled value 

---

packages/nocodb/src/db/BaseModelSqlv2.ts

trim added options when typecast = true

---

packages/nocodb/src/services/v3/data-v3.service.ts
packages/nocodb/tests/unit/rest/tests/dataApiV3/beforeEach.ts
packages/nocodb/tests/unit/rest/tests/dataApiV3/post-insert.test.ts

fix: if fields is somehow not defined, return empty object

fix: if fields is somehow not defined, return empty object

---

packages/nocodb/src/services/v3/data-v3.service.ts

fix: optimize error messages in backend scripts

---

packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/components/smartsheet/details/Fields.vue

- undefined is not an object (evaluating 'V.value[H].fk_column_id')
- Cannot read properties of undefined (reading 'fk_column_id')

Nc Fix: Sentry Errors 21 Aug

---

tests/playwright/pages/Dashboard/common/Cell/UserOptionCell.ts

fix(test): User test fail issue due truncated user tooltip blocking click action

---

packages/nocodb/src/helpers/PagedResponse.ts
packages/nocodb/tests/unit/rest/tests/dataApiV3/list-and-crud.test.ts

Nc fix/pagesize data v3

---

packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts

fix: parse json only if it is object and array

---

packages/nc-gui/composables/useOnboardingFlow.ts
packages/nc-gui/nuxt-shim.d.ts
packages/nc-gui/plugins/tele.ts

Nc refactor/onboarding

---

packages/nc-gui/components/shared-view/Gallery.vue
packages/nc-gui/components/shared-view/Grid.vue
packages/nc-gui/components/shared-view/Kanban.vue
packages/nc-gui/components/smartsheet/calendar/SideRecordCard.vue
packages/nc-gui/composables/useTemplatedMessage.ts
packages/nc-gui/store/sidebar.ts

Nc fix/regex issue

---

packages/nocodb/src/modules/auth/auth.service.ts

- Re https://github.com/nocodb/nocodb/issues/4997#issuecomment-2893717602 

fix(auth): User signin - better error handling

---

packages/nocodb/src/controllers/api-version-not-found.controller.ts
packages/nocodb/src/modules/noco.module.ts
packages/nocodb/tests/unit/rest/index.test.ts
packages/nocodb/tests/unit/rest/tests/dataApiV3/error-handling.test.ts
packages/nocodb/tests/unit/rest/tests/payment/beforeEach.ts
packages/nocodb/tests/unit/rest/tests/payment/helpers.ts
packages/nocodb/tests/unit/rest/tests/payment/payment.test.ts

Nc fix/not found module

---

packages/nocodb/src/guards/global/global.guard.ts
packages/nocodb/src/helpers/apiHelpers.ts
packages/nocodb/src/schema/swagger-v2.json
packages/nocodb/src/schema/swagger-v3.json
packages/nocodb/src/schema/swagger.json
packages/nocodb/src/services/api-docs/swagger/swagger-base.json
packages/nocodb/src/services/api-docs/swaggerV2/swagger-base.json
packages/nocodb/src/strategies/authtoken.strategy/authtoken.strategy.ts

Nc feat/authorization header

---

packages/nc-gui/components/cell/Date/Editor.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/Date.ts

Nc fix/date parsing

---

packages/nocodb/src/db/BaseModelSqlv2/insert.ts
packages/nocodb/tests/unit/rest/tests/dataApiV3/audit-log.test.ts

fix oss audit log on bulk insert. Ref: https://github.com/nocodb/nocohub/issues/6556

fix oss audit log on bulk insert

---

packages/nc-gui/components/cell/Date/Editor.vue
packages/nc-gui/components/smartsheet/grid/canvas/cells/Date.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/tests/unit/rest/tests/dataAPIsV3.test.ts
packages/nocodb/tests/unit/rest/tests/dataApiV3/list-and-crud.test.ts

Nc fix/date format

---

packages/nc-gui/composables/useBetaFeatureToggle.ts

Nc enable row action

---

packages/nc-gui/composables/useInfiniteData.ts

fix: records not removed from group when value changes

---

packages/nocodb-sdk/src/lib/helperFunctions.ts

fix: Avoid treating user-defined created_at and updated_at field as system column

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/Formula.ts
packages/nc-gui/components/smartsheet/grid/canvas/cells/LongText.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nocodb-sdk/src/lib/UITypes.ts
packages/nocodb-sdk/src/lib/aggregationHelper.ts
packages/nocodb-sdk/src/lib/arrayHelpers.ts
packages/nocodb-sdk/src/lib/columnHelper/columns/Formula.ts
packages/nocodb-sdk/src/lib/formula/operators.ts
packages/nocodb-sdk/src/lib/formula/referenced-info-extractor.ts
packages/nocodb-sdk/src/lib/formula/types.ts
packages/nocodb-sdk/src/lib/formula/validate-extract-tree.ts
packages/nocodb-sdk/src/lib/formulaHelpers.spec.ts
packages/nocodb-sdk/src/lib/helperFunctions.ts
packages/nocodb/src/db/functionMappings/pg.ts
packages/nocodb/tests/unit/rest/tests/attachment.test.ts

Nc feat/formula column reference

---

packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/grid/canvas/utils/headerUtils.ts

feat: Show related fields in tooltip when relation is from external DB

---

packages/nc-gui/composables/useGlobal/types.ts
packages/nocodb/src/utils/nc-config/constants.ts

feat: allow whitelist domains for iframe widget

---

packages/nc-gui/components/smartsheet/Gallery.vue
packages/nc-gui/components/smartsheet/calendar/index.vue

fix: gallery view do not prefill form with filters

---

packages/nocodb/src/modules/jobs/redis/jobs.service.ts

fix: attachment issue when redis used

---

packages/nc-gui/assets/nc-typography-plugin.ts
packages/nc-gui/assets/style.scss
packages/nc-gui/windi.config.ts

fix(nc-gui): font weight issue if we use custom fontSize windicss variables

---

packages/nc-gui/utils/browserUtils.ts

fix: App loading issue

---

packages/nc-gui/assets/nc-typography-plugin.ts
packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/components/smartsheet/form/FieldMenu.vue
packages/nc-gui/lang/en.json

fix: form view show hide field btn on top right corner of active field

---

packages/nc-gui/helpers/tiptap-markdown/extensions/nodes/hard-break.ts
packages/nc-gui/lang/en.json

fix: scroll inside rich text input even on shift + enter without any text

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/BaseModelSqlv2/add-remove-links.ts
packages/nocodb/src/db/CustomKnex.ts
packages/nocodb/src/meta/meta.service.ts
packages/nocodb/src/services/data-table.service.ts

- Pass custom args to trx
- Use single trx to reduce roundtrips

feat: link trx

---

packages/nc-gui/components/smartsheet/grid/canvas/cells/DateTime.ts
packages/nc-gui/utils/datetimeUtils.ts

fix: Cannot read properties of undefined (reading 'abbreviation')

---

packages/nocodb/src/db/BaseModelSqlv2.ts

Provide summary of changes with issue number if any. Closes https://github.com/nocodb/nocodb/issues/12245#top

fix: change sort priority on api v3

---

packages/nc-gui/composables/useProvideChatwoot.ts

fix: additional attributes

---

README.md

docs: remove nix details

---

packages/nocodb/src/plugins/spaces/Spaces.ts

Closes https://github.com/nocodb/nocodb/issues/12266#top

fix: digitalocean fix

---

packages/nc-gui/components/smartsheet/Gallery.vue
packages/nc-gui/components/tabs/Smartsheet.vue
packages/nc-gui/composables/useCalendarViewStore.ts
packages/nc-gui/composables/useGalleryViewData.ts
packages/nc-gui/composables/useInfiniteData.ts
packages/nc-gui/composables/useMetas.ts
packages/nc-gui/composables/useViewData.ts
packages/nc-gui/pages/index/[typeOrId]/[baseId]/index/index/[viewId]/[[viewTitle]].vue
packages/nc-gui/store/views.ts

Closes https://github.com/nocodb/nocohub/issues/6632
Simplify View Meta States for Gallery and Calendar

fix: redirect to base homepage on 404

---

packages/nc-gui/components/cell/Date/Editor.vue
packages/nc-gui/components/cell/DateTime/Editor.vue
packages/nc-gui/components/cell/Decimal/DecimalInput.vue
packages/nc-gui/components/cell/Email/Editor.vue
packages/nc-gui/components/cell/PhoneNumber/Editor.vue
packages/nc-gui/components/cell/RichText.vue
packages/nc-gui/components/cell/TextArea.vue
packages/nc-gui/components/cell/Time/Editor.vue
packages/nc-gui/components/cell/Year/Editor.vue
packages/nc-gui/components/cell/attachment/Modal.vue
packages/nc-gui/components/cell/attachment/UploadProviders/Camera.vue
packages/nc-gui/components/cell/attachment/UploadProviders/Local.vue
packages/nc-gui/components/nc/Select.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/ColumnList.vue
packages/nc-gui/components/smartsheet/expanded-form/presentors/Fields/index.vue
packages/nc-gui/components/virtual-cell/Links.vue
packages/nc-gui/components/virtual-cell/components/LinkedItems.vue
packages/nc-gui/components/virtual-cell/components/ListItem.vue
packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue

- ref: #12189
- ref: some cell input related changes

Nc Feat: Mobile friendly responsive UI 

---

packages/nc-gui/components/dashboard/settings/DataSources.vue

Fix: Avoid assigning order value 1 to non default source

---

packages/nc-gui/components/dashboard/TreeView/Table/Node.vue
packages/nc-gui/components/dashboard/TreeView/Views/Node.vue
packages/nc-gui/components/smartsheet/details/Erd.vue
packages/nc-gui/components/smartsheet/header/Cell.vue
packages/nc-gui/components/smartsheet/header/Menu.vue
packages/nc-gui/components/smartsheet/header/VirtualCell.vue
tests/playwright/tests/db/features/erd.spec.ts

fix: show description as a multiline text and initially don't show all field in relations erd

---

packages/nc-gui/components/smartsheet/column/EditOrAdd.vue

Hide show more option

---

packages/nc-gui/app.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/loaders/ActionManager.ts
packages/nc-gui/composables/useUserSync.ts
packages/nc-gui/utils/urlUtils.ts

feat: sync user obj 

---

packages/nc-gui/components/smartsheet/PlainCell.vue
packages/nc-gui/components/virtual-cell/components/LinkedItems.vue
packages/nc-gui/components/virtual-cell/components/ListItem.vue
packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue

- Use Plain Cell in LTAR List Item

fix: use Plain Cell in ltar list item

---

packages/nc-gui/components/general/FormBranding.vue
packages/nc-gui/components/notification/Item/Wrapper.vue
packages/nc-gui/components/smartsheet/header/ColumnMenu.vue
packages/nc-gui/components/virtual-cell/components/ListItem.vue
packages/nc-gui/composables/useViewColumns.ts
packages/nc-gui/composables/useViewData.ts

Nc Fix: Update nocodb logo from form view and hide field time issue

---

packages/nc-gui/components/ai/Erd/view.vue
packages/nc-gui/components/auth/onboarding/Layout/index.vue
packages/nc-gui/components/auth/onboarding/Question/index.vue
packages/nc-gui/components/cell/attachment/Carousel.vue
packages/nc-gui/components/erd/View.vue
packages/nc-gui/components/nc/Button.vue
packages/nc-gui/components/smartsheet/Map.vue
packages/nc-gui/layouts/empty.vue
packages/nc-gui/layouts/top.vue
packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index.vue

fix: Mobile friendly responsive onboarding flow

---

.github/workflows/release-executables.yml
.github/workflows/release-timely-executables.yml
packages/nocodb/Dockerfile
packages/nocodb/Dockerfile.local
packages/nocodb/Dockerfile.timely
tests/playwright/pages/SsoIdpPage/GoogleLoginPage.ts

Nc chore/jsdom dependency issue

---

packages/nc-gui/composables/useScriptExecutor.ts
packages/nc-gui/pages/index.vue
packages/nc-gui/pages/index/[typeOrId]/calendar/[viewId]/index.vue
packages/nc-gui/pages/index/[typeOrId]/gallery/[viewId]/index.vue
packages/nc-gui/pages/index/[typeOrId]/kanban/[viewId]/index.vue
packages/nc-gui/pages/index/[typeOrId]/map/[viewId]/index.vue
packages/nc-gui/pages/index/[typeOrId]/view/[viewId].vue
packages/nc-gui/utils/routeUtils.ts

fix: shared form not working

---

packages/nc-gui/composables/useLTARStore.ts
packages/nocodb/src/db/BaseModelSqlv2/relation-data-fetcher.ts

Nc fix/ link issues

---

packages/nc-gui/composables/useApi/interceptors.ts
packages/nc-gui/composables/useCalendarViewStore.ts
packages/nc-gui/composables/useKanbanViewStore.ts
packages/nc-gui/plugins/a.socket.ts

Nc fallback socket

---

packages/nc-gui/assets/nc-windicss-shortcuts-plugin.ts
packages/nc-gui/assets/style.scss
packages/nc-gui/components/ai/Erd/view.vue
packages/nc-gui/components/dashboard/TreeView/Table/Node.vue
packages/nc-gui/components/dashboard/TreeView/Views/List.vue
packages/nc-gui/components/dashboard/View.vue
packages/nc-gui/components/erd/View.vue
packages/nc-gui/components/extensions/Extension.vue
packages/nc-gui/components/smartsheet/details/Fields.vue
packages/nc-gui/components/smartsheet/grid/index.vue
packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue
packages/nc-gui/components/smartsheet/topbar/ViewListDropdown.vue
packages/nc-gui/composables/useGlobal/actions.ts
packages/nc-gui/composables/useGlobal/types.ts
packages/nc-gui/composables/useTableNew.ts
packages/nc-gui/lib/types.ts
packages/nc-gui/store/views.ts
packages/nc-gui/store/webhooks.ts
packages/nc-gui/utils/urlUtils.ts
packages/nc-gui/windi.config.ts

🔦 Feature: Use Table+ViewName as slug in active view URL 

---

packages/nocodb/src/db/CustomKnex.ts
packages/nocodb/src/modules/jobs/migration-jobs/nc_job_009_audit_migration.ts

fix(audit-migration): Adjust batch size for SQLite compatibility

---

packages/nc-gui/components/webhook/index.vue

fix: Can't upgrade Webhook to v3

---

packages/nc-gui/composables/useProvideChatwoot.ts

fix: enable support for all users

---

packages/nc-gui/components/cell/attachment/sort.ts
packages/nc-gui/components/dashboard/TreeView/Project/List.vue
packages/nc-gui/components/dashboard/TreeView/Table/List.vue
packages/nc-gui/components/dashboard/TreeView/Views/List.vue
packages/nc-gui/components/dashboard/TreeView/index.vue
packages/nc-gui/components/dashboard/settings/DataSources.vue
packages/nc-gui/components/extensions/Pane.vue
packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/components/smartsheet/Kanban.vue
packages/nc-gui/components/smartsheet/column/SelectOptions.vue
packages/nc-gui/components/smartsheet/details/Fields.vue
packages/nc-gui/components/smartsheet/form/LimitOptions.vue
packages/nc-gui/components/smartsheet/header/AddLookupsOrRollups.vue
packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
packages/nc-gui/utils/commonUtils.ts

Fix: Auto scroll issue while reorder

---

packages/nc-gui/components/erd/RelationEdge.vue

fix(nc-gui): Improvise tooltip for links in ERD

---

packages/nc-gui/components/smartsheet/expanded-form/Sidebar/Audits.vue
packages/nocodb/src/db/BaseModelSqlv2.ts

fix: data bulk operation audit corrections

---

packages/nc-gui/components/dashboard/Sidebar.vue
packages/nc-gui/components/dashboard/TreeView/Table/Node.vue
packages/nc-gui/components/dashboard/TreeView/Views/List.vue
packages/nc-gui/utils/colorsUtils.ts

fix: prevent table highlight from affecting child views in sidebar

---

packages/nocodb/src/plugins/r2/R2.ts

Closes https://github.com/nocodb/nocodb/issues/12266#issuecomment-3341902466

fix: decode key in r2

---

packages/nc-gui/composables/useMcpSettings.ts
packages/nc-gui/lang/en.json
packages/nc-gui/pages/account/index/[page].vue
packages/nc-gui/utils/filterUtils.ts

fix(i18n): Add deleted keys from en.json file

---

packages/nocodb/tests/unit/rest/tests/meta-apis/table.test.ts

fix: remove only on table.test

---

packages/nc-gui/components/dlg/Record/DeleteAll.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/context/Cell.vue
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/grid/index.vue
packages/nc-gui/composables/useGridViewData.ts
packages/nc-gui/composables/useInfiniteData.ts
packages/nc-gui/lang/en.json
packages/nocodb-sdk/src/lib/is.ts
packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/BaseModelSqlv2/delete.ts
packages/nocodb/src/schema/swagger.json

Feature: Deselect Specific Records After SELECT ALL

---

.github/workflows/release-docker.yml

Docker build action improvemnt

---

packages/nocodb/src/services/hooks.service.ts

Closes https://github.com/nocodb/nocohub/issues/6897

fix: Test webhook fails when on form submission is configured

---

.github/workflows/release-nocodb.yml

Remove aiopusher from release action

---

packages/nc-gui/components/shared-view/Calendar.vue
packages/nc-gui/components/smartsheet/Gallery.vue
packages/nc-gui/components/smartsheet/Kanban.vue
packages/nc-gui/components/smartsheet/calendar/index.vue
packages/nc-gui/components/smartsheet/toolbar/Export.vue
packages/nc-gui/components/tabs/Smartsheet.vue
packages/nc-gui/composables/useCalendarViewStore.ts
packages/nc-gui/composables/useKanbanViewStore.ts
packages/nc-gui/composables/useSharedView.ts
packages/nc-gui/composables/useSmartsheetStore.ts

fix: URL where query filter not working in Calendar, Gallery, kanban view

---

packages/nc-gui/assets/style.scss
packages/nc-gui/components/cell/RichText/SelectedBubbleMenu.vue
packages/nc-gui/components/dashboard/View.vue
packages/nc-gui/components/general/ChromeWrapper.vue
packages/nc-gui/components/nc/Select.vue
packages/nc-gui/lang/en.json
packages/nc-gui/plugins/monaco.ts

Hide Splitter if sidebar hidden

fix: sidebar ux fix

---

packages/nocodb/src/services/tables.service.ts
packages/nocodb/tests/unit/rest/tests/dataApiV3/error-handling.test.ts
packages/nocodb/tests/unit/rest/tests/typeCasts.test.ts

Nc fix/ensure id system column

---

packages/nocodb/src/db/BaseModelSqlv2.ts
packages/nocodb/src/db/BaseModelSqlv2/group-by.ts
packages/nocodb/tests/unit/rest/tests/groupby.test.ts
tests/playwright/tests/db/general/groupCRUD.spec.ts

Nc revert 6881 revert 6716 fix/group by

---

packages/nc-gui/components/cell/attachment/Card.vue
packages/nc-gui/components/cell/attachment/index.vue
packages/nc-gui/components/cell/attachment/utils.ts
packages/nc-gui/components/dashboard/Sidebar/HeaderWrapper.vue
packages/nc-gui/components/project/View.vue
packages/nc-gui/components/smartsheet/Form.vue
packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
packages/nc-gui/components/smartsheet/grid/Table.vue
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasRender.ts
packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
packages/nc-gui/components/smartsheet/grid/canvas/index.vue
packages/nc-gui/components/smartsheet/grid/canvas/utils/groupby.ts

Fix: Reduce grid row height in mobile view and dont show unsupported options from row meta col

---

tests/playwright/tests/db/features/verticalFillHandle.spec.ts

fix: fill handle

---

packages/nocodb/src/models/RowColorCondition.ts

fix invalid parameters return undefined if data not found

---

packages/nocodb-sdk/src/lib/error-handler/nc-error-base.ts
packages/nocodb/src/services/calendars.service.ts
packages/nocodb/src/services/forms.service.ts
packages/nocodb/src/services/galleries.service.ts
packages/nocodb/src/services/grids.service.ts
packages/nocodb/src/services/kanbans.service.ts
packages/nocodb/src/services/views.service.ts
packages/nocodb/tests/unit/processor/duplicate/duplicate-base.test.ts
packages/nocodb/tests/unit/rest/tests/viewRow.test.ts

Nc fix/duplicate view alias

---

packages/nocodb/src/services/api-tokens.service.ts
packages/nocodb/src/services/integrations.service.ts
packages/nocodb/src/services/mcp.service.ts
packages/nocodb/src/services/sources.service.ts

trim titles for several things

---

packages/nc-gui/components/dlg/LockView.vue
packages/nc-gui/components/feed/Error.vue
packages/nc-gui/lang/en.json

Nc fix/sentry errors 7 oct
